### ISSUE TITLE
Vice City isn't launch

### ISSUE THREAD

**Issue by v-progs** [NVIDIAGameWorks/rtx-remix#1]
[D3D9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11211995/D3D9.log)
[gta-vc_1.1_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11211999/gta-vc_1.1_d3d9.log)
[gta-vc_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11212000/gta-vc_d3d9.log)
GTA VC isn't launching with this wrapper

**Comment by AlexDunn** [comment]
Hey, thanks for the report!

Can you also attach a NvRemixBridge.log (which you'll find in the .trex dir) please ?

**Comment by omer1615** [comment]
I'm on Steam version of the Vice City and not able to succed to run the game.
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11216509/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11216511/d3d9.log)
[gta-vc_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11216512/gta-vc_d3d9.log)

**Comment by lam-ux** [comment]
> I managed lo get the game launched but it crashed after the intro movie (Steam version, clean install) [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11212209/d3d9.log) [gta-vc_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11212210/gta-vc_d3d9.log)

how?

**Comment by mirh** [comment]
Isn't vice city a d3d8 game?
Maybe you'll have better today.

**Comment by Kim2091** [comment]
Vice City works well now. @AlexDunn this issue can be closed

**Comment by CanerKaraca23** [comment]
> Vice City works well now. [@AlexDunn](https://github.com/AlexDunn) this issue can be closed

<img width="1917" height="1078" alt="Image" src="https://github.com/user-attachments/assets/ab83ce4b-2527-4b88-a325-ded4ee7cdf1c" />
