### ISSUE TITLE
Ford Racing 3 - the cursor doesn't move in the RTX Remix UI and clicks aren't registered

### ISSUE THREAD

**Issue by ThatD07** [NVIDIAGameWorks/rtx-remix#102]
**The bug**
- The cursor doesn't move in the RTX Remix UI ingame and clicks aren't registered, so settings can't be tweaked and textures can't be assigned. Right clicking resets the cursor pos to 0,0.
- RTX Remix version: 0.1.1
- GPU: RTX 3070
- GPU Driver version: 531.26
- Game build: Retail (should be the same as the Steam version which was available for a brief period)

**Logs:**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11260757/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11260754/d3d9.log)
- [fr3_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11260756/fr3_d3d9.log)

**To Reproduce**
1. Launch the game
2. Force the window size with Dxwnd or Borderless Gaming (as otherwise the game launches in a small window of 200x39
3. Open the RTX Remix ui with ALT+X
4. The cursor doesn't move (Visibility can be toggled with Alt+Delete but doesn't fix the issue).

**Expected behavior**
The cursor should move.

**Comment by mralexs5** [comment]
There is a potential fix on the RTX Remix discord, I can't pull it up at the moment however.

**Comment by ThatD07** [comment]
Update: I got it working by hooking dinput8 in DxWrapper

**Comment by ThatD07** [comment]
I forgot to close the issue, doing it now since I solved it
