### ISSUE TITLE
Silent Hill 2 freezes with RTX Remix

### ISSUE THREAD

**Issue by gebdag** [NVIDIAGameWorks/rtx-remix#104]
Silent Hill 2 immediately freezes upon launch when used with RTX Remix. The video output freezes (the RTX Remix countdown is displayed with the timer stuck at 9-8 seconds) but the game still runs in the background. When pressing enter a bunch of times you can load into the game and hear the audio. 

According to the log files NV Remix Bridge crashes. 
Exception code 0xc0000005 - The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

- Which Remix version - 0.1.1
- Which GPU - 4090
- Which GPU driver version - 531.61
- Which game build - Retail build with crosire d3d8to9 or Enhanced Edition

**Attach logs!**
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266080/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266070/NvRemixBridge.log)
[sh2pc_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266082/sh2pc_d3d9.log)

**To Reproduce**
1. Start the game
2. It'll freeze
3. Press enter a bunch of times to start the game

**Expected behavior**
Game freezes immediately

**Screenshots**
![sh2](https://user-images.githubusercontent.com/130744615/232897308-19fd26c1-3f89-463c-bf45-68165c11ed97.png)

**Comment by Rmurray2006** [comment]
ConvertFormat: Unknown format encountered: 65 in the sh2 log, so probably a wrapper issue im guessing. but on other github threads about the remix bridge log, they're looking at a fix.

**Comment by mrSuave00** [comment]
the interesting thing is that, the game isn't frozen here. i've tried myself and you can actually get in game, it's just gonna be a black screen.

**Comment by AlexDunn** [comment]
We fixed some issues I think are related to this.  Please, give remix-0.2.0 a try and let me know how it goes: https://github.com/NVIDIAGameWorks/rtx-remix/releases/tag/remix-0.2.0

**Comment by gebdag** [comment]
> We fixed some issues I think are related to this. Please, give remix-0.2.0 a try and let me know how it goes: https://github.com/NVIDIAGameWorks/rtx-remix/releases/tag/remix-0.2.0

Awesome, it is indeed now booting with RTX Remix. Thanks!

![Screenshot 2023 05 12 - 04 23 40 11](https://github.com/NVIDIAGameWorks/rtx-remix/assets/130744615/38ecbd64-c2ab-4182-ab86-8792d451f90f)
