### ISSUE TITLE
Is this thing even supposed to work in DX9 ?

### ISSUE THREAD

**Issue by Panjaksli** [NVIDIAGameWorks/rtx-remix#108]
**Describe the bug**
Call of juarez 2 - can't initialize renderer
Mirrors edge - just hangs on splashscreen
**Expected behavior**
Game should launch ???

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11271237/d3d9.log)
[MirrorsEdge_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11271238/MirrorsEdge_d3d9.log)
[CoJBiBGame_x86_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11271261/CoJBiBGame_x86_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11271262/d3d9.log)

**Comment by Ferdam** [comment]
If game uses Shaders it most likely won't be compatible with Remix.
Unless this game has some sort of fallback to fixed function mode, that gets rid of shaders, then it might be possible to get it working with Remix

Mirrors Edge is too recent right now for what Remix can do.

You can still try finding out if you can tweak the game to run in a mode that skips using shaders

**Comment by Panjaksli** [comment]
Alrigh, thanks.
