### ISSUE TITLE
not a issue but guys read this.

### ISSUE THREAD

**Issue by Rmurray2006** [NVIDIAGameWorks/rtx-remix#109]
[https://discord.gg/tHYbHfNC](url)
if you want more support come on over to the discord if you want too, theirs plenty of people online in here if you need help as well just in case no-one gets back to you. <3

**Comment by thedinosoar** [comment]
Please only post issues here, it just bloats the issues list and gives the impression to new people that people can put whatever they want here which makes working on real issues more difficult

**Comment by Rmurray2006** [comment]
> Please only post issues here, it just bloats the issues list and gives the impression to new people that people can put whatever they want here which makes working on real issues more difficult

um this was so people can find the discord so they do not have to post here all the time, i think kim one of the people who manages these does not mind but closing this because you were the only one having the problem
