### ISSUE TITLE
Error: This Game does not support your video card

### ISSUE THREAD

**Issue by Explorographer** [NVIDIAGameWorks/rtx-remix#110]
Have not gotten this to work on any  Direct X9.0 game yet.  But this is the closest I have come.

I get the error:  This game does not support your video card.  Please refer to the game's Minimum System Requirements.

I have a Founders Edition RTX4080.
The game I am trying to mod is: Star Wars: The Force Unleashed - Steam Ed.
ReMix version 0.1.1

To reproduce, Install game, copy over the contents of Remix 0.1.1 folder from .zip.  Run game from Steam or from game folder.

If someone could please point me to a game on Windows that you KNOW works with ReMix, please share as I really just want to get in there and start learning.  A list of known working titles would be nice as well.

**Screenshots
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11275160/NvRemixBridge.log)
**
[SWTFU Launcher_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11275153/SWTFU.Launcher_d3d9.log)

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11275148/d3d9.log)

**Comment by Explorographer** [comment]
Welp, I am done trying.  This software just plain does not work as described on the front page.  Done wasting time here.

**Comment by mralexs5** [comment]
I'm guessing the game isn't supported by RTX Remix as it is too new. Try changing the shader model in the bridge.conf file

**Comment by EthanZoneCoding** [comment]
It requires shader model 3, which I hear is unsupported.

**Comment by Explorographer** [comment]
Yeah, but honestly I have tried it on so many games and cannot get it to work.  Latest was Morrowind and Oblivion.  Oblivion is from the DVD version I still had from it's original release.  Still nothing but fails.

**Comment by NV-LL** [comment]
Thank you for reaching out. As mentioned, this game is unlikely to be compatible with Remix. You can try again on the latest release (0.5.1), however we likely won't be able to address any bugs due to incompatibility.
