### ISSUE TITLE
Error message when launching LEGO Marvel Superheroes

### ISSUE THREAD

**Issue by Veitaserum4** [NVIDIAGameWorks/rtx-remix#111]
**Describe the bug**
- A clear and concise description of what the bug is.
- When I try and launch the game, I get an error and it doesn't launch
- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
- 0.1.1
- Which GPU
- RTX 2060 12GB
- Which GPU driver version
- 527.56
- Which game build (and whether it is from Steam/GOG/Other)
Steam
**Attach logs!**
- NvRemixBridge.log
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11275523/NvRemixBridge.log)
- d3d9.log
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11275514/d3d9.log)
- The game specific log will be named gamename_d3d9.log
- [LEGOMARVEL_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11275516/LEGOMARVEL_d3d9.log)

**To Reproduce**
Extract remix-0.1.1.zip to th LEGO Marvel Superheroes folder
Run game
**Expected behavior**
For the game to run with RTX remix
**Screenshots**
![image](https://user-images.githubusercontent.com/63559389/233143598-ba2311da-e523-4a80-8c70-fdc2ffbdcf51.png)

**Comment by mralexs5** [comment]
I'm pretty sure this game is too new to run with RTX remix. Anything that came out during the PS3/360 era is very unlikely to work

**Comment by Ferdam** [comment]
Error message tells exactly why it isn't working. It requires Shader Model 3, so it probably depends on shaders to work, which makes it incompatible with Remix.

You may google to find out if this game can be tweaked to run without depending on shaders

**Comment by Veitaserum4** [comment]
Sorry for my late reply, I have found a way to play Lego Marvel Superheroes without Shader model 3, but it overrides the d3d9.dll that is used in RTX Remix, and it's not working without it

**Comment by NV-DM** [comment]
Shader-based games are not in scope for Remix, as it's a difficult technical problem to solve. We therefore have no plans to support them for now. (There is extremely limited support for vertex shaders in some games, but it's focused on specific use cases that we can currently support.)
