### ISSUE TITLE
Sonic Adventure 2 (Steam) Crashing

### ISSUE THREAD

**Issue by Veitaserum4** [NVIDIAGameWorks/rtx-remix#112]
**Describe the bug**
- A clear and concise description of what the bug is.
- White screen when booting up Sonic Adventure 2 
- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
- 0.1.1
- Which GPU
- RTX 2060 12GB
- Which GPU driver version
- 531.68
- Which game build (and whether it is from Steam/GOG/Other)
Steam
**Attach logs!**
- NvRemixBridge.log
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11277588/NvRemixBridge.log)
- d3d9.log
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11277583/d3d9.log)
- The game specific log will be named gamename_d3d9.log
- [sonic2app_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11277585/sonic2app_d3d9.log)

**To Reproduce**
1. Extract .zip from releases into game folder with exe
2. Crash
**Expected behavior**
Run the game with RTX Remix
**Screenshots**
![image](https://user-images.githubusercontent.com/63559389/233199789-9c27fc60-8ec9-4e25-92e3-8807cf1d5258.png)
![image](https://user-images.githubusercontent.com/63559389/233200155-a91a8c61-b485-4412-b8ea-7ba2b63adbe9.png)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by Veitaserum4** [comment]
The menu appears and the game is playable, you do have to enable v-sync or else the game is sped up, but apart from being able to ignore a texture in the game setup menu, RTX remix seems to do nothing
Logs:

[sonic2app_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15239485/sonic2app_d3d9.log)
[d3d9_01.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15239486/d3d9_01.log)
[NvRemixBridge_01.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15239487/NvRemixBridge_01.log)


![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/63559389/8e417077-ffb4-43e0-9d07-713aff3589e6)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/63559389/9d3471f4-7df7-4e00-95e2-9d3d8634b533)

**Comment by NV-LL** [comment]
Thank you for confirming that the crashing is fixed. Will you please open a new ticket for the issue with the Remix menu? That way we can investigate and track it separately. Thanks!

**Comment by Veitaserum4** [comment]
👍
