### ISSUE TITLE
Tom Clancy's Rainbow Six 3: Gold Edition alternates window/fullscreen, freezes, then crashes with error

### ISSUE THREAD

**Issue by acoulte93** [NVIDIAGameWorks/rtx-remix#113]
**Describe the bug**
- Upon launching the game, the window will alternative fairly quickly between fullscreen and windowed (in the top left corner of the screen) and video memory usage climbs 25% each time the game goes to fullscreen, then windowed and repeat until it crashes.

RTX Remix Version: 0.1.1
GPU: 3070 FE
Nvidia Driver Version: 531.41
Game Build: Steam
Crosire d3d8to9: v1.11.1.0

**Attach logs!**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11278396/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11278399/d3d9.log)

**To Reproduce**
1. Install crosire d3d8to9 and Remix 0.1.1
2. Launch the game through Steam
3. Watch the game alternate between fullscreen/windowed mode
4. The game will then freeze, and stall then crash after a few seconds

**Expected behavior**
Upon launching the game, it should load in fullscreen (at 800 x 600 window size) and reach the main menu.

**Screenshots**
After usage climbed
![rs3_bug](https://user-images.githubusercontent.com/5293492/233226819-3873b541-cd39-4070-a011-331043e1f251.png)
When the game finally crashes
![image](https://user-images.githubusercontent.com/5293492/233226781-53502c26-bda9-4f99-8dcc-5f9cdc7fa53d.png)

**Comment by AlexDunn** [comment]
From the logs it looks like the crash is a bridge-remix "shared heap" allocation failure.  

In Remix 0.2.0 we disabled this feature by default due to instability, it'd be worth giving remix 0.2.0 a shot to see if it gets you further.

**Comment by NV-DM** [comment]
Hello. Could you please re-test this with the latest Remix release?

**Comment by NV-DM** [comment]
Marking as fixed to sync with JIRA
