### ISSUE TITLE
Simpsons hit and run

### ISSUE THREAD

**Issue by howdoicodeplease** [NVIDIAGameWorks/rtx-remix#121]
**Describe the bug**
the screen is black when booting up the game and then crashes however remix overlay appears
remix version: 0.1.1
GPU: RTX 3070TI
Game build: Simpsons: Hit and run
error: [RTX-Compatibility-Info] Trying to raytrace but not detecting a valid camera

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11305032/d3d9.log)
[Simpsons_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11305034/Simpsons_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11305035/NvRemixBridge.log)

**To Reproduce**
start game with rtx-remix installed

**Expected behavior**
The game should load the main menu

Screenshots

**Comment by AlexDunn** [comment]
We fixed issues that may be related to this in remix-0.2.0, try giving it a shot!

https://github.com/NVIDIAGameWorks/rtx-remix/releases/tag/remix-0.2.0

**Comment by howdoicodeplease** [comment]
works now thanks
