### ISSUE TITLE
Dead Space Error

### ISSUE THREAD

**Issue by simeonradivoev** [NVIDIAGameWorks/rtx-remix#122]
- When you try and start Dead Space from steam or from its exe directly you get an error:
`Your Graphics Card does not meet Dead Space minimum requirements`
- Remix version 0.1.1
- RTX 3080
- GPU driver version: 531.68
- Steam

**Logs**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11305296/NvRemixBridge.log)
[Dead Space_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11305290/Dead.Space_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11305291/d3d9.log)

**To Reproduce**
1. Launch From Steam or exe
2. See error

**Comment by AlexDunn** [comment]
Yes.  Agree with @mralexs5, it sounds like the game does not support a fixed function path and so is unlikely to work with Remix at this time unfortunately.

**Comment by simeonradivoev** [comment]
yea that seems to be the case
