### ISSUE TITLE
Remix bug with oblivion 

### ISSUE THREAD

**Issue by prestonofgrace** [NVIDIAGameWorks/rtx-remix#126]
**Describe the bug**
- all player models and npc models are stretched out towards lights and invisible world cameras  game dosent crash I don't have the logs on my phone

**Attach logs!**
- NvRemixBridge.log
- d3d9.log
- The game specific log will be named gamename_d3d9.log

**To Reproduce**

**Expected behavior**

**Screenshots**
![9babf0a4-7669-407d-9b90-e4bc26a67e7f](https://user-images.githubusercontent.com/66422634/233991277-a151b4d7-4381-4d80-b171-33f1125632ca.jpg)
![864a1572-13f8-4429-808f-b5c0b5e4a570](https://user-images.githubusercontent.com/66422634/233991281-6c774068-206a-439f-8e92-7cf862ae7e7d.jpg)
![ff0b40c6-4f20-4305-a58b-6b7145b4b9f6](https://user-images.githubusercontent.com/66422634/233991286-48c13dc0-ccf5-4488-a410-97f90dd34c59.jpg)

**Comment by Rmurray2006** [comment]
yes and can confirmed, it does not use dxvk as stated in this, why it was compatible with the portal dlls, which used dxvk and thus the repros being released now do not. it can be reproduced. Try the portal ones for yourself, look at the logs. Go to the repros released after try those and compare trex folder remix logs. 
![image](https://user-images.githubusercontent.com/87949223/233992703-ca68c893-bd5f-4e5e-bf67-14e0fd935405.png)

**Comment by Rmurray2006** [comment]
> yes and can confirmed, it does not use dxvk as stated in this, why it was compatible with the portal dlls, which used dxvk and thus the repros being released now do not. it can be reproduced. Try the portal ones for yourself, look at the logs. Go to the repros released after try those and compare trex folder remix logs. ![image](https://user-images.githubusercontent.com/87949223/233992703-ca68c893-bd5f-4e5e-bf67-14e0fd935405.png)

the reason it needs dxvk is because of the render issues

**Comment by AlexDunn** [comment]
We fixed an issue I think is related to this in the commit: https://github.com/NVIDIAGameWorks/dxvk-remix/commit/f3cb674467e24bdf4576e6ab608cac543febc469
