### ISSUE TITLE
Material updates (POM or Tessellation)

### ISSUE THREAD

**Issue by KioryFreeman** [NVIDIAGameWorks/rtx-remix#129]
This isn't a bug, but it was suggested I post here.

I was hoping to get some parallax occlusion mapping support for Remix, or some kind of tesselation, the latter would be ideal but, POM is the next best thing.

The reason I think this addition would be in everyone's interest is due to the fact that not everyone using Remix will want/be able to create new models from scratch, with higher poly counts etc.

Adding higher polygon budgets is great but, older games make heavy use of BSP which is still usable for simple material changes. People looking to mod (Remix) these older games will show varying degrees of skill, and having more options cannot hurt, especially for people who aren't as savvy with 3D modelling in general.  

As it stands right now, you guys have the bare minimum for Remix materials, I think they could be better as normal maps on their own don't really cut it anymore, we have very powerful RTX cards and POM/Tessellation shouldn't affect performance all that much, and it adds a ton of depth to a scene, what better way to showcase more raytracing detail?

I'm proposing the addition of (at the very least) POM for use in the Aperture materials, tessellation would absolutely be better, but POM is a good second choice. 

Thanks for hearing me out, and thanks for such a great tool, I'm getting a lot of use out of it already and I can't wait to see what's coming in future!

![maxresdefault](https://user-images.githubusercontent.com/131802751/234353954-09aa3ef5-bde0-4ddf-ab23-a7dc2b8629d4.jpg)

**Comment by NV-LL** [comment]
Hello, and thank you for your suggestion! We have implemented this support in a recent release and will be closing this ticket.
