### ISSUE TITLE
option to have rtx remix settings render in a seperate window

### ISSUE THREAD

**Issue by howdoicodeplease** [NVIDIAGameWorks/rtx-remix#133]
in some games, the menu interacts weirdly with the actual game and it becomes impossible to change the rtx remix settings.

**Comment by mralexs5** [comment]
They're working on a program that will essentially be that plus more

**Comment by NV-LL** [comment]
Thank you for reaching out. We don't currently plan to implement this feature. However, if you are still having issues with the menu on the latest release (0.5.1) in some games, please open a new ticket for that and specify which games exhibit that problem. Thanks!
