### ISSUE TITLE
Might & Magic IX isn't starting

### ISSUE THREAD

**Issue by an00biz** [NVIDIAGameWorks/rtx-remix#134]
**Describe the bug**
- Black screen after launching lithtech.exe, Task Manager shows that the process isn't responding. Having Widescreen fix installed or uninstalled doesn't affect the game's launch (DirectX settings are also applied)
- 0.1.1
- GeForce RTX 3060 (Laptop)
- 531.68
- GOG. The patch is TELP's 1.3 (latest)

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11361527/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11361528/d3d9.log)
- [lithtech_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11361530/lithtech_d3d9.log)

**To Reproduce**
1. Go to '...\GOG Galaxy\Games\Might and Magic 9\'
2. Click on 'lithtech.exe'
3. Nothing happens

**Expected behavior**
At least enter the main menu

**Screenshots**
![image](https://user-images.githubusercontent.com/44441226/235359369-2d32b113-883e-4842-a663-ebfe7d6cb556.png)
![image](https://user-images.githubusercontent.com/44441226/235358991-7e2d6ad6-737f-46e8-982f-5778d4d66a09.png)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by an00biz** [comment]
> Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

Hello! Yes, the game runs now, but:
1) You have to change the native resolution (800x600) to 1920x1080 in autoexec.cfg, otherwise the game runs in a very small window:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/44441226/0dcb6277-7099-4f5b-bb02-9921d581b105)
2) The game doesn't seem to change in terms of graphics, though the Alt + X menu works:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/44441226/c7eac6fa-b81b-4317-ad2d-20b775b9c598)

**Comment by NV-LL** [comment]
Thank you for confirming the launch issue is fixed! Will you please open a new ticket for the rendering issues? That way we can track them separately. Thanks!

**Comment by an00biz** [comment]
> Thank you for confirming the launch issue is fixed! Will you please open a new ticket for the rendering issues? That way we can track them separately. Thanks!

Yes, I think I will. Thank you for the feedback!
