### ISSUE TITLE
Trash (Demo) - Main menu broken up into blocks and shuffles around when mouse is moved

### ISSUE THREAD

**Issue by Expack3** [NVIDIAGameWorks/rtx-remix#138]
**Describe the bug**
- Main menu and introduction splash screen is broken up into blocks and shuffles around when mouse is moved.
- 0.1.1
- Nvidia GeForce RTX 3060 Laptop
- 531.79
- Demo Version: 05Sep1, [Internet Archive (download `Trash_demo.exe`)](https://archive.org/download/TrashDemo)

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11402129/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11402130/d3d9.log)
- [Trash_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11402136/Trash_d3d9.log)

**To Reproduce**
1. Start game.
2. Left-click past introduction splash screen.
3. Move mouse around screen.
4. See error.

**Expected behavior**
Main menu and introduction splash screen is not broken up into blocks and does not shuffle around at any point, regardless of mouse movement. 

**Screenshots**
![Trash_Demo_BlockyMenu](https://user-images.githubusercontent.com/5042911/236345059-ffc37565-e416-4415-ba2f-8d3c9c8ae208.png)

**Note**
- Used dxWrapper as configured for D3D8 acquired from [here](https://discord.com/channels/1028444667789967381/1099010051294908446/1103162958311325697) (download `dxwrapper_dx8.7z`) to convert DX8 calls to DX9 calls suitable for the RTX Bridge.

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by Expack3** [comment]
This issue no longer occurs when using the release versions of dvk-remix a911c31-540 and bridge-remix-c062326-70 alongside using the version of D3D8to9 included with Remix 0.5.0.
