### ISSUE TITLE
Dark Souls Prepare to Die Edition (DX9)

### ISSUE THREAD

**Issue by stickyfran** [NVIDIAGameWorks/rtx-remix#139]
**Describe the bug**
Remix 0.1.1
RTX3080
Win11

The game won't even boot with remix on it. But it genereates this log
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11407266/d3d9.log)

**Comment by mralexs5** [comment]
This game is most likely to new to run with remix. Rule of thumb is that if the game had a 360 or PS3 version it probably won't work with remix.

**Comment by NV-LL** [comment]
Hello! Will you please check on the latest release (0.5.1) and let us know if this issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please reopen this ticket.
