### ISSUE TITLE
Midnight Club 2 (Steam Version) Issues

### ISSUE THREAD

**Issue by LauraWebdev** [NVIDIAGameWorks/rtx-remix#14]
Here are some of the issues I've encountered trying to add rtx-remix to [Midnight Club 2](https://store.steampowered.com/app/12160/Midnight_Club_2/).

* Does not work windowed (this seems to be due to dxvk incompatibilities, as the log points out). I've used DxWnd to force the game in windowed mode
* Intro videos don't play
* Main menu occasionally softlocks (In this case, the RTX menu can be opened via Alt+X but is unresponsible)
* Visual artifacts, certain faces are completely black, certain models are not visible
  * Cars are invisible, however their lights reflect on the ground

![image](https://user-images.githubusercontent.com/7365286/231554480-ec002407-11dc-41b8-ad49-6eaffecb30d1.png)
![image](https://user-images.githubusercontent.com/7365286/231554781-dc1105e9-01f7-4cb6-aef6-0cbf22c260f1.png)
![image](https://user-images.githubusercontent.com/7365286/231554915-94afef8b-5319-4241-a7ca-bcc22bf9f53e.png)

[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11214840/NvRemixBridge.log)

**Comment by LauraWebdev** [comment]
Release 0.1.1 fixed the issue not being able to open the game fullscreened. The game still has an issue when changing resolutions (needs game restart) and doesn't play the intro videos (in .bik file format). Other than that, I think all graphical issues happen due to not having set up the game yet. Or potentially the games strong culling.

![image](https://user-images.githubusercontent.com/7365286/231761126-721f0b48-c5ad-4d75-bf3a-86c93b4b2165.png)
![image](https://user-images.githubusercontent.com/7365286/231761177-041dca01-c9dd-4489-a935-19502061f301.png)
![image](https://user-images.githubusercontent.com/7365286/231761479-2b20f311-a0a1-40ea-bc0f-20d87b8ce025.png)

**Comment by LauraWebdev** [comment]
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/7365286/57c8b17d-13e6-48a2-a308-e7cfe9092063)
I can confirm that the same rendering issues persist in the newest "public release" version.

**Comment by NV-LL** [comment]
Hello! Will you please check on the latest release (0.5) and let us know if this issue persists? Thank you!

**Comment by LauraWebdev** [comment]
@NV-LL Hello, the problems persist.
![mc2_ECsQEuMYiJ](https://github.com/NVIDIAGameWorks/rtx-remix/assets/7365286/999997f3-5b84-47c6-b157-b54297f316da)
![mc2_12zPAIeoVz](https://github.com/NVIDIAGameWorks/rtx-remix/assets/7365286/b47702d9-a1a8-418b-960e-80566aaba8aa)
[mc2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15239607/mc2_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15239608/d3d9.log)

**Comment by NV-LL** [comment]
Thank you for checking! This may be a rendering issue; it may also be an issue with setup. If you haven't already, we recommend checking in with the community on Discord to see if other members know how to address these issues - there's a thread of folks working on this title [here](https://discord.com/channels/1028444667789967381/1203162776932196352). If you can help rule out setup problems, that would make it easier for us to investigate any possible rendering bugs. Thanks!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
