### ISSUE TITLE
Barnyard (numerous issues)

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#143]
**Describe the bug**
This game has numerous issues, ranging from Remix not working in specific view angles to geometry spinning seemingly at random. The following warning also spams the log, and I can't determine the reason:
`warn:  ConvertFormat: Unknown format encountered: 65`

I'm using remix-0.2.0 unmodified, and the game is DX8 so I'm using dxwrapper to wrap it to DX9. The game was also modified in a hex editor to run at 1080p, however these issue occur with the default version of the game as well.

3070 ti
Driver 531.29

**Attach logs!**
- NvRemixBridge.log
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11458693/NvRemixBridge.log)

- d3d9.log
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11458700/d3d9.log)

- The game specific log will be named gamename_d3d9.log
[Barnyard - Copy - Copy_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11458697/Barnyard.-.Copy.-.Copy_d3d9.log)

**To Reproduce**
Simply make a new character in the game, and get past the introduction sequence. The location it starts you out at is where I tested.

**Expected behavior**
Remix is only actually path tracing when the sun is on-screen. Enabling `In View Transform` for the `Fused World-View Mode` setting fixes this. However geometry will still rotate during daytime hours. 

I'm not sure where the Unknown Format warning is stemming from however. The geometry hash debug view also flickers intensely.

**Screenshots**
I have attached a video: https://cdn.discordapp.com/attachments/1106420949257044061/1106423673734303774/2023-05-11_23-29-10.mp4
It has a lot of flickering, be warned.

**Comment by AlexDunn** [comment]
Interesting, looks like alot is wrong here.  

Is this a shader based game?  If so, we can try disabling the  "Use World Transforms" feature.  It's useful in fixing unwanted movement/jitter for some games...

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/19891226/043640d7-6966-4a02-afa1-e066e5d4662b)

**Comment by Kim2091** [comment]
Thanks for the response! It is indeed shader based, with the entirety of the terrain being rendered through shaders. As for `Use World Transforms`, it's disabled already and sadly the rotation issue still persists.

However, removing the skybox on the game level rather than through Remix did fix the rotation issue. Without a skybox though the game is very dark. There is a workaround (selecting a seemingly random texture in the game as a sky texture), but it ends up with the game being green:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/f4453d74-ff1d-4a42-a115-56a3b504c9db)


This game is also very noisy compared to other games. I believe this is related to the shader based terrain, as there are also many visible artifacts on the ground. In addition, small amounts of movement can cause intense trailing noise artifacts (This is running at 1080p with DLSS Quality, which looks fine in most other games): 

https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/598128b2-fbd2-40a9-a56b-c282e4cd17ed

**Comment by Kim2091** [comment]
Actually sorry for the confusion, but that was on a build of the Remix runtime from 4 days ago. The very latest builds have fixed the rotation bug even with the original skybox in place, no game mods necessary! The noise issue does remain however, along with the artifacts on geometry

**Comment by Kim2091** [comment]
Disabling `Capture Normals from Shader` fixes both the strange geometry appearance and the intense noise! The only issues remaining are culling and unstable geometry hashes now

**Comment by Kim2091** [comment]
The game is now crashing any time I alt-tab. This issue started randomly and I cannot find the cause. It happened previously, but mysteriously resolved itself

Logs:
[Barnyard 1440p_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11632931/Barnyard.1440p_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11632934/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11632936/NvRemixBridge.log)

**Comment by Kim2091** [comment]
The previous issue is resolved, however this is still present: https://github.com/NVIDIAGameWorks/rtx-remix/issues/181

**Comment by Kim2091** [comment]
I will be closing this issue in favor of a new, reworked issue documenting issues that were not present in the original post.
