### ISSUE TITLE
Torchlight II: Game crashes when main menu is loaded

### ISSUE THREAD

**Issue by Expack3** [NVIDIAGameWorks/rtx-remix#149]
**Describe the bug**
- The game crashes whenever the main menu is loaded.
- 0.2.0
- Nvidia GeForce RTX 3060 Laptop
- 531.79
- v.1.25.5.6, Steam

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11464987/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11464982/d3d9.log)
- [Torchlight2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11464985/Torchlight2_d3d9.log)
- [Torchlight-20230512-101348-33812-18976.dmp](https://github.com/NVIDIAGameWorks/rtx-remix/files/11464968/Torchlight-20230512-101348-33812-18976.zip)

**To Reproduce**
1. Run the game through Steam. When prompted, run without mods.
2. When presented with a black screen, wait until game crashes. It should display its crash handler interface.

**Expected behavior**
Game should load into the main menu without incident.

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by Expack3** [comment]
This issue no longer occurs when using the release versions of dvk-remix a911c31-540 and bridge-remix-c062326-70 so long as the following RTX.conf file is used:
[rtx.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/15226623/rtx.zip)
