### ISSUE TITLE
Zeno Clash (2009) fails to lock DX8 vertex buffer

### ISSUE THREAD

**Issue by Expack3** [NVIDIAGameWorks/rtx-remix#15]
When attempting to run a fresh install of Zeno Clash (2009) using rtx-remix 0.1.0 without modifying any settings in the config file, the game CTDs with the following error:

```---------------------------
Engine Error
---------------------------
failed to lock index buffer in CMeshDX8::LockIndexBuffer

---------------------------
OK   
---------
------------------
```
Attached is the crash logs generated by the game, as well as the RTX Remix output log, which also includes my GPU information: [ZenoClash_rtxremix0_1_0_crashlog_1242023.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11214845/ZenoClash_rtxremix0_1_0_crashlog_1242023.zip)

**Comment by NV-DM** [comment]
Thank you for reporting. When is the crash happening? Is it on launch?

**Comment by Expack3** [comment]
The crash happens directly after the opening videos.

**Comment by Expack3** [comment]
Just tested against remix-0.1.1, and the game now launches.
