### ISSUE TITLE
Call of duty 2 see through walls

### ISSUE THREAD

**Issue by DoomDude531** [NVIDIAGameWorks/rtx-remix#150]
**Describe the bug**
- Everything is transparent except for the players weapons
- remix 0.2.0
- MSI 2070 super
- 531.79
- 1.2 (Steam)

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11467085/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11467087/d3d9.log)
- [CoD2SP_s_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11467090/CoD2SP_s_d3d9.log)

**To Reproduce**
Get in game

**Expected behavior**
For walls to be opaque

**Screenshots**
![COD 2](https://github.com/NVIDIAGameWorks/rtx-remix/assets/76069060/e0c30378-4927-4f72-a6c7-2df9fc76832c)

**Comment by mralexs5** [comment]
How are you getting it to work with Remix? I can get it to hook but it won't do any ray tracing

**Comment by baehny** [comment]
@mralexs5 you can toggle the DirectX version in the graphics settings. It worked for me when setting it to DirectX 7 and also using the d3d8on9 DLL.

I think some of the transparency issues might be related to how COD impements texture blending for world geometry:
https://www.youtube.com/watch?v=SH8ABbY5eas#t=10m58s

Atleast in the cod4 map editor there are two geometries layered on top of each other. One with the a transparent texture and one with opaque texture.

**Comment by pkristof** [comment]
Hi,

Thanks for the feedback. Here are a few suggestions how to handle this scenario better and/or how to workaround some of the issues as we are working on improvements to the RTX Remix runtime.

You can use `Terrain Baking` system that was just merged to the RTX Remix runtime. Get a latest `dxvk-remix` build from [https://github.com/NVIDIAGameWorks/dxvk-remix/actions](https://github.com/NVIDIAGameWorks/dxvk-remix/actions). The terrain baking system is in experimental stage, but you can already tag textures as `Terrain Textures` that are composed of multiple blend layers on top of each other (i.e. snow, mud, etc). The baker will bake them into a single terrain texture that's then sampled during path tracing. For this to work properly you need to identify vertical axis as the terrain system bakes the layers from top to bottom. By default Y axis is the up axis. You can identify if Z axis is the up axis instead by looking at normals of ground surfaces via DebugView's Normal view. If the ground is blue then you need to set Z axis as up  i.e. `rtx.zUp = True`. If it's green then the default Y axis is correct. RGB color coding corresponds to XYZ axes. With that set up, you need to tag corresponding textures in the Terrain Textures list. 

The terrain system works for ground/horizontal features that are to be blended. For vertical features, you can tag textures as decals. You pointed out that the game has two layers on top of each other. Try tagging the translucent wall layer that's to be blended on top as a decal. There are multiple lists, `Dynamic Decal Textures` list may work better here. If that doesn't work, you can add the textures to the `Ignore Textures` list.

Last, as a workaround for the background features rendering on top , set following setting in `rtx.conf`:
`rtx.skipDrawCallsPostRTXInjection = True`

Let us know if you any further feedback, especially around the `Terrain Baker` system in this case.

**Comment by Blisto91** [comment]
Remember running into a similar issue (might not be exact same) when testing regular dxvk a while back. Back then it was because i had accidentally left a dxvk.conf with `d3d9.forceSwapchainMSAA = 0` while it was turned on ingame.

**Comment by tadpole3159** [comment]
setting r_drawsun "0" fixes this issue. not sure what that has to do with decals but it's perfect after that. or you can use this config file if you wish
