### ISSUE TITLE
Textures get shown as scrambled symbols

### ISSUE THREAD

**Issue by alfonslm** [NVIDIAGameWorks/rtx-remix#158]
**Describe the bug**
- A clear and concise description of what the bug is. - textures get shown as scrambled symbols
- Which Remix version - Release 0.2.0
- Which GPU - 4070Ti
- Which GPU driver version - DCH 531.61
- Which game build (and whether it is from Steam/GOG/Other) - C&C Generals (Disk release)

**To Reproduce**
1. Run the game
2. Start a map
3. Check the textures in the dev options

**Expected behavior**
Display the textures as a representation that will help identify them visually. 

**Screenshots**
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/10770782/0211f974-55a7-4301-a94a-441c95e86f56)

**Comment by alfonslm** [comment]
I have not tried Vampire the Masquerade yet but this isn't workable 
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/10770782/638b9a46-9cef-48f4-8edd-4d552de43ea0)

**Comment by Ferdam** [comment]
In the first screenshot, it looks like there are just a few of these. But latest screenshot shows a bunch of them. Could you confirm if all textures are showing up as "scrambled symbols"? Or is it the case where you can see dozen of these but also some actual model textures?

Anyway, these are usually just text UI elements. Maybe game has some different way of rendering UI elements which creates one texture for each UI element?

**Comment by alfonslm** [comment]
The first half of the textures did have a clear majority of correctly shown textures but the second half only have a handfull of them

**Comment by alfonslm** [comment]
It's a picked sample to show the extent of the issues but it was neither planned, expected or hard to find

**Comment by AlexDunn** [comment]
I believe this was fixed!  Have you tried the Github builds from this commit: https://github.com/NVIDIAGameWorks/dxvk-remix/commit/dadeb4b55911473a5d434117af15b8f04888c54d

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by CattoSalad** [comment]
I believe this also has been fixed. I have been actively using it and texture previews match the texture ingame.

**Comment by alfonslm** [comment]
I should probably check it out again, could be something with that game engine that causes the issue. I think that I will have to install the game again so I will put a reminder for it.
