### ISSUE TITLE
Vampire: The Masquerade - Bloodlines texture issues

### ISSUE THREAD

**Issue by DrSharky** [NVIDIAGameWorks/rtx-remix#159]
**Describe the bug**
- At first, I loaded the game with the same configuration as below, but I saw many objects and surfaces have red looking textures as first. I believe this is because I previously tried to load the game with RTX Remix about a month ago, and changed the Remix developer settings. This is shown in the first screenshot. After turning off "Debug Mode", I began to see every object and surface with a blank white texture, which is shown in the 2nd screenshot provided below. Finally, I pressed the button to reset ALL settings, and that was when I was seeing the issues shown in the 3rd and 4th screenshot. Those two screenshots are taken in the same place, looking in the same direction. The textures appear to flicker occasionally, from normal, and then back to a black surface. It becomes worse and turns completely black if I turn the player to look in certain directions.
Lastly, I pressed Escape to return to the menu, and that is when I saw the problem in the final screenshot, where the menu is not displaying properly. I checked the game setup after I pressed Reset Settings, and the UI textures and terrain textures were still selected, so I am not sure if that is the issue.

- I am using RTX Remix version 0.2.0.
- My GPU is: NVIDIA GeForce RTX 4090.
- My installed GPU drive is: NVIDIA Studio Driver, version 531.61, Release date 04/13/2023
- The game build is official 1.2, with the unofficial patch version 11.3 installed. The game is from Steam.

**Attach logs!**
- NvRemixBridge.log: [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11480588/NvRemixBridge.log)
- d3d9.log: [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11480589/d3d9.log)
- The game specific log will be named gamename_d3d9.log [Vampire_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11480594/Vampire_d3d9.log)
 - DxDiag: [DxDiag.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11480586/DxDiag.txt)

**To Reproduce**
1. Launch Vampire: The Masquerade - Bloodlines in windowed mode with the newest version of the RTX Remix runtime (at time of writing this bug, it is 0.2.0).
2. Enter a map or saved game.
3. View the graphical issues that are occurring as a result.

**Expected behavior**
I would expect that when loading into the game, that there is not an immediate graphical issue such as the textures turning completely black.

**Screenshots**
Screenshot 1, with the red problem as described above. This occurred when I had "Debug mode" on in the developer settings of RTX Remix.
![20230515134356_1](https://github.com/NVIDIAGameWorks/rtx-remix/assets/16927040/c967ea2e-c997-467b-aead-d638fcbb80be)
Screenshot 2, with the all-white texture problem described above. This happened when I had turned off "Debug mode" in the developer settings of RTX Remix.
![20230515135203_1](https://github.com/NVIDIAGameWorks/rtx-remix/assets/16927040/3f6a7993-e1c9-408f-a322-62d426231818)
Screenshot 3, with the all-black texture problem described above. I believe it is a texture problem and not a lighting problem. This is what was happening when I returned the developer settings to default by pressing "Reset settings" in RTX Remix.
![20230515135412_1](https://github.com/NVIDIAGameWorks/rtx-remix/assets/16927040/12952283-667f-4aca-bbac-49308b7ddb36)
Screenshot 4, this is what I think I should be expecting when loading the game maybe? It looks like the textures are loading correctly, but it will return to the problem in screenshot 3 very often, and it will stay completely black when looking in most directions.
![20230515135413_1](https://github.com/NVIDIAGameWorks/rtx-remix/assets/16927040/2887b0eb-3286-4328-a7ad-38908eac0cad)
Screenshot 5, this is what I am seeing after pressing Escape and returning to the main menu after entering the map. It should be noted that the main menu UI works fine for me when starting up the game before loading the map.
![20230515135424_1](https://github.com/NVIDIAGameWorks/rtx-remix/assets/16927040/ea6f53c0-4093-4409-8d2e-30ae48afc974)

**Comment by Ferdam** [comment]
Could you please include a screenshot of how it looks like with Debug Mode enabled for Geometry Hash?

**Comment by DrSharky** [comment]
> Could you please include a screenshot of how it looks like with Debug Mode enabled for Geometry Hash?

I can see the option "Enable Debug View" and when I had that on, it looked like the first screenshot in my original post. I am not sure where to find any options related to Geometry Hash.

However, after talking with a friend, they did manage to get better results than I did, and they gave me this advice. 
First, we set the game's launch parameters to contain: -dxlevel 70, which sets the game to use DirectX 7.
With these settings, we get the following results. I believe it is showing objects that are found in the 3d skybox, but not any of the textures nearby. More info below.

![20230524151929_1](https://github.com/NVIDIAGameWorks/rtx-remix/assets/16927040/2a95e3f1-a755-45c9-a9d2-5af6be6ee233)

But, if we go into the game console by using the ~ key, and set the r_3dsky to 0 instead of 1, then we get the following results.

![20230524151942_1](https://github.com/NVIDIAGameWorks/rtx-remix/assets/16927040/ba74deb0-453c-4d1b-8737-64d731487c13)

These two screenshots are taken from the exact same position.
Something to do with the 3d skybox, which is less about textures, but I'd like to document as much as possible. That can be broken into a separate issue, though.

**Comment by Ferdam** [comment]
Yep! Looks great
Be sure to check how people got HL2 to work with Remix and you may be able to get path tracing to work (case it isnt yet)
There are a few tricks (console commands mostly) that will make it more compatible.

Good luck! 😎

**Comment by DrSharky** [comment]
I suppose I'll close this for now, after consideration. The original texture issues were my own fault setting "Debug Mode" or not using the 3d skybox set to 0 option.
I'd prefer Remix work alongside games with this 3D skybox rendering strategy, but that's a separate issue that is not unique to Vampire: The Masquerade - Bloodlines.
