### ISSUE TITLE
Memory Read/Write Error - Remix Server Setup

### ISSUE THREAD

**Issue by JP111555** [NVIDIAGameWorks/rtx-remix#160]
**When Remix tries to boot up 18 Wheels of Steel: Extreme Trucker 2, it throws this error on the server side 
Exception 0xc0000005, a memory read/write error.**

- When I try to boot into the game using Remix. It hooks into the game but the Bridge server refuses to create and crashes immediately causing an eventual Black Screen crash to the game.
 
Remix 0.2 - Stable 
- RTX 3060
- 531.79 - Game Ready Driver
- Build 1.0 - Steam

**Logs**
To make this easier to reproduce, I will keep all bridge settings and additional files I used in trying to circumvent this at their defaults as they don't seem to impact the outcome of the bug.

- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11482685/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11482683/d3d9.log)
- [extremetrucker_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11482678/extremetrucker_d3d9.log)

**To Reproduce**
1. Go to 18 Wheels of Steel: Extreme Trucker 2 Config file (Found in documents under C:\Users\<USER>\OneDrive(if you have it)\Documents\18 WoS Extreme Trucker 2\config.cfg) and paste this in:
[config.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11482702/config.txt)
'Changes engine to DX 9, forces windowed screen and also should set graphics to minimum, however you may have to do that yourself'
2. Save config.cfg
3. Go to 'Steam'
4. Click on '18 Wheels of Steel: Extreme Trucker 2, or click on it's .exe file in file explorer'
5. Navigate to the game files under 'C:\Program Files (x86)\Steam\steamapps\common\18 WoS Extreme Trucker 2\bin\win_x86'
6. Navigate to the bridge log under .trex folder
7. See error

**Expected behavior**
Upon clicking 18 Wheels of Steel: Extreme Trucker 2, the game will briefly show a white screen before turning black then crashing with no error messages popping up after. 

**Screenshots**
**White Screen**
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/77561912/efeaee93-6520-46d8-afe8-6ec58c2bf6b1)

**Black Screen**
'Black Screen does not allow me to take a screenshot. But it comes after the white screen. Waiting times for the screen to appear black vary.'

**Comment by Sertelegger** [comment]
@JP111555 there isn't enough information in the description to understand what your issue is. Can you please fill out the bug form and let us know what game, GPU, attach logs etc.?

**Comment by SSertel** [comment]
@JP111555 there isn't enough information in the bug description to understand your issue. Can you please fill out the bug template and what game, GPU etc. you are running on and attach log files?

**Comment by JP111555** [comment]
*Also I didn't mean to close that comment. I really suck at Github lol*

**Comment by JP111555** [comment]
> @JP111555 there isn't enough information in the description to understand what your issue is. Can you please fill out the bug form and let us know what game, GPU, attach logs etc.?

Everything should be filled out now. Sorry, I accidentally hit enter before filling everything out.

**Comment by JP111555** [comment]
Ighty, I made a new issue post one where I didn't close the issue accidentally. Link is [here](https://github.com/NVIDIAGameWorks/rtx-remix/issues/161)
