### ISSUE TITLE
Fallout New Vegas: Multiple Bridgecommand instances

### ISSUE THREAD

**Issue by adamplayer** [NVIDIAGameWorks/rtx-remix#163]
**Describe the bug**
- A clear and concise description of what the bug is.
When FNV loads in textures, it seems to create multiple bridgecommand instances.
- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
0.2
- Which GPU
RTX 3080
- Which GPU driver version
535.5

- Which game build (and whether it is from Steam/GOG/Other)
GOG

**Attach logs!**
[FalloutNV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11511536/FalloutNV_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11511538/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11511539/NvRemixBridge.log)
[CobbCrashLogger.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11511510/CobbCrashLogger.log)

**To Reproduce**
1. Load into an exterior cell or load into an interior map and then go outside.
2. Bridge throws exception that there are multiple bridge command instances. 

**Expected behavior**
Loads textures

**Screenshots**
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/94309006/956fafa7-08bb-494c-8867-c397d3bb981b)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/94309006/f661c582-a41c-46f3-a51b-8eedba2053e6)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/94309006/6ae5d0fc-4099-4992-8265-bc3d01f9adac)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/94309006/92afded0-6b7e-4197-9976-40557121ea97)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
