### ISSUE TITLE
World in Conflict: ALT + X input not working

### ISSUE THREAD

**Issue by RareKiwi** [NVIDIAGameWorks/rtx-remix#164]
**Describe the bug**
- ALT + X input not working
- Remix 0.2.0
- RTX 3070
- driver version: 531.41

**logs**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11515327/NvRemixBridge.log)  
[z3D9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11515329/z3D9.log)  
(bridge d3d9.dll is renamed and wic.exe is hex edited in order to load it instead of the one in system)  
[wic_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11515332/wic_d3d9.log)

**To Reproduce**
0. Bridge d3d9.dll is renamed to z3d9.dll and wic.exe is hex edited (first two found) to load it instead of the one in system
2. Start wic.exe, ensure windowed is enabled and dx10 is disabled in game options
3. Press cancel on the graphics card warning to bypass it and load the game.
4. At the main menu of the game, attempt to press ALT + X

**Expected behavior**
Overlay shows that remix has loaded in game, but the input to enable the menu is non-functional.
I've also tried with `client.hookMessagePump = True` enabled in bridge.conf

Game is available on [GOG ](https://www.gog.com/en/game/world_in_conflict_complete_edition) or the sierra version is available for download at [massgate.org](https://www.massgate.org/downloads.php)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
