### ISSUE TITLE
The Matrix - Path of Neo white screen

### ISSUE THREAD

**Issue by Tarasus** [NVIDIAGameWorks/rtx-remix#166]
- A clear and concise description of what the bug is.
NVRemixBridge crash on startup, white screen in game, sounds and keyboard/mouse inputs continue to work

- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
remix-0.2.0

- Which GPU
Gigabyte RTX 4080 Gaming OC

- Which GPU driver version
Game Ready 531.68

- Which game build (and whether it is from Steam/GOG/Other)
The Matrix: Path of Neo DVD-ROM Edition V. 1.1

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11522534/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11522535/d3d9.log)
- [Matrix3W32S.bin_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11522536/Matrix3W32S.bin_d3d9.log)

**To Reproduce**
- Steps to reproduce the behavior:
Extract .zip from releases into game folder with exe
Start the Matrix3.exe
See white screen instead of visual output, but hear sounds and reaction sounds to inputs

**Expected behavior**
Run the game with RTX Remix

**Screenshots**
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/11211913/06ab2a40-8720-42a3-9bce-b61b718eb868)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by Tarasus** [comment]
It works now! Thank you!
