### ISSUE TITLE
XIII (2003) anti-culling corrupts water

### ISSUE THREAD

**Issue by DoomDude531** [NVIDIAGameWorks/rtx-remix#167]
**Describe the bug**
- When I enable anti-culling the water looks corrupted
- Commit 6b4fe7d
- MSI 2070 super
- 531.79
- 1.4.2.1 (GOG)

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11525381/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11525383/d3d9.log)
- [XIII_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11525385/XIII_d3d9.log)

**To Reproduce**
Enable anti-culling and look at the water

**Expected behavior**
For the water to look normal

**Screenshots**
![XIII](https://github.com/NVIDIAGameWorks/rtx-remix/assets/76069060/1947e9a5-b803-43fb-a31c-53643186c33c)

**Comment by xbei-nv** [comment]
We updated code to enable bounding box by default when anti-culling is enabled. You could try it in latest build.

**Comment by DoomDude531** [comment]
While the latest version has improved it significantly, there is still some weird artifacts.

https://github.com/NVIDIAGameWorks/rtx-remix/assets/76069060/04eaa810-c451-4eb2-9090-2c6b661132ff

**Comment by xbei-nv** [comment]
Ok thanks for sharing, we will continue investigate on this issue

**Comment by xbei-nv** [comment]
We have pushed fix for this issue, could you check if it's still existing?
