### ISSUE TITLE
peter jacksons king kong unexpected error

### ISSUE THREAD

**Issue by howdoicodeplease** [NVIDIAGameWorks/rtx-remix#169]
**Describe the bug**
peter jacksons king kong has unexpected error when booting nvidia remix
Remix 0.2
rtx 3070 ti
latest GPU drivers
other

**Attach logs!**

[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11530224/NvRemixBridge.log)

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11530229/d3d9.log)

[SettingsApplication_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11530235/SettingsApplication_d3d9.log)
[KingKong8_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11530236/KingKong8_d3d9.log)
[CheckApplication_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11530238/CheckApplication_d3d9.log)
there are 3 ways of opening the game so included all 3 logs

**To Reproduce**
click on exe

**Expected behavior**
game should run

**Screenshots**

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
