### ISSUE TITLE
dead rising 2

### ISSUE THREAD

**Issue by howdoicodeplease** [NVIDIAGameWorks/rtx-remix#170]
**Describe the bug**
crashes after loading intro cutscene
remix 0.2
rtx 3070 ti
latest gpu driver version
steam

**Attach logs!**

[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11534612/NvRemixBridge.log)

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11534607/d3d9.log)
[deadrising2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11534609/deadrising2_d3d9.log)

crash log
[crash_0522_184637.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11534613/crash_0522_184637.txt)

**To Reproduce**
click on game on steam

**Expected behavior**
game should run

**Screenshots**
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/105949717/b43693cc-85b6-4df1-b306-594479fb4169)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
