### ISSUE TITLE
[Request] Add "Feature Request" issue template

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#171]
As of right now, there's only a "Bug Report" template. There's been a lot of confusion about where to submit feature requests on the discord server, and this would do a lot to clear it up. Thanks!

**Comment by AlexDunn** [comment]
This is a great suggestion.  We'll have a think internally on the best way to write that up and get back to you

**Comment by NV-LL** [comment]
Thank you for your suggestion! We've added a template for a [Runtime Feature Request](https://github.com/NVIDIAGameWorks/rtx-remix/issues/new?assignees=&labels=feature%2Cruntime%2Ctriage&projects=&template=runtime_feature_report.yml&title=%5BRuntime+Feature%5D%3A+) and a [Toolkit Feature Request](https://github.com/NVIDIAGameWorks/rtx-remix/issues/new?assignees=nvdamien&labels=feature%2Ctoolkit%2Ctriage&projects=&template=toolkit_feature_report.yml&title=%5BToolkit+feature%5D%3A+). Please let us know if you have any other requests!
