### ISSUE TITLE
Fallout New Vegas fails to launch with large rtx.conf

### ISSUE THREAD

**Issue by adamplayer** [NVIDIAGameWorks/rtx-remix#172]
**Describe the bug**
When using an (absurdly) large rtx.conf, rtxremix fails to initialize the d3d9 device when trying to launch New Vegas.

**Attach logs!**
[rtx.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11559792/rtx.txt) - It doesn't like `.conf` files.
[FalloutNV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11559809/FalloutNV_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11559810/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11559811/NvRemixBridge.log)
[NvRemixBridge.exe_20230524_190326.dmp.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11559812/NvRemixBridge.exe_20230524_190326.dmp.zip)

**To Reproduce**
1. Fill out tens of thousands of hashes in a rtx.ignoretextures 
3. Attempt to launch game
4. No render will be found by the game.

**Expected behavior**
Ignore the tens of thousands of textures.

**Screenshots**
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/94309006/025917d4-161d-4bd6-9b74-84becef076c1)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
