### ISSUE TITLE
rtx.ignoreTextures behaves differently from usda inputs:ignore_material

### ISSUE THREAD

**Issue by BlueAmulet** [NVIDIAGameWorks/rtx-remix#173]
**Describe the bug**
When removing objects with inputs:ignore_material, a dark gray version of the mesh is drawn instead. If rtx.ignoreTexture is used, the object is removed as expected.
dxvk-remix https://github.com/NVIDIAGameWorks/dxvk-remix/commit/e010672cb5d11273a9462cbcdef85a8e75dc3380 using https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/5094526795
bridge-remix: https://github.com/NVIDIAGameWorks/bridge-remix/commit/4d6dc564e3fcdbadefd972589e0d902bffa87256 using https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/5095209923
NVIDIA GeForce RTX 3050
Driver Version 531.79
Game: Fallout New Vegas GOG

**Attach logs!**
I don't believe logs are relevant for this issue, but I can upload if requested.

**To Reproduce**
1. Find hashes of textures to ignore
2. Create a usda of the follow
```
#usda 1.0
(
    upAxis = "Z"
)

over "RootNode"
{
    over "Looks"
    {
        over "mat_2F6B08234982561E"
        {
            over "Shader"
            {
                bool inputs:ignore_material = 0
            }
        }
    }
}
```

**Expected behavior**
inputs:ignore_material should fully remove the object as well and not leave behind an odd gray untextured version instead.

**Screenshots**
When using rtx.ignoreTextures:
![2023-05-24_220458](https://github.com/NVIDIAGameWorks/rtx-remix/assets/43395286/6f921f43-73a2-416d-91de-e657dcdb1e82)

When using a usda with inputs:ignore_material:
![2023-05-24_220311](https://github.com/NVIDIAGameWorks/rtx-remix/assets/43395286/d33a9359-bc70-422c-af67-53b6be273ffc)

**Comment by BlueAmulet** [comment]
As of https://github.com/NVIDIAGameWorks/bridge-remix/commit/4d6dc564e3fcdbadefd972589e0d902bffa87256 the patched bridge-remix is no longer required. I have retested with the latest nightlies for both bridge-remix and dxvk-remix and can confirm this issue still occurs.

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
