### ISSUE TITLE
The Sims 2 Fails to Inject

### ISSUE THREAD

**Issue by adamplayer** [NVIDIAGameWorks/rtx-remix#177]
**Describe the bug**
Latest nightly builds of DXVK and Bridge as of 5/29. 
Launching the game seems to crash on creation of render targets? This game always had an issue with render targets being used improperly. Crashes clean with no dumps or solid trace of what's going on. I was able to pull this info from x32DBG:
```
0351E7D4  01332BE0  sims2ep9.01332BE0

0351E7E4  6B6BC984  return to d3d9.Bridge<BridgeId::Device>::Command::send_data+A4 from d3d9._memcpy

0351E804  6B6D6F96  return to d3d9.Direct3DDevice9Ex_LSS<0>::SetPixelShader+176 from d3d9.public: __thiscall Bridge<struct BridgeId::Device>::Command::~Command(void)

0351EABC  6B6F7C21  return to d3d9.Bridge<BridgeId::Device>::syncDataQueue+4A1 from d3d9.@__security_check_cookie@4

0351EDD8  6B6CAB06  return to d3d9.Direct3DDevice9Ex_LSS<0>::CreateRenderTarget+206 from d3d9.@__security_check_cookie@4
```

**Attach logs!**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11595655/NvRemixBridge.log)
[_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11595658/_d3d9.log)
[Sims2EP9_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11595659/Sims2EP9_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11595672/d3d9.log)

**To Reproduce**
1. Launch game
2. Game crashes

**Expected behavior**
Game injects and runs

**Screenshots**
N/A

**Comment by NV-DM** [comment]
Could you please confirm if this issue still occurs? Thanks.

**Comment by adamplayer** [comment]
This issue has been resolved. Game now has https://github.com/NVIDIAGameWorks/rtx-remix/issues/224?notification_referrer_id=NT_kwDOBZ8KjrM3MzExOTAyMjg0Ojk0MzA5MDA2#issue-1840332045 instead.
