### ISSUE TITLE
light textures breaks selecting as worldspaceui

### ISSUE THREAD

**Issue by baazthefalcon** [NVIDIAGameWorks/rtx-remix#180]
**Describe the bug**
- A clear and concise description of what the bug is.
Selecting textures as worldspaceui breaks texture after loading next time mostly happens to lights, in order to fix it have to deselect as  worldspaceui then select ui which will rasterize the game partially sometimes the whole game then deselect ui which will also fix breaking texture then selecting as worldspaceui works but again after game loads next stage it breaks.
![texture break](https://github.com/NVIDIAGameWorks/rtx-remix/assets/135221005/3761d2ec-7009-446e-bbc0-e4a88c83d4a7)
- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
Remix 0.2, DXVK Remix release 90/93, Bridge Remix release 6, but doesn't matter happening all the older versions
- Which GPU
Galax RTX 2060 Super 
- Which GPU driver version
Latest Driver 532.03 anyway was happening before updating too
- Which game build (and whether it is from Steam/GOG/Other)
Using NFS Underground ver1.4, it is happening in Underground 2 also can't see the version.

**Attach logs!**
- NvRemixBridge.log
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11624113/NvRemixBridge.log)
- d3d9.log
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11624098/d3d9.log)
[d3d9_01.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11624099/d3d9_01.log)
- The game specific log will be named gamename_d3d9.log
[speed_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11624101/speed_d3d9.log)

**To Reproduce**
1. Go to in-game, selecting any race
2. select the car taillight textures as worldspaceui which is easy because its always on screen
3. then restart the race 
4. it breaks the texture ( it also breaks with hiting with speed)

**Expected behavior**
lights texture should not break by hitting the car or after next load
https://www.youtube.com/watch?v=dKGg9_6ef2k
**Screenshots**

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by baazthefalcon** [comment]
this issue was fixed already, i forgot this is up thanks for reminding, i am closing it
