### ISSUE TITLE
Bridge is crashing shortly after alt-tab

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#182]
**Describe the bug**
Any time I Alt-Tab in Barnyard, the Remix bridge crashes or closes soon after. If I'm quick enough, I can click back into it and it will not crash. However if I leave it for 30 seconds, the bridge closes. The game is still running as I can hear it afterward and move around, but the visuals are frozen. This is typical behavior of the bridge crashing from past experience with it.

-   Remix build: 77900b5 (and many earlier ones)
-   Bridge build: 4d6dc56 (but all of the builds that I've tested since the 0.2.0 launch do this)
-   3070 ti
-   531.29 and 535.98
-   Barnyard: Retail

**Attach logs!**
[Barnyard.1440p_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11637614/Barnyard.1440p_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11637615/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11637616/NvRemixBridge.log)

**To Reproduce**
Install Barnyard
Install the latest Remix and Bridge builds
Alt-tab out of the game and leave it for at least 30 seconds. It appears to happen most consistently when the game window is minimized or when the window is hidden behind another

**Expected behavior**
The game should remain stable, and the bridge should not close

There's a discussion about this in the Remix Discord server as well: https://discord.com/channels/1028444667789967381/1114261497187667978

**Comment by SSertel** [comment]
Matching dump files for this issue:
[NvRemixBridge.exe_20230602.dmp.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11638207/NvRemixBridge.exe_20230602.dmp.zip)

**Comment by Kim2091** [comment]
This is occurring with other games for me now. This just happened with Skyrim as well. Logs:
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11644173/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11644174/d3d9.log)
[TESV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11644175/TESV_d3d9.log)

Given that dump files are not being generated in combination with these other crashes, the dmp files uploaded above may not actually be directly related

**Comment by baazthefalcon** [comment]
same thing is happening with me in GTA San andreas

**Comment by Kim2091** [comment]
Additional info: It seems to crash mostly when there's 3d stuff going on, rather than an intro video or 2d. I alt-tabbed 5 times on the intro screen and it was fine, but if I alt-tab on the the main menu with 3d and path tracing, it crashes immediately.

Here's 2 more dump files that appear to be related to this issue: 
[dumps.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11654710/dumps.zip)

Latest logs:
[Barnyard_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11654712/Barnyard_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11654713/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11654739/NvRemixBridge.log)

**Comment by Kim2091** [comment]
This appears to be resolved with Bridge build [a18db5f](https://github.com/NVIDIAGameWorks/bridge-remix/suites/13451474078/artifacts/737749509)!
