### ISSUE TITLE
Debug Build usability issues

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#184]
### Issue
It'd be great if `enableValidationLayers` in `dxvk_instance.cpp` from the `dxvk-remix` repo were toggleable in a .conf file. This single setting renders the debug build unusable in many instances, and severely inhibits debugging games. The effect it causes: games take 5+ minutes just to load, and aren't usable at all even after that. You cannot interact with the games. It'd be very helpful to be able to toggle this setting manually without recompiling Remix

When it is forcibly disabled it in a custom debug build, it reduces the lag and delay significantly. This issue persisted across 7+ games in my testing, and is particularly bad with the latest debug builds

### System information
- GPU: 3070 ti
- Driver: 531.29 and 535.98
- DXVK version: 657a328 (and newer)

(this was originally posted in the dxvk-remix repo, but was moved here)

**Comment by nsubtil** [comment]
Yeah, VL is known for being pretty slow. We can look into adding a toggle for this.

FWIW, the reason we didn't implement a runtime toggle so far is two-fold: we use DebugOptimized a lot more often than Debug, and if we do need Debug, we are generally working in an IDE and can "configure" the build by modifying the constant directly in the code (which ends up being not much different than editing a config file). I'd be curious to know what other people are doing here, though --- are you trying to use Debug builds outside a development environment?

**Comment by Kim2091** [comment]
> Yeah, VL is known for being pretty slow. We can look into adding a toggle for this.
> 
> FWIW, the reason we didn't implement a runtime toggle so far is two-fold: we use DebugOptimized a lot more often than Debug, and if we do need Debug, we are generally working in an IDE and can "configure" the build by modifying the constant directly in the code (which ends up being not much different than editing a config file). I'd be curious to know what other people are doing here, though --- are you trying to use Debug builds outside a development environment?

I've been attempting to use debug builds to troubleshoot games when injecting Remix, usually with newer games that exhibit strange issues such as geometry rotation or missing objects in Remix vs the base builds. Basically the main appeal of these builds to me (and others) is the path tracing toggle which allows us to see the original game vs the Remix renderer. This allows us to identify issues with the new render, so we can either file a bug report or fix it ourselves if possible.

With how slow these builds are, I cannot even get into the game to begin debugging. Maybe I've misunderstood how to use these builds, or what the goal of them is? I also wasn't aware of DebugOptimized at all, as I've just been using the automated builds (which builds release and debug only)

**Comment by Kim2091** [comment]
I'm going to close this issue, as it was largely resolved by including debugoptimized in Actions builds.
