### ISSUE TITLE
GTA San Andreas not lauching correctly

### ISSUE THREAD

**Issue by BolinhoFofo69** [NVIDIAGameWorks/rtx-remix#186]
**Describe the bug**
- I putted the RTX Remix files in my GTA SA folder (d3d9.dll, .trex folder and the NvRemixLauncher32.exe). However, when i open the game (with compatibility mode) the icon does appear in the task bar but it doesn't actually happend nothing or even open the game properly, not even with ALT+TAB. And when i turn off the compatibility mode, the game opens but it only appears a black screen which keeps on forever. Also strangely, my CPU usage goes to like 80%. 
- Remix version 0.20 
- GPU: RTX 2060
- Driver: 535.98
- GTA SA version 1.0

**To Reproduce**
1. Download RTX Remix 
2. Paste the files in the GTA SA folder
3. Click on gta-sa.exe

**Expected behavior**
The game opening normally and the rockstar logo appearing.

**Comment by baazthefalcon** [comment]
It does why u dont check the thread first.

**Comment by BolinhoFofo69** [comment]
> It does why u dont check the thread first.

I mean, maybe for you it did and that's good, but for me it didn't work at all.

**Comment by baazthefalcon** [comment]
are u in rtx remix discord server ?... no then join ...if yes then go to community section theres a remix-projects/Gta-sa thread... any way game works...use remix 0.2 + latest bridge + latest dxvk remix (dxvk remix files goes under the trex folder)

**Comment by BolinhoFofo69** [comment]
> 



> are u in rtx remix discord server ?... no then join ...if yes then go to community section theres a remix-projects/Gta-sa thread... any way game works...use remix 0.2 + latest bridge + latest dxvk remix (dxvk remix files goes under the trex folder)

Oh i will definitly try that! Thanks for the help!

**Comment by baazthefalcon** [comment]
did ur game run?

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by baazthefalcon** [comment]
there is no issue this needs to closed.

**Comment by NV-LL** [comment]
Thank you for confirming!
