### ISSUE TITLE
[Feature Request] Show Remix build version in GUI

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#187]
It'd be great for troubleshooting purposes if the Remix version (including the CI build number if it's a CI build) could be shown somewhere in the GUI, like the title bar. This would be very helpful when helping users through Discord, or for just understanding what's going on from a quick glance.

**Comment by anon-apple** [comment]
Alright I added this in commit [here](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/1e29acb450f6ff19a3aa24764c2694db126d2e82). It should be part of the next Remix release or is available now if you build locally.

The version is displayed in the About section of the developer settings as well as a button to copy it now:

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/131701566/ec4fc664-ecc6-4c7b-a6a1-eb30f357647c)

This change also adds the version to the traditional DXVK HUD (the one enabled with `dxvk.hud=1`) just so it is in more places too.
