### ISSUE TITLE
Emissive Map overwrites albedo/diffuse

### ISSUE THREAD

**Issue by countbuggula** [NVIDIAGameWorks/rtx-remix#188]
Emissive maps are overwriting the diffuse map.  Areas that shouldn't have any light (black or 0 value in emmissive) become black on the mesh.
remix: 62b0956
bridge: 4d6dc56
Observed on 3070 ti and 3060 ti, others likely.
driver 535.98
Barnyard, retail version
Note: also observed in Iron Storm.  Working on reproducing in other games for additional info.

**To Reproduce**
Add attached emissive map
Enable enhanced assets
Note: we tested this with rgb emissive map (black as zero value) as well as rgba.  Attaching both versions.

**Expected behavior**
Black areas of the emissive map should be transparent and not effect the albedo of the mesh.
**Screenshots**
![Original](https://github.com/NVIDIAGameWorks/rtx-remix/assets/578358/94f8eadc-442f-4115-b40c-5cf30a64cb84)
![Emissive_Transparent](https://github.com/NVIDIAGameWorks/rtx-remix/assets/578358/c9ce6331-451f-4656-a3a6-2b14db6bd312)
![Emissive2_Black](https://github.com/NVIDIAGameWorks/rtx-remix/assets/578358/95693e38-8ebe-4d47-a350-c55e684f0f43)
[mod.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11647858/mod.zip)

**Comment by anon-apple** [comment]
Emissive textures should already work like this (as in they should only add light on top of the original material's colors). By the looks of it your mod USD file does not have an albedo texture. When you replace a material like this it will override most things from the original game (other than a few things which are carried over like alpha state in some cases, vertex color, etc), so in this case the lack of the albedo texture in the USD is causing there not to be one when the material is replaced.

Easy fix for that should just be to set it to the original albedo texture the exporter exported along with the capture (this is how it usually exports by default if I am not mistaken).

**Comment by countbuggula** [comment]
Ok if I understand then correctly if it replaces a map it no longer loads any vanilla textures for that mesh.  So as long as we stick a diffuse map along with the emissive map in the mod directory it should work properly?

**Comment by countbuggula** [comment]
Ok we've confirmed that this method works.

My concern with this is that unless we create a brand new diffuse texture, we're forced to provide original assets from the game as part of a mod pack.  That doesn't sound like a good idea from a copyright perspective.

**Comment by countbuggula** [comment]
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/578358/a024cb90-c2c7-467f-8a22-05d9aec6d833)

**Comment by anon-apple** [comment]
Yes I could see how that might be an issue. Ideally you'd replace the original game's albedo with something "remastered" or whatever in addition to other PBR textures, but for simpler mods that may be a bit too much work.

We could potentially add a mode though in the material to indicate that the original game's color texture should be inherited as the albedo (similar to how you can conditionally override the alpha state from the game in the material).

**Comment by countbuggula** [comment]
> 

Yeah in most cases I think people will be upscaling or replacing textures, but having that functionality would be great in instances where it's not needed or wanted.  It would also keep us from having to distribute copyrighted assets in WIP mods where all original texture replacement hasn't been completed.

**Comment by anon-apple** [comment]
Yeah it's a fair use case, I'll add a task internally to track the request and close this issue for now since the original problem with why the albedo was missing has been resolved.
