### ISSUE TITLE
Need For Speed Prostreet Black screen 

### ISSUE THREAD

**Issue by krisis111** [NVIDIAGameWorks/rtx-remix#192]
When I open the game I only see a black screen but in the background the game is heard
- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
- RTX 3070
- Zotac RTX 3070
remix-0.2.0

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11689332/d3d9.log)
[nfsps_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11689338/nfsps_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11689341/NvRemixBridge.log)

![Sin título](https://github.com/NVIDIAGameWorks/rtx-remix/assets/73320176/3d91ccb4-0960-493c-a91d-be645e21911e)

Just open the game

**Comment by Ferdam** [comment]
Try enabling Debug Mod with Geometry Hash view and see if anything shows up
If not, it might have hooked to the point you see menu and all, but not to the point it can output path traced scene

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.

**Comment by NeHooYeY** [comment]
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/7e6cb291-2b1b-40bf-8c69-a1d19fd359c0" />
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/26a0a30e-41f1-4059-8a02-b6cd398cb3af" />
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/3dc7da3f-2d9b-493d-aa4d-708340cefbbf" />
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/ce8605bc-960e-4168-a7f3-a8bcc7179dff" />
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/875d72bf-269a-47ff-8ba2-d6ed0aca2f2d" />
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/befb6d3b-d522-47ae-a813-9b5ef1ad1321" />

That’s all I could get, geometry moves with camera, Ray tracing/Path Tracing turns off while I start driving faster, some areas won’t have it(revert to vanilla) no matter what I do, drive or stand still.
