### ISSUE TITLE
TAAU's "Jitter" shows in final render

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#194]
**Describe the bug**
The TAAU implementation doesn't appear to be working correctly. Even at reasonable resolutions, the "jitter" used in TAA solutions is showing in the final image. There also appears to be no real anti-aliasing going on.
- Remix version: cb1d0a3
- Bridge version: [a18db5f](https://github.com/NVIDIAGameWorks/bridge-remix/suites/13451474078/artifacts/737749509)
- 3070 ti
- 535.98
- Barnyard, Retail

**Attach logs!**
- NvRemixBridge.log
- d3d9.log
- The game specific log will be named gamename_d3d9.log

**To Reproduce**
1. Launch any Remix game at a resolution of 1080p
2. Enable TAAU
3. Compare with other renderers at native resolution (or lower) and observe the jitter

**Expected behavior**
TAAU should be applying anti-aliasing, and hiding the jitter as part of that process. No anti-aliasing appears to occur, and only the jitter is passing through

**Example Video:**

https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/d689dbf7-de68-42a4-ac75-60cbb7ce88ea

Higher quality, non-embedded example: https://cdn.discordapp.com/attachments/1056847194809970748/1116927457350651944/TAAU_Example_High_Quality.mp4

**Comment by anon-apple** [comment]
This should be fixed now as of e23762e41ad8367af91a24686dbf789ee7cdcb3c.

The TAA wasn't broken exactly, it just had a bad default which essentially turned the temporal part of the TAA off in everything other than Source games (as hl2.exe had an application configuration defined for this for Portal RTX). You can fix this on older builds too by setting `rtx.temporalAA.newFrameWeight = 0.1`.
