### ISSUE TITLE
XIII (2003) Exploding models

### ISSUE THREAD

**Issue by DoomDude531** [NVIDIAGameWorks/rtx-remix#197]
**Describe the bug**
- Random models will go crazy with the latest build. It only seems to affects model that show up when capture vertices from shaders is enabled.
- Runtime c7778d8-117, Bridge bf0984b-11
- 2070 super
- 535.98
- 1.4.2.1 (GOG)

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11738771/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11738773/d3d9.log)
- [XIII_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11738775/XIII_d3d9.log)

**To Reproduce**
Get in game and swap through some weapons

**Expected behavior**
For models to be stable

**Screenshots**
potential epilepsy warning
[XIII_2023.06.08_-_01.22.54.01.webm](https://github.com/NVIDIAGameWorks/rtx-remix/assets/76069060/4d664678-e96c-4e1f-bc8d-734c46ddc819)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
