### ISSUE TITLE
Tony Hawk's Underground 2 crashes after initial loading screen

### ISSUE THREAD

**Issue by NolanMarch** [NVIDIAGameWorks/rtx-remix#199]
**Describe the bug**
- A clear and concise description of what the bug is.
The Game crashes after the launching videos finish.  A loading bar pops up but the game crashes soon after
- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
0.2.0
- Which GPU
RTX 3070
- Which GPU driver version
535.98
- Which game build (and whether it is from Steam/GOG/Other)
A download found on internet archive, probably ripped from a game disk. https://archive.org/details/thug-2-install

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11741915/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11741918/d3d9.log)
- [THUG2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11741920/THUG2_d3d9.log)

**To Reproduce**
1.  Launch the Game
2.  Wait for, or skip, the intro videos.
3.  Game crashes shortly after

**Expected behavior**
The game's main menu to load

**Screenshots**
[Video](https://www.youtube.com/watch?v=NJ21tNvlTwQ)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
