### ISSUE TITLE
Ford Racing 3 doesn't launch with the wrapper

### ISSUE THREAD

**Issue by Btheislandcar2313** [NVIDIAGameWorks/rtx-remix#2]
[fr3_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11212065/fr3_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11212066/d3d9.log)

**Comment by nv-ajaus** [comment]
REMIX-3476 for tracking.

**Comment by nv-ajaus** [comment]
Hi @Btheislandcar2313 , I took a look at this issue and made a change that I believe should help.

Can you please retry this game using this [bridge build](https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/10582008055/artifacts/1860699831) and the most recent  [dxvk-remix build](https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/10582252919/artifacts/1860843871)?

**Comment by NV-LL** [comment]
Hi @Btheislandcar2313 - we wanted to see if you've been able to re-test this issue as per the comment above. We also want to inform you about our stale ticket policy, namely that we will close this ticket as 'went-stale' if it does not receive a response in the next two weeks. Thank you!

**Comment by NV-LL** [comment]
Hi @Btheislandcar2313 - we're closing ticket as 'went-stale', as it hasn't received an update in the past month. You can reopen it here at any time if you'd like to continue investigating the issue.
