### ISSUE TITLE
Sid Meier's Pirates doesn't hook with official releases of Remix despite doing so with Portal with RTX files

### ISSUE THREAD

**Issue by BobaWithTheFire** [NVIDIAGameWorks/rtx-remix#200]
**Describe the bug**

While the game did hook with Remix using the Portal with RTX files, no version or build since works. The game will launch, audio can be heard of the opening movies and of the menu, but the screen is entirely black, save for the cursor icon. 

- Remix Build: Any (The logs are from Bridge build bf0984b and DXVK build c6356ac)
 
- GPU
  RTX 3070

- Driver Version
 535.98

- This was tested with the Steam version of the game.

**Attach logs!**
[D3D9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11745018/D3D9.log)
[Pirates!_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11745014/Pirates._d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11745020/NvRemixBridge.log)
Bridge minidump:
[NvRemixBridge.exe_20230614_070548.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11745038/NvRemixBridge.exe_20230614_070548.zip)

**To Reproduce**

- Copy the RTX Remix builds into the root folder of Sid Meier's Pirates.

- Launch the Game

**Expected behavior**
Game won't hook. All that can be seen is a black screen in the game window.

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.

**Comment by Millefeuille42** [comment]
This is because the executable launches the game virtualized, thus it uses system librairies instead of the local ones (but the launcher uses the local d3d9, explaining why you still got logs.)

I got it to work today, will issue a patch for Sid Meier's Pirates! on my personal Github soon!
