### ISSUE TITLE
Nullptr crash in imgui.cpp - Sword and Fairy 4

### ISSUE THREAD

**Issue by anchorlightforge** [NVIDIAGameWorks/rtx-remix#204]
### Describe the bug
- At a glance: Attempting to open the Remix menu will crash if ImGui's CurrentWindow value is not set.
- Remix Versions: 
  - DXVK Remix 8bb6932-110
  - Bridge Remix a18db5f-10 
  - See also: [PAL4Fix WIP Commit for DXVK-Remix](https://github.com/NVIDIAGameWorks/dxvk-remix/compare/main...anchorlightforge:dxvk-remix:PAL4Fix))
- GPU: Nvidia Geforce RTX 3080
- Drivers: Nvidia Studio Driver 531.41
- Application: Sword and Fairy 4 ([Steam](https://store.steampowered.com/app/1621680/Sword_and_Fairy_4/), current release build)

### Logs:
- Callstack analysis: [S&F4 Debug - imgui crash Error.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11777748/S.F4.Debug.-.imgui.crash.Error.txt)

### To Reproduce
1. Open Sword and Fairy 4 from Steam.
2. Press Alt-X.
3. If the game crashes on a white screen before starting, make sure the Prerequisites below are installed to the game directory and try again.
4. If the game crashes before pressing Alt-X, try again.
5. Upon pressing Alt-X, the game will crash immediately.

### Prerequisites
Please use the following files to improve compatibility in the game. CONF files are attached as a ZIP below.
(GitHub doesn't allow CONF's, sorry!)
- [PAL4_CONF.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11777753/PAL4_CONF.zip)

Note: There is another crash related to an in-game error handler (abort.cpp) that will occur after a couple of seconds on the menu. There is also another crash that occurs intermittently on startup.  Neither of these appear to be related to the error, or fix, reported above.

### Expected behavior
- Alt-X should open the Remix Menu without exiting the game.
- A PR is currently in drafting for this issue: #https://github.com/NVIDIAGameWorks/dxvk-remix/pull/29

**Comment by anon-apple** [comment]
Did you use the Debug or Release versions of the Bridge and Runtime binaries? Also, how often would you say this is reproducible, does it happen every time you try to open the Remix menu with Alt+X or only sometimes?

**Comment by anchorlightforge** [comment]
I used the Release build to do a callstack analysis.  It's 100% reproducible. The only confusing factor is that there's a couple of other unrelated crashes in this game, some of which start with the game binary itself.

Before I applied my fix it was happening 100% of the time I pressed Alt-X, but after adding a nullptr check before opening the menu I was able to properly open up the menu and begin marking textures.  I have a Pull Request posted in draft form for the tweak, ideally I'd like to investigate why the ImGuiContext value was null to begin with but I haven't had another chance to look at it.

**Comment by anchorlightforge** [comment]
Sorry I didn't see this comment earlier, I'll recreate the conditions and get you a crash dump.  While I'm at it, I'll try to verify that the bug is still present as it's possible that the condition in which ImGui wasn't having its current context set in time was addressed elsewhere.

**Comment by anchorlightforge** [comment]
[NvRemixBridge.exe_20230727_005114.dmp.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/12179432/NvRemixBridge.exe_20230727_005114.dmp.txt)

Please remove '.txt' from the end of this file to make it usable, I had to append that to make GitHub happy.  This was done using the latest dxvk-remix and bridge-remix commits without an extra nullptr check added.  That branch is pretty stale at the moment as I put this game off for a while for a variety of reasons, so I'll try to give that a pass tomorrow night.

This was done on a completely fresh installation of the game installed on my external SSD.  Most of my Remix testing titles are installed to this drive and I haven't noticed this in any other title before.

**Comment by anon-apple** [comment]
Sorry for the long delay on this, we had some issues with debug symbols being associated with builds before, but I think this has been fixed now. If you're able to capture this still in a newer build and upload the minidump I think I'd be able to debug it better, also worth checking anyways to see if it has magically fixed itself somehow in the past months.

**Comment by anchorlightforge** [comment]
@anon-apple Based on light testing I'm leaning towards the latter, I've had difficulty reproducing it in modern versions.  When this issue was occurring, I could reproduce it 100% of the time; I am no longer having any issues opening the menu.  I'll be closing this ticket for now and will reopen the issue if anything changes.
