### ISSUE TITLE
[Request] Light texture color

### ISSUE THREAD

**Issue by mralexs5** [NVIDIAGameWorks/rtx-remix#205]
I don't know if this is planned, but it would be very nice to have light textures have their color changed or inherit their color from the texture itself.

**Comment by anon-apple** [comment]
What do you mean exactly? Emissive on objects can already have their emissive color controlled per-pixel with the emissive color texture.

**Comment by mralexs5** [comment]
> What do you mean exactly? Emissive on objects can already have their emissive color controlled per-pixel with the emissive color texture. Is that what you're talking about or something else?

I haven't seen that, can it be set on a per texture basis?

**Comment by anon-apple** [comment]
Well depends on what you mean by that. You can replace materials on the basis of a texture used in the original application (since the texture hash of the color texture the game uses is how it identifies the object to replace the material on). From there you can set any of the PBR textures or properties in the replaced PBR material, one of which is the emissive color texture.

**Comment by anchorlightforge** [comment]
I think the question is based on the rtx.lightConverter option. I actually agree in that while it's probably best not to put too much time into worrying about the fine details of that setting as opposed to proper replacements, having it sample the primary color of the texture as its color would probably be a useful addition.  I've found that in most scenes where rtx.lightConverter applies to objects it clashes with the tepmerature of the original light and it limits the option's usefulness.

**Comment by mralexs5** [comment]
Currently if you mark a texture as a light texture it creates a white light. What I'm wanting is for the light to inherit the color of the texture, IE a red texture would have a red light and so forth

**Comment by nv-ajaus** [comment]
@mralexs5 Was the answer provided helpful to you?

**Comment by nv-ajaus** [comment]
Hi @mralexs5, it's been a few weeks since I reached out, so I'm going to go ahead and close this issue. If the answer that was provided is insufficient please feel free to reopen this issue or file a new one. Thank you!
