### ISSUE TITLE
OMSI 2 Crashes When Capturing

### ISSUE THREAD

**Issue by adamplayer** [NVIDIAGameWorks/rtx-remix#207]
**Describe the bug**
When attempting to capture from OMSI 2, the game ends up crashing. Captures that do finish, have broken orientations for most objects.
- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
Bridge - bf0984b
Remix -  0a9d916
- Which GPU
3080
- Which GPU driver version
545.29
- Which game build (and whether it is from Steam/GOG/Other)
Steam

**Attach logs!**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11782870/NvRemixBridge.log)
[Omsi_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11782871/Omsi_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11782872/d3d9.log)

- d3d9.log
- The game specific log will be named gamename_d3d9.log

**To Reproduce**
1. Launch game using this `options.cfg` [options.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11782874/options.txt)
2. Load into map without any buses. 
3. Once in map, attempt multiple captures.
4. Eventually the render will crash, and captures will have broken orientation.

**Expected behavior**
Good captures and no crashes.

**Screenshots**
N/A

**Comment by NV-DM** [comment]
@adamplayer Could you please retest with the most recent release?

**Comment by adamplayer** [comment]
Game now hangs once entering the world. Ends up throwing this error and crashing. 
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/94309006/d3590489-a24e-40b3-8af0-803939ff1f59)
Logs:
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13386425/NvRemixBridge.log)

[Omsi_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13386419/Omsi_d3d9.log)

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13386418/d3d9.log)
[NvRemixBridge.exe_20231116_213223.dmp](https://github.com/NVIDIAGameWorks/rtx-remix/files/13386426/NvRemixBridge.exe_20231116_213223.dmp)

**Comment by NV-DM** [comment]
REMIX-2457 for tracking.

**Comment by nv-ajaus** [comment]
Hi @adamplayer , I noticed that in your most recent `d3d9.log` file that the message
```
[21:32:23.431] warn:  Data Queue override condition triggered
[21:32:23.432] err:   Command's data batch size is too large and override could not be prevented!
```
occurs. 

The override recovery code seems to have been broken, and I just pushed a commit to try to fix that. Could you please try the build from the new commit (https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/7107996207) I just made to see if you can make further progress?

**Comment by nv-ajaus** [comment]
Hi @adamplayer , it's been a while since I reached out about this issue. This change to correct the override recovery code has been in the codebase for a while, and we recently made an fix where we correct two threads accessing the same bridge data can cause a hang or crash. Can you please try out the latest [bridge build](https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/7715937965) and let me know if it improves anything?

**Comment by adamplayer** [comment]
Game no longer hangs on load _and_ does not crash when capturing. 👍 Issue resolved.
