### ISSUE TITLE
dxso.cpp - Access Violation on Game Startup - Hitman: Codename 47 (GOG - OpenGL)

### ISSUE THREAD

**Issue by anchorlightforge** [NVIDIAGameWorks/rtx-remix#209]
**Describe the bug**
- Bug: On startup, dxso will trigger an access violation while compiling shaders. (dxso.cpp:21)
- Remix Version: (include branch and commit info for dxvk and bridge if not a stable build)Bridge bf0984b, DXVK 0a9d916 + PR#29 (0a9d916 should be fine)
- GPU: GeForce RTX 3080
- Drivers: Studio Driver 531.41
- Platform: GOG

Related issue (and a much more thorough analysis of the issue) courtesy of Watbulb:
#212 

**Attach logs!**
- [HitmanC47.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11806088/HitmanC47.txt)
- FEAR logs removed, see #212 

Note: Hitman: Codename 47 log includes Call Stack at the bottom of the file

**To Reproduce**
1. Download GLDirect5 and place opengl32.dll into the game folder.
2. If the game cannot launch due to GLDirect's shader version not being compatible, set d3d9.shaderModel = 3 in dxvk.conf.
3. Open the configuration tool and make sure that OpenGL is set as the renderer.
4. Open hitman.exe.
5. The game will crash on startup.
Note: The Steam version of Codename 47 cannot be debugged due to a bugged implementation of Steam's DRM.

**Expected behavior**
- The game should boot to the menu as intended.

Note: Per developer request this ticket is being separated into two issues.  The ticket above refers to Hitman: Codename 47's issue.  A link will be provided to a separate ticket to F.E.A.R.'s issue as soon as it is posted; please look into the FEAR issue first as Watbulb has put a lot of work into tracing it to a Bridge-related issue and it will most likely affect the other title when fixed.

**Comment by anchorlightforge** [comment]
Thanks to the diligent and very thorough work of @watbulb this issue has been located.  I'm not even going to attempt to summarize it here because he explained it better than I could.  The link below will take you to a full report of where the code is breaking:

https://discord.com/channels/1028444667789967381/1120755588729675806/1121310253611499601

**Comment by anchorlightforge** [comment]
For future issue tracking, please refer to watbulb's comment.
https://github.com/NVIDIAGameWorks/rtx-remix/issues/212

**Comment by nv-ajaus** [comment]
This issue may have been fixed by bridge commit a06bdc0, which maps to Build #16 on github. Can you please try it out to see if it helps?

**Comment by anchorlightforge** [comment]
Fixed by bridge-remix commit [a06bdc0](https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/5559868342).  I can no longer reproduce this bug in any of the titles I observed it with and as such I think the issue can be safely closed.  Thanks to all who contributed to the fix.
