### ISSUE TITLE
Max Payne VertexBuffer crash after few minutes of gameplay

### ISSUE THREAD

**Issue by acoulte93** [NVIDIAGameWorks/rtx-remix#21]
**Wrapper used:**
d3d8.dll = [Widescreen fix](https://github.com/ThirteenAG/WidescreenFixesPack/releases/download/mp1/MaxPayne.WidescreenFix.zip)
d3d9.dll = RTX Remix 0.1.0

**Driver Version:**
Nvidia Driver 531.41

**Startup arguments:**
-skipstartup -dx7 -resize -developerkeys -developer -window

**Game Settings:**
Max settings 
2560 x 1440 x 32
No Anti-Aliasing 

### **Issue:** Game crashes at various points during gameplay
**Reproduced:** 3/5 times

1. Load into any map, and play through the level as normal. 
2. F12 to toggle developer console
3. Type "coder" for all unlocks and god mode
4. After roughly 5 minutes the game crashes with the character or other geometry turning invisible

`Exception:
An error has occured in graphics engine. Try to downgrade your settings by pressing the "Options..." button in Max Payne startup dialog. 
P_D3DDDVertexBuffer: VertexBuffer->Lock : E_FAIL
Closing...`

**Logs:**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11215635/NvRemixBridge.log)
[maxpayne_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11215642/maxpayne_d3d9.log)

**Other notes:**
Using startup hang patch e2mfc.dll (d3d9 log, rtx.conf in /Max Payne/e2driver/)
Using previous rtxconf. Remove .txt extension to use [rtx.conf.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11215668/rtx.conf.txt)

![image](https://user-images.githubusercontent.com/5293492/231579105-6a48de29-90a8-447f-980d-5d9dc9574934.png)

### **Same issue on 0.1.1**
[maxpayne_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11217677/maxpayne_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11217678/d3d9.log)

**Comment by NV-DM** [comment]
REMIX-2052 for tracking.

**Comment by NV-DM** [comment]
Hello. Could you please retest this with the latest released version of Remix?

**Comment by NV-DM** [comment]
REMIX-2052 marked as fixed. Closing as fixed.
