### ISSUE TITLE
[Feature Request] Include .trex\usd in dxvk-remix CI builds

### ISSUE THREAD

**Issue by anchorlightforge** [NVIDIAGameWorks/rtx-remix#211]
**Describe the bug**
- USD capture will result in a crash on applications built with only CI nightlies.  This is due to the usd folder not being included.
- Version: Any CI dxvk-remix/bridge-remix installation where Remix 0.2.0 was not installed first
- Game: Multiple observed

**To Reproduce**
1. Install Bridge/DXVK-Remix CI builds onto a supported game without RTX Remix having been installed prior (tested with Pathologic Classic HD)
2. Attempt to perform a USD capture
3. The game will freeze and eventually crash.

**Expected behavior**
- USD capture should refer to the correct files and capture the scene unless another outlying issue is present.

**Comment by MarkEHenderson** [comment]
This should be resolved as of https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/6344554261
