### ISSUE TITLE
[Feature] Enable PT Toggle + build debugOptimized in GitHub Actions

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#213]
We had a discussion here: https://discord.com/channels/1028444667789967381/1028444668918235197/1124528209610936360

The gist of it was basically: 
* enable `debugOptimized` builds for GitHub Actions.

The initial reason for this discussion was to enable the path tracing toggle in Release builds. However, later discussion seemed to lean toward using `debugOptimized` builds, so long as they're added to GitHub Actions. This would resolve the issue of limited debugging options and it'd allow us to toggle path tracing as necessary for development/troubleshooting reasons.

`enableValidationLayers` under this mode also must be `false` to be optimized

Thanks!

-----------------------------------------------
If there are concerns about unfair comparisons even when limited to debugOptimized builds, there is [another option](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/5a085a8a55a72885b724508d56bde95dc2374ce2#diff-abed281dc1ae7f2dcce56f609df6de21a4f3156dc02d492be474b850a26b7702R83) by @anchorlightforge
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/2247ce58-5be3-43cd-ab3f-1486059a7ac8)

Ideally if this were implemented, it should be smaller for both `debug` and `debugOptimized` builds, otherwise it'd be very intrusive and in the way.

**Comment by pkristof** [comment]
This can be closed: we added `debugOptimized` build into actions
https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/5449382635

**Comment by Kim2091** [comment]
Thanks!
