### ISSUE TITLE
[Crash] Setting a texture from a texture resource that has already been released causes a crash

### ISSUE THREAD

**Issue by szlobipeti** [NVIDIAGameWorks/rtx-remix#216]
- A clear and concise description of what the bug is.
D3D9Device.SetTexture() call crashes the game.
Crash is caused by the texture that is being used to call SetTexture begin already released.
Pseudocode:
// texture creation and usage
texture.Release(); // texture is released, should not be used anymore
device.SetTexture(texture); // released texture is used in SetTexture call, causing a crash
Fix:
Patching the .exe not to release the texture fixed the issue. Remix could include a flag to handle such cases by ignoring the call or some other error recovery solution, that does not crash the title.

- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
remix 0.2.0 release

- Which GPU
RTX 3060 Laptop

- Which GPU driver version
535.98

- Which game build (and whether it is from Steam/GOG/Other)
Latest Disney Pixar Cars (2006) from Steam

[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12047428/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12047421/d3d9.log)
[Cars_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12047431/Cars_d3d9.log)

1. Launch title
2. Watch splash screen, logo videos and legal notice
3. Experience crash upon entering main menu

Expected behavior:
Main Menu renders and behaves as in regular game without crashing.

**Comment by nv-ajaus** [comment]
Confirmed that the crash is resolved with szlobipeti on the RTX Remix Showcase discord channel.
