### ISSUE TITLE
Bridge Memory read/write error at 00007FF6B3DA7D5D - Remix Server Error

### ISSUE THREAD

**Issue by JP111555** [NVIDIAGameWorks/rtx-remix#217]
## General Info 
**When Remix tries to boot up 18 Wheels of Steel: Extreme Trucker 2, it throws this error on the server side Exception 0xc0000005 at 00007FF6B3DA7D5D, a memory read/write error for something.**

When I try to boot into the game using Remix. It hooks into the game but the Bridge server creates but later crashes while the game boots up fine. 

## Specifications
Remix 0.2 - Stable

RTX 3060

536.67 - Game Ready Driver

Game - 18 Wheels of Steel: Extreme Trucker 2

Build 1.0 - Steam

## **Logs**
_To make this easier to reproduce, I will keep all bridge settings and additional files I used in trying to circumvent this at their defaults aside from the log settings as they don't seem to impact the outcome of the bug._
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12090590/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12090591/d3d9.log)
[extremetrucker_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12090593/extremetrucker_d3d9.log)

## **To Reproduce**

1.  Go to 18 Wheels of Steel: Extreme Trucker 2 Config file (Found in documents under C:\Users\USER\OneDrive(if you have it)\Documents\18 WoS Extreme Trucker 2\config.cfg) and paste this in:
[config.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11482702/config.txt)
_Changes engine to DX 9, forces windowed screen and also should set graphics to minimum, however you may have to do that yourself_

2.  Save config.cfg

3. Add in this dxvk.txt file and then change it to .conf. This changes the shader model to 1 so the game will load
[dxvk.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/12090633/dxvk.txt)

3.  Go to **Steam**

4. Click on 18 Wheels of Steel: Extreme Trucker 2, or click on it's .exe file in file explorer

5.  Navigate to the game files under 'C:\Program Files (x86)\Steam\steamapps\common\18 WoS Extreme Trucker 2\bin\win_x86'

6.  Navigate to the bridge log under .trex folder

7.  _See error_

## **Expected behavior**

Upon clicking 18 Wheels of Steel: Extreme Trucker 2, the game will load, however Bridge will refuse to hook resulting in you playing the game as if nothing has been changed

**Comment by NV-DM** [comment]
Hello! Could you please re test this with latest released build. Thanks!

**Comment by nv-ajaus** [comment]
@JP111555 Did you get a chance to retest with the latest release, or the most recent github builds?

**Comment by JP111555** [comment]
Sorry for such the late response; I forgot that this post even existed lol. But yes. This issue has been fixed. However, now I've been getting an error saying that Remix can't detect a camera in the game. However, that's another bag of worms to dive into. Anyway, I will be sure to close this issue.
