### ISSUE TITLE
Build f891472 breaks conf file parsing

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#219]
**Describe the bug**
- Running Remix with dxvk-remix build f891472 seemingly breaks conf file parsing. dxvk.conf and rtx.conf are no longer read properly
- dxvk-remix: f891472
- bridge-remix: 44ed02b
- GPU: RTX 3090, driver 536.67
- Barnyard, Retail

**Attach logs!**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12189091/NvRemixBridge.log)
[Barnyard 1080p_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12189087/Barnyard.1080p_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12189088/d3d9.log)

**To Reproduce**
The easiest way to test this is to set HUD = 1 in dxvk.conf. It will not actually appear once in-game

**Expected behavior**
conf files should be parsed properly

**Screenshots**
https://cdn.discordapp.com/attachments/1106420949257044061/1134283485520076810/image.png

**Comment by Kamilkampfwagen-II** [comment]
I can confirm this happening in a x64 game (dxvk-remix only).
[chess_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12192068/chess_d3d9.log)
```
info:  Game: chess.exe
info:  DXVK_Remix: remix-0.2.0+f891472e
info:  Init config: User
info:  Looking for config: User
info:  Env[DXVK_CONFIG_FILE]: 
info:  Init config: App
info:  Looking for config: App
info:  Did not find app config for executable: D:\Games\Chess Titans RTX\chess.exe
info:  Set startup config.
info:  Init config: RtxUser
info:  Looking for config: RtxUser
info:  Env[DXVK_RTX_CONFIG_FILE]: 
info:  Set custom config.
info:  Init config: RtxMod
...
```

> info:  Did not find app config for executable: D:\Games\Chess Titans RTX\chess.exe

I also removed my custom config file then saved settings in game. After restarting, game failed to read generated config.

**Comment by nv-ajaus** [comment]
Fixed with commit https://github.com/NVIDIAGameWorks/dxvk-remix/commit/94f5ab7ab2e7d20cd5ba63dbd68becb304716ee2
