### ISSUE TITLE
Sprite Sheet Support for AperturePBR_Translucent and Non-Emissive Materials

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [NVIDIAGameWorks/rtx-remix#220]
Remix already supports animation with sprite sheets for emissive mask maps. However that is not the case for translucent materials.
Being able to animate albedo, normal, metallic and roughness maps would be quite useful especially for animating materials of mesh replacements.

**Comment by anon-apple** [comment]
Ah slight correction I noticed, the MDL we use on the Omniverse side of things is actually fairly outdated and does only expose this option as a subset of the emission category, but it does in fact apply to all the other textures in the Opaque material. This will be something fixed soon though.

**Comment by Kamilkampfwagen-II** [comment]
@MarkEHenderson 's comment on this in the Discord server:
> We implemented sprite sheets in translucent materials for the Half Life 2 RTX announcement trailer, but only in the runtime loading code.  We apparently haven't gotten around to adding it to the MDL yet, so it doesn't show up in USD composer (and USD Composer will actually try to strip it out of the material if you open that material)
You can see the list of properties that the runtime loads here:
https://github.com/NVIDIAGameWorks/dxvk-remix/blob/main/src/dxvk/rtx_render/rtx_material_data.h#L99

**Comment by MarkEHenderson** [comment]
REMIX-1802 for tracking.

**Comment by anon-apple** [comment]
Spritesheet support should now be part of Translucent materials as of https://github.com/NVIDIAGameWorks/dxvk-remix/commit/9e776b43c17ad8ecfaa637843743c50f6b1be054. Closing.
