### ISSUE TITLE
Bet on Soldier: Blood Sport geometry flying away

### ISSUE THREAD

**Issue by DoomDude531** [NVIDIAGameWorks/rtx-remix#226]
**Describe the bug**
- Sometimes the world/models fly away, but only when I stand still and don't move the mouse
- bridge-remix-9789379, dxvk-remix-626bcc0
- RTX 2070 Super
- Driver 536.99
- Patch 1.3 (Steam)

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12340174/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12340176/d3d9.log)
- [BoS_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12340178/BoS_d3d9.log)

**Expected behavior**
For things to stay in place

**Screenshots**

https://github.com/NVIDIAGameWorks/rtx-remix/assets/76069060/b9c71d60-9015-4dfc-93ae-9cd40cc8b177

**Comment by NV-DM** [comment]
@DoomDude531 We have recently fixed a number of bugs that could be related to what you are seeing. Could you please re-test on TOT?

**Comment by NV-DM** [comment]
Thank you for filing the issue. Closing the ticket as it's been a while since last response. If this is still an issues, please file a new ticket. Thanks!
