### ISSUE TITLE
Sonic Adventure DX ( 2003 CD Version ) Crashes on new version of RTX-Remix

### ISSUE THREAD

**Issue by alex-suspicious** [NVIDIAGameWorks/rtx-remix#241]
The game crashes on new RTX-remix versions, on the old one from the portal rtx the game is playable without crashes, but flickers.
When you launch a game with the lates rtx-remix the GUI, menus are rendered much better than on the old one, but you cannot see models, they are not drawn. when you launch the game, everything is black, you cannot see everything, and then after 2 seconds it crashes.

- Stable build ( [remix-0.2.0](https://github.com/NVIDIAGameWorks/rtx-remix/releases/tag/remix-0.2.0) )
- RTX 3080
- 535.104.05
- Game from CD ( Steam version crashes with every version of remix )

**Attach logs!**
- [NvRemixBridge.log](https://pastebin.com/raw/BT7hB34R)
- [d3d9.log](https://pastebin.com/raw/afY6BgF2)
- The game do not make logs

**To Reproduce**
1. Download the latest rtx-remix
3. Drop all files to the sonic adventure DX root folder
4. Install any d3d8to9
5. Start the new game

**Expected behavior**
Normal rendering, the game is like can't hook the models idk, or just doesn't draw anything except for gui

**Screenshots**
On the new version of rtx-remix i can only show the screenshots of menu, but here's the proof screenshot that it works on old rtx-remix

<img src="https://i.imgur.com/YDBVDKG.png" >

**Comment by AlexDunn** [comment]
This was fixed confirmed in discord.
