### ISSUE TITLE
DLSS Visuals have degraded in recent builds

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#244]
**Describe the bug**
DLSS's visual quality has dipped quite a bit in the last month or so. There's a noticeable bloom effect around opacity objects, such as trees. I have also noticed more ghosting
- dxvk-remix: [7460a2f](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/7460a2f682390c6a4297679de73aff3cc76b779f)
- bridge: [b41ad87](https://github.com/NVIDIAGameWorks/bridge-remix/commit/b41ad87551aaa04e30cc62e203cf079c8402fef2)
- RTX 3090
- Driver: 536.67
- Skyrim - Steam
- Barnyard - Retail

**Attach logs!**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12554183/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12554184/d3d9.log)
[TESV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12554186/TESV_d3d9.log)

**To Reproduce**
1. Load up Skyrim
2. Go in-game, and find trees
3. Toggle DLSS on/off

Barnyard:
1. Load Barnyard
2. Wait until night
3. Move the camera around. You'll notice very noticeable trails on the ground from the main character

**Expected behavior**
Trees should not appear "bloomy". This did not appear in previous Remix builds, it only started around 8/20/23. I cannot currently find the specific build this started in

**Screenshots**
DLSS Off:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/32b7b9b5-0c4e-4be7-a281-542e7a6d442d)
DLSS On:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/3c2b2865-2c0b-412c-80e7-86adb648fe91)

**Comment by baazthefalcon** [comment]
thats the issue with dlss 3.1 try changing it

**Comment by Kim2091** [comment]
It's not just 3.1, I have changed the DLLs for testing. Also as stated in previous versions of Remix, this was not an issue.

**Comment by NV-DM** [comment]
@Kim2091 Could you please confirm this issue does not occur on a CI build before 8/20/23. If so, could you please post DLSS ON screenshots that show the difference compared to recent builds.

**Comment by Kim2091** [comment]
I intended to post this as well: https://www.youtube.com/watch?v=gLy_VGpJmg4
This is the original demo video I did for Skyrim, and the issue is not present there. I will post proper screenshots in a couple hours with some specific build numbers

**Comment by Kim2091** [comment]
@NV-DM My apologies. Something must have changed in my setup to have introduced this issue. This is a build from early June (cb1d0a3), and it does indeed have the same issue:
![Skyrim 9_13_2023 8_50_53 PM](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/2ab6f776-5735-4a7e-9b9a-aa8d59a75fc8)

Should I open a new issue about this separately? It does appear in a few games and definitely changes visuals in an unintended way

**Comment by Kim2091** [comment]
I'm just gonna file a separate issue with additional details. Thanks :)
