### ISSUE TITLE
 Strange rendering on replacement textures with colour data in transparent spots

### ISSUE THREAD

**Issue by Xenthio** [NVIDIAGameWorks/rtx-remix#249]
Replacement textures with colour data where there's alpha have a strange rendering effect.

- dxvk commit: 10c71ba94fb7b26ccc30484c9d55019063b95674
- bridge commit: b41ad87551aaa04e30cc62e203cf079c8402fef2
- RTX 4090
- Game Ready Driver 537.34
- Garry's Mod (Steam)
 
 

Uploading NvRemixBridge 2023.09.21 - 09.43.59.55.mp4…

**Comment by Xenthio** [comment]
Thanks github for not attaching my file properly
https://github.com/NVIDIAGameWorks/rtx-remix/assets/28588188/84871608-4117-4c7e-b1ee-3bcb66b3948f

**Comment by anon-apple** [comment]
What do you mean by color data where there's alpha? Could you potentially provide the USD for the replacements and the textures involved in that since it's not super clear what's going on there otherwise with the materials.

**Comment by NV-DM** [comment]
REMIX-2163 for tracking.

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
