### ISSUE TITLE
Toggling some options causes display driver to crash in Chess Titans

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [NVIDIAGameWorks/rtx-remix#251]
**Describe the bug**
- Toggling some options -that generally have significant impact on gpu- causes the game to crash.
- bridge-remix: [06d10f5](https://github.com/NVIDIAGameWorks/bridge-remix/commit/06d10f57c74ecdbc88b2cce82fdab6b1508bc587) and dxvk-remix: [49711d9](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/49711d97d599b8b60e601a472dd5c18e714445cf)
- RTX 2060 Desktop
- 536.67
- Chess Titans, bundled with Windows 7 (patched)

**Attach logs!**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12703710/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12703719/d3d9.log)
[chess_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12703720/chess_d3d9.log)

**To Reproduce**
1. Launch the game
2. Enable enhanced assets on a scene where majority of materials will be replaced. (This always causes the issue in my testing)
or
2. Toggle Reflex or DLSS on and off (This doesn't always cause the issue, rather majority of the time. I think it has a higher chance when performance profiler enabled)

**Expected behavior**
The game will continue to function normally

**Actual behavior**
The display driver crashes. Event viewer log:
```
\Device\Video3
Error occurred on GPUID: 900
```
source: `nvlddmkm`

**Screenshots**

Video showcase:

https://github.com/NVIDIAGameWorks/rtx-remix/assets/84380947/da3f4784-d720-43f3-9365-82e0fa67425e

During display driver crash (the performance graph glitched):
![2023-09-22 21_09_42-](https://github.com/NVIDIAGameWorks/rtx-remix/assets/84380947/fc371017-fd4d-4f8e-b1cf-3ad1e4a80a7c)

IMGUI briefly shows this during transitions
![2023-09-22 21_05_48-Greenshot](https://github.com/NVIDIAGameWorks/rtx-remix/assets/84380947/c2603346-e145-47bd-837b-ffb49ba81338)

**Comment by Kim2091** [comment]
This initially happened on my system, which is the following:
RTX 3090
537.42

The bug can be consistently reproduced across these two systems. Also, upon launching the game, it can crash the Nvidia driver. This happens (on my system) 2 out of 3 times. Looking in event viewer makes the crash evident, although the screen does not flicker black as would be typical with a driver crash.

**Comment by Kamilkampfwagen-II** [comment]
https://file.io/N3HkiPKwZiAd
Here are the apitraces of the game with and without dxwrapper (dxwrapper was used for borderless fullscreen, not for api convertion)

**Comment by NV-DM** [comment]
REMIX-2158 for tracking.

**Comment by Kamilkampfwagen-II** [comment]
Resolved as of https://github.com/NVIDIAGameWorks/dxvk-remix/commit/7fcb5e3e5229316ac5539b9b792d718cbe6aa3b1 in response to the issue https://github.com/NVIDIAGameWorks/rtx-remix/issues/261
