### ISSUE TITLE
The Stanley Parable 2013 - Remix doesn't start

### ISSUE THREAD

**Issue by Friend-LGA** [NVIDIAGameWorks/rtx-remix#252]
I was trying to use Remix with the original "The Stanley Parable" game from Steam.
No splash screen with "Welcome to NVIDIA Remix…" appeared and `alt+x` doesn't do anything.
Looks like Remix doesn't launch at all.

**Info**

- Remix version: `remix-0.2.0`
- GPU: `GeForce RTX 4090`
- GPU driver version: `537.42`
- Game: The Stanley Parable - Steam - original version from 2013

**Logs**

I didn't find any useful logs unfortunately

**To Reproduce**

1. Download The Stanley Parable game from Steam
2. Press "Manage" -> "Browse Local Files"
3. Add all the files from `remix-0.2.0`
4. Launch the game
5. Observe no splash screen with welcome message "Welcome to NVIDIA Remix…"
6. Try `alt+x` hotkey, observe it doesn't work

There are a few ways to launch a game:
1. From the Steam menu
2. From the game folder using `stanley.exe`, for this you need to create a shortcut with flags:
    - `-game thestanleyparable` - to specify which game folder should be used
    - `-dxlevel 90` (optional) - to specify DirectX version, expected supported values are: 60, 70, 80, 81, 90, 91, 95, 98 and 100

**Expected behavior**

1. After game is launched splash screen with welcome message "Welcome to NVIDIA Remix…" should appear.
4. Hotkey `alt+x` should open Remix control panel

**Comment by Friend-LGA** [comment]
Actually, it doesn't work for any games I tried, including:
- Portal
- Half-Life 2

I am following the [runtime-user-guide](https://github.com/NVIDIAGameWorks/rtx-remix/wiki/runtime-user-guide) by doing this step:

> To prep the game, simply copy the contents of the remix-0.1.0 directory into the game’s directory, right next to the main executable of the game. You should end up with the d3d9.dll and .trex/ folder sitting right next to the main game executable.
>
> Once RTX Remix files are in place, you can start the game normally. You can verify RTX Remix is working by checking for the splash message at the top of the screen when the game starts. It should say: “Welcome to NVIDIA Remix… ” and provide hotkey information to access the Remix menus. 

The only overlay welcome message I can see is "GeForce Experience" with `alt+z` hotkey, which is working.

This is how "The Stanley Parable" game folder file tree looks like with added "remix-0.2.0" content:

![Screenshot 2023-09-25 174336](https://github.com/NVIDIAGameWorks/rtx-remix/assets/5897136/366e6950-5c67-48fb-a1b2-c262c7d01fbd)

**Comment by Friend-LGA** [comment]
Okay... looks like some files should actually be placed inside `bin` folder for some reason. Could [runtime-user-guide](https://github.com/NVIDIAGameWorks/rtx-remix/wiki/runtime-user-guide) be updated to reflect where in which cases files should be places, to avoid confusion?

**Comment by NV-DM** [comment]
@nv-ajaus Could you take a look please?

**Comment by nv-ajaus** [comment]
Hi @Friend-LGA , thanks for bringing this up! Just to clarify, when you installed rtx-remix to the `bin` folder, did The Stanley Parable + Remix work for you? I'll bring this up with the team to see how we could improve the documentation.

**Comment by nv-ajaus** [comment]
I've added a note to the Runtime User Guide for this installation case.
