### ISSUE TITLE
Stability issues and graphical bugs on latest Remix

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#256]
**Describe the bug**
- Since updating to the latest Remix and Bridge builds, I have experienced major stability and graphical issues
- Issues:
  - Skyrim - Crashes seemingly at random after extended periods of time. I cannot narrow down what portion of Remix is crashing
  - Barnyard - Graphical corruption. The floating sleep/save icons decided to explode after playing for about 20 minutes. I have never experienced this before in this game
  - Portal RTX - Lots of crashing with these DLLs, again cannot determine cause.
- Bridge: [5aa73bc](https://github.com/NVIDIAGameWorks/bridge-remix/commit/5aa73bc223e78871632c85a54a1e754bc47e875b)
- Remix: [7f763ed](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/7f763ed0288703ffe3f0152d297a2486cced120e)
- RTX 3090
- 537.42
- Barnyard - Retail
- Skyrim - Steam
- Portal RTX - Steam

**Attach logs!**
Skyrim:
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773549/d3d9.log)
[TESV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773550/TESV_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773551/NvRemixBridge.log)
Barnyard:
[Barnyard 1080p_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773553/Barnyard.1080p_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773554/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773555/NvRemixBridge.log)

**To Reproduce**
This isn't easily reproducible. The issues are abundant and present in a strangely inconsistent manner

**Expected behavior**
Anything but this

**Screenshots**
Video demonstration of the issue in Barnyard:
https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/3ab2b975-e3f2-4cf2-888c-c6eb7c01bea5

**Comment by pkristof** [comment]
We made some fixes to instance handling just now. Is this any better with the latest runtime build?

**Comment by pkristof** [comment]
Set following in dxvk.conf and share any `*.dmp`, `*.nv-gpudmp` files along with `shaderDebugInfo` folder on crashes

**Comment by NV-DM** [comment]
@Kim2091 after looking at the attached logs, we believe this is not the same issue. Could you please file an individual issue for each game? Thanks!

**Comment by Kim2091** [comment]
Sure, thanks for taking a look. I'll close this issue and open the separate ones
