### ISSUE TITLE
Skyrim crashes with recent builds

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#257]
**Describe the bug**
- Since updating to the latest Remix and Bridge builds, I have experienced major stability and graphical issues
- Issues:
  - Skyrim - Crashes seemingly at random after extended periods of time. I cannot narrow down what portion of Remix is crashing. Reverting to older builds fixes the issue
- Bridge: [5aa73bc](https://github.com/NVIDIAGameWorks/bridge-remix/commit/5aa73bc223e78871632c85a54a1e754bc47e875b)
- Remix: [7f763ed](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/7f763ed0288703ffe3f0152d297a2486cced120e)
- RTX 3090
- 537.42
- Skyrim - Steam

**Attach logs!**
Skyrim:
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773549/d3d9.log)
[TESV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773550/TESV_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773551/NvRemixBridge.log)

**To Reproduce**
This isn't easily reproducible. The issues are abundant and present in a strangely inconsistent manner

**Expected behavior**
Anything but this

(This is a repost, split from the original issue)

**Comment by NV-DM** [comment]
REMIX-2240 for tracking

**Comment by NV-LL** [comment]
Hello! We have been able to confirm this fix internally on a recent build. Please try again on the latest release and let us know if this issue persists. Thank you!

**Comment by Kim2091** [comment]
@NV-LL The main crashing issue does appear to have been resolved, which is great!

I did run into this crash, but this has been happening across various games for me. As far as I can tell, it's only in games that pause rendering when you alt-tab:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/91f7c974-1497-4477-937f-859f64054535)

**Comment by NV-LL** [comment]
Glad to hear the crashing has been resolved. Will you please open a new ticket for the alt-tabbing issue? That way we can investigate and track it separately. Thanks!
