### ISSUE TITLE
Barnyard has graphical issues on recent builds

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#258]
**Describe the bug**
- Since updating to the latest Remix and Bridge builds, I have experienced major stability and graphical issues
- Issues:
  - Barnyard - Graphical corruption. The floating sleep/save icons decided to explode after playing for about 20 minutes. I have never experienced this before in this game
- Bridge: [5aa73bc](https://github.com/NVIDIAGameWorks/bridge-remix/commit/5aa73bc223e78871632c85a54a1e754bc47e875b)
- Remix: [7f763ed](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/7f763ed0288703ffe3f0152d297a2486cced120e)
- RTX 3090
- 537.42
- Barnyard - Retail

**Attach logs!**
Barnyard:
[Barnyard 1080p_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773553/Barnyard.1080p_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773554/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12773555/NvRemixBridge.log)

**To Reproduce**
Ride or run outside of the barnyard, and go to the right. You'll experience major artifacts and vertex explosions. It also happens in the main barnyard area after an extended duration of time

**Expected behavior**
Anything but this

**Screenshots**
Video demonstration of the issue in Barnyard:
https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/3ab2b975-e3f2-4cf2-888c-c6eb7c01bea5

(This is a repost, split from the original issue as requested)

**Comment by NV-DM** [comment]
REMIX-2239 for tracking

**Comment by NV-DM** [comment]
@Kim2091 Do you happen to know which build the regression started in?

**Comment by Kim2091** [comment]
> @Kim2091 Do you happen to know which build the regression started in?

Sorry, I didn't receive a notification for this. I have not been able to narrow down the exact build this began with, I've been very short on time to test Remix. I'll do some further testing when I can to see if I can narrow it down.

**Comment by Kim2091** [comment]
Got lucky and managed to figure it out quickly. 

`dxvk-remix-7f763ed-259-release` is responsible for the visual corruption. 

I tested `dxvk-remix-52ea640-258-release` and it doesn't have the issue.

These tests were confirmed with the latest bridge at the time of writing (`bridge-remix-0903dd0-33-release`)

**Comment by Kim2091** [comment]
When testing Barnyard, this save file should make it much easier to reproduce the bugs I've mentioned, since it's the one I'm using.

Put it in the `Save` folder in the game directory, and load "Choccy" from the main menu: [savedata.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13034390/savedata.zip)

This is also my latest rtx.conf file: [rtx.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13034392/rtx.zip)

If you want to run the game in a higher resolution, this tool published by the game community is capable of doing it easily: https://discord.com/channels/1028444667789967381/1106420949257044061/1107620529285890129

**Comment by AlexDunn** [comment]
Thanks @Kim2091, the specific regression commit really helps narrow it down.  Although I am unable to test this game, I do see a couple potential problem areas with the stated merge.  I put in a speculative fix here: https://github.com/NVIDIAGameWorks/dxvk-remix/commit/8285d0512bf0c1efbd6bdceeea28d7f396ebfd2d

Please let me know if this helps.

**Comment by Kim2091** [comment]
@AlexDunn Thank you for the response. I am sad to report that the changes did not fix the issue. It still behaves exactly the same as it did with dxvk build `7f763ed-259`

**Comment by Kim2091** [comment]
Got an update with some more specific details. Apparently it's caused when geometry fails to load in while running around in the game. This may be an issue with the base dxvk implementation, rather than Remix, given that it is invisible with RT turned off as well

RT Off:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/58185da3-8db6-4675-ab1c-fde1846f91ef)

On:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/05fc188c-6cb1-4e10-ab95-96a0c009b8b9)

**Comment by AlexDunn** [comment]
Interesting, thats a good find.  Would it be possible to grab an API trace of that exact spot?

**Comment by Kim2091** [comment]
Sure. I apologize, but I've forgotten what I need to do to properly get the API trace for this. If you could provide some steps, or a link to some, that'd be great

**Comment by AlexDunn** [comment]
This is what I'm referring to: https://apitrace.github.io/#documentation

**Comment by Kim2091** [comment]
It seems that any time I hook apitrace (32 bit), it crashes the game before any visuals even appear

This is my command:
`.\apitrace.exe trace --api d3d9 --output .\output.trace "E:\DRM Free Games\Barnyard Game\Barnyard - Copy\Barnyard - copy.exe"`

It appears to be crashing the bridge

**Comment by AlexDunn** [comment]
We discovered an issue which might fix this issue.  Please, retry with this build: https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/7507564365

**Comment by Kim2091** [comment]
Thank you! I will begin testing and report back by tonight. So far I cannot seem to recreate it, which is exciting.

**Comment by Kim2091** [comment]
@AlexDunn After spending a few hours testing and modding, the game hasn't done it at all. I'm almost certain the bug has been fixed, thank you all for your efforts. I'll close this issue now

**Comment by Kim2091** [comment]
This issue has returned in newer builds of Barnyard. I've been unable to narrow down the cause or specific build. I can say that the Portal RTX build that introduced Ray Reconstruction had the issue as well though, if that helps.

**Comment by NV-LL** [comment]
Hi @Kim2091 - will you please open a new GH issue for the regression? That will help us stay on top of tracking it. Thank you!

**Comment by Kim2091** [comment]
Opened a new issue here: https://github.com/NVIDIAGameWorks/rtx-remix/issues/496
