### ISSUE TITLE
ImGUI Crashes Remix + Visual Corruption

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#261]
**Describe the bug**
- In builds of Remix for the last month, various games have been experiencing crashes and visual corruption in Remix menus. This issue however will only focus on Flatout 2, as I have the most info for it. This is a small subset of the issues, which is visual corruption in ImGUI that leads to crashing
- Last tested on:
- dxvk-remix: daf94dd
- bridge-remix: 0903dd0
- RTX 3090
- 537.42
- Flatout 2 - Steam
Other games:
  - Skyrim - Steam
  - Chess Titans - Retail
  - Barnyard - Retail

**Attach files!**
- [FlatOut2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12887484/FlatOut2_d3d9.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12887486/d3d9.log)
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/12887487/NvRemixBridge.log)
- [rtx.conf](https://github.com/NVIDIAGameWorks/rtx-remix/files/12887492/rtx.zip)
- nv-gpudmp: [FlatOut2_129123-181050_aftermath.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/12887495/FlatOut2_129123-181050_aftermath.zip)

**To Reproduce**
1. Load Flatout 2
2. Go into Singleplayer -> Single Race -> Forest -> Pinegrove 3
3. Choose default car
4. Open Remix Overlay
5. Open Latency Stats Window
6. Toggle Reflex
7. Observe visual corruption

**Expected behavior**
- Reflex mode should change without issue

**Screenshots**
[Video Demonstration](https://cdn.discordapp.com/attachments/1113472651277652028/1162150970390757396/FlatOut_Remix_Corruption.mp4?ex=653ae46f&is=65286f6f&hm=eb3e58a3d59f1be1f46733360783456d4576cedd115083bfaa8093cac3c4ad33&)
https://discord.com/channels/1028444667789967381/1113472651277652028/1162150971430936698

**Comment by NV-DM** [comment]
REMIX-2245 for tracking.

**Comment by anon-apple** [comment]
This should be fixed in 7fcb5e3e5229316ac5539b9b792d718cbe6aa3b1. Feel free to re-open if the issue persists after that commit.
