### ISSUE TITLE
Scrapland Remastered - Crash on USD Capture

### ISSUE THREAD

**Issue by anchorlightforge** [NVIDIAGameWorks/rtx-remix#263]
**Describe the bug**
- On attempting to capture a USD scene, Bridge crashes.  This affects scene capture but assets-only capture is unaffected.
- Remix ver.: DXVK 65dab8b Debug-Optimized, Bridge 5aa73bc Debug-Optimized
- GPU: Nvidia Geforce RTX 3080
- Driver: Nvidia Studio 536.67
- Version: [GOG](https://www.gog.com/en/game/scrapland_remastered)

**Attach files!**
- [ScraplandRTXSaves.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/12899628/ScraplandRTXSaves.zip)
  - Extract the contents to User\<user>\Documents\MercurySteam\Scrapland\
- [gameconf.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/12899818/gameconf.zip)
  - Includes conf files to place inside the Scrapland Remastered folder.
- [USDDump.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/12899856/USDDump.zip)
  - Dump generated on Bridge crash. 

Installation instructions (to be replaced with link to repo):
- Install game from GOG
  - Steam will work as well but that version has anti-debug protection in place.
- Place the contents of gameconf.zip inside Scrapland Remastered
- Place the contents of ScraplandRTXSaves.zip inside Documents/MercurySteam/Scrapland (Create if it doesn't exist)
  - If using the Steam version, run the game at least once then replace the contents of the subfolder with an ID string for a name
  - Verify that Scrap.cfg is read-only
- Rename the "Video" folder
- Install DXVK and Bridge Remix to Scrapland Remastered/bin
- Open game (Bin/Scrap.exe) using a new shortcut with the launch arguments ` -console -debug:10 -enginedebuglevel:10`
  - When using the debug console shortcut all game info will be dumped to log.html and logAI.html.

**To Reproduce**
1. Click on "Single Player," then "Load Game" and load the map "Police Station" (any Load Game save will work-- see above instructions with included saves)
2. Allow the game to load and let the metro arrival animation finish
3. Open the Remix menu, go to Enhancements, disable the Enable Enhanced Assets box, and capture a USD scene
4. Observe Bridge Crash

**Expected behavior**
- The USD Capture should show a progress bar, run through USD capture functions, and dump a usable USD scene file as well as USD asset files.

**Comment by nv-ajaus** [comment]
Similarly to my response on Issue #262 , can you please repro this issue with a release build of rtx-remix, and disabling the ` -console -debug:10 -enginedebuglevel:10` arguments if possible? Thank you!

**Comment by anchorlightforge** [comment]
The following crash info was captured without the extra debug launch arguments (confirmed as no console opened up alongside the game window).  This ZIP contains an archive of walking around and loading a few environments before disabling all enhancements and attempting a USD capture.  Please note that unlike the original Issue, this was done using the latest RTX Remix 0.3.0 Release binaries.
[USDCrash030Release.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13066803/USDCrash030Release.zip)

**Comment by nv-ajaus** [comment]
Hi @anchorlightforge , since the release of 0.3, there's been a change that fixes a capture crash (https://github.com/NVIDIAGameWorks/dxvk-remix/commit/940d912094f42509731b259b9e39b3fee3498b6f) and I'm curious to see if that change impacts or improves this crash issue. 

Can you please try to reproduce this crash with a build of dxvk-remix that contains that change (https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/6592590891 or sooner)?
