### ISSUE TITLE
Scrapland Remastered - Crash on New Game

### ISSUE THREAD

**Issue by anchorlightforge** [NVIDIAGameWorks/rtx-remix#264]
**Describe the bug**
- On attempting to start a new game, the game attempts to load the first level (Orbital Station), then crashes with an error.
- Remix ver.: DXVK 65dab8b Debug-Optimized, Bridge 5aa73bc Debug-Optimized
- GPU: Nvidia Geforce RTX 3080
- Driver: Nvidia Studio 536.67
- Version: [GOG](https://www.gog.com/en/game/scrapland_remastered)

**Attach files!**
- [ScraplandRTXSaves.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/12899628/ScraplandRTXSaves.zip)
  - Extract the contents to User\<user>\Documents\MercurySteam\Scrapland\
- [gameconf.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/12899818/gameconf.zip)
  - Includes conf files to place inside the Scrapland Remastered folder. (just the base folder, not Bin)
- [crashlogs.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/12900171/crashlogs.zip)
  - A zip including the game logs and Remix log up until the point of crashing.

Installation instructions (to be replaced with link to repo):
- Install game from GOG
  - Steam will work as well but that version has anti-debug protection in place.
- Place the contents of gameconf.zip inside Scrapland Remastered
- Place the contents of ScraplandRTXSaves.zip inside Documents/MercurySteam/Scrapland (Create if it doesn't exist)
  - If using the Steam version, run the game at least once then replace the contents of the subfolder with an ID string for a name
  - Verify that Scrap.cfg is read-only
- Rename the "Video" folder
- Install DXVK and Bridge Remix to Scrapland Remastered/bin
- Open game (Bin/Scrap.exe) using a new shortcut with the launch arguments ` -console -debug:10 -enginedebuglevel:10`
  - When using the debug console shortcut all game info will be dumped to log.html and logAI.html.

**To Reproduce**
1. Open Scrap.exe with the debug arguments mentioned above
2. Click on "Single Player," then "New Game" and pick any difficulty
3. Allow the game to load briefly
4. Observe crash message

**Expected behavior**
- The game should complete loading and with Video renamed, the game should immediately cut to gameplay with the player on Orbital Station.

**Error**
```
Actual Level at :  Levels/Orbit
No PythonExecute
Python script subsystem initialized.
ProgressBarCount: 922 (1070)
Level loaded in 5.52 seconds

FATAL ERROR: Check failed!

Expression: vp8.Width

Compiled file info:
File: 'F:\GOG Games\Scrapland Remastered\Bin\Scrap.exe' 
Date: Nov 24 2021  15:24:13

Source code info:
File: 'Engine\render.cpp'
Date: Wed Nov 24 14:55:12 2021
Line: 783
```

**Comment by NV-DM** [comment]
@anchorlightforge Hello. Could you please see if these issues will repro with the Release build?

**Comment by anchorlightforge** [comment]
Confirming that this bug still occurs with Release.  The following is a set of logs from the New Game crash tested on the release binaries for 0.3.0.

[Release030NewGameCrash.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13066850/Release030NewGameCrash.zip)

**Comment by NV-DM** [comment]
REMIX-2287 for tracking.

**Comment by nv-ajaus** [comment]
Hi @anchorlightforge , I noticed a fix I made might impact this issue. Can you please try to reproduce this issue using https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/8903349558 or more recent?

**Comment by anchorlightforge** [comment]
@nv-ajaus I tested Bridge Remix build 68 with the GOG version and was able to change resolutions and start a new game successfully.  In other words, you got it.  Thank you!

**Comment by 27hectormanuel** [comment]
Im having this issue with AMD

**Comment by NV-LL** [comment]
Hi @27hectormanuel - if you're getting a crash, will you please file a new ticket? As this one is closed and you're on an AMD card, we'd like to track it as a separate issue. Thank you!
