### ISSUE TITLE
Battlefront 1&2 (2005) Cannot create Direct3D Device

### ISSUE THREAD

**Issue by Night1099** [NVIDIAGameWorks/rtx-remix#269]
**Describe the bug**
- This Game has worked in the past on select builds of remix but with .3 it is broken again
- Battlefront 1 (2004) has the exact same error

- 3080
- Driver 537.58

Battlefront 1 Files
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13049149/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13049152/d3d9.log)
- [Battlefront_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13049154/Battlefront_d3d9.log)

BattleFront 2 Files
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13049156/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13049159/d3d9.log)
- [BattlefrontII_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13049161/BattlefrontII_d3d9.log)

**To Reproduce**
1. Run Game

**Expected behavior**
- Launch Game

**Screenshots**
![Screenshot 2023-10-19 202928](https://github.com/NVIDIAGameWorks/rtx-remix/assets/90132896/30b5cd74-5f89-492e-b286-c0c3789daca2)

**Comment by Sopitive** [comment]
Can confirm it does not work with the latest version of remix, bridge and dxvk. Remix by itself doesn't work nor does any combination with newer versions of the bridge and dxvk.

**Comment by NV-DM** [comment]
REMIX-2286 for tracking.

**Comment by nv-ajaus** [comment]
Hi @Night1099 , I see that your logs reference a .dmp file `NvRemixBridge.exe_20231019_204342.dmp`. Could you please provide the that .dmp file or if you've deleted it, reproduce the crash again and provide the .dmp file generated that time?

**Comment by Night1099** [comment]
@nv-ajaus 

[Uploading NvRemixBridge.exe_20231019_202915.dmp…]()

**Comment by Sopitive** [comment]
Are there any updates on this issue? We all have a version of the bridge and dxvk that work with the game, but they are really old versions that do not include many of the new features. The game always freezes and does not boot up. We get the last log message of `Creating a NON thread-safe D3D9 device`. There are no more log messages after that. It appears to be the bridge, running it with the older version of bridge-remix and the newest dxvk-remix allows the game to boot up, although there are lots of flashes and visual artifacts running those two together. Something was probably changed about how remix hooks into the game on launch that causes the game to hang. We all would love to hear any feedback on this issue and use remix with Battlefront II ❤️.

**Comment by nv-ajaus** [comment]
@Night1099 @Sopitive , We've recently corrected an issue where different threads in the bridge can stomp on data they can both access. Can you please retry with the latest dxvk-remix and bridge-remix builds to see if this is working now?

**Comment by NV-LL** [comment]
Hello @Night1099! We believe recent builds contain a fix that should address this issue. Will you please test with the latest release and let us know if the problem persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
