### ISSUE TITLE
Old DLSS version in current build

### ISSUE THREAD

**Issue by alfonslm** [NVIDIAGameWorks/rtx-remix#271]
Could we get an update to get DLSS 3.5 instead of DLSS 3.0. 

From my limited knowledge it should be an easy update.

**Comment by NV-LL** [comment]
Thank you for the suggestion! Great minds think alike - this feature was upgraded with our latest releases (0.5/2024.3.0). You can find more info here: https://www.nvidia.com/en-us/geforce/news/rtx-remix-dlss-3-5-ray-reconstruction/
