### ISSUE TITLE
ImGui Context Crash on Startup - Multiple Titles

### ISSUE THREAD

**Issue by anchorlightforge** [NVIDIAGameWorks/rtx-remix#273]
**Describe the bug**
- In recent versions of Remix, I have found a number of titles that are now crashing immediately.  Some of these titles appear to have regressed and worked correctly in previous tests (i.e. Condemned: Criminal Origins, F.E.A.R.).
- The error points directly to ImGui's codebase and at first glance appears to be a race condition as the ImGui function GetIO() is called before a context has actually been created and/or set.
- This crash will silently occur on Release builds. If using Debug-Optimized, an assert will fail before crashing.

**User specifications**
- Remix Version 0.3.0 Debug-Optimized
- GPU: Nvidia Geforce RTX 3080
- Driver: Nvidia Studio 536.67
- Sea Dogs [(GOG)](https://www.gog.com/en/game/sea_dogs)

**Attach files!**
[Sea Dogs ImGui Crash.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13161112/Sea.Dogs.ImGui.Crash.zip)
- This contains all logs for startup.  The logs are for a debug-optimized assert failure; the crash dump was taken immediately after by allowing the program to proceed anyway.

Setup Instructions (Sea Dogs):
1. Download and install Sea Dogs from GOG:
2. Install [ElishaCloud's DxWrapper v1.1.6900.22](https://github.com/elishacloud/dxwrapper/releases/tag/v1.1.6900.22) to the game directory, including dxwrapper.dll and stub/ddraw.dll in the base directory 
3. Extract the included INI files to the game directory: 
[SeaDogsImGuiCrashConf.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13161111/SeaDogsImGuiCrashConf.zip)

**To Reproduce**
1. Complete the setup instructions above
2. Open ENGINE.exe
3. Game will fail assert
4. If continuing, the game will hit a ddraw error

**Other titles with similar issues:**
- Condemned: Criminal Origins (Steam) (regression)
- F.E.A.R. (GOG) (regression)
- Risen 2: Dark Waters (GOG)
- MDK (Direct3D - ElishaCloud DxWrapper d3d7to9) (GOG) (Regression)

**Expected behavior**
- ImGui is supposed to begin performing basic functions such as setting the mouse cursor to the appropriate type at this point.
- A context should already exist by the time ImGui functions are called on in the program.

**Screenshots**
![NvRemixBridge_Utxdc7WMbh](https://github.com/NVIDIAGameWorks/rtx-remix/assets/55258193/3ff9afac-3846-42bc-999d-7697ec044468)

**Comment by NV-DM** [comment]
REMIX-2283 for tracking.

**Comment by anchorlightforge** [comment]
Today I had this issue with Slave Zero (GOG) after using a community provided D3D patch.  The game launched successfully the first few times then eventually began to suffer from this same ImGuiContext issue.  In the original issue filing I was uncertain as to whether this behavior was a race condition or ImGui's initialization silently failing, but my current testing experience seems to further indicate a race condition.

**Comment by anchorlightforge** [comment]
Today I reproduced the issue with a game that was already running successfully.  While testing Unreal Tournament 2003 I started the game, began a match without issue, and changed resolutions from fullscreen 800x600 to fullscreen 1680x1050, and the result was a GImGuiContext crash.  Unfortunately this game will be difficult to test with as it is not available digitally.

**Comment by NV-DM** [comment]
Hello. Do you happen to have a crash dump and logs for the UT crash? Updated bug with latest info.

**Comment by anchorlightforge** [comment]
Hi,

I'm sorry, I'm not sure I follow.  What is UT referring to?

**Comment by anchorlightforge** [comment]
Unfortunately after attempting to reproduce the UT2003 bug to provide a crash, I instead found several unrelated bugs and crashes that occurred while changing settings.  I'll collect more info on those and file them as separate issues as soon as I can.

**Comment by xbei-nv** [comment]
Hi could you try the latest REMIX and Bridge? We tested it on the some games you listed, the Sea Dogs and F.E.A.R (GOG version), both works without seeing the crash in ImGUI.

**Comment by anchorlightforge** [comment]
> Hi could you try the latest REMIX and Bridge? We tested it on the some games you listed, the Sea Dogs and F.E.A.R (GOG version), both works without seeing the crash in ImGUI.

It looks like it's fixed now.  I'll go ahead and close this thread. Thank you!
