### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by joopss** [NVIDIAGameWorks/rtx-remix#278]
**Describe the bug**
- Game Dragon Dogma Dark Arisen hmmm black screen when i start the game i hear the sound of the game, if i remove the d3d9.dll no black screen. and i see the welcome to remix UI
- Which Remix version - 0.3.0-release
- Which GPU rtx 4090
- Which GPU driver version - 546.01
- Which game build - Steam

**Attach files!**
- NvRemixBridge.log
- d3d9.log
- The game specific log will be named gamename_d3d9.log
- Used rtx.conf
- For crashes also attach dump files: {.dmp} for CPU side crashes and {.nv-gpudmp and shaderDebugInfo folder} for GPU side crashes. Automatic GPU dumps can be enabled by setting "dxvk.enableAftermath = True" in dxvk.conf. Zip these files before uploading them.
  Note, the dumps may contain personally identifiable information.

[22:07:07.667] info:  No default config found for: D:\SteamLibrary\steamapps\common\DDDA\DDDA.exe
[22:07:07.670] info:  Trying to open config file: D:\SteamLibrary\steamapps\common\DDDA\.trex\bridge.conf
[22:07:07.671] info:  ==================
[22:07:07.673] info:  NVIDIA RTX Remix Bridge Client
[22:07:07.675] info:  ==================
[22:07:07.676] info:  Version: remix-0.3.0
[22:07:07.678] info:  Loaded d3d9.dll from D:\SteamLibrary\steamapps\common\DDDA\DDDA.exe
[22:07:07.695] info:  DirectInput8 hook attached.
[22:07:07.710] info:  DirectInput hook attached.
[22:07:07.711] info:  Initializing new shared memory object.
[22:07:07.713] info:  Initializing new shared memory object.
[22:07:07.715] info:  Initializing new shared memory object.
[22:07:07.755] info:  Initializing new shared memory object.
[22:07:08.212] info:  Launching server with GUID e517682e-fcea-4582-948a-896b4f47a8d2
[22:07:08.259] info:  Process set as DPI aware
[22:07:08.261] info:  Sending SYN command, waiting for ACK from server...
[22:07:09.352] info:  Ack received! Handshake completed! Telling server to continue waiting for commands...
[22:07:09.360] warn:  Window extent != backbuffer extent in fullscreen mode. Forcing window extent to backbuffer size (1920x1080).
[22:07:09.363] info:  Creating a thread-safe D3D9 device.
[22:07:11.787] info:  DirectInput mouse acquired
[22:07:13.367] info:  Message channel UWM_REMIX_BRIDGE_REGISTER_THREADPROC_MSG handshake complete.
[22:07:13.372] info:  Remix UI deactivated.
[22:07:13.373] info:  Remix UI deactivated.
[22:07:13.591] warn:  Non-exclusive DirectInput mouse message skipped.
[22:07:15.741] info:  Remix UI activated.
[22:07:26.595] info:  Remix UI activated.
[22:07:36.552] info:  Remix UI activated.
[22:07:37.957] info:  Remix UI activated.
[22:08:15.412] info:  Remix UI deactivated.
[22:08:19.115] info:  About to unload bridge client.
[22:08:19.115] info:  Sending Terminate command to server...
[22:08:20.016] info:  Server notified that it has cleanly terminated. Cleaning up.
[22:08:20.154] info:  Most recent Device Queue commands sent from Client
[22:08:20.155] info:  Command sent: Terminate
[22:08:20.156] info:  Command sent: IDirect3DDevice9Ex_Destroy
[22:08:20.157] info:  Command sent: IDirect3DVertexDeclaration9_Destroy
[22:08:20.158] info:  Command sent: Bridge_UnlinkResource
[22:08:20.159] info:  Command sent: IDirect3DSwapChain9_Destroy
[22:08:20.160] info:  Command sent: IDirect3DSurface9_Destroy
[22:08:20.161] info:  Command sent: Bridge_UnlinkResource
[22:08:20.163] info:  Command sent: IDirect3DTexture9_Destroy
[22:08:20.164] info:  Command sent: Bridge_UnlinkResource
[22:08:20.166] info:  Command sent: IDirect3DTexture9_Destroy
[22:08:20.168] info:  Most recent Device Queue commands received by Server
[22:08:20.170] info:  Command received: Terminate
[22:08:20.171] info:  Command received: IDirect3DDevice9Ex_Destroy
[22:08:20.172] info:  Command received: IDirect3DVertexDeclaration9_Destroy
[22:08:20.174] info:  Command received: Bridge_UnlinkResource
[22:08:20.175] info:  Command received: IDirect3DSwapChain9_Destroy
[22:08:20.177] info:  Command received: IDirect3DSurface9_Destroy
[22:08:20.179] info:  Command received: Bridge_UnlinkResource
[22:08:20.179] info:  Command received: IDirect3DTexture9_Destroy
[22:08:20.180] info:  Command received: Bridge_UnlinkResource
[22:08:20.180] info:  Command received: IDirect3DTexture9_Destroy
[22:08:20.182] info:  Most recent Module Queue commands sent from Client
[22:08:20.183] info:  Command sent: IDirect3D9Ex_Destroy
[22:08:20.183] info:  Command sent: IDirect3D9Ex_CreateDevice
[22:08:20.184] info:  Command sent: IDirect3D9Ex_CheckDeviceFormat
[22:08:20.185] info:  Command sent: IDirect3D9Ex_CheckDeviceFormat
[22:08:20.186] info:  Command sent: IDirect3D9Ex_CheckDeviceFormat
[22:08:20.187] info:  Most recent Module Queue commands received by Server
[22:08:20.188] info:  Command received: IDirect3D9Ex_Destroy
[22:08:20.189] info:  Command received: IDirect3D9Ex_CreateDevice
[22:08:20.190] info:  Command received: IDirect3D9Ex_CheckDeviceFormat
[22:08:20.191] info:  Command received: IDirect3D9Ex_CheckDeviceFormat
[22:08:20.193] info:  Command received: IDirect3D9Ex_CheckDeviceFormat
[22:08:20.194] info:  Shutdown cleanup successful, exiting now!
[22:08:20.196] info:  DirectInput8 hook detached.
[22:08:20.198] info:  DirectInput hook detached.
[22:08:20.199] info:  [Uptime]: 72s

info:  Game: DDDA.exe
info:  DXVK_Remix: remix-0.3.0
info:  Init config: User
info:  Looking for config: User
info:  Attempting to parse: dxvk.conf at CWD("D:\\SteamLibrary\\steamapps\\common\\DDDA")...
info:  No config file found at: dxvk.conf
info:  Init config: App
info:  Looking for config: App
info:  Did not find app config for executable: D:\SteamLibrary\steamapps\common\DDDA\DDDA.exe
info:  Set startup config.
info:  Init config: RtxUser
info:  Looking for config: RtxUser
info:  Attempting to parse: rtx.conf at CWD("D:\\SteamLibrary\\steamapps\\common\\DDDA")...
info:  Found config file: rtx.conf
info:  Parsed config file.
info:  RtxUser configuration:
info:    rtx.allowFSE = True
info:    rtx.captureInstanceStageName = capture_2023-11-01_20-08-32.usd
info:    rtx.postfx.enableChromaticAberration = False
info:    rtx.enableUnorderedEmissiveParticlesInIndirectRays = True
info:    rtx.postfx.enableVignette = False
info:    rtx.enableVolumetricLighting = True
info:    rtx.graphicsPreset = 0
info:    rtx.postfx.enableMotionBlur = False
info:  Set custom config.
info:  Init config: RtxMod
info:  No base game mod path found. Skipping initilization.
info:  Effective (combined) configuration:
info:    rtx.allowFSE = True
info:    rtx.postfx.enableChromaticAberration = False
info:    rtx.captureInstanceStageName = capture_2023-11-01_20-08-32.usd
info:    rtx.postfx.enableVignette = False
info:    rtx.enableUnorderedEmissiveParticlesInIndirectRays = True
info:    rtx.enableVolumetricLighting = True
info:    rtx.graphicsPreset = 0
info:    rtx.postfx.enableMotionBlur = False
info:  Geometry generation hash rule:
info:  	positions
info:  	indices
info:  	texcoords
info:  	geometrydescriptor
info:  	vertexlayout
info:  	vertexshader
info:  Geometry asset hash rule:
info:  	positions
info:  	indices
info:  	geometrydescriptor
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_external_memory_capabilities
info:    VK_KHR_external_semaphore_capabilities
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Enabled Layer Names:
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce RTX 4090:
info:    Driver: 545.92.0
info:    Vulkan: 1.3.260
info:    Memory Heap[0]: 
info:      Size: 24156 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 16342 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce RTX 4090:
info:    Driver: 545.92.0
info:    Vulkan: 1.3.260
info:    Memory Heap[0]: 
info:      Size: 24156 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 16342 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:  Process set as DPI aware
warn:  ConvertFormat: Unknown format encountered: D3D9Format::R2VB
info:  Device properties:
info:    Device name:     : NVIDIA GeForce RTX 4090
info:    Vendor name:     : NVIDIA
info:    Device ID:       : 0x2684
info:    Vendor ID:       : 0x10de
info:    Driver version   : 545.92.0
info:  Enabled device extensions:
info:    VK_EXT_4444_formats
info:    VK_EXT_calibrated_timestamps
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_memory_priority
info:    VK_EXT_opacity_micromap
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_acceleration_structure
info:    VK_KHR_buffer_device_address
info:    VK_KHR_create_renderpass2
info:    VK_KHR_deferred_host_operations
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_external_memory
info:    VK_KHR_external_memory_win32
info:    VK_KHR_external_semaphore
info:    VK_KHR_external_semaphore_win32
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance4
info:    VK_KHR_pipeline_library
info:    VK_KHR_push_descriptor
info:    VK_KHR_ray_query
info:    VK_KHR_ray_tracing_pipeline
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float16_int8
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:    VK_KHR_synchronization2
info:    VK_NVX_binary_import
info:    VK_NVX_image_view_handle
info:    VK_NV_low_latency
info:    VK_NV_optical_flow
info:    VK_NV_ray_tracing_invocation_reorder
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 0
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:    hostQueryReset                         : 1
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 1
info:    formatA4B4G4R4                         : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 0
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 1
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_buffer_device_address
info:    bufferDeviceAddress                    : 1
info:  VK_NV_optical_flow
info:    nvOpticalFlow                            : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:    Async Compute : 2
info:    Optical flow : 4
info:    Present : 2
info:  DXVK: Read 377 valid state cache entries
info:  DXVK: Using 3 compiler threads
warn:  Cannot find rtx-remix\mods\ under current directory: D:\SteamLibrary\steamapps\common\DDDA
info:  [GameCapturer] DXVK_RTX_CAPTURE_ENABLE_ON_FRAME: 
warn:  [GameCapturer] LSS USD Plugins failed to load.
info:  Reflex initialized successfully.
info:  Automatic Raytrace Mode Preset in use (Set rtx.raytraceModePreset to something other than Auto use a non-automatic preset)
info:  NVIDIA architecture detected, setting default raytrace modes to Trace Ray (GBuffer/Indirect Integrate) and Ray Query (Direct Integrate)
info:  [RTX info] Opacity Micromap: supported
info:  [RTX info] Shader Execution Reordering: supported
info:  [RTX info] Shader Execution Reordering: enabled
info:  CPU supports SIMD: AVX2
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1920x1080
info:    Image count:  3
info:    Exclusive FS: 3
info:  Setting display mode: 1920x1080@71
info:  No winproc detected, initiating bridge message channel for: 0000000000510B1A
info:  No winproc detected, initiating bridge message channel for: 0000000000510B1A
info:  Message channel UWM_REMIX_BRIDGE_REGISTER_THREADPROC_MSG established.
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1920x1080
info:    Image count:  3
info:    Exclusive FS: 3
info:  [RTX-Compatibility-Info] Trying to raytrace but not detecting a valid camera.
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Setting display mode: 1920x1080@71
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1918x1078
info:    Image count:  3
info:    Exclusive FS: 3
warn:  D3D9Texture2D::QueryInterface: Unknown interface query
warn:  794950f2-adfc-458a-905e-10a10b0b503b
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_MULTISAMPLEANTIALIAS
info:  [RTX-Compatibility-Info] Skipped drawcall, colour write disabled.
info:  [RTX-Compatibility-Info] Found a draw call to a non-primary render target. Falling back to rasterization
info:  [RTX-Compatibility-Info] Texture 0 without valid hash detected, skipping drawcall.
warn:  D3D9TextureCube::QueryInterface: Unknown interface query
warn:  794950f2-adfc-458a-905e-10a10b0b503b
info:  [RTX-Compatibility-Info] Skipped shadow mask drawcall.
info:  Serializing config file: rtx.conf
info:  Serializing config file: rtx.conf
info:  Serializing config file: rtx.conf
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1918x1078
info:    Image count:  3
info:    Exclusive FS: 3
info:  Serializing config file: rtx.conf
info:  Serializing config file: rtx.conf
info:  Restoring display mode: 1920x1080@60
info:  Setting display mode: 1920x1080@60
info:  Restoring display mode: 1920x1080@71
info:  Setting display mode: 1920x1080@71

**Comment by nv-ajaus** [comment]
Hi @joopss , there is a discord community that may be able to help you with installation and bring up of RTX-Remix with titles. https://discord.gg/rtxremix

**Comment by nv-ajaus** [comment]
Thank you for filing this issue, I'm closing it for now.
