### ISSUE TITLE
Portal RTX and Doom Eternal RTX is working bad performance. Fixed re installing LunarG

### ISSUE THREAD

**Issue by jgmatu** [NVIDIAGameWorks/rtx-remix#282]
**Describe the bug**

- Running portal RTX is not working
- Steam release version until 9 Dec 2023.
- Nvidia 4070ti RTX
- Driver: 546.29.0
- Vulkan: 1.3.260
- Steam

_**warn: [06.12.2023 19-28-53][streamline][error]wrapper.cpp:408[vkCreateDevice] vkCreateDevice failed
err: DxvkAdapter: Failed to create device**_

** Steps to reproduce the behavior **

1. Go to game on your steam library.
2. Click on play.
3. The game will not launch anymore.

**Expected behavior**
- The game initialize and I can see the main game menu.

**Attached files**

- Crash dump log
- Release version config files 

[dxvk.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13625494/dxvk.txt)
[hl2_d3d9.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13625495/hl2_d3d9.txt)
[metrics.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13625496/metrics.txt)
[rtx.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13625497/rtx.txt)
[steam_appid.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13625498/steam_appid.txt)
[thirdpartylegalnotices.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13625499/thirdpartylegalnotices.txt)

Thanks,

**Comment by pkristof** [comment]
Can you try verifying your local game cache on Steam, updating to latest and running again?

**Comment by anon-apple** [comment]
I couldn't reproduce this with the latest Nvidia driver (546.33) on a RTX 4090 at least, so it may be an issue with that specific driver and it might be worth a try updating it.

**Comment by jgmatu** [comment]
Hi,

I have updated today the drivers but the problems still happens in game initialization. I have deleted steam cache and download again. I also have reinstalled steamworks tools. I have a problem if you can not replicate the issue in your environment. I give you again the config files generated. I had to change the file extension from .conf to .txt to upload to git issue. I have to do a more extended research. In my actual situation as game user, I can change the configuration files rtx.conf metrics, and dxdk.conf I have seen a lot community docs about RTX remix games. I can't access to portal RTX code and check exactly the wrapper.cpp function when the vkCreateDevice fails, but I can test with diffs configurations. I don't know if there are some Vulkan specs diffs between 4070ti and 4090ti I suppose not, the only differences is the number of CUDA processor but the technology is the same as they are same graphic card generation... I am gonna try to changes dxvk.conf parameters and rtx.conf parameters it is possible I have a mistake on this part.

[hl2_d3d9.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13653350/hl2_d3d9.txt)
[metrics.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13653351/metrics.txt)
[rtx.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13653352/rtx.txt)
[steam_appid.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13653354/steam_appid.txt)
[thirdpartylegalnotices.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/13653355/thirdpartylegalnotices.txt)

Thanks,

**Comment by jgmatu** [comment]
Hi I have resolved the issue!! I have reinstalled LunarG SDK and the problem has been resolved magically! I am sorry!

**Comment by jgmatu** [comment]
One last thing, I having some performance problems... and some rendering issues... How can I revert any changes with LunarG? and come back to mortal user? Or if you have some tips how to use Vulkan Configurator or LunarG tools to improve RTX remixed It will be nice!

**Comment by jgmatu** [comment]
Hi,

I had similar problems with Doom Eternal RTX after fix Portal RTX I have fixed also Doom Eternal RTX. Can you give some tips about performance and how to configure the Vulkan Configurator? I having some performance problems with Portal RTX.

Doom Eternal RTX with the problem, the game try to rendering with CPU.

![747fc553-cab6-4778-92ed-bde61aa6ef86](https://github.com/NVIDIAGameWorks/rtx-remix/assets/14931061/96faa694-c178-4b94-ae4b-baa2f6040c29)

Doom Eternal RTX after Vulkan Configurator Applied.

![627785da-a342-44e5-a80a-6a1f92688803](https://github.com/NVIDIAGameWorks/rtx-remix/assets/14931061/b4e47e4c-cb49-4b10-af42-09dcbcdebb6a)

Thank you for your time

**Comment by jgmatu** [comment]
Hi! :).

I don't know how to replicate again the issue! but it is a development problem then I think it is not important as game user. I can play Portal RTX again, and touching DLSS parameters I can have a good performance. The only thing is:

- When I background the game Win + Tab and I try again to put in foreground the game will close. If you can not replicate this issue then I think we can close the issue because for me now the game is playable.

I don't want to waste your time because I am expecting HL2 RTX! and I would like to play it the most soon as possible. I have to learn Vulkan API I did some work with OpenGL and GLSL shaders in the past! I don't know if I can help in something in this project! Can you give some reference guide to help? 

Thank you for all your work!!!

**Comment by EliteCombineSoldier** [comment]
> Hi! :).
> 
> I don't know how to replicate again the issue! but it is a development problem then I think it is not important as game user. I can play Portal RTX again, and touching DLSS parameters I have a good performance. Re installing LunarG solved the problem.
> 
> The only thing is:
> 
> * When I background the game Win + Tab and I try again to put in foreground the game will close. If you can not replicate this issue then I think we can close the issue because for me now the game is playable.
> 
> I don't want to waste your time because I am expecting HL2 RTX! and I would like to play it the as soon as possible. I have to learn Vulkan API I did some work with OpenGL and GLSL shaders in the past! I don't know if I can help in something in this project! Can you give some reference guide to help?
> 
> Thank you for all your work!!!
Source engine games tend to crash when putting it in the background, its more of an engine issue.

**Comment by nv-ajaus** [comment]
Hi @jgmatu , thanks for filing and working through this issue. If you are interested in helping with RTX Remix, I would recommend joining the community operated RTX-Remix Showcase discord ( https://discord.gg/rtxremix ). There's a lot of very passionate people on there, working on remix related projects and even contributing to the project directly too.
