### ISSUE TITLE
[Issue]Missing bumps on the edges of pbr displacement textures

### ISSUE THREAD

**Issue by Entityexist** [NVIDIAGameWorks/rtx-remix#285]
Every time we try to apply a PBR texture with highmap it get displayed correctly while facing the texture, but if the mesh is for example a 45 degrees angle it will display a straight cut line on the edge instead of blending the highmap and creating a smooth transition

1. Apply Bricks with height map to mesh
2. Look at the corners of the mesh 
3. The corners arent bumpy and transparent like they should be

**Expected behavior**
- Corners of the mesh should be bumpy and transparent

**Screenshots**
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/132615924/8a55559c-bd69-4749-ba14-e1b052e50dcd)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/132615924/63648fd2-5bb2-4a06-8030-faf330b02e0b)

**Comment by NV-DM** [comment]
REMIX-1963 for tracking.

**Comment by nv-ajaus** [comment]
Hi @Entityexist, this is currently working as we'd expect. We hope to improve this behavior in the future and have associated this issue with the feature.

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
