### ISSUE TITLE
World Racing 2 - Black screen upon launching the game

### ISSUE THREAD

**Issue by xKrasheR** [NVIDIAGameWorks/rtx-remix#286]
**Describe the bug**
- Upon launching the game, the game window is completely black and there are not even RTX Remix related pop-ups visible (Welcome to RTX Remix [...]). Stable versions before 0.3.0 are giving "Could not create Direct 3D device!" error, but back a while ago I was able to run the game fine with the latest unstable dxvk/bridge as of April 15th. Upon running though i can "hear" that the game runs and reacts to inputs, as there is music and various sfx playing in the background.
- remix-0.3.0-release
- RTX 3090
- 546.31
- World Racing 2 - Champion Edition (https://store.steampowered.com/app/1301010/World_Racing_2__Champion_Edition/)

**Attach files!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13746882/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13746894/d3d9.log)
- [WR2_PC_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13746900/WR2_PC_d3d9.log)

**To Reproduce**
1. Launch the game in 32-bit mode

**Comment by NV-DM** [comment]
Thank you for filling the report. Are you using a DirectX8 to 9 wrapper?

**Comment by xKrasheR** [comment]
I have tried using a DX8 to 9 wrapper but it doesnt make any difference because it seems the Champion Edition of the game runs at DX9 already

**Comment by xKrasheR** [comment]
Closing this one as the game appears to be probably not compatible with Remix

**Comment by xKrasheR** [comment]
Closing this one as the game appears to be probably not compatible with Remix
