### ISSUE TITLE
Tomb Raider: Legend - Remix hooking, but not rendering correctly

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#287]
**Describe the bug**
- It looks like Tomb Raider: Legend fits all the requirements for RTX-Remix, but remix is just not wanting to replace the render.
- Tested with RTX-Remix Debug-Optimized with updated DXVK [dxvk-remix-a01635a-360-debugoptimized]
- GPU RTX 2060 
- GPU Driver 546.33
- Tomb Raider: Legend on Steam Retail

**Attach files!**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13758280/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13758281/d3d9.log)
[trl_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13758282/trl_d3d9.log)
-No rtx.conf created
- For crashes also attach dump files: {.dmp} for CPU side crashes and {.nv-gpudmp and shaderDebugInfo folder} for GPU side crashes. Automatic GPU dumps can be enabled by setting "dxvk.enableAftermath = True" in dxvk.conf. Zip these files before uploading them.
  Note, the dumps may contain personally identifiable information.

-No crashes with rtx-remix 

**To Reproduce**

-Install RTX Remix in game folder with trl.exe
-(optional) Enable Next Generation Content in settings - can be enabled in-game or via setup.exe

**Expected behavior**
- RTX Remix hooks and loads the game normally if all of the optional settings are disabled (shadows, anti-aliasing, etc.) and you can go about playing the game. Alt+X brings up the remix menu, but no visual changes occur ingame. 

But, if you do enable the game's "Next-Generation Content" remix does appear to have a reaction.  Some of the games materials go missing. It looks like remix is trying to have a reaction, but so far it doesn't work as expected. I've tried messing with the alpha/beta render option in remix, but looks like it doesn't fix the issue.

**Screenshots**
Screenshots are of Tomb Raider: Legend in-game with  [dxvk-remix-a01635a-360-debugoptimized] with the "Next-Generation Content" enabled. 
![Screenshot (280)](https://github.com/NVIDIAGameWorks/rtx-remix/assets/148610406/9fe565af-654e-495e-96a8-937d99448872)
![Screenshot (281)](https://github.com/NVIDIAGameWorks/rtx-remix/assets/148610406/2f0aa3f4-c983-4c2b-9185-013dfdc84e7e)

Link to discord page: https://discord.com/channels/1028444667789967381/1187344851713392711
Link to compatibility page: https://trello.com/c/1FZ4i5p2

**Comment by NV-DM** [comment]
Thank you for filling the report. It looks like this is a Shader Model 3 game according to https://www.pcgamingwiki.com/wiki/Tomb_Raider:_Legend which are generally not compatible. The best bet here would be to force the game into fixed function which looks like you tried according to Discord. Closing this for now as it doesn't seem to be a DXVK issue.
