### ISSUE TITLE
Silent Hill 2: Enhanced Edition - Game is captured upside down.

### ISSUE THREAD

**Issue by traggey** [NVIDIAGameWorks/rtx-remix#294]
**Describe the bug**
- The game is captured upside down and the available settings for changing capture directions do not affect it.

- Issue is present in all versions of remix

**To Reproduce**
- Set the game and Enhanced Edition up by following my guide - https://docs.google.com/document/d/1hayGXNlAJZWOp2ivV8otdSMP23pbXk7DL-pfLq5ZJjU
- Start the game and skip the opening cinematics
- Once standing in the bathroom open the developer menu and grab a capture.
- Observe capture direction being incorrect.

**Expected behavior**
- The capture direction being oriented correctly.

**Comment by xbei-nv** [comment]
This issue has been fixed

**Comment by traggey** [comment]
This issue has indeed been fixed! Awesome-sauce
