### ISSUE TITLE
using Deus Ex: Revision bug 

### ISSUE THREAD

**Issue by twitchplayskh** [NVIDIAGameWorks/rtx-remix#3]
back with old portal rtx files Deus Ex: Revision mod  would run but all the textures bugged out but now when i run with the new files from this git hub i run into this 
![Screenshot 2023-04-12 142613](https://user-images.githubusercontent.com/7377207/231479469-15d43eac-e79c-4dba-a7d4-cbd98d622fcb.png)
now is this a bug with the game or with this updated remix as it did not happen before? 
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11212198/d3d9.log)

**Comment by twitchplayskh** [comment]
> Bump, same error after the intro scene with 'stock' Deus Ex but replaced wrappers. Old/Original Portal RTX was playable though very graphically glitchy due to textures and various odd things. Remix 0.1.0 is better and has less stuff "missing" for rendering, but that issue happens

yes the mod i am using has  a custom dx9 wrapper so i have this as soon as i boot the game haha

**Comment by NV-DM** [comment]
Thank you for reporting. We are looking into this issue. REMIX-1192 for tracking.

**Comment by NV-DM** [comment]
Hello. Could you please re-test with most recent release? Thank you!

**Comment by NV-LL** [comment]
We'll be closing this issue due to lack of response for some time now. If you still experience this problem, please open another ticket. Thank you!
