### ISSUE TITLE
Obscure 1 crash on startup.

### ISSUE THREAD

**Issue by ran-j** [NVIDIAGameWorks/rtx-remix#302]
### Contact Details (Optional)

ran-junior@hotmail.com

### Describe the bug

I`m using the steam version. but it crash before open any window.

### How do you reproduce the bug?

1. Open then game 'Obscure.exe'. 

[obscure_254460_crash_2024_1_17T3_57_41C0.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13963045/obscure_254460_crash_2024_1_17T3_57_41C0.zip)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13963033/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13963034/NvRemixBridge.log)

### What is the expected behavior?

The toolkit should work.

### Version

remix-0.3.0

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
