### ISSUE TITLE
Obscure 2 opens but does nothing

### ISSUE THREAD

**Issue by ran-j** [NVIDIAGameWorks/rtx-remix#303]
### Describe the bug

The game open and I can see the RTX menus but it changes nothing on the game.

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/17410205/b9acd0de-377a-4493-90b6-4ecb9da047e2)

The textures are loaded correctly
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/17410205/3aceb407-f34c-4563-a116-a2db367ca677)

### How do you reproduce the bug?

1. Open the game.

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13963291/d3d9.log)
[Obscure2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13963292/Obscure2_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/13963295/NvRemixBridge.log)
[dxvk.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13963311/dxvk.zip)
[bridge.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13963314/bridge.zip)
[NvRemixBridge.exe_20240116_005636.dmp.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13963316/NvRemixBridge.exe_20240116_005636.dmp.zip)

### What is the expected behavior?

The toolkit should be able to export scene.
The toolkit should be able to modify the render.

### Version

remix-0.3.0

**Comment by nvdamien** [comment]
Hey @ran-j  ,

This is a runtime bug. The toolkit is not released yet. Please use the runtime template for the following bugs..

**Comment by nv-ajaus** [comment]
Hi ran-j , I took a look at this issue and noticed that you were only getting raster rendering with RTX Remix. This might indicate incompatibility and I would usually ask you to post on the community ran RTX Remix Showcase discord for help, but it seems like you already have and have tried forcing compatibility. Unfortunately, there's not much more help I can provide at this time.

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
