### ISSUE TITLE
[Toolkit bug]: Opening a .usda project immediately crashes Remix

### ISSUE THREAD

**Issue by DrakeFruit** [NVIDIAGameWorks/rtx-remix#307]
### Describe the bug

following this tutorial: https://www.youtube.com/watch?v=MQejylcuAeU&list=PL4w6jm6S2lzvgJ97T1_VbLGBR_l6zzOUm&index=1 and when I got to the part where you actually open the usda scene capture, remix crashed. It's consistent every time.

https://github.com/NVIDIAGameWorks/rtx-remix/assets/94070205/d4bc812c-4ffb-488d-bb53-52a8192a34ac

### How do you reproduce the bug?

1. Create a new project using the example exe
2. Open the new project you created, using an RTX 2080 super

### What is the expected behavior?

the usda capture should open without crashing

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hey @DrakeFruit ,

Thanks for the report. Your zip file works for me.
Can you send us your log please?

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/128181406/2c2f0351-fb35-4ebe-82c6-2fe51fbe91e3)

**Comment by DrakeFruit** [comment]
> Hey @DrakeFruit ,
> 
> Thanks for the report. Your zip file works for me. Can you send us your log please?
> 
> ![image](https://private-user-images.githubusercontent.com/128181406/298675383-2c2f0351-fb35-4ebe-82c6-2fe51fbe91e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDc1NzUsIm5iZiI6MTcwNTk0NzI3NSwicGF0aCI6Ii8xMjgxODE0MDYvMjk4Njc1MzgzLTJjMmYwMzUxLWZiMzUtNGViZS04MmM2LTJmZTUxZmJlOTFlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxODE0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTE2ZWIwZDIxMjhjNjQ2NTc3MmJkMzM1ZWZlODc1MTcwYzA0ZDc0NTAwZDYxMmJmNGE4OTMzMzllOWI3YjMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bj4MVZ2gLt0-RQDFVuUQNHmP1yM9IvcEKI55DWRf24c)

I can't open that window to share the log, that's the screen it crashes on

**Comment by nvdamien** [comment]
What you can do is:
1. Open your usd file and make the app crash
2. Re-open the app, click on "Setup project"
3. Open the show log

Send the log (the 2 last one).

**Comment by DrakeFruit** [comment]
> What you can do is:
> 
>     1. Open your usd file and make the app crash
> 
>     2. Re-open the app, click on "Setup project"
> 
>     3. Open the show log
> 
> 
> Send the log (the 2 last one).

without a usd loaded, the right click context menu in that area doesn't pop up at all

**Comment by DrakeFruit** [comment]
[kit_20240122_111951.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14014553/kit_20240122_111951.log)

**Comment by nvdamien** [comment]
Hi,

This log is the last one, which is not the one that show the crash (this is the log created when you open the app to send me the log). Please send the 2 last logs.

From the previous steps:
1. Open your usd file and make the app crash
2. Re-open the app, click on "Setup project"
3. Open the show log

Send the log (**the 2 last one**).

**Comment by DrakeFruit** [comment]
my bad, im a bit tired ha
[kit_20240122_113103.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14014677/kit_20240122_113103.log)
[kit_20240122_113003.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14014678/kit_20240122_113003.log)

**Comment by nvdamien** [comment]
Filed on REMIX-2652

Someone from our team will look at it, and ask more info if needed.

**Comment by DrakeFruit** [comment]
just tried this again, 4 hours later... it works now? no crash

**Comment by DrakeFruit** [comment]
NEVERMIND. It was only working temporarily :/

**Comment by NV-DM** [comment]
REMIX-2652 for traking.

**Comment by NV-DM** [comment]
Minspec for RTX Remix is 3060ti, however, someone will look at the issue because it should still not crash.

**Comment by STHAKKARNV** [comment]
Hi @DrakeFruit 

Are you still experiencing this issue? Is it happening consistently or intermittently?

**Comment by DrakeFruit** [comment]
I made sure to update the runtime and it's still crashing in the same way, is there some way to update the RTX Remix app itself that I'm missing?

**Comment by STHAKKARNV** [comment]
Hi @DrakeFruit 

Can you update the drivers to the latest version and see if it still happens? Does it happen every time you try to open the file?  I couldn't reproduce on a 2080Ti but will try few more times to see if I can get it to crash. Thanks

**Comment by nvdamien** [comment]
At this point I would wait for the next build that we will release soon.

**Comment by DrakeFruit** [comment]
I tried again today with the latest drivers, looks like it works fine.
