### ISSUE TITLE
Dungeon Defenders 1 - Cannot capture scenes via RTX Remix

### ISSUE THREAD

**Issue by Traslogan** [NVIDIAGameWorks/rtx-remix#308]
**Describe the bug**
- When trying to capture a scene to begin using RTX remix on Dungeon Defenders 1, the scene simply cannot be captured, it will never do anything after pressing the capture scene button. Only additional info is that this is an Unreal Engine 3 game.
- Remix version 0.4
- RTX 4080
- GPU Driver version 546.65
- Latest on Steam

**To Reproduce**
1. Load up Dungeon Defenders 1 from Steam via RTX Remix
2. try to capture any scene, even the main menu.

**Expected behavior**
- I expected to at least get past the very first part of the process by capturing a scene.

**Comment by NV-DM** [comment]
Hello. Thank you for reporting. Could you please attach relevant logs and screenshots.

**Comment by nv-nfreybler** [comment]
Hi @Traslogan, the Capturer will not work if Remix is unable to prepare scene data and actually inject ray tracing.

Can you confirm whether you see a different render from the standard rasterization? Does the temporary RTX Remix banner appear on launch? Does the game look how it normally looks without remix installation?

If you are unsure about the above, feel free to attach pictures, and we can try to infer from those. Thank you in advance.

**Comment by traggey** [comment]
Dungeon Defenders runs on Unreal Engine 3, which is an engine that is fundamentally incompatible with Remix, it won't work.

**Comment by NV-LL** [comment]
Thank you for reaching out. As mentioned above, the title is unlikely to be supported with Remix.
