### ISSUE TITLE
[Toolkit bug]: Tiling appears to be broken for AI PBR generation

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#310]
### Describe the bug

Upscaling and processing a larger texture such as 2048x2048 reveals a major issue: it appears that tiling is broken. It immediately maxes out all 24 GB VRAM on my 3090, which is definitely not typical of tiling. It should limit it to a set VRAM amount.

### How do you reproduce the bug?

1. Load an albedo texture. Here's my sample one: 
[Barnyard_Dirt_Albedo.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14014461/Barnyard_Dirt_Albedo.zip)
2. Load it into the AI Tools tab
3. Process
4. Observe VRAM issue
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/288979d7-1e76-494b-98e5-d912c4e96a54)

### What is the expected behavior?

Tile textures while processing to avoid VRAM overflow

### Version

2024.1.1

**Comment by SmokedPete** [comment]
Can we get a screenshot of your task manager before and during the inference please? It'll give us a better idea of exactly how much memory the model is using. 

We also need this information if possible:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/136023976/0c589123-7f62-475b-9f8b-904a902011ab)

**Comment by Kim2091** [comment]
Hm. Oddly it's using a different quantity of VRAM now, despite having tested it multiple times with the same texture before. It is still quite a lot of VRAM however. Here are the results:

Before:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/db0dfcfc-a068-4c38-b812-3cd44bfc32b0)


After:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/5776dead-52ce-42e9-9282-c9b8f89bf837)

**Comment by SmokedPete** [comment]
Yeah so if you're upscaling a 2k image you'll get an 8k output which will most likely be very heavy regardless of tiling (all tiles have to be accumulated somewhere).

If you try to execute the model on a 512x512 image you should see < 8GB usage

**Comment by Kim2091** [comment]
It seems other users with lower VRAM cards are also running into this issue (even on smaller textures).

In my experience, other upscaling software does avoid this kind of VRAM utilization, even for a 2k texture. Something definitely seems off here. Are you sure each tile is being moved off of the GPU when it's finished processing?

**Comment by Kim2091** [comment]
I've also just realized that while processing finished about 25 minutes ago, it never emptied my VRAM:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/d52c25f3-7fc7-4463-8616-e4dacf308e69)

**Comment by SmokedPete** [comment]
Cool, I can repro that issue. Will look for a solution here! Thanks!

**Comment by SmokedPete** [comment]
REMIX-2654

**Comment by SmokedPete** [comment]
So the output image being 8k (x3 textures) fully uncompressed you still need quite a bit of VRAM to run this input but I managed to improve usage by 25% so in the next version of the toolkit you should only see the toolkit use about 17GB for this image.

I also fixed the VRAM not getting released after the inference is complete :)

**Comment by nvdamien** [comment]
Done. Please check the last released version.
