### ISSUE TITLE
[Toolkit bug]: CUDA Device does not support bfloat16

### ISSUE THREAD

**Issue by MykhailKozak** [NVIDIAGameWorks/rtx-remix#311]
### Describe the bug

Attempting to use the AI Texture Tools yields the following error message and fails to generate new textures.

`Plugin GeneratePBRMaterial failed with message:
 Fix:
- LOADING: Loading the AI Model
- LOADED: Successfully loaded the AI Model
- PROCESSING: Acquiring Asset
- PROCESSING: Pre-Processing Input
- PROCESSING: Running Inference Loop
- FAIL: Current CUDA Device does not support bfloat16. Please switch dtype to float16.
 stopped validation`

Tried validating with different texture formats, TGA, PNG, JPG.
Tried updating drivers.
Current GPU is RTX 2060S.

### How do you reproduce the bug?

1. Import any texture to PBR Mat Gen
2. Set type and output filepath
3. Click add to queue

### Version

2024.1.1

**Comment by SmokedPete** [comment]
Will have to test with a 20-series GPU later this week! Will update the ticket when we have a repro!

**Comment by SmokedPete** [comment]
REMIX-2661

**Comment by nvdamien** [comment]
Done. Please check the last version of the app.
