### ISSUE TITLE
[Toolkit bug]: Does not stop rendering when in the background

### ISSUE THREAD

**Issue by mmdanggg2** [NVIDIAGameWorks/rtx-remix#314]
### Describe the bug

When I tab out of remix (especially when I go and try my edits in game) toolkit does not stop rendering frames wasting gpu power.
It does stop properly when it is minimised.

### How do you reproduce the bug?

1. Load a scene in toolkit
2. Tab out to another window and see it is still rendering at a high framerate

https://github.com/NVIDIAGameWorks/rtx-remix/assets/3161587/c340311a-e514-441b-994b-56c6f7dad169

### What is the expected behavior?

The toolkit should massively reduce/stop rendering frames when it is not the active window.

### Version

2024.1.1

**Comment by nxkb** [comment]
Hi @mmdanggg2, thanks for reporting.
So far we're only pausing the viewport if the app gets minimized or if it gets hidden by another tab (like when you go to AI Tools).
I'll have to double check what is possible and whether pausing in this case is always desired... it could potentially mean that a viewport gets out of date.

**Comment by mmdanggg2** [comment]
Perhaps an option for the maximum framerate when in background/disable when in background would be nice to have at least.

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by mmdanggg2** [comment]
Yes, latest version does seem to reduce fps when in background and stop rendering when it gets minimised! Perhaps could be reduced even further when just in background but much improved for sure.

**Comment by NV-LL** [comment]
Great, thank you for confirming! We'll close this ticket, but please open another one if you ever notice a regression. Thanks!
