### ISSUE TITLE
[Documentation feedback]: Incorrect link to "Mod Packaging Interface"

### ISSUE THREAD

**Issue by rmtew** [NVIDIAGameWorks/rtx-remix#317]
### Your feedback

Page: https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/howto/learning-packaging.html

The linked "Mod Packaging Interface" links to the page the link is on, not the actual mod packaging interface.

It currently links to: https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/howto/learning-packaging.html
It should likely link to: https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/toolkitinterface/remix-toolkitinterface-layouttab.html#mod-packaging

### What browsers are you seeing the problem on?

Chrome

**Comment by NV-WendyGram** [comment]
Thank you for taking the time to report this documentation issue.  

I have submitted the corrected link.  

Please allow a minimum of 24 hours for the documentation to be updated accordingly.
