### ISSUE TITLE
Lord of the Rings: Return of the King crashes when on foreground.

### ISSUE THREAD

**Issue by HenriqueLJ** [NVIDIAGameWorks/rtx-remix#32]
**Describe the bug**
- Using dxWrapper. The game crashes immediatelly on launch, but if I force it to run in windowed mode and open another window in front of the game window, thus running the game on the background, it works normally. As soon as I bring the game to the foreground, it crashes.
- Remix 0.1.1
- RTX 3060 Ti
- Driver 531.41
- Retail version (From CDs)

**Attach logs!**
- NvRemixBridge.log
- d3d9.log
- The game specific log will be named gamename_d3d9.log

**To Reproduce**
1. Follow the steps to install the dxWrapper (https://github.com/elishacloud/dxwrapper) and on the configuration file, enable D3d8to9  and on the d3d9 section, enable windowed mode.
2. Run the game and immediately click away from the game screen.
3. Hover the mouse over the icon on the task bar, it should show a preview of the game running.
4. Click on the game icon to bring the game to the foreground, and it should crash.

**Expected behavior**
The game should open normally without crashing. It would open normally on the initial Portal RTX release, but after the update it stopped working, and both 0.1.1 and 0.1.0 exhibit this behavior.
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11217429/d3d9.log)
[dxwrapper-rotk.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11217430/dxwrapper-rotk.log)
[rotk_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11217431/rotk_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11217433/NvRemixBridge.log)

**Comment by HenriqueLJ** [comment]
Using x32dbg I found out that it crashes due to a "Access Violation" Exception. It only occurs when trying RTX remix tho.

**Comment by NV-LL** [comment]
Hello! Will you please check on the latest release and let us know if this issue persists? Thank you!

**Comment by HenriqueLJ** [comment]
The issue was fixed.

**Comment by NV-LL** [comment]
Excellent, thank you for confirming! We'll close this ticket.
