### ISSUE TITLE
DirectX 11

### ISSUE THREAD

**Issue by ArturAlekseev** [NVIDIAGameWorks/rtx-remix#322]
Is DirectX 11 support possible in the future?

**Comment by MarkEHenderson** [comment]
Please read over this page to get a general understanding of the topic:
https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/remix-overview.html#why-are-shaders-hard-to-path-trace

**Comment by ArturAlekseev** [comment]
I'v read it. DirectX 9 also have shaders as I know. I did some 3d vision shader modifications when it was not dropped. How it is related to my question?

**Comment by MarkEHenderson** [comment]
As I understand it, the fundamental barriers to supporting shader based d3d9 games, d3d10 games, and d3d11 games are all the same - needing to be able to reconstruct a scene based on the data passed to a game's arbitrary shaders.   

Is remixing shader based games with reasonable performance on modern hardware possible?  We don't know.  We've discussed a few approaches internally, but there are lots of unsolved problems here. Right now our priority is more on getting fixed function d3d9 games working well, and there's plenty to keep us busy there.

**Comment by ArturAlekseev** [comment]
Is it not possible to fix by shaders disable/replace? Like helix did to fix shaders not supporting stereoscopy? Yes its maybe not possible to automate it. But just give people tool to work with shaders and...

**Comment by NV-LL** [comment]
Per the above comment, this feature presents a lot of unsolved problems, and our current priority is to keep focus on DX9 games. We apologize if that causes any frustration, and we hope you continue to suggest features in the future.
