### ISSUE TITLE
Lineage 2 Crash

### ISSUE THREAD

**Issue by AN3Orik** [NVIDIAGameWorks/rtx-remix#325]
**Describe the bug**
- Game crash when running with rtx runtime
- Which Remix version: 0.4.0
- Which GPU: RTX 2080Ti
- Which GPU driver version: 31.0.15.4633
- Which game build: http://akumu.ru/lineage2/L2KR/P437/L2KR-P437-D20230620-G840/L2KR-P437-D20230620-G840.torrent

**To Reproduce**
1. Place rtx-runtime into system directory
2. Run l2.exe from system directory
3. See crash error
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/6397450/7e5360d7-e57a-4940-a943-67ac95619b94)

[L2_20240125_040527.dmp](https://github.com/NVIDIAGameWorks/rtx-remix/files/14046611/L2_20240125_040527.dmp)
[l2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14046612/l2_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14046614/NvRemixBridge.log)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by AN3Orik** [comment]
Sorry for late answer. 
With last build game started but with huge artifacts in menu and when open dxvk overlay, fps drops to values when i cant even move mouse.

**Comment by NV-LL** [comment]
Thank you for confirming the crash is fixed! Will you please open a new ticket for the rendering and performance issues on the game? That way we can track the issue more accurately.
