### ISSUE TITLE
[Toolkit bug]: Quadruple spawn of copies when importing one single 3D asset.

### ISSUE THREAD

**Issue by PapaSlask** [NVIDIAGameWorks/rtx-remix#327]
### Describe the bug

So after ingesting a 3D asset and importing it by mesh replacement of a selected prim (instance) in 3D space, I get 4 copies of the same asset. One replacement mesh is loaded, and two double-instances are also loaded. 

![Quad](https://github.com/NVIDIAGameWorks/rtx-remix/assets/11363281/e10dab32-8f0e-42df-97d9-8e0d94bc2c5a)

### How do you reproduce the bug?

Export 3D asset (FBX) from Blender (as USD), Ingest, import into Toolkit by 'new reference' on selected 3D-space instance.
See how four 3D assets of your mesh gets spawned around the world.

### What is the expected behavior?

Should just spawn one item

### Version

2024.1.1

**Comment by PapaSlask** [comment]
It's just those two instances. But each instance consists of two copies of the imported mesh. I'll attach my mod.usda
[mod.usda.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/14058926/mod.usda.txt)

**Comment by nvdamien** [comment]
Do you have the capture also by any chance please?

**Comment by PapaSlask** [comment]
> Do you have the capture also by any chance please?

It's all good now sir! The problem was on my end. I had groupings and quite a mess in the stages tab. Checked the mod file and the sublayers in Composer and cleaned it up. Now importing 3D assets works a treat.
