### ISSUE TITLE
[Toolkit bug]: Camera f-stop and ISO values has no effect

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#328]
### Describe the bug

Camera f-stop and ISO values changes nothing.

### How do you reproduce the bug?

Open Toolkit, Try to change Camera f-stop and ISO values.

### What is the expected behavior?

Exposure/brightness should change

### Version

2024.1.1

**Comment by sjgillard** [comment]
I've created REMIX-2686.

**Comment by nvdamien** [comment]
Hey @PappaSlask ,

Any idea why the ticket was closed please?

**Comment by PappaSlask** [comment]
> Hey @PappaSlask ,
> 
> Any idea why the ticket was closed please?

Sorry for the huge delay, I don't actually remember why I closed it, it must've been because I noticed the issue had been fixed? I'm barely never using toolkit, and I install it only for debugging or in rare cases where I need the ingest function. But as soon as you guys roll out the next big update, I will install it again and try it out thoroughly, while also checking if a number of the bugs/features I've reported on in the past have been addressed in the current build. So please stay tuned. 

If the issue hasn't been fixed by then, I'll re-open the ticket 👍
