### ISSUE TITLE
[Toolkit bug]: Ingestor bugging out when user want to ingest multiple materials

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#329]
### Describe the bug

Ingestor bugging out when user want to ingest multiple materials in the list (only ingests 3 materials at a time, missing some textures, forcing user to click "queue" multiple times, still missing to ingest some textures after pressing queue button multiple times, requires restart to fix. Clicking Queue button too rapidly or too much crashes the app.

### How do you reproduce the bug?

As explained above

### What is the expected behavior?

Properly ingest each and all materials in the list, preferable in one single go.

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hi @PapaSlask ,

Is that only during the creation of a project?
We fixed a bug where, when we create a project, the whole app is slow.

**Comment by PapaSlask** [comment]
> Hi @PapaSlask ,
> 
> Is that only during the creation of a project? We fixed a bug where, when we create a project, the whole app is slow.

That might have been it, I remember the whole app being slow. I just tried it now and it works fine. Thanks Damien!

**Comment by nvdamien** [comment]
The fix will be in the next build!
Will close the ticket when released.

Thank you

**Comment by Cyntonian** [comment]
I am having a similar issue with the Ingestor. I will ingest one or multiple texture maps the first time, apply them somewhere in the asset replacement and then come back later to maybe add more materials or texture maps. Every now and then the Toolkit will crash right after the the second or third ingestion.
