### ISSUE TITLE
[Toolkit bug]: Camera perspective undermenu-arrow dropdown comes and goes randomly

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#330]
### Describe the bug

The Camera Perspective undermenu-arrow dropdown (dropright really) to change viewport FOV is sometimes present, sometimes not (bug shared with Composer)

### How do you reproduce the bug?

Work a while in Toolkit and problem becomes noticeable

### What is the expected behavior?

The toolkit should... Always present the dropright arrow for quick access to viewport FOV

### Version

2024.1.1

**Comment by sjgillard** [comment]
@PapaSlask , is this in reference to the Camera Properties menu?

**Comment by PapaSlask** [comment]
> @PapaSlask , is this in reference to the Camera Properties menu?

It's a quick access dropdown menu that drop out to the right when an arrow is pressed next to the perspective button. I think I found what causes it to disappear. It's when you're not perfectly in fullscreen. I made gif to show how it disappears and reappears:
[https://im7.ezgif.com/tmp/ezgif-7-742f40c033.gif](url)

**Comment by PapaSlask** [comment]
I want to add an update to this. I noticed that if you work in Kit in fullscreen and all is fine and dandy. Then you exit the app to do something else. When you re-open the app, it starts where you left it, in fullscreen, BUT this time the camera properties quick access dropdown menu has disappeared. To fix this, we must resize the window down (to become smaller and windowed) and then back up to fullscreen again to get it back! It is reproduceable for me.

**Comment by sjgillard** [comment]
Created REMIX-2727

**Comment by nvdamien** [comment]
Hey @PappaSlask ,

Any idea why the ticket was closed please?

**Comment by PappaSlask** [comment]
> Hey @PappaSlask ,
> 
> Any idea why the ticket was closed please?

Hi Damien, sorry about that. I'll refer to an answer I provided on a similar topic: https://github.com/NVIDIAGameWorks/rtx-remix/issues/328#issuecomment-2375121073

Ticket will be re-opened if issue is still present in the next toolkit update.
