### ISSUE TITLE
[Toolkit feature]: DLSS Options

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#332]
### What is the context of the feature/improvement?

Please bring DLSS into Kit, my 3070 is suffocating

### Please describe the feature/improvement?

Should be a little menu for this feature. OH and framerates, lots of framerates!

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hi,

Is that a duplication of: https://github.com/NVIDIAGameWorks/rtx-remix/issues/333 ?

DLSS is a render setting

**Comment by PappaSlask** [comment]
> Hi,
> 
> Is that a duplication of: #333 ?
> 
> DLSS is a render setting

Yeah, would be great to have an easy to access place to quickly adjust Path tracing quality as well as DLSS quality. Thank you!

**Comment by nvdamien** [comment]
I will close in flavor of: https://github.com/NVIDIAGameWorks/rtx-remix/issues/333
