### ISSUE TITLE
[Toolkit feature]: Flush/Purge Vram to allocate for new needs.

### ISSUE THREAD

**Issue by PapaSlask** [NVIDIAGameWorks/rtx-remix#335]
### What is the context of the feature/improvement?

Would love an option to Dump or Flush, or is it called Purge? Vram to allocate for new needs. When it gets filled up, Toolkit lags no matter how low you set viewport resolution.

### Please describe the feature/improvement?

If Vram could be reset, or flushed to re-allocate and re-tune for the needs of the app, would be great. For now only a hard restart works for this.

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hey @PapaSlask 


I will need more details. Do you see your vram going up during time?

**Comment by PapaSlask** [comment]
> Hey @PapaSlask
> 
> I will need more details. Do you see your vram going up during time?

I think it was just a bug when a new project was created. I tested it more extensively now and Vram does go down when I lower the viewport resolution. It seam to adjust automatically which is good. You can close this Damien!

**Comment by nvdamien** [comment]
Great! Thank you!
