### ISSUE TITLE
[Toolkit feature]: Simultaneous multiple Light setup, e.g Stage light + Autoshop

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#338]
### What is the context of the feature/improvement?

Ability to select multiple options under Light setup menu, e.g Stage light + Autoshop simultaniously. To see better darkness, without having to rely on the (not yet implemented Camera light) Especially useful when going from indoors to outdoors. Whereas indoors Stage light lets us see, while outside requires One of the Light Rigs to see.

### Please describe the feature/improvement?

Include an option to choose two or more light setups/systems. For viewing convenience.

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hi @PappaSlask ,

Would adding the camera light filter solve your problem please?

**Comment by PappaSlask** [comment]
> Hi @PappaSlask ,
> 
> Would adding the camera light filter solve your problem please?

I'd say not really. But it would make things a lot better. I already opened an issue about the missing camera light. But that won't make it easier when going from inside a house or room to the outside to view the exteriors. For exterior view Stage lights are still superior. But they won't work inside, so having both of them at the same time would help a lot. Thanks!

**Comment by nvdamien** [comment]
Hey,

Perhaps I didn't understand but I believe the initial problem is:

>  To see better darkness,

Is there a reason that the camera light will not work please? Camera light is an (infinite) light in front of the camera, which would light everything in the front.

**Comment by PappaSlask** [comment]
> Hey,
> 
> Perhaps I didn't understand but I believe the initial problem is:
> 
> > To see better darkness,
> 
> Is there a reason that the camera light will not work please? Camera light is an (infinite) light in front of the camera, which would light everything in the front.

You know what, you're absolutely right. But thinking of this in hindsight, it would still be a nice feature to have, instead of having that black void when using the camera light. At least I think we should be able to use both at the same time.

**Comment by nvdamien** [comment]
To explain how things work, if you go in this folder:
`deps\content\rtx-remix-lookdev-lighting\presets`

You will see some USD stages. Those are basic USD stages that you see in the menu, with different lighting.
If an preset is not bright enough, it means he is not well calibrated.
So the solution would not be to "combine" lightings, but to fix the initial problem: the presets are too dark (?).

Also, bonus, but I believe that if you add any USD stage (with lights) in this folder, it will be picked up automatically. From here, you will have your custom lighting. Feel free to create a preset (with USD Composer for example)
