### ISSUE TITLE
[Toolkit feature]: Pause Toolkit rendering and halt its resources needs

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#341]
### What is the context of the feature/improvement?

Would love a button to pause Toolkit rendering and halt its resources needs, for allocating hardware resources to the game instead, or for Ingesting, or for AI PBR and Upscale missions. It's also references by another user over here, but as a bug: 
https://github.com/NVIDIAGameWorks/rtx-remix/issues/314#issue-2094849079

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by nxkb** [comment]
Filed as internal ticket REMIX-2688
