### ISSUE TITLE
[Toolkit feature]: "bring mesh to me!" (When importing 3d Assets and they get spawned far away).

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#343]
### What is the context of the feature/improvement?

As the title says. Would love an option to teleport meshes/assets to my direct vicinity. Sometimes importing stuff gets spawned elsewhere rather than beside me. An option to bring it over would be neat! Nothing super important or anything, but a nice little quality of life improvement in some scenarios.

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by nxkb** [comment]
Hello @PapaSlask Good news on this issue... it's actually being actively worked on. You can expect the tool in an upcoming release.

Internal ticket: REMIX-2422

**Comment by nxkb** [comment]
This feature has been completed and is part of the 2024.3.0 release. Check out the notes here: https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/remix-releasenote.html#features
