### ISSUE TITLE
[Toolkit feature]: Delete project button (a checkbox for cleaning up its content)

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#345]
### What is the context of the feature/improvement?

I would love a 'Delete project button' (a checkbox for deleting content inside the project folder and the shortcut folders it created, should also be provided in my opinion.

### Please describe the feature/improvement?

Would help tremendously when discarding or starting a new project. Instead of manually have to look for, find and clean files and leftovers.

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by po-trottier** [comment]
Tracked as REMIX-2676. There is definitely some risk in offering to delete an entire folder + symlink with 1 checkbox so we'll probably also need to add a big warning

**Comment by nvdamien** [comment]
Hi,

Having this option can be very dangerous. I would prefer to have people to do that manually to be sure that they are aware about what they are doing. Having an easy option to do that can create some very bad mistakes (people that loose some assets they wanted to re-use and so on).

For now I will close. If there is more people that want this feature, we will re-open.
