### ISSUE TITLE
[Toolkit feature]: Popup windows (or checkbox) asking to delete original asset when replacement asset is imported

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#346]
### What is the context of the feature/improvement?

Would really like a Popup windows asking if we want to delete original asset when a new 3D asset is imported/replaced (convenience for asset replacements) Or a checkbox with the same option whenever a new 3D asset is imported.

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hi,

"Would really like a Popup windows asking if we want to delete original asset"

Can you explain why? Like, the reason.

There is a button to reset an asset.

**Comment by PappaSlask** [comment]
> Hi,
> 
> "Would really like a Popup windows asking if we want to delete original asset"
> 
> Can you explain why? Like, the reason.
> 
> There is a button to reset an asset.

Because it would help a lot when replacing the vanilla "parent", to automatically delete or hide it when spawning a replacement mesh. Or maybe my thought process about this is wrong?

**Comment by nvdamien** [comment]
Hi, 
To replace an asset, you don't need to "Add mew reference" + "Remove the original".

You can directly replace the path of the selected asset:

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/128181406/afe0c077-35e7-44d4-8730-da2731eb2cd1)
