### ISSUE TITLE
[Toolkit feature]: Highlighting relevant prim (the one who matters and is viewed ingame)

### ISSUE THREAD

**Issue by PapaSlask** [NVIDIAGameWorks/rtx-remix#347]
### What is the context of the feature/improvement?

Highlighting, or otherwise informing user which prim (instance or otherwise) is the actual one that makes it into the game. Can be marked both in selection list and/or in 3D space.

### Please describe the feature/improvement?

Just a little noob helper, and for the sake of ease and convenience. I dunno, I felt like I wanted this feature today when several copies of my imported 3d asset spawned.

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hi @PapaSlask  ,

Do you mean highlight replaced assets?

**Comment by PapaSlask** [comment]
> Hi @PapaSlask ,
> 
> Do you mean highlight replaced assets?

You can remove this Damien. I felt like I needed this when multiple assets spawned, but it just turned out to be an error on my behalf. Now just a single item spawns when I import a 3d asset.
