### ISSUE TITLE
[Toolkit bug]: Ctrl-clicking boxes to change values requires two attempts

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#348]
### Describe the bug

When ctrl+clicking on boxes that has a value that needs editing, I find myself having to ctrl+click twice to select all the numbers in a box for editing. Which is annoying but no biggie. Just wanted to report it anyway.

### How do you reproduce the bug?

Hold left control while clicking on a box containing a value that can be changed, and notice how it requires two attempts to successfully mark all the text in that box.

### What is the expected behavior?

The toolkit should...

### Version

2024.1.1

**Comment by sambvfx** [comment]
I'm fairly sure this is related to how we refresh the property widgets. I have a fix for this going through the review process at the moment that should address this issue.

REMIX-1693
