### ISSUE TITLE
[Toolkit bug]: Lights have very high default Intensity

### ISSUE THREAD

**Issue by BJMart** [NVIDIAGameWorks/rtx-remix#349]
### Contact Details (Optional)

bjmartiensen27@gmail.com

### Describe the bug

In the RTX Remix Toolkit when creating new lights the default intesnsity is 30,000. This value appears to have come from USD composer and is not a suitable value in RTX Remix from my Exporience 

### How do you reproduce the bug?

1.  Open a Project in the RTX Remix Toolkit
2. Add a stage light under a mesh

### What is the expected behavior?

The light should have a intensity value around 100 which is a much more suitable value for remix

### Version

2024.1.1

**Comment by sfitzpatrickchapman** [comment]
JIRA Ticket: REMIX-2722

**Comment by nvdamien** [comment]
Done. Please check the last version of the app.
