### ISSUE TITLE
[Toolkit feature]: Larger contrast between marked box and marked text

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#352]
### What is the context of the feature/improvement?

Would like bigger contrast or higher variation in color to make it more apparent when text/numbers are marked and ready for input. 
![contrast](https://github.com/NVIDIAGameWorks/rtx-remix/assets/11363281/a2855b0e-f083-448c-a310-30e2cdba7368)

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by sambvfx** [comment]
Thanks for the suggestion. Ticketed as:

REMIX-2699
