### ISSUE TITLE
[Toolkit feature]: Method to view all ignored/deleted meshes in a capture

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#353]
### What is the context of the feature/improvement?

Would love a way to bring back the meshes that was either deleted or hidden.

Also referenced here, but for textures:
https://github.com/NVIDIAGameWorks/rtx-remix/issues/321

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by nvdamien** [comment]
I will close this ticket in favor of https://github.com/NVIDIAGameWorks/rtx-remix/issues/321

That would be the same UI/process between textures and meshes.
