### ISSUE TITLE
[Toolkit bug]: Can't mark stuff that is too close to the camera

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#355]
### Describe the bug

I'm having difficulties marking objects that are too close to the camera. I recall this being a bug or limitation in Composer as well. Just wanted to point it out if it wasn't brought up here already.

### How do you reproduce the bug?

Move close to an object, try click on it.

### What is the expected behavior?

Mark stuff no matter how close or far you are from it

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hi,

Is that a duplication of: https://github.com/NVIDIAGameWorks/rtx-remix/issues/372 ?

**Comment by PappaSlask** [comment]
> Hi,
> 
> Is that a duplication of: #372 ?

No, those are separate problems AFAIK.

**Comment by nvdamien** [comment]
Do you have a video of the problem please?

To understand it.

**Comment by PappaSlask** [comment]
> Do you have a video of the problem please?
> 
> To understand it.

Hi Damien. It was an issue with the clipping range as you suggested. If I put it down to 0.1 (down from default 1.0) I can mark stuff, and use the transforms UI cross no matter what distance. But maybe you guys should consider making clipping range 0.1 or 0.5 as a default value to prevent this issue in the future?!
