### ISSUE TITLE
[Toolkit bug]: Kit produces two projetcs despite only having one in project folder

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#356]
### Contact Details (Optional)

oscar.rosendahl@live.se

### Describe the bug

I don't understand why this happened. But I just created a new project, called it train.usda. Now booting up after a restart, the app shows that I have to projects, one with the original name I created, and with with the same name but capital T. 

There's more to the story: I created, scrapped, created, scrapped a bunch of projects prior to this, one which had the name Train with capital T. Perhaps it saved some info in some cache or something? I also have a recorded capture scene called Train with capital T, but that's an .usd file, so I don't think that's why. 

Please investigate
![bugg](https://github.com/NVIDIAGameWorks/rtx-remix/assets/11363281/ac07585f-bf83-4965-aa50-ec68b996421f)

### How do you reproduce the bug?

1. Do this.2
2. Do that.1

### What is the expected behavior?

The toolkit should...

### Version

2024.1.1

**Comment by NV-DM** [comment]
Hello, thank you for filing. Please create a new project to reproduce this issue and send attach the log files generated from that run. The log files can be found by selecting the burger menu in the layout app (top left) -> Show logs

**Comment by PappaSlask** [comment]
I closed this without providing a comment, sorry about that: The mistake was on my end, I didn't have an understanding on how the dependencies folders worked.
