### ISSUE TITLE
The Lord of the Rings: War in the North Launch Freeze

### ISSUE THREAD

**Issue by gunser12** [NVIDIAGameWorks/rtx-remix#36]
**Describe the bug**
- Game not launching and the task processes in the background freeze (https://store.steampowered.com/app/32800)

-Remix 0.1.1
-RTX 2070
-Driver 531.41
-Steam Build

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11218527/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11218534/d3d9.log)
- [witn_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11218535/witn_d3d9.log)

**To Reproduce**
1. Install Remix
2. Click on exe game

![image](https://user-images.githubusercontent.com/124139373/231664979-6f214b39-f992-449d-8d62-d72a139c00f9.png)

**Comment by NV-LL** [comment]
Hello! Will you please check on the latest release and let us know if this issue persists? Thank you!

**Comment by gunser12** [comment]
> Hello! Will you please check on the latest release and let us know if this issue persists? Thank you!

Okay, I'll check it out. this account has been inactivated for almost a year, it has just been restored

**Comment by gunser12** [comment]
> Hello! Will you please check on the latest release and let us know if this issue persists? Thank you!

The game is starting now, before that there was just a hang on launching the exe file and that's it, and I'll ask the same way and it should be that the effect of dlss is not here yet, settings in the game all low
![Screenshot (5)](https://github.com/NVIDIAGameWorks/rtx-remix/assets/124139373/3e7cd936-e3b8-4915-adeb-b3b9638ed0f2)

**Comment by NV-LL** [comment]
Thank you for confirming the launch issue is resolved. Will you please open a new ticket for the DLSS issue? Thanks!
