### ISSUE TITLE
[Toolkit feature]: Option to copy/paste all Xforms/transforms

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#361]
### What is the context of the feature/improvement?

I would love a feature to copy and paste all the transforms/xforms, all at once. To quickly insert stuff at specific locations. Or if you want to scratch something and redo it with a different asset. Could be very useful!
![xforms](https://github.com/NVIDIAGameWorks/rtx-remix/assets/11363281/55cb636a-bfee-415c-863d-e5bd578711c8)

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by sambvfx** [comment]
I have a working prototype of attribute copy/paste that I just need to polish up and get released. Hopefully you wont have to wait long on this one.

REMIX-1923

**Comment by nvdamien** [comment]
Done. Please check the last released version.
