### ISSUE TITLE
[Toolkit feature]: Place Lights on cursor

### ISSUE THREAD

**Issue by BJMart** [NVIDIAGameWorks/rtx-remix#364]
### Contact Details (Optional)

bjmartiensen27@gmail.com

### What is the context of the feature/improvement?

In USD Composer we had the ability to create a light on the cursor. This made positioning lights a much easier task 

### Please describe the feature/improvement?

As Above 

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by nvdamien** [comment]
I am not sure if this is a dupe of: https://github.com/NVIDIAGameWorks/rtx-remix/issues/343
If 343 works also with light.
I will let @nxkb  answer.
