### ISSUE TITLE
[Toolkit bug]: Launch Game with Remix does not remember what was last selected

### ISSUE THREAD

**Issue by mahalis** [NVIDIAGameWorks/rtx-remix#368]
### Contact Details (Optional)

mahalis@gmail.com

### Describe the bug

When I select this button in the toolkit, it always opens in the folder containing RemixSample.exe. I would like it to open the folder containing the last executable I launched instead.

### How do you reproduce the bug?

1. Click Launch Game with Remix and select something other than RemixSample.exe
2. Exit the launched game, optionally exit and relaunch the Remix toolkit itself, and click Launch Game with Remix again

### What is the expected behavior?

The “Select a game executable” window opens showing the folder where the last-launched executable was, ideally with it selected already.

### Version

2024.1.1

**Comment by po-trottier** [comment]
That is currently on purpose, we open the file picker at the sample app location every time. 

@AlexDunn is that a behavior we want to change?

**Comment by po-trottier** [comment]
After discussing this with the team we will refactor the wizard/project setup flow so the user will have to select the game. The details aren't all solidified yet but we should be improving this flow in a future version of the app!

**Comment by mahalis** [comment]
That’s great to hear! Thanks for taking a look at this.

**Comment by po-trottier** [comment]
Will close this issue for now. Feel free to re-open once the refactored homescreen is in the toolkit if you still see issues!
