### ISSUE TITLE
[Toolkit feature]: Option to deselect ALL

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#369]
### What is the context of the feature/improvement?

Please let me press ESC to deselect anything and everything

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

...

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hey @PapaSlask  ,

Do the other DCCs (Maya, Blender, etc etc) uses ESC to deselect? I just tested in Maya, it doesn't.

I believe just clicking anywhere in the viewport (not on an object) should deselect everything.

**Comment by PappaSlask** [comment]
> Hey @PapaSlask ,
> 
> Do the other DCCs (Maya, Blender, Unreal, etc etc) uses ESC to deselect? I just tested in Maya, it doesn't.
> 
> I believe just clicking anywhere in the viewport (not on an object) should deselect everything.

Well that's not very convenient if you're inside a house and want to quickly deselect something. I don't know about those programs you mention above, but ESC works in Composer to deselect :)
