### ISSUE TITLE
[Toolkit bug]: There are two or more places to change transforms for an object, instead of one.

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#371]
### Describe the bug

I found that you can change the scale of an object in two places, one is buggier than the other. Also, object changes position when scaling it XForms, World, or the one above the object. This is confusing for a user. Transforms should be done ONLY on the object, not via items above them in the menus.

https://github.com/NVIDIAGameWorks/rtx-remix/assets/11363281/3a52a916-dd69-4d1e-b723-9c1492e811f1

### How do you reproduce the bug?

Insert object, scale with different submenuitems.

### What is the expected behavior?

The toolkit should... Make sure that there are only one place to change transforms, and the object shouldn't change position when doing it!

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hi @PapaSlask  ,

I am not sure I understand:
- what we see is the hierarchy of your asset. Your asset has multiple Xforms, so this is normal that you can set the position of your asset at different level
- you are switching between 0.002 and 0. Meaning that when you are at 0, the asset disappear. This is not a bug, this is a scale to 0.

**Comment by PappaSlask** [comment]
> Hi @PapaSlask ,
> 
> I am not sure I understand:
> 
> * what we see is the hierarchy of your asset. Your asset has multiple Xforms, so this is normal that you can set the position of your asset at different level
> * you are switching between 0.002 and 0. Meaning that when you are at 0, the asset disappear. This is not a bug, this is a scale to 0.

Don't you see the bug in the video sir? When I change the scale of the object it changes position, it does not remain in its place while it's getting resized. It does stay in one place when selecting the object to transform scale, but when you choose one of the other items above it in the hierarchy, the phenomena is apparent.

Also the X axis is different depending on if you select the object or one of the Xforms above it. When I manipulate X axis for scale on the object, it raises up towards the ceiling, when I do the same for one of the xforms it scales in another direction. Inconsistent and buggy.

**Comment by nvdamien** [comment]
> When I change the scale of the object it changes position

This is because the scale value goes to 0.
On the first second of the video, you go from 2 to 1 to 3 to 1. You replace the number 2 directly by 1.
After you switch from 0.002 to 0.00. Like, 0.002 -> 0.00 -> 0.004 -> 0.00 -> 0.005... You don't replace the 2 of 0.002 by 4, you do 0.002, backspace (so 0.00), and 4 (so 0.004).
So with a scale of 0, this is normal that the object jump/disappear on the axis you are editing.

> Also the X axis is different depending on if you select the object or one of the Xforms above it.
Did you use the original asset as a reference in term of rotation order/etc please? or did you start the modeling from scratch (in Blender or other) with different rotation order?

Thank you

**Comment by PappaSlask** [comment]
> > When I change the scale of the object it changes position
> 
> This is because the scale value goes to 0. On the first second of the video, you go from 2 to 1 to 3 to 1. You replace the number 2 directly by 1. After you switch from 0.002 to 0.00. Like, 0.002 -> 0.00 -> 0.004 -> 0.00 -> 0.005... You don't replace the 2 of 0.002 by 4, you do 0.002, backspace (so 0.00), and 4 (so 0.004). So with a scale of 0, this is normal that the object jump/disappear on the axis you are editing.
> 
> > Also the X axis is different depending on if you select the object or one of the Xforms above it.
> > Did you use the original asset as a reference in term of rotation order/etc please? or did you start the modeling from scratch (in Blender or other) with different rotation order?
> 
> Thank you

Thanks Damien. It's all sorted out now. I see what you mean and I tried it in Kit now, works as supposed. I guess I was just a little confused of which one to mark when adjusting scale, since it can be done on all the "items" in the hierarchy. I now know it should be done on Xforms. All good!
