### ISSUE TITLE
[Toolkit bug]: Going too close to an object (for inspection) introduces BLACK, obscuring our view

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#372]
### Describe the bug

BLACK happened!

![brrrr](https://github.com/NVIDIAGameWorks/rtx-remix/assets/11363281/11de9d5d-6d7c-4330-a2ae-4b4b9df6378f)

Note that this doesn't happen in the same way if extremely high viewport FOV's are used. I just realized we can use extreme FOV's to inspect models closely, but I don't like that workaround. Let us use any FOV we want, and get as close to an object as we want, without being greeted by BLACK.

### How do you reproduce the bug?

Get too close, you'll get a black eye!

### What is the expected behavior?

Allow us to go as close as we want, no matter FOV settings

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hi @PapaSlask ,

What you see is called "clipping range": https://en.wikipedia.org/wiki/Clipping_(computer_graphics)
This is normal thing from any DCCs (Maya, Blender, etc etc).

Click on the camera settings:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/128181406/c2f0d20f-ee52-4bb1-8647-f2b65d4ca641)

Lower your clipping range:

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/128181406/2ae051f9-0fdf-448d-83d6-dcfdcb831ebc)

**Comment by PappaSlask** [comment]
Oh, now I learned something new. Thanks Damien!
