### ISSUE TITLE
[Toolkit bug]: Changing (some) properties of material has no effect

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#376]
### Describe the bug

Seem as Emission, Filtering, and possible other things, has no effect on my custom 3D asset. Maybe I'm novice and miss something. Please investigate.
![Effect](https://github.com/NVIDIAGameWorks/rtx-remix/assets/11363281/9359a534-7fc3-453a-8924-e211a081d047)

### How do you reproduce the bug?

asd

### What is the expected behavior?

The toolkit should...

### Version

2024.1.1

**Comment by sfitzpatrickchapman** [comment]
Could you please describe in more detail what your custom 3D asset is? Thanks.

**Comment by sfitzpatrickchapman** [comment]
JIRA Ticket: REMIX-2721

**Comment by PappaSlask** [comment]
> Could you please describe in more detail what your custom 3D asset is? Thanks.

Hi! It's a 3d model of FBX kind, that was ingested and then imported into Kit. I can add Albedo, normal, and so. But some settings have no effect, as described already above.

**Comment by nvdamien** [comment]
@PappaSlask  Do you:
1. Ingest the fbx asset, add the asset in RTX Remix, go in USD Composer, do things and override the USD asset?
or
2. Ingest the fbx asset, go in USD Composer, do things, override the USD asset, re-ingest (only ingested asset have to be in RTX Remix. The asset should not be edited after), add the asset in RTX Remix?

**Comment by PappaSlask** [comment]
> @PappaSlask Do you:
> 
> 1. Ingest the fbx asset, add the asset in RTX Remix, go in USD Composer, do things and override the USD asset?
>    or
> 2. Ingest the fbx asset, go in USD Composer, do things, override the USD asset, re-ingest (only ingested asset have to be in RTX Remix. The asset should not be edited after), add the asset in RTX Remix?

It's a false alarm sir. I noticed the issue now, the render doesn't update when Emissive is applied, and you have to move around to have it updating. It's all good I think.
