### ISSUE TITLE
[Runtime Bug] Unreal Tournament 2004 often hangs after a little while with runtime enabled, only since last two driver updates

### ISSUE THREAD

**Issue by mahalis** [NVIDIAGameWorks/rtx-remix#380]
**Describe the bug**
- A clear and concise description of what the bug is.
- Remix version: 0.4.0
- GPU: RTX 4090 FE
- Driver version: 551.23
- Which game build: 3369 / “2005-11-23_16.22”. From an archive.org patched version [here](https://archive.org/details/unreal-tournament-2004-complete) (CD key set up via Steam)

**Attach files!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14073621/NvRemixBridge.log)
- [UT2004_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14073624/UT2004_d3d9.log)
- [rtx.conf](https://github.com/NVIDIAGameWorks/rtx-remix/files/14073617/rtx.conf.txt)
- [bridge.conf](https://github.com/NVIDIAGameWorks/rtx-remix/files/14073620/bridge.conf.txt)

**To Reproduce**
1. Add d3d8to9 next to ut2004.exe as “d3d8.dll”
2. Copy the attached [UT2004.ini](https://github.com/NVIDIAGameWorks/rtx-remix/files/14073828/UT2004.ini.txt) next to UT2004.exe (applies the same graphics-etc. settings I’m using)
3. Launch the game, verifying that the Remix banner appears
4. Wait a few minutes, optionally while in a game (via Instant Action -> Deathmatch -> select DM-Rankin -> Play)

**Expected behavior**
- The game does not hang

**Actual behavior**
- The game hangs

**Notes**
- Reproducing this is weird: sometimes it’ll happen thirty seconds in while I’m sitting at the main menu, sometimes it won’t happen until 5+ minutes in game. It seems to happen more often if I have the Remix app itself open (to a capture from the game) in the background.

**Comment by NV-DM** [comment]
Sorry for the delay. We have recently pushed a number of hang fixes in DXVK/Bridge. Could you please grab latest DXVK/Bridge from the actions tab in GitHub and give it another shot? Thank you.

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
