### ISSUE TITLE
[Runtime Bug] VTMB - 3D Skybox Transparency and Depth Issues

### ISSUE THREAD

**Issue by FreedomsFlame** [NVIDIAGameWorks/rtx-remix#381]
**Describe the bug**
When rendering 3D skyboxes they are transparent. In addition, if sections of skybox pass in front of each other (common in this game because the skybox is used to top buildings) there are issues resolving the depth and they are rendered through each other.
- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
0.4.0
- Which GPU
RTX 2080 Super
- Which GPU driver version
551.23
- Which game build (and whether it is from Steam/GOG/Other)
Vampire the Masquerade - Bloodlines, Steam, Installed Unofficial Patch 11.5

**Attach files!**
- NvRemixBridge.log
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14074323/NvRemixBridge.log)
- d3d9.log
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14074325/d3d9.log)
- The game specific log will be named gamename_d3d9.log
[Vampire_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14074326/Vampire_d3d9.log)
- Used rtx.conf
[rtx.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14074328/rtx.zip)

**To Reproduce**
Any exterior map will have building skyboxes where you can see the issue

**Expected behavior**
Skybox building toppers should not be transparent or display through each other.

**Screenshots**
![skybox_rtx](https://github.com/NVIDIAGameWorks/rtx-remix/assets/14211365/7cbfcbf1-7b47-43a5-a213-ffed757528cb)
![skybox_raster](https://github.com/NVIDIAGameWorks/rtx-remix/assets/14211365/92edfa80-d27a-42b6-bd63-8760da39baec)

**Comment by KingDavidW** [comment]
This issue also occurs in Dark Messiah. The game does not play nice with the camera shift. 

RTX:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/40400837/0cba8d41-8084-4475-afb9-856b1ece44b5)

What it's supposed to look like:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/40400837/60130025-4654-4916-a0e3-7473f58ed0fc)

Additionally I find that enhancements made for textures within the skybox just don't activate. The blue indicates that the regular DX7 fallback is being used. All this with RTX on.
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/40400837/7efff85a-36a1-4bdd-9577-b2d5ba7eacde)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/40400837/5cbad1fb-c6c7-4511-9e16-8105e36a3350)

Functionally, here is the skybox from a different level:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/40400837/b5ea15d0-b861-474b-ae62-ff3f516618bf)

And here is what it looks like if I noclip there:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/40400837/b1675271-d458-4145-85c1-02eefa6c8baf)

**Comment by KingDavidW** [comment]
I am trying to clean up my code and have a PR for this out on the weekend. This has been identified as the depth not being shared with the skybox as it should be. I have given the VTMB people an adjusted version and it has yielded great results

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!
