### ISSUE TITLE
[Toolkit feature]: Easily anchor old meshes to another original mesh to bypass culling

### ISSUE THREAD

**Issue by Kiro32** [NVIDIAGameWorks/rtx-remix#388]
### Contact Details (Optional)

Discord: automata.

### What is the context of the feature/improvement?

As it stands now, many games have issues with culling out of the box. This means when we start the runtime to get an idea of our starting point, shadows and lightsources will often disappear depending on the context, making it hard to evaluate the general state of the game with Remix

Example: The scene is in a small pit surrounded by rocks for walls. By default, the game behaves in a way where the rocks behind you will be culled and it'll affect how well you can evaluate the scene in runtime, due to the lighting constantly being affected. In some games this is incredibly difficult to prevent in-engine, and in other games it can be straight up impossible. 

### Please describe the feature/improvement?

Proposal: Once a capture is made, in the Toolkit there would be a seamless way of anchoring old meshes to a parent that is known (by the user) to not be culled. Once a game scene capture is opened, multiple meshes could be selected, then you would select one mesh as a parent/anchor. The original assets selected would be tagged to not render within the Remix mod, and exact replicas in the same size, shape, orientation (w/ the same texture) would automatically be put in their place as functional stand-ins that wouldn't share the same culling concerns.

Point of consideration: There would need to be a way to easily and quickly see the parent of an object in the editor as a reference to this previous action. There should also be an easy way to remove the group override to make each asset visible and independent again, alongside deleting the stand-in replicas.

### What would be your solution? (optional)

How this would address the earlier example: In the Remix Toolkit, (with this feature proposal) you could Ctrl + Click to select every rock asset manually, then right click a mesh to set as an anchor/parent. After saving the project and going back into the Remix runtime, culling issues with the rock assets would be essentially solved, and you could evaluate the scene/take one larger scale scene capture with ease. This also would allow the user more time to create new assets and work within the toolkit than look at each game's documentation (if it exists) to find a way to disable culling.

### Version

202x.x.x

**Comment by nvdamien** [comment]
Hi,

I'm not sure just link things could solve the issue. The culling is always done in drawcalls commands which is actually sent to GPU. Link things can't prevent the game culls drawcalls, b/c the game logic doesn't know if you link things or not, it only checks the original meshes to decide culling or not. So, base on this logic, current anti-culling system keeps drawcalls from game in the previous frames if it's outside the screen, then our Remix can render the things that originally culled by games properly.

Is that answering your problem/question please?

**Comment by Kiro32** [comment]
I've been told by a couple other Nvidia devs that this was something that does work, and that they made good use of it in portal rtx. The idea would be that the linked meshes are actually just copies of the original, so as long as the draw calls of one object are intercepted, the clones of the other objects will come with it

**Comment by xbei-nv** [comment]
OK I see, so this is for the toolkits right, with the assumption that the runtime capture has stored everything it needed (include the meshes behind the camera)?

**Comment by Kiro32** [comment]
Yes that is correct. All of the necessary information is available in the captures, but this would get around culling concerns in-game. I tried this same process manually the other day and it was extremely cumbersome, though it did seem to work as intended by shifting the culling behavior to follow that of an object I know is always rendered when needed

**Comment by nsubtil** [comment]
As nvdamien mentioned, we have built-in features in the runtime to attempt to defeat engine-side culling, which in theory would mean this problem doesn't show up. It sounds like those aren't quite working, so first step would be to try to understand why.

@Kiro32 can you post details on which game you're running into culling issues with, and repro steps for it? Can you confirm that anti-culling is enabled in the runtime?

**Comment by Kiro32** [comment]
>@Kiro32 can you post details on which game you're running into culling issues with, and repro steps for it? Can you confirm that anti-culling is enabled in the runtime?

It would appear as if something has been changed and/or fixed in the runtime since I last commented on this issue, as anticulling does seem to now work as intended. I'll likely still take a look at anchor meshes in some capacity to avoid the full performance hit from anticulling. Thanks for your time guys
