### ISSUE TITLE
[Toolkit bug]: Search button says it needs an extension to work

### ISSUE THREAD

**Issue by ryzendew** [NVIDIAGameWorks/rtx-remix#389]
### Describe the bug

go to search through textures and the search bar is greyed out saying it needs a plugin to work

### How do you reproduce the bug?

1. go to search through textures and the search bar is greyed out saying it needs a plugin to work

### What is the expected behavior?

Search by default without any plugins this isn't unity after all or godot

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/84041391/d4759ab3-5841-4b5c-a4bc-58a54f8cb0d5)

### Version

202x.x.x

**Comment by nvdamien** [comment]
Hey @RyzenDew ,

Nice find, thank you! REMIX-2723

**Comment by nvdamien** [comment]
Done
