### ISSUE TITLE
[Toolkit bug]: Second or third texture ingestion crashes the Remix toolkit

### ISSUE THREAD

**Issue by Cyntonian** [NVIDIAGameWorks/rtx-remix#393]
### Describe the bug

When ingesting textures the first ingestion works just fine, can even be multiple maps at once too. Upon the second or third ingestion the toolkit will successfully ingest the textures (as seen by them appearing in the output folder) but then freeze and crash right after.

### How do you reproduce the bug?

1. Ingest textures
2. Apply them in the asset replacement layout tab
3. Repeat step 1, or ingest missing maps for the material ingested in step 1
4. The ingestion will finish and the remix toolkit will freeze and shortly crash after

### What is the expected behavior?

No crash ;)

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hey @Cyntonian ,

We are working on having the ingestion using an external process (which will not affect the app). It should solve this problem.
The internal ticket: REMIX-2692
This is wip. So we should have this thing soon.

Thank you.

**Comment by NV-LL** [comment]
Hi @Cyntonian! This issue has been addressed in the most recent toolkit release and confirmed internally. As such, we're going to close this ticket. Please open another one if the issue persists for you.
