### ISSUE TITLE
All geometry rendered through shaders is marked as "opacity"

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#394]
**Describe the bug**
- This bug initially showed up in Barnyard, where I noticed that all geometry (characters, terrain, etc.) that was rendered with shaders is marked as "opacity". Using the Opaque debug mode shows that it's all marked this way.

- It shows up in The Simpsons: Hit and Run as well on anything handled by shaders. Basically, the one thing in common is shaders
- dxvk-remix-876eb35-419-debugoptimized
- bridge-remix-0bc8984-54-debugoptimized
- RTX 3090
- 546.33
- The Simpsons Hit and Run (Retail)
- Barnyard (Retail)

**To Reproduce**
1. Load the games
2. Get in-game using the latest shared rtx.conf files in each game's project channel
3. Turn on the debug mode to view opacity
4. Toggle "Capture Verticies from Shader"
5. Observe correlation

**Expected behavior**
- These objects being marked as opacity could be a serious blow to performance. Handling them properly would be ideal.

**Screenshots**
"Capture Verticies from Shader" On:
![Screenshot (1120)](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/96571364-4ea3-4dcc-b30d-3b02850c4670)
"Capture Verticies from Shader" Off:
![Screenshot (1121)](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/8518ef41-5ccc-46c5-9146-1cc38e46bd03)

**Comment by nsubtil** [comment]
The game is probably rendering characters with blending turned on, even though they're opaque. The runtime has to assume that the blend state is correct, since we can't detect that the meshes are actually fully opaque, so they come out on the RT side with opacity enabled. Unfortunately it's somewhat common for games to get this state wrong sometimes, since it doesn't cause visual problems.

Marking closed since we can't really do much about this. If you think that's an error feel free to comment/reopen. Thanks!

**Comment by Kim2091** [comment]
@nsubtil I understand your final decision, however I'm still curious about one thing.

I was told previously that having many objects marked as opacity could be very detrimental to performance. If this is indeed the case, is there a way to forcibly override it globally for a game? In the case of Barnyard, everything is marked as opacity and performance is quite bad, yet disabling opacity in a mod.usda file does not appear to work.

**Comment by nsubtil** [comment]
A global toggle would likely lead to incorrect rendering elsewhere (like the foliage in the background in your screenshots). It's also likely that the blend state for characters is set that way for a reason, even if it's not completely efficient: some character meshes may have translucent portions that would render incorrectly under a global toggle.

In this case, I don't expect the cost to go up by a significant amount in practice. These meshes are "opaque blended", which still uses the opaque material. Traversal still needs to return the same first hit as fully opaque, and it's up to the material shader to determine whether to continue the ray --- if the mesh is fully opaque, the shader will always stop traversal. The extra cost here compared to the non-blended path is pulling in the alpha value and an extra bit of logic to determine that it's actually fully opaque, which isn't that significant.

The guidance to keep opacity down holds in general, for a few reasons: jumping to the translucent material (as opposed to opaque + blending) increases cost much more significantly, and things like alpha-blended particles go into a separate BVH which makes traversal more expensive.

**Comment by Kim2091** [comment]
I was thinking in regards to the global toggle that it'd be easier to effectively whitelist transparent objects, rather than going through one by one to blacklist everything.

But given your explanation of performance, it seems that's not too necessary. Thank you 🙂
