### ISSUE TITLE
Star Wars: Republic Commando Mouse Input Oddity

### ISSUE THREAD

**Issue by ChimerasGavel** [NVIDIAGameWorks/rtx-remix#397]
**Describe the bug**
- Mouse input acts odd; slow, trails, resolution/overlay issue? Unusable, forces mkb input 
- 0.3.0 (presumably 0.4.0 and open beta; have not tested new runtimes)
- 2080ti
- 546.29
- Star Wars: Republic Commando, Steam

**Attach files!**
- NvRemixBridge.log
- d3d9.log
- The game specific log will be named gamename_d3d9.log
- Used rtx.conf

**To Reproduce**
1. Launch game with RTX Remix installed

**Expected behavior**
- Mouse input to work properly

[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14133289/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14133302/d3d9.log)
[SWRepublicCommando_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14133304/SWRepublicCommando_d3d9.log)
[rtx.json](https://github.com/NVIDIAGameWorks/rtx-remix/files/14133314/rtx.json)

**Comment by Kiro32** [comment]
Hi, I'm the one working on Republic Commando the most at the moment. What you're describing is likely the default behavior in the vanilla game, where mice with high polling rates aren't handled correctly.

The solution to this is Star Wars Republic Commando Fix. A community mod that fixes mouse input, adds an FOV slider, fixes bump mapping (you still need this off for remix!), among other things. 

However I'd strongly encourage that you update to the latest runtime and get the rtx.conf file for Republic Commando from moddb's Remix compatibility list. I was able to get the game in the best state that I've seen from Remix so far, so give it a shot alongside the SWRC Fix mod.

**Comment by ChimerasGavel** [comment]
Hey, Kiro32, thanks for the reply.

I've actually had the SWRC fix mod installed (it's a staple, right?), so I'm not sure why the issue would occur.

I'll try the beta/updated runtime when I can to see if the issue persists.

**Comment by nv-ajaus** [comment]
@ChimerasGavel Did this end up being an issue with the base game itself?

**Comment by ChimerasGavel** [comment]
Hey @nv-ajaus,

The issue seems to be resolved as of runtime 0.4.1

**Comment by nv-ajaus** [comment]
Thanks for the follow up! Please let us known if this issue comes up again, I'll close this for now.
