### ISSUE TITLE
Tribes Ascend, a UI bug

### ISSUE THREAD

**Issue by CryptoMares** [NVIDIAGameWorks/rtx-remix#398]
Can't see anything because the UI is bugged, Alt+X menu not working.
![TribesAscend_TNCBFubGle](https://github.com/NVIDIAGameWorks/rtx-remix/assets/91812580/d2085612-6d4f-4cd1-b493-e6a5fce9901d)
![TribesAscend_ZsS6t13XsO](https://github.com/NVIDIAGameWorks/rtx-remix/assets/91812580/0a8b1efa-7f80-4063-8c3c-478f1b542ebf)

**Comment by traggey** [comment]
Tribes ascend is an unreal engine 3 game, Unreal Engine 3 is currently completely incompatible with remix

**Comment by NV-DM** [comment]
As @traggey mentioned, this is very unlikely to be compatible with Remix.

**Comment by CryptoMares** [comment]
> As @traggey mentioned, this is very unlikely to be compatible with Remix.

That sucks, but oh well
