### ISSUE TITLE
[Toolkit feature]: Ability to see size of area/cylinder lights

### ISSUE THREAD

**Issue by macxwdc** [NVIDIAGameWorks/rtx-remix#401]
### What is the context of the feature/improvement?

It gets a bit difficult to see the size of lights.

### Please describe the feature/improvement?

Positioning and rotating lights can get frustrating when you don't even know what direction it's facing.

### What would be your solution? (optional)

A little wireframe of the shape of the light (like in blender) would be really helpful.

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hey @macxwdc ,

We have an internal ticket ( REMIX-2670 ) to create better light manipulators (with interactive features).
This should implement your feature.

Thank you

**Comment by nxkb** [comment]
Hi @macxwdc ,
We now have manipulators for the 5 main light types and they should all be in the 2024.4.1 version of the toolkit [full changelog](https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/remix-full-changelog.html)
