### ISSUE TITLE
Company of Heroes - No Main Menu Buttons

### ISSUE THREAD

**Issue by doopt5** [NVIDIAGameWorks/rtx-remix#404]
**Describe the bug**
- Main menu is not showing up after multiple restarts. Works without the use of RTX remix. Unable to get into game to capture since no menu.
- Beta 2024.1.1
- RTX 3070
- Studio 551.23
- Steam - Company Of Heroes Relaunch

**Attach files!**
- NvRemixBridge.log
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14168600/d3d9.log)
- [RelicCOH_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14168579/RelicCOH_d3d9.log)
- No rtx.conf used
- Does not crash

**To Reproduce**
1. Start game through exe
2. Get through loading screen
3. Wait for intro to finish
4. No main menu present

**Expected behavior**
- Main menu to come up.

**Comment by nv-ajaus** [comment]
Hi doopt5, I strongly suspect that the game is not raytracing, which might signify incompatibility with the RTX Remix runtime. For game bringup, I would recommend going to the community owned/ran discord server https://discord.gg/rtxremix . Someone in the community may be able to help you configure this game to work or something may have already gotten it working.

**Comment by NV-DM** [comment]
Closed as not planned. Please re-open if needed.
