### ISSUE TITLE
Barnyard fails to launch on a fresh Windows install

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#406]
**Describe the bug**
~~Barnyard runs, but no window appears for it.~~ 
Barnyard runs, and eventually after about 7 minutes a window appears, but is non-functional. The game and NVRemixBridge.exe are running in the background. NVRemixBridge.exe has to be closed first to end the main game exe. None of the logs contain useful information or errors. NvRemixBridge.exe pins a single CPU thread at 100% while this is going on.

I had this issue on a previous Windows install, reinstalling Windows was the only way to fix it. Barnyard is the only game I've tested with this issue

- dxvk-remix-d8a3c8a-425-debugoptimized
- bridge-remix-0bc8984-54-debugoptimized
- RTX 3090
- 551.23
- Barnyard (Retail)

**Attach files!**
[Barnyard_No_Sun_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14173635/Barnyard_No_Sun_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14173639/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14173641/NvRemixBridge.log)

**To Reproduce**
1. Run Barnyard
2. Observe it being stuck in the background

**Expected behavior**
- The game runs

**Comment by Kim2091** [comment]
When I had server.useVanillaDxvk set to True, I was able to get this dump file upon ending the game's exe in Task Manager: 
[NvRemixBridge.exe_20240205_204451.dmp](https://github.com/NVIDIAGameWorks/rtx-remix/files/14173667/NvRemixBridge.exe_20240205_204451.dmp)

**Comment by NV-DM** [comment]
Crash dump generated by Procdump located here: https://cloud.kim2091.art/index.php/s/wLX8cA7LFNN4GF7

**Comment by nv-ajaus** [comment]
I took a quick look at this, unfortunately I can only see the host application + the bridge client from a dump of the host application. It looks like client is waiting for a response from CreateDevice(). Can you please send me a procdump of NvRemixBridge.exe from the same scenario? This might give us some insight into what's going on in the bridge server and dxvk-remix.

**Comment by Kim2091** [comment]
@nv-ajaus Here's the new dump file: https://cloud.kim2091.art/index.php/s/Gxim2Ne5yDMt65Y

**Comment by nv-ajaus** [comment]
@Kim2091 Are you still using bridge-remix-0bc8984-54-debugoptimized? My debugger doesn't seem to want to load symbols from that version.

**Comment by Kim2091** [comment]
@nv-ajaus I am, yes. These dumps were actually generated through Task Manager, as dumping with Procdump was only generating files about 3 MB large. I'll try one more time with Procdump

**Comment by Kim2091** [comment]
[NvRemixBridge.exe_240207_223531.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14203940/NvRemixBridge.exe_240207_223531.zip)

**Comment by NV-DM** [comment]
REMIX-2797 for tracking.

**Comment by nv-ajaus** [comment]
Hi @Kim2091 , I just made a change to fix a deadlock that can occur in the bridge. Can you please retest this issue with the latest build of the bridge (https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/7935582965) ? Thank you

**Comment by Kim2091** [comment]
@nv-ajaus Sadly this did not seem to fix the issue. Here's another bridge dump just in case it'd help, taken on that build:
[Barnyard_No_Sun.exe_240216_182044.dmp.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14316792/Barnyard_No_Sun.exe_240216_182044.dmp.zip)

**Comment by nv-ajaus** [comment]
@Kim2091 Thank you for trying that test and for generating a dump file for the bridge client. I recently added support for API Call logging and Server Command logging to the bridge in debug-optimized builds. Using the latest [debugoptimized build](https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/7935582965/artifacts/1252278934) can you please make sure the following settings are set and send me the generated log files again?

`server.useVanillaDxvk = False`
`logApiCalls = True`
`logServerCommands = True`

**Comment by Kim2091** [comment]
I apologize, I just realized I sent the dump file for the game itself, not the bridge. I just did a GPU swap, but the issue persists. I'm now using an RTX 4090 rather than a 3090.

Here's the correct dump file, redone on the 4090. I want to clarify that I initially used the `-h` flag in procdump as suggested by Dmitriy, but it never produced a dump file. I ended up using the default mode, which dumps it in its current state.

I've also included the requested log files in this zip file with the changes made to bridge.conf

[Barnyard Troubleshooting.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14317957/Barnyard.Troubleshooting.zip)

**Comment by nv-ajaus** [comment]
I had a question come up while looking at the logs, what exactly is Barnyard_No_Sun.exe vs. the standard Barnyard.exe?

**Comment by nv-ajaus** [comment]
@Kim2091 Thank you again for continuing to work through this issue with me by collecting logs and testing. It's unclear to me how the bridge is getting into this state, so I've added some additional logging code that I believe will be helpful in figuring out what's going on. 

Can you please use the latest [debug-optimized bridge build ](https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/8026636009/artifacts/1271322044), and try reproducing this issue with `logAllCalls = True` and `logAllCommands = True` in your `bridge.conf `file, and then send me the `d3d9.log` and `NvRemixBridge.log` generated? This might be very large this time since we will be logging a ton of data about the bridge state.

**Comment by Kim2091** [comment]
@nv-ajaus Surprisingly the files are very tiny. I left it running for about 5 minutes. I enabled `logAllCalls`, `logServerCommands`, and `logApiCalls`. Here you are:

[Barnyard logs.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14392067/Barnyard.logs.zip)

**Comment by Kim2091** [comment]
Actually I realized I forgot to enable the most important one, my apologies. Here are the correct logs with `logAllCalls` and `logAllCommands` set to `True`:
[Barnyard_Logs_2.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14392599/Barnyard_Logs_2.zip)

**Comment by nv-ajaus** [comment]
@Kim2091 This is a bit of a moonshot, but can you please try renaming your `Barnyard_No_Sun.dxvk-cache` file (I just added an '_'  before it) and rerunning the game?

**Comment by Kim2091** [comment]
@nv-ajaus No such luck. I did try with a completely fresh install of the game as well and the issue persists

**Comment by nv-ajaus** [comment]
From a discussion on discord:

Issue only occurs for Barnyard
d3d8to9 instead of dxwrapper yields are immediate return of the "Failed to create the display. Please run the Barnyard setup program and reconfigure." message, instead of waiting 6 to 7 minutes.
[Barnyard_No_Sun_d3d9_logs.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14455640/Barnyard_No_Sun_d3d9_logs.zip)

**Comment by Kim2091** [comment]
This was resolved through discussion in the discord server.

See the following messages:
https://discord.com/channels/1028444667789967381/1106420949257044061/1212953285963812895
https://discord.com/channels/1028444667789967381/1106420949257044061/1212988462395949086
