### ISSUE TITLE
Versions above 0.2.0 lack dawn of war (dx9b/c) support.

### ISSUE THREAD

**Issue by CannibalToast** [NVIDIAGameWorks/rtx-remix#410]
Remix version above 0.2.0 do not hook into the game for an odd reason which i have yet to narrow down. I was instructed to make a github issue regarding this. Here are the logs that i was able to gather which have some accounts of me using .4 .3 and .2 for troubleshooting.

Currently using that steam version of dawn of war soulstorm version 1.3.

I have an RTX 3080 on driver version 551.23|

Attempted using the LAA patch (Increase game memory capacity from 2 to 4gb) But no change.

The Graphics Config executable seems to display fine regardless of version. I will do more digging in regards to this.
I have learned from testing commits from the actions page that this issue arose between versions .2 and .3

The latest available commit, build 309 presents with this exact behavior

Steps to remake this error are simply by using runtime version greater than 2.0. I will attatch a zip with logs
[2-9-2024_12_59_12_ErrorLog.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14225081/2-9-2024_12_59_12_ErrorLog.zip)

**Comment by CannibalToast** [comment]
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14225334/NvRemixBridge.log)
More logs.

**Comment by nv-ajaus** [comment]
@CannibalToast Are you saying that this [commit](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/c0b74f969c13741185d7454104871d5c06fcdc1f) to dxvk-remix that generated this [build](https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/6817855117), is where the game becomes incompatible? What exactly does "not hooking" mean in this context? Can you please provide some comparison screenshots so that we can see what is going on?

**Comment by CannibalToast** [comment]
> @CannibalToast Are you saying that this [commit](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/c0b74f969c13741185d7454104871d5c06fcdc1f) to dxvk-remix that generated this [build](https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/6817855117), is where the game becomes incompatible? What exactly does "not hooking" mean in this context? Can you please provide some comparison screenshots so that we can see what is going on?

The problem I'm currently having is that RTX remix does not connect to the game at all. Nor apply any of the path tracing and such. No developer menu on exe launch. 

RTX remix does not connect to the game if a version above .20 is used. 


The build that I mentioned is the earliest built i was able to download for testing and remix still had the issue of not connecting to the game. 

There must have been a change between .2 and .3 which caused this bug. That's my hypothesis

**Comment by nv-ajaus** [comment]
To confirm that the RTX Remix runtime is not being invoked, can you please delete `d3d9.log` and `.trex/NvRemixBridge.log`, try running the game and seeing if those files are being generated?

If they are not, can you try using `NvRemixLauncher32.exe` to launch the game instead? This tool attempts to make sure the host application/game uses RTX Remix's d3d9.dll (which is the bridge client).
```
Usage:
    NvRemixLauncher32.exe [-w work folder] [-i] <command line>

The <command line> MUST contain full path to the executable file and the command line options if any.

Options:
    -w : set working folder if different from executable path in command line.
    -i : attempt DLL injection instead of changing the search path.
    ```

**Comment by CannibalToast** [comment]
So logs do appear. I am not sure if it is correctly hooking though.  Here are the logs. 
[Soulstorm_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14227186/Soulstorm_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14227187/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14227192/NvRemixBridge.log)

**Comment by nv-ajaus** [comment]
Okay, so assuming Souldstorm_d3d9.log was deleted and also regenerated, we've shown that RTX Remix is being "hooked". Can you please provide a screenshot of before it stopped working, and after so we can get a better understanding of what might be going on?

**Comment by CannibalToast** [comment]
Currently Using a config for dawn of war dark crusade i am able to get the alt X menu to appear with a few tweaks using .2


Using .2 i am able to get the Remix UI up and select textures and do the normal workflow. 

.4 does not allow that. 
[Dawn_of_War_Dark_Crusade.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14227231/Dawn_of_War_Dark_Crusade.zip)

**Comment by nv-ajaus** [comment]
Hi @CannibalToast, it seems to me that this issue might be caused by RTX Remix not properly passing through input to the renderer. After 0.4.0, there has been a change to the bridge that was made to correct this behavior. Can you please retest this with the latest release, version [0.5.0](https://github.com/NVIDIAGameWorks/rtx-remix/releases/tag/remix-0.5.0) ?

**Comment by NV-LL** [comment]
Hello @CannibalToast! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Hi @CannibalToast - due to an extended period with no response, we're going to close this ticket. If the issue persists and you'd like to reopen it, you can and we'll be happy to keep investigating. Thank you.

**Comment by Lesha485** [comment]
Hello! I decided to try to run dawn of war soulstorm with rtx remix. The interface does not appear. Version rtx remix 2024.5.1
[d3d9.log](https://github.com/user-attachments/files/18102124/d3d9.log)
[Soulstorm_d3d9.log](https://github.com/user-attachments/files/18102133/Soulstorm_d3d9.log)
