### ISSUE TITLE
[Toolkit bug]: AI Tools do not free video memory

### ISSUE THREAD

**Issue by ArturAlekseev** [NVIDIAGameWorks/rtx-remix#411]
### Describe the bug

After texture upscale video memory goes full and does not cleared.

### How do you reproduce the bug?

Open AI Tools and process a dds texture into PNG files.

### What is the expected behavior?

Free video memory after processing texture.

### Version

2024.1.1

**Comment by po-trottier** [comment]
This is a duplicate of this issue: https://github.com/NVIDIAGameWorks/rtx-remix/issues/310 which was fixed and will be available in the next release of the app!
