### ISSUE TITLE
Vertex memory handled incorrectly causing geometry corruption

### ISSUE THREAD

**Issue by Frissj** [NVIDIAGameWorks/rtx-remix#414]
Describe the bug

Large triangles flickering around in certain scenes
Present in bridge-remix-584a896-59-release with dxvk-remix-1be52c2-409-release but not present in bridge-remix-584a896-59-release with dxvk-remix-90bb5a0-408-release

4080 mobile gpu
Driver version 551.23
Lego Batman (Epic Games, latest version)

[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14233383/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14233384/d3d9.log)
[Game_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14233386/Game_d3d9.log)
[rtx.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/14233389/rtx.txt)
You will also need to change the pcconfig file to get textures to work so implement this file instead 
[pcconfig.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/14234257/pcconfig.txt)     in the folder "C:\Users\user name\AppData\Local\Warner Bros. Interactive Entertainment\LEGO Batman"

To Reproduce
After skipable cut scene finishes, press New Game. In that rendered cut scene, issues will be very apparent after clock tower chimes. 

Expected Behaviour
Stable geometry and clear skies 

Video example

Broken
https://github.com/NVIDIAGameWorks/rtx-remix/assets/49733753/2a27cdf3-7016-4c3b-a2b4-57fdf45fa0ce

Working
https://github.com/NVIDIAGameWorks/rtx-remix/assets/49733753/3d4b8e23-1fa5-4da0-8fe7-bc6e3c60d4fd

**Comment by NV-DM** [comment]
REMIX-2795 for tracking.

**Comment by Frissj** [comment]
@nyleusmani

**Comment by AlexDunn** [comment]
Hello, we were looking into causes of geometry corruption and have submitted a fix we believe may help this issue: https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/10910405835

Please test this change and let us know if this bug is improved.

**Comment by Frissj** [comment]
Thank you you amazing people
