### ISSUE TITLE
COD Games GPU Feature Error

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#418]
**Describe the bug**
- A clear and concise description of what the bug is.
Whenever I install remix with the COD games I get a "GPU Feature error!", it pops up like 10x times and I keep clicking Ok. I do eventually get into the game and it renders and works. The discord thread for COD 2 recommends changing the resolution in the config files to 1920x1080 (or your monitor resolution) and to save and then start the game - but once I start the game and this error comes up and I click ok 10x times, the game launches but back into the 640x480 default resolution, and in game the 1920x1080 resolution is not an option when it originally once was. 

- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
Latest release of Remix 4.1, and tested on latest releases and bridges ([dxvk-remix-6061236-429-debugoptimized] [bridge-remix-584a896-59-debugoptimized via the Discord's Auto Downloader

- Which GPU
RTX 4090

- Which GPU driver version
551.52
- Which game build (and whether it is from Steam/GOG/Other)
Call of Duty 2 via Steam
**Attach files!**
- NvRemixBridge.log
- d3d9.log
- The game specific log will be named gamename_d3d9.log
- Used rtx.conf
- For crashes also attach dump files: {.dmp} for CPU side crashes and {.nv-gpudmp and shaderDebugInfo folder} for GPU side crashes. Automatic GPU dumps can be enabled by setting "dxvk.enableAftermath = True" in dxvk.conf. Zip these files before uploading them.
  Note, the dumps may contain personally identifiable information.
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14278386/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14278390/d3d9.log)
[CoD2SP_s_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14278392/CoD2SP_s_d3d9.log)

**To Reproduce**
I get this error once installing COD 2 with Remix
1. Go![Screenshot 2024-02-13 041750](https://github.com/NVIDIAGameWorks/rtx-remix/assets/148610406/97daacbb-f138-46ab-8d02-8c09e9fcafc3)

**Expected behavior**
- A clear and concise description of what you expected to happen.
The game WILL eventually launch with remix, but I have to press ok about 10ish times. Launching the game also doesn't seem  to give me the same resolution options as I once had in the vanilla game. 1920x1080 is an option for resolution when the aspect ratio is set to Auto, but once Remix is installed, 1920x1080 is no longer there.

**Screenshots**
- If applicable, add screenshots to help explain your problem.
- If it is a visual issue where the raytraced version is wrong/different in comparison to the rasterized version, attach a screenshot of the rasterized version for reference. You can view the rasterized version by disabling raytracing (available in debug and debugOptimized builds).

**Comment by skurtyyskirts** [comment]
This only appears to be happening in all of the COD games for me, Remix works fine with other games for me.

**Comment by skurtyyskirts** [comment]
The issue is resolved - I had an hdmi cord on my 4090, and an hdmi on the motherboard for dual monitors. I got displayports today and put them both on the motherboard and removed the hdmi's. Now the game launches just fine with no errors. Not sure if I should close this issue if there even is one. The only thing I'm curious is why COD specifically chose to read integrated graphics rather than the dedicated gpu.

**Comment by NV-DM** [comment]
@skurtyyskirts Glad to hear it's been resolved. No easy way to tell why it was defaulting to that GPU but closing as resolved. If this pops up again, please feel free to re-open.
