### ISSUE TITLE
[feature]: add support for non-rt accelerated GPUs 

### ISSUE THREAD

**Issue by Soleil-des-chats** [NVIDIAGameWorks/rtx-remix#419]
### What is the context of the feature/improvement?

I tried to make it work on a 1060 6gb

### Please describe the feature/improvement?

The bridge and rtx remix isn't compaptible with non rt accelerated hardware.

### What would be your solution? (optional)

Add support for non-rt accelerated GPUs like gtx 1060 6gb and other. So developers can make their games working on older hardware with raytracing

### Version

0.4.1

**Comment by anon-apple** [comment]
This is likely not going to be possible. Remix is a very demanding application and while ray tracing can be done in software on older cards such as a GTX 1080, performance would be borderline unusable without the hardware acceleration (even with hardware acceleration lower end cards like a 2060 can struggle a bit with Remix which should go to show how demanding it can be).

**Comment by NV-DM** [comment]
Closing as WNF.

**Comment by anon-apple** [comment]
Just a quick followup, while we don't intend to provide a ton of support for GPUs that aren't likely going to have good performance like that, I am still curious what exactly went wrong. I think Pascal GPUs like that should expose the required Ray Tracing extensions which should at least let Remix launch, so if you're seeing it not launch it'd be useful to attach an error log or crash dump. It may just be the GPU lacking some other feature we require, but it would be good to know this in any case.

**Comment by soup587** [comment]
+1, my gtx 1080 can handle ray traced games even if they are at a pretty low resolution

i've found portal with rtx errors on startup, any other game i manually apply remix to just silently doesn't load remix without creating any logs?

**Comment by lemonify90az-max** [comment]
> Thank you for the suggestion. Unfortunately, this is not something we will be working on in the foreseeable future. Closing.

I wanted to ask if the feature is on the horizon after 2 years.

**Comment by lemonify90az-max** [comment]
> What error do you get when you launch Portal RTX? Is it some sort of dialog box complaining about missing features or is there something in the log? (Ideally providing a log in either case is going to be the best way to see what's going on there).

Summary: `Required Vulkan extension VK_KHR_ray_query not supported`

[remix-dxvk.log](https://github.com/user-attachments/files/27640081/remix-dxvk.log)
