### ISSUE TITLE
[Toolkit bug]: Search Option Disabled

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#420]
### Describe the bug

It looks like the search option is disabled when in the file picker. Please see screenshot. 
![Screenshot 2024-02-16 205417](https://github.com/NVIDIAGameWorks/rtx-remix/assets/148610406/63d64dea-bd4d-4cfe-9339-9067ad424140)

### How do you reproduce the bug?

Go to Asset Replacements, Material Properties, and click on the folder icon next to one of the tabs. The File picker page has the search function disabled. 

### What is the expected behavior?

The toolkit should...

### Version

2024.1.1

**Comment by nvdamien** [comment]
Duplication of https://github.com/NVIDIAGameWorks/rtx-remix/issues/389
