### ISSUE TITLE
[Toolkit bug]: RTX Remix doesn't start snd closes itself

### ISSUE THREAD

**Issue by 3elze** [NVIDIAGameWorks/rtx-remix#426]
### Contact Details (Optional)

Mattiabardinu00@gmail.com || Belze#3275 on Discord

### Describe the bug

When I open RTX remix from the omniverse launcher, instead of opening, a window appears and closes after a while, like some sort of loading failed.
You know when a software is loading and if you click, the window becomes white with often a "XX is not responding" which usually goes away after the software finished loading? That happens, but I don't need to click, and it closes instead of loading

### How do you reproduce the bug?

1) I open the omniverse launcher
2) I go to library, then RTX Remix
|______2.5) I am in the RTX Remix main page (in the OV launcher)
3) I press launch
4) a window appears, loads, gets white, closes
5) I go back to 2.5)

### What is the expected behavior?

When I click launch, I should see the "Project Setup" window

https://github.com/NVIDIAGameWorks/rtx-remix/assets/158559142/68d74b40-7cf1-4876-92c2-187d0ae7e425

[kit_20240226_031330.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14398904/kit_20240226_031330.log)
![2024-02-26 01-54-04 00_00_28_28 Still001](https://github.com/NVIDIAGameWorks/rtx-remix/assets/158559142/63bfb572-4443-4089-a260-ca21187cf851)

### Version

2024.1.1

**Comment by nxkb** [comment]
Hi @3elze, can you click on the red bell icon in the upper right of the OV launcher to see if there's a helpful error message there?

And for even more detail ... Upper right again > Profile Icon > Settings > Logs Location > launcher.log file

My guess is that something happened to your install. An uninstall and re-install of RTX Remix would most likely resolve your issue.  You can do all that via the launcher app.

**Comment by 3elze** [comment]
Hello. I had to cut the video due to GH restrictions, but I did a fresh reinstall of Omniverse and Remix. The result has been the same.
I just reinstalled Remix.
the red notification was " Error occurred during installation of RTX Remix: ENOSPC: no space left on device, ..." etc
even tho I HAD enogu space. Roughly 22GB
after this new reinsallation, I got rid of this notification, but the software still have the same behavior
I attached a new log anyways, hoping for the better
[launcher.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14410385/launcher.log)
^ Launcher log
v RTX Remix log
[kit_20240226_210839.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14410393/kit_20240226_210839.log)

**Comment by sultim-t-nv** [comment]
May you provide `kit_d3d9.log`? Usually it's at

`C:\Users\<YOUR_USER_NAME>\AppData\Local\ov\pkg\rtx-remix-2024.2.1`

Sanity check: can you try launch Remix from one display, then from another?

**Comment by 3elze** [comment]
Hello. I just installed a new version and now I can proceed to the main window, but I get this screen
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/158559142/54b63d5d-65a6-4af8-b98b-2dc2c42e9302)
Changing displays didn't help, I got the same results.
I'll provide the kit and d3d9 logs here now.
---
1) D3D9
I don't have this file anywhere. Checked on the path u gave me and everywhere. nothing.

2) Kit log
[kit_20240227_221827.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14425974/kit_20240227_221827.log)

Just to make it clear, I am now on the 2024.2.1 and not on the previous one anymore

**Comment by nvdamien** [comment]
Dup of https://github.com/NVIDIAGameWorks/rtx-remix/issues/382 ?

**Comment by 3elze** [comment]
Well, now I can open it. I just get the error and I'm forced to close it, but now it changed from what it was, so not being able to even reach the project tab

**Comment by nvdamien** [comment]
Same as https://github.com/NVIDIAGameWorks/rtx-remix/issues/382#issuecomment-1965886212 ?

**Comment by 3elze** [comment]
Okay, yes. That's the same thing. I guess I can say thank you and let you manage to close the ticket? 😂
Really thanks for the support and the help💯🔥💪🏻

**Comment by nvdamien** [comment]
Closing, following on https://github.com/NVIDIAGameWorks/rtx-remix/issues/382

Thank you
