### ISSUE TITLE
Taz Wanted title screen doesn't render any assets only the ui textures.

### ISSUE THREAD

**Issue by OmenFox** [NVIDIAGameWorks/rtx-remix#429]
**Describe the bug**
- On the title screen no 3D world space assets will render just the UI but i can select them with the model selection in Remix.
- remix-0.4.1-release
- RTX 4090
- GPU driver version: 551.61
- Game version 1.0 installed off an official retail CD using Elishacloud's directx wrapper: https://github.com/elishacloud/dxwrapper

**Attach files!**
[Log and Config FIles.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14408253/Log.and.Config.FIles.zip)

**To Reproduce**
1. Open the game and skip all the intro video's and cutscenes
2. On the title screen the issue is present immediately 

**Expected behavior**
- There is a scene on the title screen (present in the rasterized screenshots i have provided) that should display in the background.

**Screenshots**
- Remixed:
![NvRemixBridge Screenshot 2024 02 26 - 16 11 55 100](https://github.com/NVIDIAGameWorks/rtx-remix/assets/144848807/1d1b6d77-5b05-4cbe-913b-08bea40645e6)
![NvRemixBridge Screenshot 2024 02 26 - 16 12 13 72](https://github.com/NVIDIAGameWorks/rtx-remix/assets/144848807/eea7b99a-718b-4772-8e06-3af6d4ff0660)
![NvRemixBridge Screenshot 2024 02 26 - 17 37 59 92](https://github.com/NVIDIAGameWorks/rtx-remix/assets/144848807/2a0cbdc5-304d-40be-9282-d9bceb9e0595)

- Rasterized:
![taz Screenshot 2024 02 26 - 16 42 42 43](https://github.com/NVIDIAGameWorks/rtx-remix/assets/144848807/d787e1a6-8284-48e0-a780-06345709ec37)
![taz Screenshot 2024 02 26 - 16 42 46 05](https://github.com/NVIDIAGameWorks/rtx-remix/assets/144848807/bf0cf827-7b06-473d-8e8f-63845705c63a)

**Comment by NV-DM** [comment]
Thanks for posting. For bring up of RTX Remix with a particular game I would recommend reaching out to the community discord server https://discord.gg/rtxremix
