### ISSUE TITLE
Battlefield 2 not launching

### ISSUE THREAD

**Issue by heakasr** [NVIDIAGameWorks/rtx-remix#43]
**Describe the bug**
- Battlefield 2 (demo) gets stuck on a black screen on launch and crashes
- Remix 0.1.1
- RTX 4090
- 531.41
- Battlefield 2 demo 1.0.2446

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11219563/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11219576/d3d9.log)
- [BF2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11219580/BF2_d3d9.log)

**To Reproduce**
1. install remix
2. bf2.exe or shortcut
3. Darkness...

**Expected behavior**
Would have thought it would on early DX9 versions, have tried disabling intro videos, running windowed mode, etc. no luck

**Comment by Kamilkampfwagen-II** [comment]
- Battlefield 2 v1.51
- Remix 0.1.1
- 531.41
- RTX 2060 Desktop

**Here is the logs:**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11231507/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11231509/d3d9.log)
[BF2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11231514/BF2_d3d9.log)

I have tried it with the latest patch and encountered the same issue.
The UI Setup mentioned in the guide [guide ](https://github.com/NVIDIAGameWorks/rtx-remix/wiki/runtime-user-guide) does not work altough menu video can be seem playing there
To bypass UI, created a dedicated server then connected it using launch parameter **+joinServer 127.0.0.1**  but the game crashes immediately after loading section where it tries to "optimize shaders" while the screen remaining pitch black.

**Comment by heakasr** [comment]
Hmm ok, will reinstall full game and 1.5 sometime soon. In the meantime `Clearing Shader Optimizations: When you change the graphical settings BF2 attempts to optimize the shaders used in the game for the best performance on your particular hardware. These optimized files are stored in your \Documents and Settings\[username]\My Documents\Battlefield 2\mods\bf2\cache\ directory. If you've changed your settings several times, I recommend you finalize your changes, close BF2, go to the above directory and delete everything under the \cache\ directory. The next time you start the game and play single or multiplayer, your shaders will be optimized again. Close BF2 one more time, defragment your hard drive, and now things should be much smoother and load much faster the next time you go to play BF2.`

This may be a way to bypass shader opti... launch game, drop settings to lowest, restart and load into a map, shut down game and relaunch with rtx remix and load into same map again... may help to do "read only" on the config file

**Comment by Kamilkampfwagen-II** [comment]
After some research I found that the latest Battlefield game GeForce 2 was capable of running was Vietnam due to not supporting pixel shaders. Remix requires the renderer to be fixed function and that probably means it is impossible to get BF2 working with Remix, for now.

**Here is the mention:**
_Supported GPU
The Nvidia Geforce 2 graphics card was the last card to be fixed function only, so if the game could run on that card, it's probably fixed function.  Note that many games supported fixed function when they released, but removed that support in later updates._
https://discord.com/channels/1028444667789967381/1096179350933618718/1096179390481711154

**Comment by heakasr** [comment]
I have considered that possibility prior to starting on BF2... hence why I started on the earliest build of the game (BF2 Demo). The minimum requirements ask for directx9a/b and shader model 2.0 capable cards such as the radeon x700 and the geforce FX 5800.

I wouldnt doubt that later patches to BF2 increased these requirements due to the introduction of Expansions such as Special Forces and the other two...

I feel that there is still a chance in making progress here but it definitely may be an easier time switching over to BF 'Nam... BF1942 is already proven with the Portal version.

Anyhow I will attempt BF2 retail release with the Dedicated Server workaround you discovered.

**Comment by Kamilkampfwagen-II** [comment]
**Here is the dedicated server:**
https://www.moddb.com/downloads/battlefield-2-v15-windows-server-unranked
**or**
https://www.bf2hub.com/home/serversetup.php

Don't forget to set the server ip to the 127.0.0.1 -or your local ip-
**Here is the parameters to skip the intro and directly join the server:**
+restart +joinServer 127.0.0.1

**Comment by Kamilkampfwagen-II** [comment]
I tried you solution as well but still no chance :/
However you might get lucky as your hardware and software configurations are different.

**Comment by heakasr** [comment]
I cant get autologin to work on the shortcut via +playerName defaultPlayer... so I get stuck on log in screen, which is still preventing my from successfully hooking nvremix... +joinServer gets interrupted in my case

Here is the demo version in case anyone else wants to try. (Demo installer comes with Dedicated server tools as well, so link below is redundant but may be useful just in case)
https://www.gamefront.com/files/battlefield-2-demo-client-files/download
https://www.gamefront.com/files/battlefield-2-demo-windows-server-files/download

**Comment by Kamilkampfwagen-II** [comment]
If you create an "Singleplayer" account the +joinServer parameter should automatically skip login menu. I had only one account so you might have to delete others as well

**Comment by heakasr** [comment]
only have the defaultPlayer offline account, it just wont skip the menu... Could be some of these commands did not exist until later patches but thats just a wild guess...

have tried various different combos of shortcut commands from joining server to creating an offline ai bot match but the roadblock is still auto logging into offline account...

regardless my bf2_d3d9.log is giving me D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_MULTISAMPLEANTIALIAS

which im sure is just being caused by the main menu

**Comment by Kamilkampfwagen-II** [comment]
Here is the list of available launch parameters (I think for v1.51)
https://forums.bf2s.com/viewtopic.php?id=25085
I only tried **+restart +joinServer 127.0.0.1** and it straight up redirected to loading menu (can be verified by the sound and cursor icon) then crashed.

**Comment by heakasr** [comment]
Can you share your bf2_d3d9.log, d3d9.log and NvRemixBridge.log please?

**Comment by Kamilkampfwagen-II** [comment]
[BF2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11233064/BF2_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11233066/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11233067/d3d9.log)

Can you try creating a new singleplayer account by:
1. Disable remix
2. Log in and enter the menu
3. Log out from the bottom left button
4. Accept terms
5. Select Singleplayer tab
6. Enter some name
7. Create Account
8. Configure settings (I tried with everything set to off-low and max render distance)

That is what I did in first installation

**Comment by heakasr** [comment]
Just tried it again, even manually deleted default profiles... no combination of commands (with +playerName and without, with create local server, joining dedicated server)... These commands just wont work for demo version BF2 I guess... 

You definitely had it successfully hooked though! I feel like a modder from BF:PR or something can probably get around the loading menu and make it bypass some functions to skip your current roadblock though...

On a side note have you started to mess with BF:'Nam?

**Comment by Kamilkampfwagen-II** [comment]
Sorry for replying late; I have tried Battlefield Vietnam as well and it hooks, the main menu works as expected but I was not able to enter a level. If I set texture quality above **medium** the game crashes at  ~50% else it will be stuck at 50% forever. I didn't experiment much, will investigate when I have time. If it refuses to load I will open a dedicated issue.

**Comment by Kamilkampfwagen-II** [comment]
> Just tried it again, even manually deleted default profiles... no combination of commands (with +playerName and without, with create local server, joining dedicated server)... These commands just wont work for demo version BF2 I guess... so Im hard locked unless theres a way to trick into hooking after the Menu
I just installed the demo client & server and I can confirm launch parameters are not working in this build.
Since Battlefield 2 is an abandonware and DRM free as for patch 1.51, you can acquire it from web archive

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!
