### ISSUE TITLE
Duplicate Model Ghosting

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#431]
**Describe the bug**
- A clear and concise description of what the bug is.
It looks like when 2 similar models are spawned in gmod, there's some ghosting happening between the models.

- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
DXVK_Remix: remix-main+58bf1a36

- Which GPU
4090

- Which GPU driver version
Game Ready Driver - 551.61
- Which game build (and whether it is from Steam/GOG/Other)
Steam
**Attach files!**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14419330/NvRemixBridge.log)
emixBridge.log
- d3d9.log
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14419344/d3d9.log)

- The game specific log will be named gamename_d3d9.log
- Used 
[hl2_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14419349/hl2_d3d9.log)

- For crashes also attach dump files: {.dmp} for CPU side crashes and {.nv-gpudmp and shaderDebugInfo folder} for GPU side crashes. Automatic GPU dumps can be enabled by setting "dxvk.enableAftermath = True" in dxvk.conf. Zip these files before uploading them.
  Note, the dumps may contain personally identifiable information.

**To Reproduce**
Spawn one instance of a model, and spawn a second instance - perhaps the same model, but with different clothing. 
**Expected behavior**
Flickering of the same assets spazzing around the models will start to appear. Once one or the other model is removed, the ghosting stops.
![Screenshot 2024-02-27 062603](https://github.com/NVIDIAGameWorks/rtx-remix/assets/148610406/cdc77574-9d5f-4a6f-927a-fc074ea63fa0)

I posted a video to discord further showing the flickering/ghosting

**Comment by NV-DM** [comment]
Hello. Thank you for posting. Could we please get a link to the video? Thanks!

**Comment by skurtyyskirts** [comment]
Yes https://discord.com/channels/1028444667789967381/1028444668918235197/1212000626318385243 But it looks like this issue is well known via NV_Mark on discord - he says it's in relation to drawcalls and provided a fix for the mean-time. Closing ticket, thank you!
