### ISSUE TITLE
[Toolkit feature]: Allow scanning files in subdirectories for ingestion

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#436]
### What is the context of the feature/improvement?

The main reason for this is that users may pre-process textures in an external tool (such as chaiNNer) and save them in dedicated directories for each texture (improves organization).

The recent "PBRify" AI model set I made recently has an issue with this. It's an alternative to your guys' AI tools. I set it up to save in dedicated folders for each texture, exactly how the official AI tools do. It's a great method to organize them.

### Please describe the feature/improvement?

For users to ingest textures, all of the textures need to be saved in a single directory. This leads to it being very messy in general usage.

### What would be your solution? (optional)

Allow the toolkit to scan subdirectories when ingesting textures

### Version

2024.1.1

**Comment by nvdamien** [comment]
Hi @Kim2091 , 

We are working on some features that would let people integrate third party app with RTX Remix...
Also, we are adding some features in the ingestion to keep the folder structure from the input.

From your ticket, the only feature we didn't added is something that would scan a whole directory.

REMIX-2874 was created.

**Comment by NV-LL** [comment]
Hi @Kim2091! This feature should be available in the latest toolkit release build (2024.5.1). Will you please check it out and confirm that it works as intended per this request? Thanks!

**Comment by Kim2091** [comment]
@NV-LL Works perfectly, PBRify has been updated to work with it!

Thank you
