### ISSUE TITLE
[Toolkit bug]: remix::dxvk_CreateD3D9' has failed. Error code 1

### ISSUE THREAD

**Issue by SuperGameBug** [NVIDIAGameWorks/rtx-remix#437]
### Contact Details (Optional)

sumit.sdas@outlook.com

### Describe the bug

RTX Remix would not start and give the following error.
RT Remix Renderer failed to Initialize
![kit_A6oQVeLnY7](https://github.com/NVIDIAGameWorks/rtx-remix/assets/48118135/31334198-f3c8-4545-826a-b31b8c667e38)

### How do you reproduce the bug?

This Error occurs if there a pre-installed OpenCL, OpenGL or Vulkan wrapper.

### What is the expected behavior?

The Toolkit should atleast start and shouldn't just exit after that error prompt. I've realised changing some parameters in the "_lightspeed.app.trex.app.settings.toml_" I was able to at least start the Toolkit. In the viewport I was able to use Pixar's renderer and Remix renderer didn't work, obviously.

For a lot people it wasn't clear what could be the root cause and I've seen for some it was multi GPU for me it was the uninstalling the OCL, OGL and Vulkan Compatibility Pack from Microsoft and then I was able to use RTX Remix normally

### Version

2024.2.1

**Comment by nvdamien** [comment]
Hi @SuperGameBug ,

Thanks for your report. It looks like this is dup of https://github.com/NVIDIAGameWorks/rtx-remix/issues/382

Thank you

**Comment by SuperGameBug** [comment]
Hey @nvdamien ,
It is a possible fix to the issue. I wasn't sure there was already an issue raised.
Thanks :)

**Comment by nvdamien** [comment]
Hi,

Someone in our team is working on it.
