### ISSUE TITLE
Feature: Multi-GPU support (SLI / NVLink)

### ISSUE THREAD

**Issue by neuhaus** [NVIDIAGameWorks/rtx-remix#44]
I haven't seen SLI on the roadmap, is it doable as part of this project?

**Comment by nelak2** [comment]
Not to speak for anyone at Nvidia or this project's contributors but SLI is deprecated functionality at this point.

So even if it's technically possible to support a deprecated technology on the only two RTX cards capable of it (3090 and 2080); only the 3090 SLI/Nvlink might be able to handle path tracing and even then its probably not competitive with a single 4090. I wonder how many dozens of people are out there that could afford a 3090 SLI setup and haven't already upgraded to the 4090.

**Comment by NV-LL** [comment]
Thank you for reaching out. We don't currently plan to implement SLI support with Remix. If you have other questions or suggestions, please open another ticket and we'll be happy to take a look.
