### ISSUE TITLE
[Toolkit feature]: Runtime Rolling Capture Feature

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#442]
### What is the context of the feature/improvement?

A rolling capture option that will continuously search for/capture chunks of a level that render in and out of a level.

### Please describe the feature/improvement?

In the Remix Runtime, there would be an option that would allow end users to capture a scene as the level loads in and they move about. Rather than only capturing what is present at the given time of the capture, remix will take another capture and piece together the level as rendered to make a complete map of the level.

### What would be your solution? (optional)

Perhaps this feature could be limited to only a certain map or level and not the entirety of a game. Maybe this feature doesn't even need to make a "complete map" and rebuild the level as is, it just captures multiple captures in 1 capture. 

### Version

2024.2.1

**Comment by NV-DM** [comment]
Thank you for posting. This is already being considered, however, it is a very difficult problem. We're already tracking it under REMIX-2358 so we're going to close this one for now.
