### ISSUE TITLE
[Toolkit feature]: "Lights Off" Feature

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#443]
### What is the context of the feature/improvement?

In the toolkit, could there be a feature that turns off all of the existing stage lights present in a capture to off? That would set the exposure/intensity to 0 for all lights present. 

### Please describe the feature/improvement?

This feature would get rid of all the existing light that's present in a scene, rather than going to each stage light one by one disabling and turning off the intensity/exposure. That way end users can go in and redesign the lighting in a scene.

### What would be your solution? (optional)

Even better yet, a way to delete all lights would be nice too. But, a full "lights off" feature would be nice ideal as a quality of life update.

### Version

2024.2.1

**Comment by nvdamien** [comment]
Hi,

We have a feature planned where we would be able to manage multiple objects at the same time (with filters and so on. So you would have a "light manager").

From here, for example, you would be able to, for example, select all the light, put them into a layer and set all the intensity values to 0 (so you can do a quick on/off).

Internal ticket: REMIX-2735

**Comment by skurtyyskirts** [comment]
That's perfect, that's exactly what I was looking for - thank you!
