### ISSUE TITLE
RTX Remix d3d9.dll crashes DXWrapper Game after 3 seconds (ddraw.dll to dx9)

### ISSUE THREAD

**Issue by rbarisic-lme** [NVIDIAGameWorks/rtx-remix#447]
**Describe the bug**
- A clear and concise description of what the bug is.
- Which Remix version: 0.4.1
- Which GPU: RTX 3060 Ti 
- Which GPU driver version: NVIDIA Graphics Driver 551.76 
- Which game: Cold Zero: No Mercy
- Which game build: GOG - 1.02 UK
- DXWrapper.ini: [dxwrapper.ini.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/14725707/dxwrapper.ini.txt)

**Attach files!**
- NvRemixBridge.log: [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14725696/NvRemixBridge.log)

- d3d9.log: [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14725680/d3d9.log)
- The game specific log: [ColdZero_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14725685/ColdZero_d3d9.log)
- Used rtx.conf: default / [rtx.conf.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/14725686/rtx.conf.txt)
- dxwrapper log: [dxwrapper-coldzero.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14725778/dxwrapper-coldzero.log)

- For crashes also attach dump files: {.dmp} for CPU side crashes and {.nv-gpudmp and shaderDebugInfo folder} for GPU side crashes. Automatic GPU dumps can be enabled by setting "dxvk.enableAftermath = True" in dxvk.conf. Zip these files before uploading them.
  Note, the dumps may contain personally identifiable information.
[NvRemixBridge.exe_20240322_173039.dmp](https://github.com/NVIDIAGameWorks/rtx-remix/files/14725702/NvRemixBridge.exe_20240322_173039.dmp)

**To Reproduce**
1. Enable ddraw.dll from DXWrapper stubs
2. Enable attached Config
3. Game runs for 3 Seconds, alt+x is accessable and RTX is ON
4. In Fullscreen, the game blanks (black screen) for half a second, then freezes, music keeps playing but game does not respond anymore. (Interface is missing)
5. Without rtx-remix / d3d9.dll, game is playable and User Interface is available
6. The crash happens exactly at the point where Nvidia Experience game capture message is displayed (press ctrl+z to open in game overlay), I've deinstalled Nvidia Experience and some windows services, but to no avail.

I'm aware that this is a ddraw / dx7 game made compatible with d3d9, but it works for a whole 3 seconds until the lady in the office chair turns her head around. The main error message I see is:

`warn:  Data Queue override condition triggered`

**Expected behavior**
- A clear and concise description of what you expected to happen.

**Screenshots**
- If applicable, add screenshots to help explain your problem.
- If it is a visual issue where the raytraced version is wrong/different in comparison to the rasterized version, attach a screenshot of the rasterized version for reference. You can view the rasterized version by disabling raytracing (available in debug and debugOptimized builds).
- Before Crash
- ![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/54026388/d5008e98-0ebf-4759-8dd8-56da03097b28)

- Crashed State
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/54026388/122c0d06-ba3e-44a4-b241-68d453275510)

**Comment by nv-ajaus** [comment]
REMIX-2905 and REMIX-2904 for tracking.

**Comment by nv-ajaus** [comment]
@rbarisic-lme I took a look at the mini dump you provided and for some reason the host application is making an invalid call to SetTransform(). I made an update to the bridge client that checks for invalid values and returns the correct response to the game. You can download the updated binaries [here](https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/8397501958/artifacts/1351674904).

It's not guaranteed to make your game work, but it should alleviate the crash in RTX Remix that you found. Please give it a another shot with the updated binaries when you can.

**Comment by rbarisic-lme** [comment]
@nv-ajaus wow, thanks for taking your time to look into this issue.

Sadly, the crash persists even with the updated binaries.

[ColdZero_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14731205/ColdZero_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14731206/d3d9.log)
[dxwrapper-coldzero.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14731207/dxwrapper-coldzero.log)

[NvRemixBridge.exe_20240323_113351.dmp](https://github.com/NVIDIAGameWorks/rtx-remix/files/14731209/NvRemixBridge.exe_20240323_113351.dmp)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14731210/NvRemixBridge.log)

Is there anything I could try to help? I could try different settings for DXWrapper, another alternative to DXWrapper or look into debugging the error in bridge

[dxwrapper.ini](https://github.com/NVIDIAGameWorks/rtx-remix/files/14731220/dxwrapper.ini.txt)

**Comment by nv-ajaus** [comment]
@rbarisic-lme I took a look at your new logs and crash dump and they seem to indicate that the bridge client (the d3d9.dll next to your game executable) is not actually receiving a call to SetTransform() with the D3DTRANSFORMSTATETYPE argument set to 0, but that the bridge server (NvRemixBridge.exe) is incorrectly seeing that argument set to 0.

Can you please use the latest [debug-optimized bridge build ](https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/8397501958/artifacts/1351674903), and try reproducing this issue with `logAllCommands = True` set in your `bridge.conf` file, and then send me the d3d9.log and NvRemixBridge.log generated? This might be very large and very slow since we will be logging a ton of data about the bridge state. The motivation is to see if we can get some info on what's going on with the command stream.

If a `bridge.conf` file doesn't exist next to your installed `NvRemixBridge.exe` in the `.trex` folder, you can use [this default one](https://github.com/NVIDIAGameWorks/bridge-remix/blob/main/bridge.conf). Please  make sure the line does not have a leading `#` as this marks the setting as a comment instead, and then it will be ignored.

**Comment by rbarisic-lme** [comment]
@nv-ajaus I think we might have a heisenbug situation, as the game runs normally as long as I have set `logAllCommands = True`, I'll tinker around and see If I can still make it crash.

What's interesting, I managed to dump the game in the 3 seconds I had that lead to the freeze and the usd scene is working almost fine in rtx remix

For consistency, here are the logs (that didn't crash):
[ColdZero_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14748941/ColdZero_d3d9.log)
[d3d9.log.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14748945/d3d9.zip)
[NvRemixBridge.log.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14748950/NvRemixBridge.zip)

**Comment by rbarisic-lme** [comment]
Good news!

Setting `useSharedHeap = True` made the game run, although player models were missing. But, additionally setting `sharedHeapPolicy = Textures, StaticBuffers` makes the game run and player models shown. Only thing missing now is the UI

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/54026388/fd09041c-0643-4b09-a609-118cb96b1bb9)

**Comment by nv-ajaus** [comment]
REMIX-2908 for tracking

**Comment by nv-ajaus** [comment]
@rbarisic-lme Could you please try enabling `sendAllServerResponses = True` in bridge.conf instead of `useSharedHeap = True` ?

**Comment by rbarisic-lme** [comment]
@nv-ajaus this also works, no freeze. Still no UI though (I can load another scene / my savegame with F9), so no movement possible, only rotation and zoom via mouse

**Comment by rbarisic-lme** [comment]
Another issue I encounter is that when loading the dumped scenes in the remix editor after adding assets, the RTX Remix Editor consistently crashes after closing and re-opening the project. However, I suppose that's an entirely separate problem. While I can load the game with the mod, editing is not possible a second time.

**Comment by nv-ajaus** [comment]
For the issue with the RTX Remix Toolkit, please file a separate github issue. That helps us a bunch with respect to tracking and assigning issues to the right engineer.

**Comment by nv-ajaus** [comment]
Hi @rbarisic-lme , thank you again for filing this issue. With the info you provided, I believe I was able to find the bug that was causing the crash and pushed an update to the bridge repository today to resolve it.

https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/8574006517

With this build (or more recent), you shouldn't need to set `sendAllServerResponses` or `useSharedHeap` to True.
