### ISSUE TITLE
 Fast & Furious Showdown open but not enable to capture.

### ISSUE THREAD

**Issue by PoonRX952** [NVIDIAGameWorks/rtx-remix#448]
**Describe the bug**
The game open and have some change but not enable to capture.
RTX Remix 0.4.1
RTX 3050
551.86
(Steam) Game engine : Octane
How do you reproduce the bug?
Open the game
dxvk.conf
# d3d11.disableMsaa = True
# d3d9.shaderModel = 0
# d3d9.disableA8RT = True
# d3d9.supportX4R4G4B4 = False
What is the expected behavior?
Can captures.
![rtxImageDxvkView_262124-22260](https://github.com/NVIDIAGameWorks/rtx-remix/assets/164624200/a6da2de5-e202-407a-944c-5cd8a772c360)

**Comment by traggey** [comment]
This game is from 2013, and runs DX9.0c, it's heavily shader reliant and the likelyhood of the engine actually being compatible at all is extremely low.

For remix you're generally looking at games between 2000-2005, 2013 is much too new.

**Comment by NV-DM** [comment]
Thank you for posting. Just for clarification, the button in your screenshot is to capture screenshots. To do a USD capture, please select the Enhancements tab as outlined in the Documentation [here](https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/howto/tutorial-remixtool.html#:~:text=From%20the%20%E2%80%9CDeveloper%20Settings%20Menu%E2%80%9D%20click%20on%20the%20%E2%80%9CEnhancements%20Tab%E2%80%9D%3A)
