### ISSUE TITLE
Distant Lights Not Transforming with Parent Mesh

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [NVIDIAGameWorks/rtx-remix#449]
**Describe the bug**
- Distant lights do not transform with their parent mesh.
- Game agnostic, observed in multiple games consistently: Call of Duty 2, Unreal Tournament

**To Reproduce**
1. Attach a distant light as the child of a moving-rotating mesh.
2. Observe that the distant light still has the same transformation despite its parent moving - rotating.

**Expected behavior**
- Distant lights should be transformed as their parent do.

I am not sure if this is the exact same issue, but a similar behaviour can be observed when distant light parameters are set externally in memory. While fallback sphere light can be moved just fine this way.

**To Reproduce**
1. Set distant fallback light direction in memory using a debugger, cheat engine etc.
2. Observe that the fallback distant light is still pointing at the same direction unless the parameters are flushed in imgui.
3. Switch to sphere fallback light, observe it move as you change its position in memory.

**Comment by anon-apple** [comment]
The fallback light should not be used as an actual light in your project. It is meant to be used as a debugging tool. Not sure what you really mean by this issue, you cannot attach the fallback light to meshes, so is this an issue with the fallback light you're seeing or one with replaced distant lights?

**Comment by Kamilkampfwagen-II** [comment]
> The fallback light should not be used as an actual light in your project. It is meant to be used as a debugging tool. Not sure what you really mean by this issue, you cannot attach the fallback light to meshes, so is this an issue with the fallback light you're seeing or one with replaced distant lights? I assume you're saying the fallback light has the same issue or something, but I am also not sure what you mean by "parameters flushed in ImGui".

The main issue is with replaced distant lights, they don't follow the transformation of their parent mesh.
I think the first occurance was with the dynamic sky for CoD 2 by tadpole3159 where he had to use a sphere light to the rotating skybox, because a distant light wouldn't rotate this way.

The latter is that I had a case where I can set sphere fallback light parameters in cheat engine and observe the changes in real time, while not with the distant light variant. I thought this could be related so I also included it as a side note.
"parameters flushed in ImGui" really just means "set in the ui", it works as intended when done through the ui, so I assume doing that does more than just setting the respective variables.

**Comment by anon-apple** [comment]
Ah yes, obviously changing things with cheat engine is not going to work. When the light parameters change for the fallback light the light list needs to be refreshed and that is only done when a change is detected through the UI.

Anyways the other issue does sound like a problem as the USD transform should be part of how the light's direction is derived for replaced lights at least.

**Comment by mmdanggg2** [comment]
Here's a short clip of the issue. The distance light doesn't get rotated along with the cube.
https://github.com/NVIDIAGameWorks/rtx-remix/assets/3161587/0c67dbbf-d9aa-434d-8f0c-c628113671a1

**Comment by anon-apple** [comment]
Ah yes that missing updated orientation makes sense. Good catch.
