### ISSUE TITLE
RTX Remix working but rtx.conf not generated and runtime settings not saved

### ISSUE THREAD

**Issue by nomad5oul** [NVIDIAGameWorks/rtx-remix#451]
**Describe the bug**
- RTX remix is hooking with the game and everything seems normal but there is no rtx.conf file being created and if I try to save my runtime settings nothing happens. There is no rtx.conf file and nothing is being saved.
- RTX Remix version 0.4.1
- GPU is Nvidia RTX 3050
- GPU driver version is 537.58
- Game is built from FPS Creator. A DX9 game engine from early 2000's

**Attach files!**
- NvRemixBridge.log
- d3d9.log
- game demo for testing

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14765817/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14765819/NvRemixBridge.log)
https://drive.google.com/file/d/1G9z8Xf4tg3Zf-hd3-x9aine_gAmSJ6jl/view?usp=sharing

**To Reproduce**
1. Unzip the folder rtx_test.zip
2. Open the folder called rtx
3. Right click on rtx.exe and select 'run as administrator'
4. Wait for game menu to load with RTX remix prompts
5. Press Alt+X to open RTX remix menu
6. Select to save settings on any part of the RTX remix menu
7. Return to rtx folder and there is no rtx.conf file in the root directory
8. No settings have been saved

**Expected behavior**
- I am expecting when the game is run with RTX remix that a rtx.conf file should be generated and I should be able to save my runtime menu settings as per the runtime menu options.

**Screenshots**
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/37256116/47636888-c22c-4dce-b664-793bea8b03b3)

**Comment by NV-DM** [comment]
Thank you for posting. Could you please make sure that the directory you have this is is not marked as Read-Only. This can be accessed by right clicking on the directory and selecting Properties.

**Comment by nomad5oul** [comment]
@NV-DM I have checked the game folder is not set to read-only but the rtx.conf file is still not being created and the runtime settings are not being saved. 

I am able to save the level when the game is running and the save files are created in the directory so there doesn't appear to be a problem with the directory settings.

I have also been able to capture the scene and save those files so this issue appears to be specific to generating the rtx.conf file and saving the runtime settings. Please can you try the exe and see if you are able to save the runtime settings.

**Comment by NV-LL** [comment]
Thank you for reaching out. Unfortunately, at NVIDIA, we have security policies that prevent us from testing non-commercial/non-official content. We will be unable to service this ticket and will have to close it. We apologize if this is disappointing.
