### ISSUE TITLE
fix this bug plsss like too reinstall it 

### ISSUE THREAD

**Issue by lionv56** [NVIDIAGameWorks/rtx-remix#460]
Failed to start RTX Remix -- Error: Can't launch rtx-remix -- C:\Users\lionv\AppData\Local\ov\pkg\rtx-remix-2024.2.1\lightspeed.app.trex.bat is not found.

**Comment by nv-ajaus** [comment]
Hi @lionv56, can you please open a new issue  as a Toolkit bug report? This will give you a form to fill out with fields for information that might be necessary or helpful to the engineers tracking down this problem. Thank you!

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
