### ISSUE TITLE
Mass Effect crashes on start

### ISSUE THREAD

**Issue by mirh** [NVIDIAGameWorks/rtx-remix#468]
**Describe the bug**
- A runtime error pops up and the process quits.
- Remix 0.50
- 2080S
- 552.12
- Steam version
 
**Attach files!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15176339/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15176341/d3d9.log)
- [MassEffect0_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15176342/MassEffect0_d3d9.log)
- No rtx.conf
- [NvRemixBridge.exe_20240501_124346.dmp](https://github.com/NVIDIAGameWorks/rtx-remix/files/15176349/NvRemixBridge.exe_20240501_124346.dmp) (heap corruption?)

**To Reproduce**
Just start the game

**Expected behavior**
It should launch.

**Comment by NV-LL** [comment]
REMIX-3031 for tracking

**Comment by Kim2091** [comment]
Mass Effect 1 is an Unreal Engine 3 title. UE3 (according to a former UE developer) has no fixed function fallback and relies entirely on shaders.

**Comment by mirh** [comment]
That's true I guess, but it still shouldn't crash. 
Gamebryo fallout games are also in the same situation AFAIU, but they reportedly get in-game.

**Comment by NV-LL** [comment]
Hi @mirh - we believe an update in a recent build should address this issue. Will you please check with the latest bridge and DXVK builds and let us know if the crashes persist? Thank you!

**Comment by mirh** [comment]
https://github.com/NVIDIAGameWorks/bridge-remix/commit/aa9285e9950bf1e51b04239978288cda12acdda5 did the trick indeed. Thank you!
