### ISSUE TITLE
[Toolkit bug]: No images in interface

### ISSUE THREAD

**Issue by CasketPizza** [NVIDIAGameWorks/rtx-remix#470]
### Describe the bug

No images or icons load in the RTX Remix Toolkit. I've tried reinstalling both it and Omniverse, as well as changing directories and drives and updating gpu drivers.
Windows 10 Pro 22H2, GeForce RTX 2080 TI, AMD Ryzen 9 5950X, 64GB ram.
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/29517500/515cc9e1-5cff-4a79-b493-e9f9b636246f)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/29517500/9a809e19-9a49-44df-afaa-877af3f5cca3)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/29517500/10b130be-18ea-4b3e-9a61-d60b1ce0ab64)

### How do you reproduce the bug?

Literally just opening the program.

### What is the expected behavior?

The toolkit should be showing the images in the interface as demonstrated in online screenshots and tutorials

### Version

2024.3.0

**Comment by nvdamien** [comment]
Hey @CasketPizza ,

Do you have the icons with USD Composer?

**Comment by CasketPizza** [comment]
hi @nvdamien,
yes it happens there also
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/29517500/1084da1b-3124-4d93-806d-58e5d43bcd50)

**Comment by nvdamien** [comment]
Can you try this please:
- go in "settings" in the launcher

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/128181406/0ebcec99-26dd-496a-ac28-bb873371571f)

- check where in your "data path" path:

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/128181406/f58cb46c-ecd5-4f7f-a33c-346090fb2d64)

- go in this path with the Windows file explorer

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/128181406/e7fd909f-7ccf-4009-856e-926004e03617)

- remove the "RTX Remix" folder

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/128181406/182bcff7-04b8-4a83-87dd-aa67d9447e3d)

This will remove your user setting for the app.
Please run the app and tell us if it works.

**Comment by nvdamien** [comment]
Any update please?

**Comment by CasketPizza** [comment]
Well it looks like the issue comes down to my windows username contains the character "æ" and  that breaks the toolkits functionality

**Comment by nvdamien** [comment]
I see, thanks for the update. I would not be surprised if because of that, it would give more problem elsewhere (that we can't control). Best thing to do here would be to rename the windows username.

Should I close this ticket please?

**Comment by CasketPizza** [comment]
I tried renaming but i feel I'll have to make a new user completely and cant be bothered to go through the whole process. Yow can close the ticket, thanks for your help anyway.
