### ISSUE TITLE
[Toolkit feature]: Size representation for lights

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#473]
### What is the context of the feature/improvement?

I would like to see a feature from Composer added to Toolkit. A visual representation of the physical size/radius for lights, in the form of archs that loop around the light, and increases/decreases in size depending on the value being set. 

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

...

### Version

2024.3.0

**Comment by nxkb** [comment]
Hi @PappaSlask We have an internal ticket ( REMIX-2670 ) to create better light manipulators (with interactive features).

The plan is to show intensity, radius, height, width etc. and allow users to drag the manipulator to change their values. 

(Tagging as similar to #401)

**Comment by PappaSlask** [comment]
> Hi @PappaSlask We have an internal ticket ( REMIX-2670 ) to create better light manipulators (with interactive features).
> 
> The plan is to show intensity, radius, height, width etc. and allow users to drag the manipulator to change their values.
> 
> (Tagging as similar to #401)

That sounds awesome, but I still think you should add lines wrapping around the light to give us a quick visual representation of the radius and shape of the light source, like this: 
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/11363281/73f75f15-576b-4b2c-9965-e3f97c2df5d0)

Thank you!

**Comment by nxkb** [comment]
Hi @PappaSlask, yep that is the idea and you should be able to try these out now! 

We did manipulators for the 5 main light types and they should all be in 2024.4.1 [full changelog](https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/remix-full-changelog.html)
