### ISSUE TITLE
[Toolkit feature]: Basic mesh shapes

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#474]
### What is the context of the feature/improvement?

I was gonna add in a moon to my scene, but couldn't find a way to create a basic sphere mesh. So I had to open Composer and do it from there, then export the mesh to my toolkit project folder. Please add this feature from Composer into Toolkit, to allow us to make basic shapes for various things. For example adding a moon, or adding a thin rectangle to use as an emissive texture in our scene. I'm sure this feature could be used for many creative ideas.

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

...

### Version

2024.3.0

**Comment by PappaSlask** [comment]
@nvdamien Update on this sir?

**Comment by PappaSlask** [comment]
@sfitzpatrickchapman Hi Scott, any update on this sir?

**Comment by sfitzpatrickchapman** [comment]
Hi @PappaSlask . Which specific features from USD Composer would you like to have in Remix? (screenshots appreciated)

I encourage you and other interested modders to react to this issue with the "thumbs up" emoji on your initial comment above as a form of upvoting. Thanks.

**Comment by NV-LL** [comment]
Hi @PappaSlask - checking in to see if you can provide the info requested above. Thank you!
