### ISSUE TITLE
[Toolkit feature]: A comprehensive selector

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#477]
### Contact Details (Optional)

oscar.rosendahl@live.se

### What is the context of the feature/improvement?

I would love to have a more competent selector tool in Toolkit, akin to that of Blender. Keeping the current drag-resize rectangle but also adding a lasso to select multiple items in one go. We should also be able to filter the selector to only select specific classes of items, such as lights, custom meshes or original meshes only! That way, we could quickly select a couple of specific assets that were already placed by us in the scene, without the risk of selection something we didn't intend to select. 

As of right now, whenever we select something with the rectangle, everything within the rectangle gets selected, which is counter-productive if we, for example, only wanted to select a couple of lights but not the mesh(es) behind those lights. Having a filter-by-type for the selector tool, as well as a lasso, would solve that problem and help us speed up work.

Thanks in advance!

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

...

### Version

2024.3.0

**Comment by sjgillard** [comment]
Jira created: REMIX-3130

**Comment by nxkb** [comment]
Hi @PappaSlask , Thanks again for filing this issue and your feedback. After some investigation we're going to close this issue in order to focus on other areas in the app. However, I do think this user story will be helped by some of the work we've got queued up. The problem of selecting objects and filtering them is one we are looking at.
