### ISSUE TITLE
[Toolkit feature]: Save and automatically set viewport resolution

### ISSUE THREAD

**Issue by xoxor4d** [NVIDIAGameWorks/rtx-remix#485]
### What is the context of the feature/improvement?

Settings -> Viewport -> Render Resolution

### Please describe the feature/improvement?

Toolkit should save and automatically set the last selected resolution instead of defaulting to 1920x1080 on each start.
I'm a fan of using the `viewport` setting that automatically adjusts the resolution to the overall application width and height.

### Version

2024.3.0

**Comment by nvdamien** [comment]
Hi @xoxor4d ,

Thanks for you ticket.
It looks like this is a dup of https://github.com/NVIDIAGameWorks/rtx-remix/issues/326
