### ISSUE TITLE
[Bug + Feature Req.] Worldspace UI Background offset does not offset the texture along its surface normal

### ISSUE THREAD

**Issue by xoxor4d** [NVIDIAGameWorks/rtx-remix#488]
**Describe the bug**
Assigning the worldspace ui category to a texture does not offset the texture along its surface normal. Instead, it offsets it along the Z axis, so shifts it upwards and downwards.

The game: Call of Duty titles - Z axis up and Y forward
I was trying to fix some decals with Z fighting issues by using the worldspace ui offset when I noticed this:

https://github.com/NVIDIAGameWorks/rtx-remix/assets/45299104/918972e4-494b-446e-a328-03b7efb0db08

**To Reproduce**
1. Install cod4 remix compatibility mod: https://github.com/xoxor4d/iw3xo-dev
2. Load any map
3. Assign any texture as worldspace ui
4. Adjust worldspace ui background offset

**Expected behavior**
- It should offset the surface along its surface normal to stop z fighting

### Feature Request:
A slider in the toolkit to adjust the offset off the material would be really helpful when trying to fix z fighting decals or to manually set the decal order.

https://github.com/NVIDIAGameWorks/rtx-remix/assets/45299104/5f13f8c2-07d6-4a79-89c0-b8598790dd87

**Comment by MarkEHenderson** [comment]
I believe the decal sort order problems are fixed (or at least changed) by a change I just made.  Please test using the build from https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/9521650210 and close the ticket if it is fixed.

Note that this is only going to do anything for decals.  No changes were made to world space UI.  If that's still something you still need fixed, please file a new ticket for that issue.

**Comment by MarkEHenderson** [comment]
@xoxor4d mind updating or closing this issue?

**Comment by xoxor4d** [comment]
Sorry completely forgot about this one. Your changes no longer require hacky work arounds on my side. Thanks again!
