### ISSUE TITLE
Mirrors Edge Not starting

### ISSUE THREAD

**Issue by SlincHD** [NVIDIAGameWorks/rtx-remix#49]
**Describe the bug**
just the standart opening and than nothing happends

[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11222762/NvRemixBridge.log)

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11222752/d3d9.log)

[MirrorsEdge_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11222758/MirrorsEdge_d3d9.log)

**To Reproduce**
Start the game

![image](https://user-images.githubusercontent.com/85231739/231779066-31359864-36c6-4f83-bc49-f3d1fac7e757.png)

**Comment by NV-DM** [comment]
Shader model 3.0 is not supported by Remix.

**Comment by DarkElementPL** [comment]
Are there any plans to add support for it in the future?

**Comment by jhaapasa** [comment]
Although we're very interested in exploring this area of compatibility, at this time we have no concrete plans to support games which are exclusively shader model 3.

**Comment by MWaerzner** [comment]
Very unfortunate. I suspect F.E.A.R does not work for the same reason. Hopefully support will be added in the future cause I feel some of the most remix worthy games could be affected. Is there a reliable way to check which shader model a game is using / if it is exclusively using shader model 3.0?

**Comment by jhaapasa** [comment]
Here's some more context on potential shader support: https://github.com/NVIDIAGameWorks/rtx-remix/wiki/Compatibility#why-are-shaders-hard-to-path-trace

**Comment by plhappylemonpl** [comment]
Do you know if they will add support for Shader Model 3.0? Because that's what Mirror's Edge needs to look insanely good with RTX.

**Comment by NV-LL** [comment]
> Although we're very interested in exploring this area of compatibility, at this time we have no concrete plans to support games which are exclusively shader model 3.

As mentioned above, we currently have no concrete plans for this. As such, we will be closing this ticket.
