### ISSUE TITLE
[Toolkit bug]: Kit crashes when attempting to deleting light

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#490]
### Describe the bug

I'm crashing when I attempt deleting a sphere light that I placed ~~while another sublayer was activated (NoFog5)~~

It's reproduceable

This is how the Selection menu looks like once I've marked the light I intend to delete, it has no prim?
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/11363281/caf690f2-e48a-49d9-a12b-832e057977a4)

UPDATE: Pressing the "Restore original asset" button deletes the light and all seem fine.

If needed, I'll send my level files to you via DM nvdamien

### How do you reproduce the bug?

1. Use my files, load Intro project
2. Apply any layer
3. Move camera far back until you see the sphere light above the level
4. Mark it and attempt deleting it via the rubbish-bin button
5. Crash

### What is the expected behavior?

The toolkit should...

### Version

2024.3.0

**Comment by PappaSlask** [comment]
UPDATE: The light attempted for deletion was placed using Composer, from a project migrated to Toolkit.

**Comment by nvdamien** [comment]
Hi @PappaSlask  ,

Does that mean we can close the ticket please?

We don't do support for anything created outside of the RXT Remix app.

**Comment by sjgillard** [comment]
@PappaSlask , is this happening for lights created within the toolkit, or only with lights created in another program?

**Comment by PappaSlask** [comment]
> @PappaSlask , is this happening for lights created within the toolkit, or only with lights created in another program?

Sorry for late reply. I'm not sure, I stopped using Remix/Kit some time ago, it's just too limited for now.

Furthermore, I understand the issue. Stuff made in Composer isn't compatible with Remix app, or it is to some extent but it's not supported and falls under a "do it at your own risk" category. For a software such as Remix, to have been built on the foundation of USD Composer for such a long time, to not be compatible with the new Remix app, is unfortunate.
