### ISSUE TITLE
[Runtime bug] Enable Volumetric Lighting option doesn't stick/always resets

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#493]
Enable Volumetric Lighting option doesn't stick/always resets

- Remix-0.5.0, Bridge Version: remix-main+e0dbe92d, DXVK Version: remix-main+d61d1ac2
- RTX 3070
- GPU Driver: 31.0.15.5123
- Max Payne Retail CD version, patch [1.05]

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15210654/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15210658/NvRemixBridge.log)
[MaxPayne_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15210668/MaxPayne_d3d9.log)
[rtx - Copy.conf.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15210672/rtx.-.Copy.conf.log)

**To Reproduce**
1. Load game
2. Turn off Volumetric Lighting under Froxel Radiance Cache/Volumetrics settings under the Rendering tab
3. Save config
4. Restart game
5. Volumetric Lighting is turned on by itself.

**Expected behavior**
- Does not change on its own

**Comment by NV-LL** [comment]
REMIX-3123 for tracking

**Comment by PappaSlask** [comment]
@NV-LL Hi Lindsay, just a headsup. This issue should be merged with **REMIX-3340**: https://github.com/NVIDIAGameWorks/rtx-remix/issues/539 

Feel free to close this as soon as they've been merged. Thank you!

**Comment by NV-LL** [comment]
Perfect, thank you so much for calling that out @PappaSlask! We've updated everything accordingly. :D
