### ISSUE TITLE
[Runtime bug]  FEAR2 Crash / Game crashes after launch.

### ISSUE THREAD

**Issue by Igrom4ik** [NVIDIAGameWorks/rtx-remix#495]
**Error Description**.
- Game crashes a few seconds after startup.
- Remix 2024.3.0 is installed from Omniverse.
- RTX 3090Ti
- Studio 552.22.
- FEAR 2: Project Origin (Steam version)

**For Replay**.
1. Add Remix files to the game directory.
2. Start the game.

**Expected Behavior**
- Expected the game to launch without problems (usually happens without the d3d9.dll file).

[crash_report.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/15211572/crash_report.zip)

**Comment by NV-LL** [comment]
REMIX-3107

**Comment by nv-ajaus** [comment]
Hello @Igrom4ik, I made a change to fix an issue where a crash in dxvk-remix can crash again during DLSS deconstruction, which masks the original issue, leaving a NvRemixBridge crash dump file (.dmp) that we can't use to track down the original crash. I noticed that the dump file provided with this GitHub ticket seems to show a symptom of this. If and when you can, please reproduce the crash you previously reported using the latest dxvk-remix release build here (https://github.com/NVIDIAGameWorks/dxvk-remix/actions) or the build for the specific commit I made https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/10118513607/artifacts/1745781365 , and upload a newly generated .dmp file.

Thank you!

**Comment by NV-LL** [comment]
Hi @Igrom4ik - checking in to see if you've been able to re-test per the comment above and provide us a new .DMP file. We also want to inform you of our stale ticket policy, namely that we will close this ticket as 'went-stale' if it doesn't receive a response in the next two weeks. Thanks!

**Comment by NV-LL** [comment]
Hey, @mirh, thanks for confirming! Glad to hear the bridge crash is resolved for you. Since the .dll crash doesn't appear related to Remix, we're going to close this ticket as fixed, but please do reach out again if you have any other issues.
