### ISSUE TITLE
Remix Runtime Regression - Barnyard visual corruption

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#496]
**Describe the bug**
- Visual corruption has returned in Barnyard. This is geometry corrupting and covering the entire screen. It was resolved in this issue previously: https://github.com/NVIDIAGameWorks/rtx-remix/issues/258
- Builds:
  - dxvk-remix-a911c31-540-debugoptimized
  - bridge-remix-c062326-70-debugoptimized
- RTX 4090
- 551.86
- Barnyard Retail copy

**Attach files!**
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15227790/d3d9.log)
- [Barnyard_1080_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15227791/Barnyard_1080_d3d9.log)
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15227792/NvRemixBridge.log)
- [rtx.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/15227794/rtx.zip)

**To Reproduce**
1. Load Barnyard
2. Load into the Barnyard area
3. Observe visual corruption

**Expected behavior**
- A stable image

**Video demonstration**
- https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/43d94918-0058-4de5-9f88-526e9fada31c

**ADDITIONAL ISSUE**
- There's an additional new issue that has never appeared before. The sun and moon are shaking violently. I have absolutely no idea what's causing this:
- https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/7fda7160-14f2-4a8a-98a9-2f91b26e16c2

**Comment by NV-LL** [comment]
REMIX-3122 for tracking

**Comment by Kim2091** [comment]
Barnyard now crashes with the latest Github Actions builds as soon as the main menu is reached. Rolling back to dxvk-remix build 408 fixes the issue and the visual corruption

**Comment by Kim2091** [comment]
Thankfully with the latest build to fix geometry corruption, Barnyard's stability + visual issues have been fixed. Thank you!

https://github.com/NVIDIAGameWorks/rtx-remix/issues/181 remains open however, as sadly this build did not fix the replacements failing to work.
