### ISSUE TITLE
Windows Defender detects nvremixlauncher as trojan

### ISSUE THREAD

**Issue by svelle** [NVIDIAGameWorks/rtx-remix#5]
Seems like WD is detecting the launcher as a false positive right now.

![image](https://user-images.githubusercontent.com/7526550/231500584-1f0da26c-1a1c-4b35-92fd-f5ba8b3489ed.png)

**Comment by Dumpgrah** [comment]
same here , Windows 11 is treating it like a Trojan.

**Comment by Fabi** [comment]
Can't confirm with latest definitions

**Comment by Aokromes** [comment]
no problem here.

**Comment by kotn3l** [comment]
Same here, W11 Pro

**Comment by Aokromes** [comment]
i tested on both windows 10 and 11 canary insider with latest definitions and no problem
