### ISSUE TITLE
Wrong location of bridge.conf

### ISSUE THREAD

**Issue by Kam1k4dze** [NVIDIAGameWorks/rtx-remix#50]
d3rd9.log says:
[19:21:35.239] info:  Trying to open config file: GameLocation\\.trex\bridge.conf

But in the 0.1.1 release, the "bridge.conf" file is located in the main folder. Like so:
remix-0.1.1
|--- d3d9.dll 
|---bridge.conf
|--- .trex/

**Comment by jhaapasa** [comment]
Thanks for the report. This is a good point. Our current intent was for the bridge.conf to be more of a sample, but it's location in the root of the package is indeed a bit unintuitive. We are considering moving it into the .trex directory in the future. If you do want to set any options, you can move this file into .trex.

Are you still able to run normally, or is this log message accompanied with a crash?

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!
