### ISSUE TITLE
Might & Magic IX (#134 continuation)

### ISSUE THREAD

**Issue by an00biz** [NVIDIAGameWorks/rtx-remix#504]
### Describe the bug

The game runs now, but:

1. You have to change the native resolution (800x600) to 1920x1080 manually in autoexec.cfg, otherwise the game runs in a cropped window:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/44441226/0dcb6277-7099-4f5b-bb02-9921d581b105)
2. The game doesn't seem to change in terms of graphics, though the Alt + X menu works:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/44441226/c7eac6fa-b81b-4317-ad2d-20b775b9c598)

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15283390/d3d9.log)
[lithtech_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15283391/lithtech_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15283392/NvRemixBridge.log)

### How do you reproduce the bug?

Just run the game.

### What is the expected behavior?

At least some graphical changes. The game looks absolutely the same now (except for the cropped window).

### Version

0.5.0

**Comment by NV-LL** [comment]
REMIX-3087 to track the resolution issue. Issue #2 may be a problem with setup; if you haven't already, we suggest checking with the [Discord community](https://discord.com/channels/1028444667789967381/1095455547748257862) to see if anyone there can help.

**Comment by nv-ajaus** [comment]
@an00biz , was the resolution issue resolved?
