### ISSUE TITLE
[Runtime Bug]: A "floating" cursor in the RTX Remix menu

### ISSUE THREAD

**Issue by llMADNESSll** [NVIDIAGameWorks/rtx-remix#506]
### Describe the bug

I tried to install RTX Remix on Dishonored, but for some reason the mouse just "floats" on the screen, preventing it from being properly fixed on the screen and finally pressing the button I need. What files do I need to find and send to get help, and where do I find them?

### How do you reproduce the bug?

I'm not sure that everyone will have this error, but I did this: I put ReShade on the game (I haven't even set it up yet), put HD textures, and then RTX Remix.

### What is the expected behavior?

After what I described above, the cursor began to float.

### Version

0.5.0

**Comment by NV-LL** [comment]
Thank you for reaching out. Could you attach a video of what you're seeing? That will help us investigate the issue. Please note that we can't guarantee that the game will be compatible with Remix, even if we're able to resolve the problem you're reporting.

**Comment by NV-LL** [comment]
REMIX-3106 for tracking

**Comment by nv-nfreybler** [comment]
Hello @llMADNESSll, I see online that Dishonored makes use of Windows DirectInput. If you can confirm this in `d3d9.log` (found in the remix install path, then search for "DirectInput"), I would recommend playing around with our DirectInput setting toggles, and see whether it makes a difference. Some games used DirectInput to handle mouse and keyboard events, and this does not play nicely with how we capture those events in our GUI.

Shortcut:
Download the conf file below and place it in your Remix install path's `/.trex/` directory. You will need to rename it from `bridge.txt` to `bridge.conf` as GitHub does not support the `.conf` extension.
[bridge.txt](https://github.com/user-attachments/files/15542014/bridge.txt)
It overrides both values from their usual default values, so play around with toggling them a bit. The `d3d9.log` should indicate that it reads this file if you've installed it successfully.

**Comment by PappaSlask** [comment]
> ### Describe the bug
> I tried to install RTX Remix on Dishonored, but for some reason the mouse just "floats" on the screen, preventing it from being properly fixed on the screen and finally pressing the button I need. What files do I need to find and send to get help, and where do I find them?
> 
> ### How do you reproduce the bug?
> I'm not sure that everyone will have this error, but I did this: I put ReShade on the game (I haven't even set it up yet), put HD textures, and then RTX Remix.
> 
> ### What is the expected behavior?
> After what I described above, the cursor began to float.
> 
> ### Version
> 0.5.0

Same thing happens in Max Payne 1. Temporary solution is to close the Remix UI and click somewhere on the screen and then opening the Remix UI again.

Very annoying and I'd love to see this fixed as well 🙏

**Comment by AndreasKarg** [comment]
Hi @NV-LL, I am not the OP, but had the same issue. Your bridge.conf resolved the floating cursor problem for me in Discord, thanks! 👍

**Comment by azaxim** [comment]
Привет! Получилось ли у тебя внести хоть какие - то изменения без вылета? Ремикс не то что сцену не захватывает, он просто вылетает при взаимодействии с параметрами
