### ISSUE TITLE
[Toolkit Feature]: Async Executor as Default Ingestion Executor 

### ISSUE THREAD

**Issue by Arrokoth7323** [NVIDIAGameWorks/rtx-remix#509]
### What is the context of the feature/improvement?

Batch ingestion of textures can take quite a while. Please consider setting Async Executor as the default instead of Process. Due to the likelihood of batch uploads when dealing with PBR textures, it would make sense to use the fastest solution by default.

Apologies as I do not know the technical reasons/limitations as to why it is not default.

### Please describe the feature/improvement?

Async Executor as the default executor for the Ingestion tab.

### What would be your solution? (optional)

Async Executor as the default executor for the Ingestion tab OR a way to save last selected executor.

### Version

0.5.0

**Comment by NV-LL** [comment]
Thank you for reaching out. Using Async Executor is less performant overall, which is why we introduced Process Executor. At this time we plan to leave Process Executor as the default option.

**Comment by NV-LL** [comment]
Thank you for reaching out. Using Async Executor is less performant overall, which is why we introduced Process Executor. At this time we plan to leave Process Executor as the default option.
