### ISSUE TITLE
[Runtime Bug]: AIM Racing Bridge Crash

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#516]
### Describe the bug

The RTX Remix bridge crashes in the main menu while pressing "Continue". It only happens sometimes. It also consistently happens when performing a capture

Logs:
[AIMRace_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15437342/AIMRace_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15437343/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15437345/NvRemixBridge.log)

Bridge dump file:
[NvRemixBridge.exe_20240524_121001.dmp](https://github.com/NVIDIAGameWorks/rtx-remix/files/15437346/NvRemixBridge.exe_20240524_121001.dmp)

### How do you reproduce the bug?

1. Load the game
2. Press Continue

OR

1. Load the game
2. Perform a capture

Use this rtx.conf file: [AIM-Racing-rtx-conf.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/15437174/AIM-Racing-rtx-conf.zip)

### What is the expected behavior?

The game should continue running

### Version

0.5.1 debugoptimized

**Comment by NV-LL** [comment]
REMIX-3115 for tracking

**Comment by nv-ajaus** [comment]
Hi @Kim2091, I made a change to fix an issue where a crash in dxvk-remix can crash again during DLSS deconstruction, which masks the original issue, leaving a NvRemixBridge crash dump file (.dmp) that we can't use to track down the original crash. I noticed that the dump file provided with this GitHub ticket seems to show a symptom of this. If and when you can, please reproduce the crash you previously reported using the latest dxvk-remix release build here (https://github.com/NVIDIAGameWorks/dxvk-remix/actions) or the build for the specific commit I made https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/10118513607/artifacts/1745781365 , and upload a newly generated .dmp file.

Thank you!

**Comment by Kim2091** [comment]
Will do when I have time! Thanks for the update
