### ISSUE TITLE
Driv3r (and Driver Parallel Lines) not launching

### ISSUE THREAD

**Issue by TheEngiGuy** [NVIDIAGameWorks/rtx-remix#52]
**Describe the bug**
- Game does not launch at all. No black screen either.
- Remix version 0.1.1
- RTX 2080Ti
- Driver version: 531.41
- Driv3r Patch 2

**Attach logs!**
- NvRemixBridge.log
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225591/NvRemixBridge.log)
- d3d9.log
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225593/d3d9.log)
- The game specific log will be named gamename_d3d9.log
No game-specific log present

**To Reproduce**
1. Install RTX Remix to Driv3r and Driver Parallel Lines
2. Launch them through their respective .exe files

**Expected behavior**

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by TheEngiGuy** [comment]
> Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

Hello! It does run now, but with extremely low framerates and all effects missing.

**Comment by NV-LL** [comment]
Thank you for confirming the launch issues are fixed. Will you please open new tickets for the low performance issue and the missing effects? That way we can investigate and track them separately.

**Comment by NV-LL** [comment]
Closing as original issue is fixed. Please open new tickets for emergent issues so we can investigate separately.
