### ISSUE TITLE
[Toolkit bug]: Unable to package mod (unable to find the exported mod file)

### ISSUE THREAD

**Issue by Veitaserum4** [NVIDIAGameWorks/rtx-remix#521]
### Describe the bug

When I try to package my mod, I get this error:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/63559389/9148d607-ec65-482c-90aa-1acbfa3393a4)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/63559389/4ce8d089-4499-491d-8ec7-655e62f732e4)

### How do you reproduce the bug?

1. Press the "Package" button
2. Wait for error

### What is the expected behavior?

The toolkit should package the mod and not give me that strange error

### Version

2024.3.1

**Comment by Veitaserum4** [comment]
I have removed all of the references to the deleted files, and I still get the error that they can't be found, and I have no idea what the last error means

**Comment by po-trottier** [comment]
The errors you're seeing is a side-effect of previous failures. When we package a mod, we look for the packaged mod layer in the output directory to write some metadata to it but if the packaging failed the layer won't exist. 

That means you need to fix the previous errors before continuing. Seems like all the errors you're seeing are related to missing referenced assets so you'll need to make sure all your references are valid in your mod.

**Comment by Veitaserum4** [comment]
Right, but I have deleted the references to the removed files, and I still get the error

**Comment by po-trottier** [comment]
Can you share the complete error you are now getting after fixing the references ?

**Comment by Veitaserum4** [comment]
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/63559389/d798ed0f-9369-41fe-ba14-0f92a432401a)
Heres the other half of the error, they're just files from when I was messing around with AI textures

**Comment by po-trottier** [comment]
Yeah, so as long as you have these errors packaging will fail. 

Somewhere in your mod you reference these texture files and they don't exist anymore so we can't collect them. 

You need to remove the references from your mod. If you don't fix the broken references, packaging won't succeed.

**Comment by Veitaserum4** [comment]
Well, I know 100% for a fact that I removed one of the references (under the folder spring), and that error is still there (image of spring)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/63559389/9e650ccd-0553-4373-a184-6be09b4b2635)

**Comment by po-trottier** [comment]
It's not really possible for me to know where these overrides are set but we take all the references set in the stage to package the mod, so the reference still definitely exists. 

I would recommend opening your `mod.usda` file and searching for the invalid references to see where they are set.

Removing those will fix your issue.

**Comment by po-trottier** [comment]
Using any text editors (Notepad, VS Code, etc.)

**Comment by Veitaserum4** [comment]
This worked! Thank you so much for your help!
