### ISSUE TITLE
[Toolkit feature]: Texture Manager

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#524]
### What is the context of the feature/improvement?

For the RTX-Remix toolkit, I think it'd be useful to have a section where you have a list of all of the textures that are in a capture that have been ingested, and from there you can manage the roughness/normals/mettalic etc etc right from the list, rather than needing to click the textures in the worldspace view from the toolkit. 

### Please describe the feature/improvement?

Rather than having to click on or find/see the texture you're wanting to edit in the worldview, you can find the texture from a list. This would help assist when a capture has captured a muzzle flash, or a particle texture, or fast moving texture that wasn't captured in the worldview in the toolkit that can be clicked on, but was still captured. 

This would be helpful because when I run a script to auto-replace every texture in a capture with AI-upscaled textures, I'll be able to go to the list and remove the roughness maps/normal maps that were ingested without needing to find these particle textures in the worldview. 

### What would be your solution? (optional)

![Screenshot 2024-05-30 163729](https://github.com/NVIDIAGameWorks/rtx-remix/assets/148610406/61616dfc-08b9-4f36-b0f8-559b4aaec70c)
Here's just an idea of the implementation, there'd be possibly a new tab, or perhaps a new section in the "Ingestion" tab named Ingested manager, or Overview to review textures/models you've already ingested. From here, there'd be a list with a thumbnail of the texture, you'd click it, and a menu similar to the Material Properties would appear and you can manage it's Properties there without needing to find it in the Worldview of the Toolkit. 
![Screenshot 2024-05-30 163634](https://github.com/NVIDIAGameWorks/rtx-remix/assets/148610406/2f82626a-cb36-49bb-93f3-078dc2ae10c4)

### Version

2024.3.1

**Comment by nvdamien** [comment]
Hi @skurtyyskirts ,

We have an epic where we will have a stage manager to show different things from the stage using filters (and action). This should  handle your request.
Tracking number: REMIX-2185

**Comment by skurtyyskirts** [comment]
Hi Damien,

Very exciting, glad to hear! Thank you for your time.

-skurty
