### ISSUE TITLE
GTA4 - complete edition | Shader Model 3.0 or higher required

### ISSUE THREAD

**Issue by HelIHound** [NVIDIAGameWorks/rtx-remix#53]
**Describe the bug**
- Just crash
- 0.1.1 remix version
- RTX3060ti desktop
- 531.41 | on 531.61 it shows the first frame on game launch intro (some times)
- Steam version

**To Reproduce**
1. Launch game

**logs**
[NvREmixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225589/NvREmixBridge.log) | [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225592/NvRemixBridge.log)   old | new drivers
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225600/d3d9.log) |  [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225610/d3d9.log)
[GTAIV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225611/GTAIV_d3d9.log) | [GTAIV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225614/GTAIV_d3d9.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/55206773/231855488-66ddc982-4911-4e04-9a58-f59e819d89e4.png)

**Comment by Joshhhuaaa** [comment]
GTA IV isn't going to be working anytime soon. 

Remix works mostly on a fixed function pipeline, and games after 2005-2006 mostly moved to shader-based rendering (like your Shader Model 3.0 error).

Anyways, Remix is spoofing your graphics card to not support Shader Model 3.0 even though it does, by default it is set to 1.4.
You can check out bridge.conf and see the command: 
# client.shaderVersion = 1.4
This is what causing your error.

You can remove the #, and put client.shaderVersion = 3.0 to get by that error, but the game is not going to work regardless.

**Comment by HelIHound** [comment]
> Remix works mostly on a fixed function pipeline, and games after 2005-2006 mostly moved to shader-based rendering (like your Shader Model 3.0 error).
Thanks for the advice

**Comment by DerP4si** [comment]
so games like far cry 3 or desperados 2 wont work either?
