### ISSUE TITLE
[Runtime Feature]: Adding keyboard inputs to Free-camera rotation (Pitch & Jaw)

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#534]
### What is the context of the feature/improvement?

I'd love to be able to control the pitch and jaw of the camera using keyboard buttons rather than the mouse in some scenarios. Because during in-game cut-scenes the mouse movement is disabled, and if I wanna use the free camera during this time, the mouse won't allow me to look around, only going into Remix settings for the free camera and altering the values for pitch and jaw works.

### Please describe the feature/improvement?

As described above

### What would be your solution? (optional)

Allow us to toggle between mouse or keyboard input controls for pitch and jaw, possible allow us to customize which keys are controlling the camera. Thank you in advance!

### Version

0.5.1

**Comment by NV-LL** [comment]
REMIX-3342 for tracking

**Comment by MarkEHenderson** [comment]
@PappaSlask Just merged this, it should show up on github within the next hour or so.

This includes making all of the free camera navigation keys customizable via rtx.conf:
rtx.freeCam.keyMoveForward = P

full list of keys:
```
rtx.freeCam.keyMoveFaster
rtx.freeCam.keyMoveForward
rtx.freeCam.keyMoveLeft
rtx.freeCam.keyMoveBack
rtx.freeCam.keyMoveRight
rtx.freeCam.keyMoveUp
rtx.freeCam.keyMoveDown
rtx.freeCam.keyPitchDown
rtx.freeCam.keyPitchUp
rtx.freeCam.keyYawLeft
rtx.freeCam.keyYawRight
```

**Comment by NV-LL** [comment]
Hi @PappaSlask - checking in to see if you've been able to verify the feature per the comment above. We also want to inform you of our stale ticket policy, namely that we will close this ticket as 'went-stale' if it doesn't receive a response in the next two weeks. Thank you!

**Comment by PappaSlask** [comment]
@MarkEHenderson Hi Mark, so sorry about the long delay. I've now tested your new set of camera cvars on the latest dxvk/bridge builds. Unfortunately the Pitch and Yaw commands doesn't work, at least not for Max Payne. I will try in other games tomorrow.

I've tried typing in various button commands such as Up, Down, Left, Right, VK_UP, VK_DOWN, VK_LEFT, VK_RIGHT, as well as regular keys V, B, N, and M... But no dice. Furthermore, whenever I make any changes inside Remix ui and then press the save button: The whole suit of rtx.freeCam cvars is wiped away from my rtx.conf. Please investigate. 

@NV-LL My sincere apologies for being absent and not taking responsibility of my tickets. I shall improve when it comes to this. I was notified by Kim on discord about this, so I wanna pitch in a thanks to her.

Sorry and thanks for all the work and dedication you guys continue to pour into this amazing software, and the community!

**Comment by MarkEHenderson** [comment]
@PappaSlask the default bindings for yaw / pitch can be seen here:
https://github.com/NVIDIAGameWorks/dxvk-remix/blob/fb5dcc9ca91df27407953e1dab3bb2f1ff614014/src/dxvk/rtx_render/rtx_options.h#L360
Can you confirm that the `IJKL` buttons don't do anything when free cam is enabled?

The list of key names is here - looks like you would need "UP" instead of "Up".  Not sure why regular letter keys wouldn't work.


> The whole suit of rtx.freeCam cvars is wiped away from my rtx.conf. Please investigate.
This... sounds like you may be still be using an old version of the runtime?  I'm not sure why else this would happen, unless there's some problem with saving out key bindings.  Does setting `rtx.captureHotKey` also get wiped out on conf save?  i..e `rtx.captureHotKey = CTRL, SHIFT, P`

**Comment by PappaSlask** [comment]
@MarkEHenderson Hi Mark! I've now properly updated to the latest versions of everything, and the added functionality is working good. Thanks a lot for this useful addition to Remix! 🥇 

Here's some ideas and wishes for improvements:
- Give us a way to set the speed or sensitivity of the pitch and jaw axes independently, now it simply follows the main camera speed value, which makes it too sensitive as we increase the camera speed in order to move around faster.
- Consider adding some sort of delay or, softness or laziness to the input/key, is it called inertia? I dunno, but USD Composer has that for its movement keys, its also possible to configure how much or little of this "effect" the user wants.

**Comment by NV-LL** [comment]
Hi @PappaSlask - thanks for confirming the functionality works for you! 

We've opened REMIX-3588 as a separate ticket for the requested improvements.

**Comment by MarkEHenderson** [comment]
Went ahead and did another round of improvements to the camera keyboard controls.  Should address all your comments aside from the momentum one.  Please check out Action build #657 (https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/11187016853) 

REMIX-3588 will remain open to capture the task of implementing momentum for free cam controls.

**Comment by PappaSlask** [comment]
@MarkEHenderson Thanks Mark, works nicely now, no issues on my end 💯

**Comment by NV-LL** [comment]
Hi @PappaSlask - checking in to see if all your requests have been addressed and the ticket can be closed. Please let us know if there's anything else you need regarding this feature. Thank you!
