### ISSUE TITLE
Cannot create mod

### ISSUE THREAD

**Issue by Frissj** [NVIDIAGameWorks/rtx-remix#537]
### Contact Details (Optional)

Frisser4@gmail.com

### Describe the bug

In the toolkit, I try to create a usda file. Once I press create, it goes back to the toolkit without an error. The current path is what the path would be if the mod was created and contains the mod name I was trying to create. But nothing else happens. No details can be found in mod details. Asset replacements are still greyed out. If I refresh the capture list the current path returns to "...". One mod is created in C:\Projects\LegoBatman\rtx-remix\mods\Mod called mod.usda. When I try to load it, it gives me this error.
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/49733753/42f2406d-59ad-440d-9138-c862c5a28910)
The path of that mod is C:\Projects\LegoBatman\rtx-remix\mods\Mod. The game is in C:\Projects\LegoBatman. Remix version is 2024.3.1. 

### How do you reproduce the bug?

Load this project and capture. 
[1st.zip](https://github.com/user-attachments/files/15811883/1st.zip)
[MainProjectFile.zip](https://github.com/user-attachments/files/15811885/MainProjectFile.zip)
[mod.zip](https://github.com/user-attachments/files/15811886/mod.zip)

### Version

2024.3.1

### Logs

[kit_20240612_232742.log](https://github.com/user-attachments/files/15811891/kit_20240612_232742.log)

**Comment by sjgillard** [comment]
Created REMIX-3380

**Comment by Frissj** [comment]
This seems to only affect Lego Batman which seems to be because the game name in taskbar is 
![image](https://github.com/user-attachments/assets/5fb1764f-0851-44d2-a9c3-cea49149f05e)
which has some funky characters. Logs seem to indicate that as well. 
When you open the project in toolkit you get this
![image](https://github.com/user-attachments/assets/3f9fd37e-e826-44c1-bfb9-d64b1b19dffa)
![image](https://github.com/user-attachments/assets/44eb5f50-40f6-4d43-ac63-0561c9cdd538)
You have to edit mod.usda and input this to make asset replacement work
![image](https://github.com/user-attachments/assets/ebf72b16-5c38-40fd-9aa7-ab0667fe1ddb)
Otherwise it will look like this after creating a project
![image](https://github.com/user-attachments/assets/d27de8d6-ea05-4963-ba86-ab8cfd045b45)
