### ISSUE TITLE
[Runtime Bug]: Game freezing up when Auto-Exposure is deactivated

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#538]
### Describe the bug

Inside Max Payne 1, when I was about to turn off Auto-exposure under post-processing settings. Bug is consistent/repeatable.

***EDIT:*** Freeze doesn't happen if I shut down USD Composer and more Vram is allocated -
GPU: RTX 3070

### How do you reproduce the bug?

As described above

### What is the expected behavior?

The runtime should...

### Version

0.5.1

### Logs

[d3d9.log](https://github.com/user-attachments/files/15822059/d3d9.log)
[MaxPayne_d3d9.log](https://github.com/user-attachments/files/15822066/MaxPayne_d3d9.log)

**Comment by NV-LL** [comment]
REMIX-3044 for tracking

**Comment by NV-LL** [comment]
Hi @PappaSlask - checking in again to see if you've been able to check this issue on the latest runtime build. Please let us know if it persists for you. Thanks!

**Comment by NV-LL** [comment]
Hi @PappaSlask - checking in to see if you've been able to re-test this issue on the latest runtime build. We also want to inform you of our stale ticket policy, namely that we will close this ticket as 'went-stale' if it doesn't receive an update in the next 2 weeks. Thank you!

**Comment by PappaSlask** [comment]
@NV-LL Again, my apologies for the lack of reconnection on my tickets. I will investigate this in the coming days!

**Comment by NV-LL** [comment]
Hey @PappaSlask - just bumping this again to see if you've had a chance to retest on the latest runtime build. We don't want to close it out from under you if you plan to keep working on it. Thanks!
