### ISSUE TITLE
[Runtime Bug]: Portal RTX & dxvk-remix failing to launch on RTX GPUs

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#554]
### Describe the bug

There are numerous bug reports from users on the Steam forums and our Discord server about this issue:
https://steamcommunity.com/app/2012840/discussions/0/4409669206921465356/
https://steamcommunity.com/app/2012840/discussions/0/4409669206917831055/
https://steamcommunity.com/app/2012840/discussions/0/4409669041607637016/
https://discord.com/channels/1028444667789967381/1028444668918235197/1257356837267701793

In the Discord link, the user provided their logs. I've asked for more users experiencing this issue to share their logs, but haven't received any responses as of this post.

The way it behaves: It launches as a black screen, a crash from the bridge appears (or sometimes does not), and the game closes.

### How do you reproduce the bug?

Currently unknown

### What is the expected behavior?

The game should launch.

### Version

Multiple

### Logs

Refer here: https://discord.com/channels/1028444667789967381/1028444668918235197/1257359008579452990

**Comment by NV-LL** [comment]
REMIX-3330 for tracking

**Comment by NV-LL** [comment]
Hi @Kim2091 - we believe this may be addressed with driver 560.81. When you have the chance, will you please update your graphics driver and see if Portal still fails to launch? Thank you!

**Comment by NV-LL** [comment]
Hi @Kim2091 - checking in again to see if you can re-test with a driver 560.81 or later and let us know if the issue persists. We also want to inform you of our stale ticket policy, namely that we will close this ticket as went-stale if it doesn't receive an update in the next two weeks. Thanks!

**Comment by Kim2091** [comment]
Apologies about the lack of a follow-up. I opened this issue as a compilation of many other user's reports. I was not able to reproduce it on my system.

I will say that I have recommended updating to 560.81 to many users on our Discord server, but the update did not fix their bridge crashing, including for Portal RTX.

**Comment by NV-LL** [comment]
Thanks for confirming, @Kim2091 - since we don't have a reliable repro and associated info for this, we're going to close this ticket. If you hear of anyone else encountering it again, please encourage them to file a GH ticket (or re-open this one) with the attendant logs/crash dumps so we can keep investigating.
