### ISSUE TITLE
[Runtime Bug]: Remix UI's mouse pointer getting stuck after tabbing in/out of game (Max Payne 1)

### ISSUE THREAD

**Issue by PappaSlask** [NVIDIAGameWorks/rtx-remix#556]
### Describe the bug

In Max Payne 1, with the latest versions of DXVK and Bridge, the mouse pointer for Remix's UI gets stuck upon tabbing in and out of the game. Only solution was to downgrade aforementioned versions.

### How do you reproduce the bug?

- Obtain Max Payne 1
- Install latest versions of DXVK and Bridge
- Launch game
- Tab out of the game, then in again
- Watch how the mouse is stuck

### Version

0.5.1

**Comment by NV-LL** [comment]
REMIX-3338 for tracking

**Comment by PappaSlask** [comment]
@NV-LL UPDATE: Mouse-stuck-issue has been resolved in later dxvk/bridge builds. But other mouse related issues were introduced. Will post a separate thread about this. Closing as solved!
