### ISSUE TITLE
[Question] Is it possible to use RTX Remix only for the purpose of adding DLSS to a game that doesn't support it natively?

### ISSUE THREAD

**Issue by LOKSTED** [NVIDIAGameWorks/rtx-remix#558]
To clarify, I want to mod DLSS into a game to boost performance, while keeping it's original lightning without ray tracing

**Comment by Kim2091** [comment]
https://github.com/NVIDIAGameWorks/rtx-remix/issues/422

**Comment by NV-LL** [comment]
Hi @LOKSTED - as pointed out above, this is a duplicate of #422. That issue was closed, as it falls outside the current design goals for Remix. Please see #422 for more info. We will close this as a duplicate.
