### ISSUE TITLE
[Runtime Bug]: Fallout New Vegas Regressions

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#559]
### Describe the bug

RTX Remix no longer hooks fully into FNV with the latest github actions builds. It generates d3d9.log and bridge log files, but does not actually change anything in-game.

In addition, build 409 many months ago caused artifacting in interiors, where fake ambient occlusion baked into meshes will take on the mesh hash and textures of surrounding objects & warp across the screen.

Installing build 408 resolves the failed hook, but users are unable to open the overlay and interact with it. Rolling back to bridge-remix build 65 resolves this particular issue.

In the end, rolling back to dxvk build 408 and bridge-remix build 65 resolves both of these issues.

### How do you reproduce the bug?

1. Follow the installation guide here: https://discord.com/channels/1028444667789967381/1106553248590090351/1210396318724522044
2. Install the latest RTX Remix builds instead of the recommended builds
3. Observe issues

### What is the expected behavior?

It should run properly

### Version

Actions

### Logs

[d3d9.log](https://github.com/user-attachments/files/16275372/d3d9.log)
[NvRemixBridge.log](https://github.com/user-attachments/files/16275373/NvRemixBridge.log)

**Comment by Frissj** [comment]
An example of the 409 issue is given in this issue here. https://github.com/NVIDIAGameWorks/rtx-remix/issues/414

**Comment by nv-ajaus** [comment]
@Kim2091 Can you please provide some videos or images of the artifacts you are encountering? Is Frissj's comment correct that the issue in Lego Batman looks like it has the same artifacts?

**Comment by Kim2091** [comment]
Sure, I'll see if I can find a video I had recorded of it.

Regarding Lego Batman: they're not the *same* artifacts, but they are just new artifacts introduced by build 409 vs the previous build 408. It seems to present differently in every game.

**Comment by Kim2091** [comment]
@nv-ajaus https://youtu.be/jKeT4f1bBcA?si=CcPTOmLzpTpd7NDi&t=34

The geometry corruption is the issue in FNV. We had to use build 490. As it turns out, none of us (that were online at the moment) had immediate access to build 409. We used build 490 here, but the issue did originally start with 409.

**Comment by NV-LL** [comment]
Thanks for the updates! We've filed REMIX-3426 for tracking.

**Comment by AlexDunn** [comment]
For the geometry corruption specifically, this latest change may improve things: https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/10910405835

If you test it please let us know.

**Comment by Kim2091** [comment]
@AlexDunn Thank you! I'm happy to report that FNV's geometry corruption has been fixed. The latest bridge build also has no issues getting in-game.
