### ISSUE TITLE
[Runtime Bug]: Anarchy Online crashes slightly after launch.

### ISSUE THREAD

**Issue by Pillboxing** [NVIDIAGameWorks/rtx-remix#563]
### Describe the bug

Dxwrapper finally supports launching ao to some degree (login menu works and some zones). When using rtx remix however it crashes before even loading the log in screen.

### How do you reproduce the bug?

Launch Anarchy Online using rtx remix and dxwrapper

### What is the expected behavior?

The runtime should...allow the game to launch?

### Version

remix-0.5.1+448c6137

### Logs

[AnarchyOnline_d3d9.log](https://github.com/user-attachments/files/16368244/AnarchyOnline_d3d9.log)

**Comment by nv-ajaus** [comment]
@Pillboxing Do you happen to have a ".dmp" file in your .trex directory? Can you please upload it if it exists as well as the d3d9.log file and the .trex\NvRemixBridge.log file too?

**Comment by NV-LL** [comment]
Hi @Pillboxing - checking in again to see if you can provide us with the above requested logs to help us investigate this issue. We also want to inform you of our stale ticket policy, namely that this ticket will be closed as 'went-stale' if it doesn't receive a response in another 2 weeks. Thank you!

**Comment by NV-LL** [comment]
Hi @Pillboxing - since this ticket hasn't received a response in the past month, we're going to close it as 'went-stale'. You can re-open it at any time if you'd like to keep investigating.
