### ISSUE TITLE
[Runtime Bug]: Tomb Raider - The Angel of Darkness - Lara/NPCS Diagonal Banding

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#568]
### Describe the bug

It looks like Lara is invisible for most of the game. But, near the end of the game, Lara's playermodel is visible. There may be some other levels and instances where she's visible, but these are two observable instances I can repeatedly recreate. Videos on the Tomb Raider: Angel of Darkness discord project page. https://discord.com/channels/1028444667789967381/1171738274767831060/1267433771360325714

### How do you reproduce the bug?

1.) Launch TR AOD
2.) Start New Game
3.) Observe Lara's invisible playermodel.

To see Lara's playermodel,

1.) Download Level 25: Vault of Trophies https://tombraiders.net/stella/savegame/TR6saves.html
2.) Place Savegame files into Savegame folder in main game directory
3.) Load the middle few save games and observe Lara's visible playermodel.

Using Remix version,
[dxvk-remix-53b0bdc-599-debugoptimized](https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/10118513607/artifacts/1745782280)
[bridge-remix-07778f9-85-debugoptimized](https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/10117516960/artifacts/1745545523)

### What is the expected behavior?

To have Lara be visible at all times.

### Version

dxvk-remix-53b0bdc-599-debugoptimized

### Logs

[TRAOD_P4_d3d9.log](https://github.com/user-attachments/files/16411508/TRAOD_P4_d3d9.log)
[d3d9.log](https://github.com/user-attachments/files/16411509/d3d9.log)
[NvRemixBridge.log](https://github.com/user-attachments/files/16411524/NvRemixBridge.log)

### Media

Videos of this found on TR AOD Discord project page https://discord.com/channels/1028444667789967381/1171738274767831060/1267433771360325714

**Comment by nv-ajaus** [comment]
Hi @skurtyyskirts , I think this problem is addressed in this prior issue https://github.com/NVIDIAGameWorks/rtx-remix/issues/80#issuecomment-2013723957

In the `bridge.conf` file in the `.trex` folder, set `alwaysCopyEntireStaticBuffer = True`, with no leading #. If you do not have a bridge.conf file, it is available here : https://raw.githubusercontent.com/NVIDIAGameWorks/bridge-remix/main/bridge.conf

Please give this a try.

**Comment by skurtyyskirts** [comment]
Oh my goodness! How exciting, thanks so much for the fix! That did the trick, Lara's back in frame again! I'll go ahead and close the ticket as everything's all fixed - thanks again! :) 
![Tomb Raider  Angel of Darkness Screenshot 2024 07 29 - 15 17 13 56](https://github.com/user-attachments/assets/5af88ef7-e702-4a74-ab0c-3eb5e2aef963)
![Tomb Raider  Angel of Darkness Screenshot 2024 07 29 - 15 19 18 92](https://github.com/user-attachments/assets/28478722-0676-4c7b-8702-404eb9bd118c)

**Comment by skurtyyskirts** [comment]
Oops, I might've spoken too soon. It looks like this fix fixes about 80% of the disappearing. The first two levels Lara's consistently present, but it looks like later on in the game there's strong moments of disappearing. I've posted a video to the Discord page demonstrating this. Hoping future Remix updates remedy/improve upon this :) https://discord.com/channels/1028444667789967381/1171738274767831060/1267601213302640803
![Tomb Raider  Angel of Darkness Screenshot 2024 07 29 - 16 38 32 89](https://github.com/user-attachments/assets/7a4f474a-893e-437a-8f4f-6a94b893f54a)
![Tomb Raider  Angel of Darkness Screenshot 2024 07 29 - 16 41 59 31](https://github.com/user-attachments/assets/c37d769d-e3ef-4c71-8a5a-2a738220cd0d)
![Tomb Raider  Angel of Darkness Screenshot 2024 07 29 - 16 42 07 71](https://github.com/user-attachments/assets/6affcec2-f46d-46d1-a801-afcd09e1564e)
![Tomb Raider  Angel of Darkness Screenshot 2024 07 29 - 16 50 20 84](https://github.com/user-attachments/assets/53ed9560-0d36-4b88-adc2-4306e67204a2)

**Comment by nv-ajaus** [comment]
I updated the title of this issue to reflect the current problem shown.

**Comment by NV-LL** [comment]
REMIX-3407 for tracking

**Comment by nv-ajaus** [comment]
Hi @skurtyyskirts, I took a look at this issue and I'm strongly convinced it's not a bug like the the original characters missing problem. This looks like z-fighting, essentially, the original game is rendering sometime exactly on top of these characters, maybe to achieve some effect.

To determine this, and resolve this behavior:
1. Play the game with RTX Remix and reproduce the banding behavior.
2. Press ALT+X and then open the Developer Settings Menu.
3. Navigate to "Game Setup", and then the big menu of textures in the "Step 1: Categorize Textures" section.
4. Go through through the textures and look for a texture that draws a highlighted border around the missing sections of Lara or other NPCs with banding. 
5. When you find the texture that's causing the banding, select it and categorize it as "Ignore Texture"

**Comment by NV-LL** [comment]
Hi @skurtyyskirts - checking in to see if you've tried the instructions above and if they resolve the banding issue for you. We also want to inform you of our stale ticket policy, namely that we will close this ticket as 'went-stale' if it doesn't receive a response in two weeks. Thanks!

**Comment by skurtyyskirts** [comment]
Hello,
My apologies for the late reply - THAT FIXED IT! Thanks so much for your help! The disappearing has gone away and she's visible in every cutscene/level now! 
Thank you,
Jeffrey
