### ISSUE TITLE
Alice Madness Returns doesn't start

### ISSUE THREAD

**Issue by ditzz84** [NVIDIAGameWorks/rtx-remix#57]
**Describe the bug**
- Alice Madness Returns game doesn't start either running it from Steam or by running the executable.
- Which Remix version: remix-0.1.1-2-gdc825b6
- Which GPU: MSI RTX 4090 GameX Trio
- Which GPU driver version: 531.61
- Which game build: Latest available Steam version of the game.

**To Reproduce**
1. Copy Remix files to files to ..\steamapps\common\Alice Madness Returns\Binaries\Win32\
2. Launch AliceMadnessReturns.exe from above location
3. Game doesn't start.

Alternatively:
1. Copy Remix files to files to ..\steamapps\common\Alice Madness Returns\Binaries\Win32\
2. Launch launch Alice Madness Returns through Steam
3. Steam "Launch" button changes to "Stop" and back to "Launch" couple seconds later.

**Attach logs!**
[AliceMadnessReturns_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225746/AliceMadnessReturns_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225793/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11225802/NvRemixBridge.log)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by NV-LL** [comment]
Excellent, thank you for confirming! We'll close this ticket out. Please open another one if you have any further issues.
