### ISSUE TITLE
[Runtime Bug]: RTX Remix not working anymore with World of Warcraft, unless you use files from PortalRTX.

### ISSUE THREAD

**Issue by Nikanoru** [NVIDIAGameWorks/rtx-remix#570]
### Describe the bug

When using any of the available RTX Remix Versions on Github and trying to play World of Warcraft with it, RTX Remix will not work.
HOWEVER, RTX Remix will work if you use  NvRemixBridge.exe from PortalRTX and put it in the .trex folder and use the d3d9.dll from the bin folder of PortalRTX and put in into the root folder where WoW's EXE resides. I was also using https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/7891589841 but I am not sure if that is necessary.

### How do you reproduce the bug?

Start WoW's executable with any version of RTX Remix on Github. Note: Only older Versions of WoW will work, I believe Version 3.3.5 is the highest that will work with RTX Remix, as newer versions aren't DX8/9 anymore.

### What is the expected behavior?

The runtime should...work.

### Version

any, but currently 0.5.1

### Logs

[NvRemixBridge.log](https://github.com/user-attachments/files/16447509/NvRemixBridge.log)
[d3d9.log](https://github.com/user-attachments/files/16447512/d3d9.log)
[_d3d9.log](https://github.com/user-attachments/files/16447513/_d3d9.log)

**Comment by NV-LL** [comment]
REMIX-3409 for tracking

**Comment by NV-LL** [comment]
Thank you for contacting us. Due to NVIDIA's security policies, we're unable to test content on unofficial or private servers. As a result, we won't be able to proceed with this request and will need to close this ticket. We apologize for any disappointment this may cause.

**Comment by Nikanoru** [comment]
Ok, I understand. Thanks regardless :)

**Comment by Nikanoru** [comment]
> Thank you for contacting us. Due to NVIDIA's security policies, we're unable to test content on unofficial or private servers. As a result, we won't be able to proceed with this request and will need to close this ticket. We apologize for any disappointment this may cause.

Actually I just got an idea. It is still possible to test this without unofficial or private servers. World of Warcraft was distributed on CD's back in the days, you can still find these CD's on the used market and install an old version of WoW and then simply start the .exe. You don't need to connect to a server at all, just getting into the log in screen is enough.

**Comment by mtumaykin** [comment]
> > Thank you for contacting us. Due to NVIDIA's security policies, we're unable to test content on unofficial or private servers. As a result, we won't be able to proceed with this request and will need to close this ticket. We apologize for any disappointment this may cause.
> 
> Actually I just got an idea. It is still possible to test this without unofficial or private servers. World of Warcraft was distributed on CD's back in the days, you can still find these CD's on the used market and install an old version of WoW and then simply start the .exe. You don't need to connect to a server at all, just getting into the log in screen is enough.

Hi! I had same trouble and didn't find any solution in google other this github issue link. So my next text is for you and anyone who has same problem.
World of Warcraft is one of a games that can't load rtx-remix dlls on run so you need to launch it as:
> NvRemixLauncher32.exe -i path\to\Wow.exe
In this way rtx-remix works fine (if we're not talking about glitches)
