### ISSUE TITLE
[Runtime Bug]: Revolt Steam release DX9 Steam version

### ISSUE THREAD

**Issue by Entityexist** [NVIDIAGameWorks/rtx-remix#580]
### Describe the bug

Runtime doesnt raytrace or read any scene assets
![image](https://github.com/user-attachments/assets/e30cb7d3-cb68-47db-b5f6-969c88ae9c91)

### How do you reproduce the bug?

![image](https://github.com/user-attachments/assets/000407c1-b392-4a2d-a8a2-42be9968ec95)
We need steam version of Re volt
and set the wrapper to these settings then it will start in any other case it will freeze on startup

### What is the expected behavior?

Read textures materials and pathtrace

### Version

0.5.4

### Logs

[dxcfg_d3d9.log](https://github.com/user-attachments/files/16567273/dxcfg_d3d9.log)
[revolt_d3d9.log](https://github.com/user-attachments/files/16567274/revolt_d3d9.log)
[NvRemixBridge.log](https://github.com/user-attachments/files/16567275/NvRemixBridge.log)

### Crash dumps

[NvRemixBridge.exe_20240809_235018.dmp](https://github.com/user-attachments/files/16567277/NvRemixBridge.exe_20240809_235018.dmp)
[NvRemixBridge.exe_20240810_000146.dmp](https://github.com/user-attachments/files/16567278/NvRemixBridge.exe_20240810_000146.dmp)

**Comment by Entityexist** [comment]
on Remix version 0.4.1 there is square that is blinking whenever camera in the menu moves but it still doesnt see assets from the game
![image](https://github.com/user-attachments/assets/7fa11912-cadf-41b5-9d83-5d35804196c1)
[revolt_d3d9.log](https://github.com/user-attachments/files/16567342/revolt_d3d9.log)

**Comment by NV-LL** [comment]
Thanks for reaching out, @Entityexist. We suspect this may be a setup issue with the game. We suggest reaching out to the Discord community for suggestions to see if anyone else has resolved this problem.

**Comment by Entityexist** [comment]
Dear Nvidia Team,

I hope this message finds you well.

There has been ongoing discussion on our Discord community, @NV-LL, where many users have tried to launch the game. Unfortunately, despite numerous attempts, the only success I've had was through an Xbox emulator, which isn't the ideal way to enjoy the game.

There are many users eager to see progress on getting this game to work, but so far, no one has been able to launch it successfully.

We would greatly appreciate your assistance in helping us resolve this issue. Your support would mean a lot to our community.

Thank you in advance for your time and consideration.

Best regards,
Entity

**Comment by Entityexist** [comment]
Hi @NV-LL ,  Is this issue being considered at all? I haven’t received any response from you for quite some time now.

**Comment by nv-ajaus** [comment]
Hi @Entityexist , I took a look at this request, and unfortunately it does not look like Re-Volt is a good candidate to be compatible with RTX-Remix."
