### ISSUE TITLE
[Toolkit bug]: RTX Remix Renderer failed to initialize

### ISSUE THREAD

**Issue by KingLionOfRoses** [NVIDIAGameWorks/rtx-remix#586]
### Describe the bug

Every time I open RTX Remix, I am met with an immediate dialog box (see screenshot) and cannot get past this point. This is my first time using the software.

### How do you reproduce the bug?

1. Open NVIDIA RTX Remix.
2. Dialog box pops up as soon as menu loads.
3. Crash

### Version

2024.3.1

### Logs

[kit_20240821_131754.log](https://github.com/user-attachments/files/16695819/kit_20240821_131754.log)
[kit_20240821_131840.log](https://github.com/user-attachments/files/16695822/kit_20240821_131840.log)

### Media

![image](https://github.com/user-attachments/assets/ba54b88d-48e4-46d8-babe-500f59942c46)

**Comment by nxkb** [comment]
Hi @KingLionOfRoses, would you be able to attach the dxvk logs as well (kit_d3d9.log)? They might help us figure out what is going wrong here.

**Comment by NV-LL** [comment]
Hi @KingLionOfRoses - checking in again to see if you can send us the DXVK logs as per the comment above. We also want to inform you of our stale ticket policy, namely that this ticket will be closed as 'went-stale' if it doesn't receive a response in the next two weeks. Thank you!

**Comment by NV-LL** [comment]
Hi @KingLionOfRoses - we're going to close this ticket as 'went-stale', as it hasn't received an update in the past month. You can reopen it at any time here if you'd like to continue investigating.
