### ISSUE TITLE
[Toolkit bug]: Can't Package Mod - Error in 'textFileFormatYyerror' at line 3162

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#589]
### Describe the bug

When I go to package my GMOD RTX mod, I'm receiving an error I've never seen before. I'm getting error message: Error in 'textFileFormatYyerror' at line 3162 in file pxr/usd/sdf/textFileFormat.yy : 'syntax error at 'inputs:displace_in' in </RootNode/Looks/mat_25DA76B1799108F9/Shader> on line 22 in file C:\Users\skurtyy\Desktop\GmPoolComplex\mod_cb9a9660-04bb-4dc4-995f-152eb2ef53fc.usda

### How do you reproduce the bug?

1. Create capture with gmod
2.Create gmod rtx folder project + start project up
3. Upscale using PBRFusion and ingest into project
4. Create a new layer called Changes
5. Auto replace everything in the project with python script
6. Go to package mod, receive error.

### What is the expected behavior?

I've sent my usda's in .txt format 
I've made atleast 100 gmod rtx mods, I'm very used to the workflow and I'm not sure what could be causing this error. I also noticed that another user in the discord recently had this issue, https://discord.com/channels/1028444667789967381/1028444668918235197/1274526130875138152

### Version

2024.4.1

### Logs

[GmPoolComplexRTX.txt](https://github.com/user-attachments/files/16735839/GmPoolComplexRTX.txt)
[mod.txt](https://github.com/user-attachments/files/16735840/mod.txt)
[changes.txt](https://github.com/user-attachments/files/16735841/changes.txt)

### Media

![Screenshot 2024-08-24 024847](https://github.com/user-attachments/assets/3b86b28b-eefc-47df-9429-fbc7b7aea703)
![Screenshot 2024-08-24 025500](https://github.com/user-attachments/assets/a28b6caf-2b9c-444a-a02d-617c04d8c205)

**Comment by skurtyyskirts** [comment]
[kit_20240823_052414.log](https://github.com/user-attachments/files/16738360/kit_20240823_052414.log)
[kit_20240823_175419.log](https://github.com/user-attachments/files/16738361/kit_20240823_175419.log)
[kit_20240824_175434.log](https://github.com/user-attachments/files/16738362/kit_20240824_175434.log)
[kit_20240824_175937.log](https://github.com/user-attachments/files/16738363/kit_20240824_175937.log)

Uploading various kit logs around my project

**Comment by skurtyyskirts** [comment]
I've posted a video demonstration of what's happening in the RTX-Remix discord, https://discord.com/channels/1028444667789967381/1028444668918235197/1277043385168826418

**Comment by skurtyyskirts** [comment]
I've tried using a different map to mod in gmod, as well as use a different upscaler, PBRify. Still receiving the error. Also tried doing a complete clean install of GmodRTX by uninstalling it, and uninstalling Garrysmod and cleaning the game folder with a fresh install. Still receiving the error.

**Comment by nxkb** [comment]
Can you attach this file `C:\Users\skurtyy\Desktop\GmPoolComplex\mod_cb9a9660-04bb-4dc4-995f-152eb2ef53fc.usda`. USDA format is fine.

**Comment by skurtyyskirts** [comment]
![Screenshot 2024-08-28 172302](https://github.com/user-attachments/assets/a7ec5a9a-0c3f-481f-ad95-ed93f2ac2515)

Hmm, I don't see that file in my project directory. Just changes.usda, GmPoolComplexRTX.usda, and mod.usda. It looks like github won't let me send the .usda file, but I can change it to a .txt file and send it here, I've attached it above in a previous post :) 
![Screenshot 2024-08-28 172402](https://github.com/user-attachments/assets/3b7090e6-df2c-4a85-bb55-d6fc3915b043)

**Comment by nxkb** [comment]
Ah ok, it looks like you just have a syntax error in a usda file, but I'm not sure at what step that's happening. The line number doesn't quite match the file you attached so I can't really tell what the exact syntax problem is.

Do you know that all your usd files load properly before you try to package them? If we can isolate the problem to the packaging step then we can hopefully find a simpler reproduction case.

**Comment by skurtyyskirts** [comment]
Ahh I see, is the line number in one of the log files? I could take a look and see, or perhaps make a new project and try to retrack my steps. I've created a thread in the RTX-Remix Discord that displays some more videos I've taken of the process if that helps! https://discord.com/channels/1028444667789967381/1278543517182066791

**Comment by skurtyyskirts** [comment]
Issue resolved! It looks like it was the old script that was causing issues. https://discord.com/channels/1028444667789967381/1278543517182066791/1278990103930339369
I should just learn the REST api tools to do this instead of python scripts. 

Thanks everyone for the help as always! :)
