### ISSUE TITLE
[Toolkit bug]: Sky asset stuck to my screen

### ISSUE THREAD

**Issue by Frissj** [NVIDIAGameWorks/rtx-remix#593]
### Describe the bug

Out of nowhere, without changing any catagorise apart from assigning it to a sky texture hours ago and after multiple reloads, the asset becomes stuck to my screen. It started further to the right but after I tried reloading, its taking up more of my screen.

https://github.com/user-attachments/assets/410fa1f2-6e12-4214-8685-75dbc7326c98

[kit_20240830_004532.log](https://github.com/user-attachments/files/16808447/kit_20240830_004532.log)

### How do you reproduce the bug?

Not sure sorry. But if I unassign it as a sky texture it goes away. Then if I reassign it it comes back as an issue.

### Version

2024.4.1

**Comment by NV-LL** [comment]
REMIX-3557 for tracking

**Comment by NV-LL** [comment]
Hi @Frissj - checking in to see if you're able to provide more detailed repro steps for this issue, and to provide some guidance about which level and texture you're seeing the issue with. We also want to inform you of our stale ticket policy, namely that this ticket will be closed as 'went stale' if it doesn't receive an update in the next 2 weeks. Thank you!
