### ISSUE TITLE
[Runtime Bug]: Garrysmod Crashing

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#594]
### Describe the bug

When I'm playing in Garrysmod RTX, I'm experiencing crashing that seems to happen when I play for about 2-3 minutes max. It's not necessarily a crash, the game is still up, but everything will freeze and whatever audio was present at the time is stuck on a mini loop. 

### How do you reproduce the bug?

1. Launch gmod rtx 32bit version with latest remix version
2. Load into any map, play for about 2-3 minutes
3. See game freezing bug

### What is the expected behavior?

The runtime should...

### Version

Build #632

### Logs

[crashlogs.zip](https://github.com/user-attachments/files/16815572/crashlogs.zip)

**Comment by skurtyyskirts** [comment]
[hl2_d3d9.log](https://github.com/user-attachments/files/16881881/hl2_d3d9.log)
[NvRemixBridge.log](https://github.com/user-attachments/files/16881883/NvRemixBridge.log)
[NvRemixBridge.exe_20240904_174719.dmp](https://github.com/user-attachments/files/16881884/NvRemixBridge.exe_20240904_174719.dmp)

Seem to be getting crashes when I load in with a mod I've made.

**Comment by nv-ajaus** [comment]
@skurtyyskirts I can't seem to find a matching binary for the dump file (.dmp) you provided in your last message. Can you point me to the exact build and build type (release/debug-optimized/debug) of dxvk-remix that you used when that crash was generated? If this is from a fork or binary release of

**Comment by skurtyyskirts** [comment]
I apologize, it looks like there isn't a dmp file that generates when it "crashes". It's more of a hanging crash, where the game will freeze and the last noise made in the game repeats. The program stops responding. Is it possible that a mod would cause the crash? The mod was packaged successfully, but I used a python script to auto-replace the textures in the mod. 

[NvRemixBridge.log](https://github.com/user-attachments/files/16999579/NvRemixBridge.log)
[hl2_d3d9.log](https://github.com/user-attachments/files/16999581/hl2_d3d9.log)

**Comment by skurtyyskirts** [comment]
Hmm, it seems to be an issue with the mod and not gmod. Another user reported that their game started crashing when they tried using my mod. Here's an example mod that I've made. I'm confused as to why the python script would be causing issues when in the toolkit the assets are properly replaced.  

But, I would be inclined to learn about the REST API system to change the textures. Or, to use the "Assign Texture Sets" to replace the textures. What format should the files be in to use this feature? I have files named for example "23402423422342_height.png" or "32394820482_diffuse.png" but the Toolkit doesn't seem to be finding the correct files, or replacing all of the other following textures. 
![Screenshot 2024-09-15 144636](https://github.com/user-attachments/assets/25ec7eec-f656-4461-ac71-2b40f00dfdc9)
I'll receive a message like this, and a "FF0D7.." texture appears on the list. I'll uncheck the texture and just select the Diffuse texture,  but when I press complete the FFF0D7 texture replaces it instead. 
![Screenshot 2024-09-15 144919](https://github.com/user-attachments/assets/e4fccfa6-ea28-4f02-9a95-0663fa919437)
![Screenshot 2024-09-15 144931](https://github.com/user-attachments/assets/47b7ac77-baef-4ed1-b383-9ebbeb58e918)

[changes.txt](https://github.com/user-attachments/files/17007165/changes.txt)
[mod.txt](https://github.com/user-attachments/files/17007166/mod.txt)

**Comment by skurtyyskirts** [comment]
I was able to capture a video of the type of crash I'm experiencing in the gmod RTX discord, and the log from that freeze
 https://discord.com/channels/1028444667789967381/1116089843479498782/1285542601050685450
[hl2_d3d9.log](https://github.com/user-attachments/files/17026665/hl2_d3d9.log)
[NvRemixBridge.log](https://github.com/user-attachments/files/17026671/NvRemixBridge.log)
[d3d9.log](https://github.com/user-attachments/files/17026675/d3d9.log)

**Comment by skurtyyskirts** [comment]
Looks like the community is having similar freezes that I am. xoxor4d is having a err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST error, which seems to be the same one I had on a few logs. I'm also experiencing what Chunkle Dorito is experiencing with the hanging computer issue.
![Screenshot 2024-09-19 173041](https://github.com/user-attachments/assets/c61dc256-7662-4ae8-90d5-dbbd301e6f89)

**Comment by UncleRito** [comment]
Also experienced this issue with Need for Speed: Underground 2 and Gmod.

**Comment by skurtyyskirts** [comment]
xoxor seems to have found a possible fix - it looks like our freezing is due to displacement being turned on? Both UncleRito and I's mod had displacement maps. UncleRito and I both concurred on discord to xoxor that disabling Displacement stopped the freezing. I don't want to jump to conclusions too fast though, would like confirmation. 
![Screenshot 2024-09-20 165442](https://github.com/user-attachments/assets/7b005fbc-c621-4958-b1df-a1fbbbaffaa4)

**Comment by xoxor4d** [comment]
The build that started the gpu crashes for us: https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/10410768831
Game affected: call of duty 4 
Current gpu driver version: 561.09 (did a complete reinstall)
Windows 11 23H2 - 22631.4169
RTX3080

Starting the game with turned off displacement or quickly turning it off after the game starts prevents a freeze. Enabling it again will likely freeze the game seconds to a minute later. Framerate will drop from 70ish to around 45 a few times before that happens.

**Comment by xoxor4d** [comment]
The latest [commit](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/20fd5da60bf81b6ebd3e618051b165e125d0ca56) did not fix the issue for me unfortunately :/

**Comment by skurtyyskirts** [comment]
Experiencing crashing when pressing the Q button bringing up the Gmod Menu. Crash dump and log files attached in zip folder. 

[gmodcrashing.zip](https://github.com/user-attachments/files/17499319/gmodcrashing.zip)

**Comment by NV-LL** [comment]
Hi @skurtyyskirts, @xoxor4d & @UncleRito - we believe this original crash issue (related to displacements) is resolved in the latest runtime build. Would you all please retest and let us know if it persists or not?

@skurtyyskirts, would you please file a new ticket for the more recent crash issue in Gmod (crash on pressing Q)? Thank you!

**Comment by skurtyyskirts** [comment]
Thanks for getting back! Yes, it looks like the displacements crashing/freezing has been resolved on my end. Also, the Q menu bug is also magically fixed lol. Closing ticket, no further action needed. Thanks a lot! I appreciate y'alls help :)
