### ISSUE TITLE
[Toolkit bug]: RTX Remix Failed to Initialize

### ISSUE THREAD

**Issue by Robsome** [NVIDIAGameWorks/rtx-remix#599]
### Describe the bug

I tried to launch RTX remix and I got an error saying it failed to initialize. I have a desktop RTX 4070 manufactured by MSI.

### How do you reproduce the bug?

1. Try to launch RTX Remix
2. Cry

### What is the expected behavior?

The toolkit should initialize

### Version

2024.4.1

### Logs

I don't think I can even get to this.

### Media

![image](https://github.com/user-attachments/assets/6db69f72-09ac-43d8-ac14-71bfcb01635b)

**Comment by nxkb** [comment]
This looks similar to what this user reported https://github.com/NVIDIAGameWorks/rtx-remix/issues/586

Would you be able to attach the dxvk logs as well (kit_d3d9.log)? They might help us figure out what is going wrong here.

**Comment by NV-LL** [comment]
Hi @Robsome  - checking in again to see if you can send us the DXVK logs as per the comment above. We also want to inform you of our stale ticket policy, namely that this ticket will be closed as 'went-stale' if it doesn't receive a response in the next two weeks. Thank you!
