### ISSUE TITLE
Sonic Adventure DX (With d3d8to9) stuck on white screen when using RTX-Remix.

### ISSUE THREAD

**Issue by KingKrouch** [NVIDIAGameWorks/rtx-remix#6]
This game (When using d3d8to9) seemingly gets stuck on a white screen when I attempt to use RTX Remix with it.
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11212897/d3d9.log)
[sonic_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11212898/sonic_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11212900/NvRemixBridge.log)

**Comment by NV-DM** [comment]
Hello, @KingKrouch. Could you please re-test this with the latest builds of the bridge and dxvk remix? 

https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/6330239550
https://github.com/NVIDIAGameWorks/bridge-remix/actions/runs/6315550860

**Comment by KingKrouch** [comment]
> Hello, @KingKrouch. Could you please re-test this with the latest builds of the bridge and dxvk remix?
Hello! After disabling one of the mods involved in the BetterSADX mod that involves shaders and fixes some of the game's lighting issues (The Lantern Engine mod), alongside updating both the bridge and DXVK versions, I can confirm that it does boot now.
