### ISSUE TITLE
Vulkan beta driver support

### ISSUE THREAD

**Issue by shoober420** [NVIDIAGameWorks/rtx-remix#601]
I use the Vulkan beta driver to get the latest features for Vulkan titles, or anything that utilizes Vulkan. I decided to give RTX Remix a try with Max Payne, and get an error that my driver is too old amd need to update. The game asks for 560.81 stable, but Im using 553.02 Vulkan beta driver. Please allow support for Vulkan beta drivers or allow a way to bypass the driver check.

**Comment by NV-LL** [comment]
Hi @shoober420 - will you please re-submit this as a Runtime Feature/Improvement Request? That will help us properly categorize and keep track of tickets. Thank you!
