### ISSUE TITLE
[Runtime Bug]: Vampire The Masquerade: Bloodlines - Some Dynamically Spawned Lights and Captured World Lights are Excessively Bright

### ISSUE THREAD

**Issue by Safemilk** [NVIDIAGameWorks/rtx-remix#609]
### Describe the bug

Certain gameplay mechanics spawn temporary dynamic lights that have massively high brightness values.
Certain lights captured and translated from the world have supernova levels of brightness.

Note: This issue happens in all versions of remix for VTMB

Some examples of the dynamic light issues include muzzle flashes on guns and the spotlight when feeding.

Example of the muzzle flashes:
![example_muzzleflash](https://github.com/user-attachments/assets/7b8a1589-3f87-4b66-8705-8b4f1511c43c)

Example of the light spawned while feeding:
![example_feed_lighting](https://github.com/user-attachments/assets/50277f8a-eb04-4c23-b3e5-ccd9d5fb5d1e)

Example of a world light being translated:
![example_world_lighting](https://github.com/user-attachments/assets/93c24d9a-0a94-4711-92a9-ae4f81fcc8f8)

Example of the same light viewed in the remix tool, value can be fixed here for this issue:
![example_capture_details](https://github.com/user-attachments/assets/7c6da773-4f97-483b-bd07-93419eaf9c5c)

### How do you reproduce the bug?

1. Install Vampire The Masquerade: Bloodlines (Steam version)
2. Install Wesps Unofficial Patch 11.5 (https://www.moddb.com/mods/vtmb-unofficial-patch)
3. Install the Remix Runtime for VTMB (https://github.com/CattoSalad/VTMB-RTX-Remix)
4. Run VTM:B
5. Start a new Game, ensure the RTX lighting is on etc.
6. Then play through the intro (theatre scene will have massively bright light in it for example)
7. Accept Jack's help afte theatr scene to follow tutorial
8. In the tutorial, approach the NPC you are instructed to feed from and use F to feed on them
9. The feed mode should activate and then a massively bright runtime light will spawn, blowing out the screen. 

### What is the expected behavior?

The Lighting should not exceed reasonable levels during level light translation or during dynamic light spawning.

Lights that are captured should not have astronomically high values when translated or captured.

### Version

remix-main+ea43e86d

### Logs

n/a

### Crash dumps

n/a

### Media

![example_feed_lighting](https://github.com/user-attachments/assets/5ededb54-0e94-4c65-9d74-becd96afdb0f)
![example_capture_details](https://github.com/user-attachments/assets/4e214434-be72-48a7-adf4-ca6a8c4f5375)
![example_world_lighting](https://github.com/user-attachments/assets/b646ad4d-e29f-4b0a-9c44-aec4f7d09476)
![example_muzzleflash](https://github.com/user-attachments/assets/88445756-f849-497f-b267-89b38cca9161)

**Comment by MarkEHenderson** [comment]
REMIX-3461

**Comment by MarkEHenderson** [comment]
The latest github build has options for scaling or capping the light intensity
https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/11185400214

@Safemilk please test it out and close this issue if this addresses your problem.

**Comment by Safemilk** [comment]
@MarkEHenderson 
This works great for half the problem, and I was able to get a result I liked for the levels, and the lights that get captured/converted in them.
However it really doesn't cover the other half of the issue which is dynamically spawned lights.

Like the feeding light and the muzzleflashes, I'd have to set this so low that the environment lights would be nonexistent
However I do think this fixes the other issue of mega bright lights in the level that currently exist.

With suppress light keeping on and the max intensity at around 10000.0 I can preserve the look of the game and it mitigates the muzzleflashes and feed lighting fairly well. However the volumetrics still persist until the camera looks away. Also supressing light keeping does create a lot of flickering as well.

This definitely solves the non dynamic portion of this problem. Should we keep the ticket open? Or open another ticket for dynamically spawned lighting issues?
![image](https://github.com/user-attachments/assets/b3e35494-b1ed-4d5e-9d7e-3bb067b38962)

![image](https://github.com/user-attachments/assets/5a08445e-54ee-44e7-bf3f-566eed339a1a)

**Comment by Safemilk** [comment]
After doing some experimentation with Freedom's Flame, it seems there is a way forward with the second set of issues. Closing this ticket.
