### ISSUE TITLE
Blender Addon

### ISSUE THREAD

**Issue by Frissj** [NVIDIAGameWorks/rtx-remix#617]
### What is the context of the feature/improvement?

The workflow is so slow.

### Please describe the feature/improvement?

An addon for blender that can work with the toolkit and allow the implementation of a button when selecting a mesh that would import the selected mesh into the running process of blender and if there are multiple, we can choose which one? That would considerably speed up the workflow.

Also we can choose (as a permanent toggle) whether the imported mesh will be imported mirrored on the X axis because me and Auto have to do this for every imported mesh so it exports in the correct position as the original from the toolkit. 

Also if we could export files directly without having to be ingested that would be great.

### Version

2024.4.1

**Comment by SmokedPete** [comment]
As discussed on Discord, this is probably more a feature we would see the community implement. 

Remix's [REST API](https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/toolkitinterface/remix-toolkitinterface-restapi.html) should allow you to do most of the requested features. 

As far as ingestion goes, it's unfortunately not possible to use non-ingested assets in your project, but you could easily create a button in Blender to ingest the opened asset and even set it as a replacement all within Blender!

**Comment by po-trottier** [comment]
As discussed on Discord, this is probably more a feature we would see the community implement.

Remix's REST API should allow you to do most of the requested features.

As far as ingestion goes, it's unfortunately not possible to use non-ingested assets in your project, but you could easily create a button in Blender to ingest the opened asset and even set it as a replacement all within Blender!

**Comment by Frissj** [comment]
@po-trottier Could you elaborate on “ you could easily create a button in Blender to ingest the opened asset and even set it as a replacement all within Blender!”, I don’t understand what you mean. I still was intending the asset to be in the state after ingesting so it could be used in Remix but I was hoping an add on could do that so I don’t have to export to obj, ingest it which would save on time and storage space. 

I will keep this ticket open because I plan to try to make it through the Rest API but if that fails I hope since you guys indirectly loosely agreed to develop it in the Remix team, this ticket will be useful.

**Comment by po-trottier** [comment]
1) You extension should take the asset opened in Blender, and run it through here: [Ingestion Endpoint](https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/toolkitinterface/remix-toolkitinterface-restapi-docs.html#tag/Ingestion/operation/add_item_to_queue_ingestcraft_mass_validator_queue_model_post)
2) You can then replace the asset using this: [Replace Asset Endpoint](https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/toolkitinterface/remix-toolkitinterface-restapi-docs.html#tag/Modding/operation/replace_asset_file_path_stagecraft_assets__asset_path__file_paths_put)
    a) If you need to get the original assets you can do it through here: [Get Assets Endpoint](https://docs.omniverse.nvidia.com/kit/docs/rtx_remix/latest/docs/toolkitinterface/remix-toolkitinterface-restapi-docs.html#tag/Modding/operation/get_assets_stagecraft_assets__get)

If you need more examples of how to use the REST API, you can refer to the [ComfyUI Nodes](https://github.com/NVIDIAGameWorks/ComfyUI-RTX-Remix/tree/main/nodes) we wrote as a reference point.

**Comment by NV-LL** [comment]
Hi @Frissj - checking in to see if you have any other questions about this ticket, or if you'd like to leave it open for another reason. Otherwise, we'd like to close it as completed. Thanks!
