### ISSUE TITLE
INFRA launches but immediately goes to a black screen and is locked up 

### ISSUE THREAD

**Issue by acehercules1196** [NVIDIAGameWorks/rtx-remix#62]
Judging by the log file for RTX remix it seems to have loaded the DX9 and DXVK stuff successfully but the game doesn't work 
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11230369/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11232325/d3d9.log)
[infra_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11232360/infra_d3d9.log)

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by acehercules1196** [comment]
> Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

instead of the game freezing in the loading screen to the main menu i get this error message instead 

The bridge server process has unexpectedly exited, closing the bridge client and host application.

**Comment by NV-LL** [comment]
Thank you for confirming. Would you please send along any log files from that last attempt to launch the game?

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.

**Comment by ActuallySandPotNoodles** [comment]
issue is that INFRA uses DX9c
