### ISSUE TITLE
[Documentation feedback]: New RTX Bridge/DXVK Commands

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#620]
### Your feedback

Would it be possible to update the documentation to list the new commands/not yet listed commands for the bridge.conf and the dxvk.conf? Commands that might help experimenting to better compatibility with some games. For example, I was recently taught the alwaysCopyEntireStaticBuffer = True command, but this command wasn't listed anywhere else. This command helped me make AOD compatible with Remix by showing Lara's playermodel. 

### What browsers are you seeing the problem on?

Chrome

**Comment by nv-ajaus** [comment]
@skurtyyskirts The options/configurations are listed here
dxvk-remix: https://github.com/NVIDIAGameWorks/dxvk-remix/blob/main/RtxOptions.md
bridge: https://github.com/NVIDIAGameWorks/bridge-remix/blob/main/bridge.conf

**Comment by skurtyyskirts** [comment]
Ahh I see now - sorry didn't notice the bridge configuration list as well. Thank you! Closing ticket.
