### ISSUE TITLE
[Toolkit bug]: Viewport is black only showing light sources

### ISSUE THREAD

**Issue by condensedcow** [NVIDIAGameWorks/rtx-remix#628]
### Describe the bug

As the title states viewport is black only showing light sources. Nothing can be selected even though there are clearly textures in the scene due to the light source markers blipping in and out of them, and being blocked by them to partially show the scene. On top of this it seems as if the scene is bobbing up and down freely disregarded to the lights sources.

### How do you reproduce the bug?

Not certain

### What is the expected behavior?

Regularly the toolkit will displayed my captured scene, keep the scene still, and let me select textures.

### Version

2024.4.1

### Logs

[kit_20240927_125546.log](https://github.com/user-attachments/files/17170779/kit_20240927_125546.log)
[kit_20240927_130032.log](https://github.com/user-attachments/files/17170780/kit_20240927_130032.log)
[kit_20240927_131036.log](https://github.com/user-attachments/files/17170781/kit_20240927_131036.log)
[kit_20240927_133057.log](https://github.com/user-attachments/files/17170782/kit_20240927_133057.log)
[kit_20240927_134411.log](https://github.com/user-attachments/files/17170783/kit_20240927_134411.log)
[kit_20240927_140914.log](https://github.com/user-attachments/files/17170784/kit_20240927_140914.log)
[kit_20240927_154025.log](https://github.com/user-attachments/files/17170785/kit_20240927_154025.log)

### Media

https://github.com/user-attachments/assets/745b29ee-7fdd-40b0-8895-675c867b9388

**Comment by NV-LL** [comment]
Hi @condensedcow - thanks for reaching out. Would you please provide us with a zip of your capture directory so we can dig into the source of the issue? Thank you!

**Comment by NV-LL** [comment]
Hi @condensedcow - checking in to see if you can provide us with a zip of your capture directory, per the above comment. We also want to let you know about our stale ticket policy, namely that we will close this issue as 'went-stale' if it doesn't receive a response in the next 2 weeks. Thanks!
