### ISSUE TITLE
[Toolkit bug]: Toolkit "Assign Texture Set" not working as intended

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#630]
### Describe the bug

It looks like when I go to Assign Texture Sets of ingested textures that have been marked accordingly, the Toolkit doesn't seem to assign the selected texture category, and assign the rest in accordance when the option is selected. Rather than bringing up the selected texture, Remix pulls a different texture out of the ingested textures, and doesn't assign the original albedo's (or any given texture type) with the ingested one.

Issue present in recent build of the Toolkit, Fix doesn't seem to be working. 167.4+release167.tc10641.83f97e7d. 

### How do you reproduce the bug?

1.) Ingest upscaled+pbr textures of original textures
2.) Remix auto-assigns textures for us when texture type is identified in file name
3.) Click selected texture, click Assign Texture Set, find ingested texture to replace original texture
4.) See different list of non-matching textures.

Video of behavior posted in Remix Discord: https://discord.com/channels/1028444667789967381/1028444668918235197/1290967299934650431

### What is the expected behavior?

To identify all of the ingested textures for the selected mesh, assign accordingly, and to repeat this pattern with the rest of the ingested textures - replacing everything found in the scene.

### Version

2024.4.1

### Logs

[kit_20241002_041013.log](https://github.com/user-attachments/files/17227312/kit_20241002_041013.log)

**Comment by sjgillard** [comment]
Created REMIX-3608 in Jira

**Comment by skurtyyskirts** [comment]
It looks like if a texture is accidentally ingested with the "Other" category, it messes up the system it looks like. It no longer recognizes and can match the other textures if there's an Other item ingested.

**Comment by sjgillard** [comment]
How is it not getting recognized? Is it not getting assigned? Or is it not getting caught in the search? Do you have a screenshot or an example that you can share?

**Comment by skurtyyskirts** [comment]
Hello! I went to make a video just now of the behavior I was experiencing before, but it seems this has been fixed! Not sure what was happening. Earlier if any texture was assigned "Other" it would somehow ruin the search when it went to assign. But it's all resolved, I'm unable to recreate the bug - thank you! I'll close out the ticket as no further action's needed.
