### ISSUE TITLE
[Toolkit bug]: Mouse cursor does not appear even after pressing Alt + X

### ISSUE THREAD

**Issue by BarbatosBachiko** [NVIDIAGameWorks/rtx-remix#633]
### Describe the bug

Mouse cursor does not appear even after pressing Alt + X

### How do you reproduce the bug?

test in game Transformers The Game

### What is the expected behavior?

That I can see my mouse so I can create the capture

### Version

2024.3.1

### Logs

There are no logs, I can only open the game

**Comment by BarbatosBachiko** [comment]
Although I can't use the cursor I got the capture using the Home key + the arrows to select what I wanted and the space to confirm

**Comment by PappaSlask** [comment]
There's tons of mouse/cursor related issues going on now. That wasn't the case before this summer. Something changed in the code that gave birth to these issues. Same in Max Payne 1. A temporary solution that might work for you, is to tab out and tab back into the game again. You can also try running the game in windowed mode.

**Related issues:** https://github.com/NVIDIAGameWorks/rtx-remix/issues/506, https://github.com/NVIDIAGameWorks/rtx-remix/issues/555, https://github.com/NVIDIAGameWorks/rtx-remix/issues/585, https://github.com/NVIDIAGameWorks/rtx-remix/issues/67, https://github.com/NVIDIAGameWorks/rtx-remix/issues/591, https://github.com/NVIDIAGameWorks/rtx-remix/issues/295

**Comment by BarbatosBachiko** [comment]
> Ei@BarbatosBachiko&@PappaSlask- um usuário confirmou uma correção no #506 , com o uso do arquivo bridge.conf neste [comentário](https://github.com/NVIDIAGameWorks/rtx-remix/issues/506#issuecomment-2146493099) . Você poderia, por favor, tentar esse arquivo com seus jogos e ver se ele aborda os problemas que você está tendo? Eles podem estar relacionados, e seria ótimo confirmar se essa correção é amplamente aplicável. Obrigado!

It worked! Thanks!

**Comment by BarbatosBachiko** [comment]
I'm getting a crash in the game, it didn't happen before

**Comment by BarbatosBachiko** [comment]
I solved it, I have to open it through rtx remix omniverse and not through the original game
