### ISSUE TITLE
[Runtime Bug]: Minecraft Story Mode displays white screen when ran

### ISSUE THREAD

**Issue by EthonicDev** [NVIDIAGameWorks/rtx-remix#640]
### Describe the bug

On opening with rtx remix it seems to run normally exept a white screen, I've tried using dxvk.conf with "d3d9.shaderModel = 1" but it makes it crash with this error
```
Could not initialize Direct3D.
Make sure you have current video drivers and
close any other applications that might be running.
You will need a video card that supports at least pixel shader version
1.2.
```
strangely, [dxvk 2.4.1](https://github.com/doitsujin/dxvk/releases/tag/v2.4.1)'s d3d9.dll with that same dxvk.conf runs perfectly fine with no issues.

### How do you reproduce the bug?

Place the RTX remix runtime in minecraft story mode's files to make the screen only show white, an make a dxvk.conf with d3d9.shaderModel = 1 to make it show the error and crash.

### What is the expected behavior?

The runtime should not display a white screen(not exactly sure what it should show), and with d3d9.shaderModel = 1 it should not crash

### Version

0.5.4

### Logs

[MinecraftStoryMode_d3d9 (remix).log](https://github.com/user-attachments/files/17267652/MinecraftStoryMode_d3d9.remix.log)

### Crash dumps

(no dmp files? not sure if im missing something im extremely inexperienced)

### Media

by default with rtx remix
https://github.com/user-attachments/assets/141805d1-d958-40e6-ba5b-9040dc82ef5e

These 2 images are when d3d9.shaderModel = 1 is added
![image](https://github.com/user-attachments/assets/3d0cfeb8-197f-4941-b421-e9c4441e33d6)
(stuff behind is my wallpaper)
![image](https://github.com/user-attachments/assets/48a2f736-deed-4a97-b833-7b4da1242ec7)

**Comment by automata-rtx** [comment]
Interesting that mainline DXVK manages to run the game fine with the lowered shader model override. If the game supports a SM that low then I feel like Remix compatibility should be viable if not for the failed launching

**Comment by NV-LL** [comment]
Thanks for reaching out! This looks like it may be a setup issue - we suggest checking in with the Discord community to see if anyone has had success with this title. Please let us know if you have any other concerns!

**Comment by NV-LL** [comment]
Hi @EthonicDev - checking in to see if you've been able to resolve this with the community's help, or if you need further assistance. We also want to inform you of our stale ticket policy, namely that this issue will be closed as 'went stale' if it doesn't receive an update in the next 2 weeks. Thank you!
