### ISSUE TITLE
[Runtime Bug]: Displacement POM Direct Lighting does not order or blend correctly with decals that have POM.

### ISSUE THREAD

**Issue by Safemilk** [NVIDIAGameWorks/rtx-remix#641]
### Describe the bug

If a decal with POM/displacement is rendered over a surface that has POM/displacement or a decal without POM/displacement, the decal will inherit the displacement from the texture below it.

POM + Direct lighting is awesome, and it would be great to have these elements blend nicely with each other, rather than turning off direct lighting as a solution.

### How do you reproduce the bug?

Render a decal with displacement directly over a normal surface with displacement.

### What is the expected behavior?

Decals with pom should override pom beneath them.

### Version

6.5.6

### Logs

no crash

### Crash dumps

no crash

### Media

![image](https://github.com/user-attachments/assets/8c334114-d421-400d-9a86-77ee8d551214)

![image](https://github.com/user-attachments/assets/f04c0cf0-baff-48fc-8432-81bf628969f0)

**Comment by Safemilk** [comment]
This actually happens on decals that DON'T have a heightmap as well. Any decal over a POM setup with "Enable Direct Lighting" turned on.
![image](https://github.com/user-attachments/assets/8aadb224-c744-4a22-8410-c1b004ea4b8e)

**Comment by xoxor4d** [comment]
dupe: https://github.com/NVIDIAGameWorks/rtx-remix/issues/486

**Comment by Safemilk** [comment]
@xoxor4d Thanks! I did a rough search but definitely missed this!

Closing this ticket as it's a dupe of #486
