### ISSUE TITLE
[Runtime Bug]: Consistent crash on startup, can't boot games with Remix anymore

### ISSUE THREAD

**Issue by Ekozmaster** [NVIDIAGameWorks/rtx-remix#647]
### Describe the bug

I've been getting these pesky bridge errors whenever using the GitHub builds. If I build dxvk-remix from source (and use bridge-remix from github) the error won't happen.

![image](https://github.com/user-attachments/assets/5a793be1-bd75-423a-a819-3ee22c719f10)

Sadly all I could track was the logs leading to a `0xc0000005 - STATUS_ACCESS_VIOLATION` exception, which in c++ world means whatever.

### How do you reproduce the bug?

Idk. I just use the github `action` release builds. ~~Works~~ in my machine.
I'd be happy to hop on a call to help debug this.

### What is the expected behavior?

The game boot up and run.

### Version

Bridge#113 Dxvk#662

### Logs

[NvRemixBridge.log](https://github.com/user-attachments/files/17321051/NvRemixBridge.log)
[d3d9.log](https://github.com/user-attachments/files/17321062/d3d9.log)
[SPEED2_d3d9.log](https://github.com/user-attachments/files/17321065/SPEED2_d3d9.log)

### Crash dumps

[NvRemixBridge.exe_20241009_232532.dmp](https://github.com/user-attachments/files/17321068/NvRemixBridge.exe_20241009_232532.dmp)

**Comment by nv-ajaus** [comment]
@Ekozmaster Just a heads up, Bridge#113 is not on the main branch, and is older than the most recent main build. GitHub lets you filter on a branch in the actions tab. For example, the most recent build is # 111. 
![image](https://github.com/user-attachments/assets/a8618438-ef85-404d-a6c9-108cbe68529c)

Additionally, the location of the log from dxvk-remix has moved since dxvk build # 661. It is now in <GameDir>\rtx-remix\logs\remix-dxvk.log . I took a look at your dxvk-remix log file and since it's the older style, it seems stale. Can you please provide the log from from the new location?

**Comment by Ekozmaster** [comment]
Hi @nv-ajaus Thanks. I believe there is a confusion, the build 113 is the latest action build on bridge.
Anyway, just tried release 0.5.4 and got an error again. This time it doesn't inform about log files or anything. There are the log files generated with 0.5.4:

![image](https://github.com/user-attachments/assets/40db2836-1f44-4464-926d-068f5116db28)
[SPEED2_d3d9.log](https://github.com/user-attachments/files/17321507/SPEED2_d3d9.log)
[NvRemixBridge.log](https://github.com/user-attachments/files/17321509/NvRemixBridge.log)
[NvRemixBridge.exe_20241010_004815.dmp](https://github.com/user-attachments/files/17321517/NvRemixBridge.exe_20241010_004815.dmp)

**Comment by NV-LL** [comment]
Hey @Ekozmaster - at the time of your last repro, we didn't realize there was an issue with the open source repo getting updated. Our apologies! Will you please pull the latest build and try one more time, as it should be updating correctly now? Thank you!

**Comment by Ekozmaster** [comment]
Hi @NV-LL 
Thank you for letting me know. I'll be out of town until the weekend.
I'll try whenever I get time again.
Just so you know, this has been happening to me since dxvk-remix build #554 roughly (it is the last working one I have)

**Comment by NV-LL** [comment]
Hi @Ekozmaster - checking in to see if you've had a chance to retry this with the latest Remix build and confirm if it's now working. We'd also like to inform you of our stale ticket policy, namely that we will close this ticket as 'went stale' if it doesn't receive an update in the next 2 weeks. Thank you!
