### ISSUE TITLE
Fallout New Vegas - Black Screen

### ISSUE THREAD

**Issue by PatrickJnr** [NVIDIAGameWorks/rtx-remix#65]
**Describe the bug**
- A Black Screen, Main Menu audio works fine.
- Remix 0.1.1
- Which GPU - 2060
- Which GPU driver version - 531.61
- Which game build - 1.4.0.525

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11232083/NvRemixBridge.log) 
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11232085/d3d9.log)
- [FalloutNV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11232087/FalloutNV_d3d9.log)

**To Reproduce**
Boot up the game, Black Screen

**Expected behaviour**
Being able to see the main menu

**Screenshots**
![20230414120659_1](https://user-images.githubusercontent.com/3267523/232028298-a2e5b9af-9834-4a19-a1f9-c14cdb35f6a2.jpg)

**Comment by LauraWebdev** [comment]
Related: #10

**Comment by mirrorcult** [comment]
did you actually tag the UI textures? main menu probably wont render without doing that

**Comment by mirrorcult** [comment]
(also--did you do anything special to get it running? couldn't get it to main menu at all either in windowed or fullscreen)

**Comment by UnknownTimelord** [comment]
For me it says "Failed to initialize renderer, unknown error creating the Gamebryo Renderer" and then closes. Hope that there being a jira ticket means that this might work someday, seeing as how this is Nexus' 4th most modded game.

**Comment by PatrickJnr** [comment]
> (also--did you do anything special to get it running? couldn't get it to main menu at all either in windowed or fullscreen)

Yes I did tag the appropriate ui elements

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by PatrickJnr** [comment]
> Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

Sure thing! I'll give it a shot, sorry for my late reply

**Comment by PatrickJnr** [comment]
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/3267523/502912a7-2abd-4acb-9590-c7438aaf589d)


gave it a quick test, using some patches from the RTXRemix discord, seems to show stuff now at least!

**Comment by NV-LL** [comment]
Thank you for confirming! As the game is now rendering, we'll close this ticket. Please open a new one if you encounter any other issues.
