### ISSUE TITLE
Alt + x does not work in the Bioshock Remastered.

### ISSUE THREAD

**Issue by Slayer3090** [NVIDIAGameWorks/rtx-remix#66]
Alt + x does not work in the Bioshock Remastered. Extracted to the main folder with the game. Tell me at what address and which archives need to be extracted. Either there's a bug here, or I made a mistake. The version of the game from Steam. RTX 3060ti video card. Remx version 0.1.1.

**Comment by BigRickNasty** [comment]
Bioshock Remastered is a DX11 game, Remix isn't designed to work with games above DX9

**Comment by Sahil12524** [comment]
> Bioshock Remastered is a DX11 game, Remix isn't designed to work with games above DX9

but GTA San Andreas is a DX8 game and it is still compatible with RTX Remix, it is not working with GTA San Andreas.

**Comment by BSoD38** [comment]
> > Bioshock Remastered is a DX11 game, Remix isn't designed to work with games above DX9
> 
> but GTA San Andreas is a DX8 game and it is still compatible with RTX Remix, it is not working with GTA San Andreas.

The issue is not about GTA San Andreas. Create a seperate issue for this game if you have issues.

**Comment by DoradoOroOro** [comment]
You try to remaster the remaster instead of the original game?

**Comment by NV-LL** [comment]
Thank you for reaching out. As mentioned, this title is incompatible with Remix.
