### ISSUE TITLE
[Runtime Bug]: Strawberry Shortcake The Sweet Dreams Game crashes with a Visual C++ runtime error

### ISSUE THREAD

**Issue by huckleberrypie** [NVIDIAGameWorks/rtx-remix#670]
### Describe the bug

I know this is a shot in the dark considering the game's obscurity and it being a niche title for kids, but out of boredom I tried loading up the runtime to see if it's even possible.

Which game build (and whether it is from Steam/GOG/Other)
A download found on My Abandonware: https://www.myabandonware.com/game/strawberry-shortcake-the-sweet-dreams-game-hf2

### How do you reproduce the bug?

Install the latest RTX Remix runtime from the installer over at Discord, then run the game as usual.

### What is the expected behavior?

The runtime should show up on-screen and do the usual thing.

### Version

dxvk-remix-80adaac-669-release and bridge-remix-7b3d696-114-release

### Logs

[bridge32.log](https://github.com/user-attachments/files/17595957/bridge32.log)
[bridge64.log](https://github.com/user-attachments/files/17595958/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/17595959/remix-dxvk.log)

### Media

Launching the game with Remix installed crashes with the following error:
![Screenshot 2024-11-01 121001](https://github.com/user-attachments/assets/d72d0c23-7e5b-47b3-b620-cb42263d8979)

**Comment by huckleberrypie** [comment]
Anyone?

**Comment by NV-LL** [comment]
Thank you for contacting us. Due to NVIDIA's security policies, we're unable to test content from unofficial sources like abandonware sites. As a result, we won't be able to proceed with this request and will need to close this ticket. We apologize for any disappointment this may cause.
