### ISSUE TITLE
[Runtime Bug]: Garrysmod Spawn In Glitch

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#672]
### Describe the bug

It looks like whenever I load into a map, and spawn something into the map (an npc, a prop, etc) there's a long ray the appears either around my playermodel, or around the spawned item that sprays across the map. I'm not sure what's causing this. If I noclip and go outside of the map and then go back in, the glitch disappears. Also, if I change the view (World View, View Transform, etc) the glitch also disappears. 

I've posted a video if this happening in the RTX-Remix Discord to show the glitch,
https://discord.com/channels/1028444667789967381/1028444668918235197/1301357132297404436
https://discord.com/channels/1028444667789967381/1028444668918235197/1301418996083720212

### How do you reproduce the bug?

1.) Load into Garrysmod
2.) Spawn an npc (you might have to do this once or twice) and notice that your playermodel has a ghosting effect that exists in the world until you move off the map. 

### What is the expected behavior?

Usually I have no issues spawning in NPCs or props, but this appears to be broken now with this glitch being consistent. 

### Version

remix-main+cd0ebf82

### Logs

[bridge64.log](https://github.com/user-attachments/files/17639230/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/17639232/remix-dxvk.log)
[bridge32.log](https://github.com/user-attachments/files/17639233/bridge32.log)
[hl2_d3d9.log](https://github.com/user-attachments/files/17639244/hl2_d3d9.log)

**Comment by NV-LL** [comment]
REMIX-3695 for tracking

**Comment by skurtyyskirts** [comment]
Thank you, that's fixed it! I appreciate your help. Closing ticket.
