### ISSUE TITLE
Silent Storm freezes due to `UWM_REMIX_BRIDGE_REGISTER_THREADPROC_MSG` handshake timeout

### ISSUE THREAD

**Issue by Expack3** [NVIDIAGameWorks/rtx-remix#68]
**Describe the bug**
- Silent Storm freezes and does not produce a window after the successful creation of a D3D9 device by the RTX Remix bridge with the following error consistently thrown the RTX Remix game EXE log: ```warn:  Message channel UWM_REMIX_BRIDGE_REGISTER_THREADPROC_MSG handshake timeout. Retrying...```
- RTX Remix 0.1.1
- Nvidia GeForce RTX 3060 Laptop
- 531.61
- ver. 1.2 Nov 21 2003, GOG

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11233704/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11233642/d3d9.log)
- [game_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11233638/game_d3d9.log)

**To Reproduce**
1. Launch game either directly from EXE (`<path-to-install>/game.exe`) or from GOG Galaxy _without_ RTX Remix.
2. Once main menu has been reached, exit game. This will generate `config.cfg` in `<path-to-install>/cfg`, which is needed for Step 4.
3. Install RTX Remix.
4. Replace `config.cfg` in `<path-to-install>/cfg` with the equivalent file contained in this ZIP file, which forces the game into a borderless windowed mode and disables all pixel shaders: [config.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11233689/config.zip)
5. Launch game again using same method as used in Step 2.
6. See error.

**Expected behavior**
The game window should show and show a video logo for the nVidia GeForce FX series of GPUs, then the game's intro, then the main menu.

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by Expack3** [comment]
This issue no longer occurs when using the release versions of dvk-remix a911c31-540 and bridge-remix-c062326-70 so long as the config provided in the original issue report is used.
