### ISSUE TITLE
Silent Hunter 5 start fails with rtx-remix

### ISSUE THREAD

**Issue by SimonLuetkebohle** [NVIDIAGameWorks/rtx-remix#71]
Describe the bug

    Silent Hunter 5 start fails with rtx-remix (game is exited after intro video/before the game itself is loaded).
    Remix 0.1.1
    RTX 3060 12GB
    531.61
    Silent Hunter 5 v.1.2.0

Attach logs!

    
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11235218/NvRemixBridge.log)
[sh5_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11235219/sh5_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11235223/d3d9.log)

    The following warning from sh5_d3d9.log could be a clue:
        warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_DITHERENABLE

To Reproduce

    Add remix files next to sh5.exe
    Execute sh5.exe
    Game is exited after intro video/before the game itself is loaded

Expected behavior
Game starts correctly like it does without rtx-remix.

**Comment by BSoD38** [comment]
The game might be a bit too recent for RTX Remix to work, although I might be wrong.

Games released after 2006 have a much slimmer chance to work with RTX Remix due to their reliance on shaders.

**Comment by SimonLuetkebohle** [comment]
Ok, i see, thank you for that hint!
I found out that Silent Hunter 5 requires a GPU capable of rendering Pixel Shader 3.0. As far as i understand, rtx-remix currently does not work with that.

Already two predecessors require Pixel Shaders:
Silent Hunter 4: Pixel Shader 2.0.
Silent Hunter 3: Pixel Shader 1.1.
Only for Silent Hunter 2 it could work: It uses DirectX 8 according to the Ubisoft page, no mention of Pixel Shaders.
