### ISSUE TITLE
The Incredibles -- Regressions since Portal With RTX version of the runtime

### ISSUE THREAD

**Issue by joeyballentine** [NVIDIAGameWorks/rtx-remix#75]
**Describe the bug**
- There has been a large regression on the game "The Incredibles" since the last version of the Portal with RTX runtime.

Here is an example image from the latest version (0.1.1):

![image](https://user-images.githubusercontent.com/34788790/232157154-2fc77fa1-7bc0-4755-a7f1-97cb4bc6254e.png)

![image](https://user-images.githubusercontent.com/34788790/232158006-6c2ff3a6-4c3d-4a8b-8d6f-f7fd75a78728.png)

As you can see, the sky is very broken (doesn't work at all), there is a giant shadow (you'll see in the old screenshots that this is where there used to be a big white box), and both the player and boss models no longer render.

I had the sky textures selected in the settings, but doing so did not change anything like it did in previous builds.

I tried to remedy the character model not loading by selecting its texture in the character models section, but the texture was not appearing at all.

Here are some old screenshots:

from the first PwRTX build:
![image](https://user-images.githubusercontent.com/34788790/232157445-1b40f66e-1443-498a-bb43-bc4f05b38365.png)

from the updated PwRTX build:
![image](https://user-images.githubusercontent.com/34788790/232157432-abff5791-92b4-4f0d-a50e-420910944454.png)

Something that might be important to note is that this is a renderware game. Based on what some other people have said about other renderware games, it seems that generally, compatibility with them has gone down.

Also, while grabbing a screenshot, it crashed. I think it's just because I tabbed out.

Logs:
[IncPC_1440p_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11237217/IncPC_1440p_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11237219/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11237220/NvRemixBridge.log)

**Comment by AlexDunn** [comment]
Thanks for the detailed post.  The two main issues I see here are, the left half of screen looks dark, and the missing sky.

In the 'Game Setup' tab, under 'parameters' there is a new option called: "Fused World-View Mode", looks like this game requires that to be set to "In View Transform".
This is a new option that allows Remix to work better with games that pre-combine their world and view matrices before submitting them to the D3D9 API. Looks like the incredibles is one such game!  Let me know if that helps.

**Comment by AlexDunn** [comment]
The missing boss character is another issue, and I've seen this pop up in a few other games too, we're actively looking into what could be causing that but no leads at this time.

**Comment by joeyballentine** [comment]
Changing it to "In-View Transform" definitely fixed the giant shadow, but the other issues persist.

![image](https://user-images.githubusercontent.com/34788790/232172003-d03b08ac-6d6e-4a59-9fca-1114868e4204.png)

One thing that I think may be related to the missing models issue, is that previously if I were to enable the "highlight objects with shared vertex buffers (dull purple)" option, the shadows (which are being projected onto the ground mesh) underneath the player and the boss would both highlight in dull purple, as seen in this image below:

![image](https://user-images.githubusercontent.com/34788790/232172303-e79ab51b-b21b-4089-a1d0-622d7c9c8512.png)

In 0.1.1, those shadow projections are also completely missing. If I had to take a guess, something broke related to the shared vertex buffers, and it's causing both the shadow and its parent to not be displayed.

**Comment by joeyballentine** [comment]
Some more info: When I set a random normal texture to be a UI texture (so it renders everything with raster), the character model is a giant vertex explosion.

![image](https://user-images.githubusercontent.com/34788790/232943483-f351542c-b1c5-4043-9472-12a6dd83a00b.png)

Hopefully that helps narrow this down :)

**Comment by AlexDunn** [comment]
Great, thank you so much for your input! It's really helpful. Just to let you know, I've been working on some fixes for related issues yesterday and today. While I can't say that all of the issues have been completely resolved just yet, there is definitely progress being made. Keep an eye out for updates!

**Comment by joeyballentine** [comment]
![image](https://user-images.githubusercontent.com/34788790/233715781-e3564582-0b39-482f-8616-d5402834dfad.png)

Slightly better using a personally built version of the latest code. That white box is no longer there but the player and boss models are still completely gone.

**Comment by AlexDunn** [comment]
We have fixed a number of issues related to the RenderWare engine games.  Would you mind trying remix-0.2.0 release, and be sure to set the `d3d9.shaderModel = 0` config option in your dxvk.conf (note with remix-0.2.0 the bridge conf is no longer required).

**Comment by joeyballentine** [comment]
I tested it as soon as the new release came out. (I've also been testing CI builds on occasion).

This build works great!

Here's a screenshot from before I turned in-view transform off. That setting apparently isn't necessary anymore.
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/34788790/785561b8-555b-4bf3-bb79-479bf8f8efa5)

And some more screenshots:

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/34788790/80d3867d-3c2d-4e72-a6b9-98c731a56fab)

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/34788790/bfa4f0e8-e130-4476-8457-318848fef7d1)


There's a certain level where some objects get outlined really strangely:

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/34788790/bc868e0d-6429-48a8-bb30-b62d089ecaa6)

And the only other weird thing I noticed is it seems the normals aren't smoothed on shader models (like Mr Incredible, you can see the polygons being individually lit). But hey, at least he shows up now and also isn't just a vertex explosion or a white box :)

Overall this is a huge improvement. Great work!

**Comment by AlexDunn** [comment]
>> like Mr Incredible, you can see the polygons being individually lit

I think if you set the d3d9.shaderModel = 0 in your dxvk.conf, then the game will actually use fixed function.  And in this mode, the characters should render correctly (with regards to normals)

If thats not set, then the game will use shaders for characters (this is common in RenderWare games) and when shaders are being used, the normals may not be picked up by remix correctly currently.

**Comment by joeyballentine** [comment]
Oh, I thought I had that set, but I forgot my bridge.conf just got overwritten, my bad. I'll try setting that in the dxvk.conf and report back.

**Comment by joeyballentine** [comment]
Meant to send this earlier, but that did work. The character/enemy/boss models are all now perfect looking. Thanks!

**Comment by pkristof** [comment]
Please close the ticket if the issues have been resolved.
