### ISSUE TITLE
Skyrim LE Shader3 error with remix 0.1.1 (Steam) Nvidia RTX 2060 super 8gb. Driver 531.41

### ISSUE THREAD

**Issue by Rmurray2006** [NVIDIAGameWorks/rtx-remix#77]
[TESV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11238778/TESV_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11238780/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11238781/NvRemixBridge.log)

Crashes with shader bug clicking play or by launching from shortcut even with skse. specs above and logs in here

**Comment by Rmurray2006** [comment]
sorry didnt know how to post it but yea it crashes

**Comment by twitchplayskh** [comment]
> [TESV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11238778/TESV_d3d9.log) [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11238780/d3d9.log) [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11238781/NvRemixBridge.log)
> 
> Crashes with shader bug clicking play or by launching from shortcut even with skse. specs above and logs in here

skyrim is to new of a game is it not ?

**Comment by Rmurray2006** [comment]
> > [TESV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11238778/TESV_d3d9.log) [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11238780/d3d9.log) [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11238781/NvRemixBridge.log)
> > Crashes with shader bug clicking play or by launching from shortcut even with skse. specs above and logs in here
> 
> skyrim is to new of a game is it not ?

sorry forgot is used shaders, wish there was a way to shut them off so it would use remix

**Comment by Lobastiy** [comment]
Try to change `client.shaderVersion` to `3.0` in `bridge.conf` and move `bridge.conf` to `.trex` folder

**Comment by Lobastiy** [comment]
> Try to change `client.shaderVersion` to `3.0` in `bridge.conf` and move `bridge.conf` to `.trex` folder

And delete # before it
