### ISSUE TITLE
games stay at a black screen and wont load with remix 0.1.1.

### ISSUE THREAD

**Issue by Rmurray2006** [NVIDIAGameWorks/rtx-remix#78]
my games freeze at stay at a black screen and just wont load with a 2060 super 8gb on any game i have tested driver 531.41

**Comment by NV-LL** [comment]
Hello! Can you please provide us with more information about this issue - specifically, what game, and if you have any log files from attempts to launch the game (as per the bug reporting template)?

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.

**Comment by NV-LL** [comment]
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.
