### ISSUE TITLE
Not a bug just a question.

### ISSUE THREAD

**Issue by Rmurray2006** [NVIDIAGameWorks/rtx-remix#79]
Will this script help improve remix? I managed to come across it. [https://pastebin.pl/view/3dd73fc3](url)

**Comment by Tramp99** [comment]
It will need to be checked

**Comment by BSoD38** [comment]
Do you know what it does, and how it is supposed to help RTX Remix?

Sending random bits of code without knowing where it's coming from and what it's supposed to do is rarely useful.

Although, if you know any improvements you could do to RTX Remix, you should create a pull request, issues aren't made to handle code changes.

**Comment by Rmurray2006** [comment]
suppose to remove some shaders, thinking it would help remove some of the shaders remix cannot use yet and help run some games
