### ISSUE TITLE
Terrible compatibility with games

### ISSUE THREAD

**Issue by wcde** [NVIDIAGameWorks/rtx-remix#89]
**Describe the bug**
We need at least some technical requirements for games that should work or understandable errors for a quick drop, not just "DX9 without shaders". It's crazy to try a lot of games, waste hours on every game and see how nothing work.

Splinter Cell (wrapper DX8->DX9, perfectly runs without Remix): shows intro and then black screen, or instantly crash with different settings.
Richard Burns Rally: on max settings can even go to gameplay, but broken graphics, even after mark textures in developer menu. On minimal settings in main menu just gray screen.
Thief III (wrapper DX8->DX9, perfectly runs without Remix): intro broken, but can get into main menu, after start new game shows only fractal glitches and crash.

I also tried: NFS Underground 1 and 2, NFS Porshe Unleashed in DD7 mode and wrapper DD7->DX9, Neverwinter Nights with DX8->DX9 wrapper. Nothing works with Remix, they just crash or have black screen.

- Remix version 0.1.1 from releases
- RTX 4090
- Testing on drivers 531.41 and 531.61

**Attach logs!**
[SplinterCell_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11242200/SplinterCell_d3d9.log)
[splinter_cell-d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11242220/splinter_cell-d3d9.log)
[splinter-cell-NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11242221/splinter-cell-NvRemixBridge.log)
[RichardBurnsRally_SSE_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11242226/RichardBurnsRally_SSE_d3d9.log)
[rbr-d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11242227/rbr-d3d9.log)
[rbr-NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11242228/rbr-NvRemixBridge.log)
[T3Main_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11242230/T3Main_d3d9.log)
[t3-d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11242231/t3-d3d9.log)
[t3-NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11242234/t3-NvRemixBridge.log)

**Screenshots**
![NvRemixBridge_2023_04_16_05_23_30_479](https://user-images.githubusercontent.com/65939220/232309736-bdcdee62-2acf-4ee4-946b-f35cfd0e340b.jpg)
![NvRemixBridge_2023_04_16_05_20_30_418](https://user-images.githubusercontent.com/65939220/232309757-5e877ded-137a-409c-8dda-f0a4181a7b3a.jpg)

**Comment by Rmurray2006** [comment]
you have to configure it to show the textures with the alt x menu

**Comment by wcde** [comment]
> you have to configure it to show the textures with the alt x menu

As I wrote, it does not help. In RBR not all textures are shows in the menu. In Thief III it still shows glitches and crashes. In games with a black screen menu is not displayed at all.

**Comment by mralexs5** [comment]
I read somewhere that if a game had an XBOX 360 and or Playstation 3 port it probably won't work with RTX Remix very well or al all.

**Comment by anchorlightforge** [comment]
Remix is experimental and many of its features are in flux. Nearly every game you mentioned makes extensive use of shaders, but has been supported through more experimental changes.

Unfortunately at this stage Remix is bound to involve a lot of trial and error for unknown titles, and it's hard to set any compatibility notes in stone when it's constantly evolving.  There are some documentation overhaul efforts on the way, but if you want to see short term documentation improvements, contribute to the Trello board with titles you've tested:
https://trello.com/b/c4NgbGoL/rtx-remix-compatibility

**Comment by NV-LL** [comment]
RTX Remix is in early beta and we are always working to expand compatibility--we welcome feedback on any titles that are or aren't working. The community has been organizing information on https://www.moddb.com/rtx on which games are most compatible with RTX Remix and how to properly set them up to get them working. Check it out to learn the easiest path to getting a compatible title hooked up with RTX Remix.
