### ISSUE TITLE
FFXI App Crash - Invalid allocation

### ISSUE THREAD

**Issue by Spadira** [NVIDIAGameWorks/rtx-remix#93]
**Describe the bug**
- App crashes to desktop some time after launch. Log says error is allocation error. Game loaded with d3d8to9.
- Remix 0.1.1
- Nvidia RTX 4090
- 531.41
- Current Version of FFXI

**Attach logs!**
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11244924/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11244922/d3d9.log)

**To Reproduce**
Load into game as normal using d3d8to9.
Wait until game crash.

**Expected behavior**
Game seems to run well, except for crash after some time.

**Comment by Spadira** [comment]
Newest RTX-remix build fixes other player issue and crashing.

**Comment by NV-DM** [comment]
Closing as fixed.
