### ISSUE TITLE
Vampire - The Masquerade - Bloodlines not correctly being injected

### ISSUE THREAD

**Issue by svelle** [NVIDIAGameWorks/rtx-remix#94]
**Describe the bug**
The game loads up just fine with the d3d9.dll attached. The same results with different dxlevels passed as startup arguments. I'm also using the autoexec.cfg from the portalrtx release, dropping in the shaderapidxx.dll's keeps the game from loading, also a complete dll overwrite with the portalrtx data doesn't work either. 
Once the game starts up the RTXR overlay works and is clickable, textures are being loaded in correctly and are visible in the menu. I've made a selection of all the UI textures 
I could find and the game's menu and everything is now totally usable and I managed to get into the game (the character creation is still broken, but that's another story).
When I load into the level I can see everything normally, but the Vampire_d3d9.log file tells me it's falling back to rasterization as it is seeing a draw call to a non-primary render target.

**Attach logs!**

- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11244954/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11244953/d3d9.log)
- [Vampire_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11244952/Vampire_d3d9.log)

These lines specifically stuck out to me from the logs, but that could also be a red herring:

```
info:  [RTX-Compatibility-Info] Found a draw call to a non-primary render target. Falling back to rasterization
warn:  D3D9Texture2D::QueryInterface: Unknown interface query
warn:  794950f2-adfc-458a-905e-10a10b0b503b
info:  [RTX-Compatibility-Info] Skipped drawcall, colour write disabled.
```

**To Reproduce**
1. Setup rtxr as usual
2. Start the game with the flags `-windowed -dxlevel 70`
3. flag the ui textures in the overlay so the menu works (you can also use this [rtx.conf.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11244956/rtx.conf.txt)) 

you can use this savegame to skip the intro sequence and directly drop into a level: [Vampire-000.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/11244961/Vampire-000.zip)

**Expected behavior**
RTXR would inject and override the game's renderer.

**Screenshots**
![image](https://user-images.githubusercontent.com/7526550/232350663-c10094b2-ec95-4d70-84ca-f0c0f3ae3699.png)

**Comment by Devion** [comment]
Tried Bloodlines as well, with all 3 dxlevel's, same effect on all. Vampire_d3d9.log mentions;

info:  [RTX-Compatibility-Info] Trying to raytrace but not detecting a valid camera.
info:  [RTX-Compatibility-Info] Skipped drawcall, colour write disabled.

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by CattoSalad** [comment]
I believe this one is fine now, with tweaks to the `rtx.conf` and adjusting the launch arguments.

**Comment by NV-LL** [comment]
Thank you for confirming! We'll close this ticket as resolved. If you run into another issue, please open a new ticket to let us know.
