### ISSUE TITLE
remix-0.1.0.zip Windows defender complains with "AndroidOS/Multiverze" virus!

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/rtx-remix#95]

**Comment by mralexs5** [comment]
Definitely a false positive, googling the virus shows that windows defender is the only one that Windows Defender is the only AV that finds it and it's usually been a false positive

**Comment by jhaapasa** [comment]
Yes, this is a false positive. Can you try with 0.1.1, we've made some improvements that should help reduce these false positive reports.

**Comment by Aokromes** [comment]
duplicate of https://github.com/NVIDIAGameWorks/rtx-remix/issues/5

**Comment by oscarbg** [comment]
understood, thanks for clarifying!
