### ISSUE TITLE
Game compatability list

### ISSUE THREAD

**Issue by ColinM9991** [NVIDIAGameWorks/rtx-remix#96]
Finding a game compatability list is quite difficult as we're in the early days. Certainly, I've had no success in loading any games with RTX-Remix. While classic games such as GTA 3, Vice City & San Andreas aren't intercepted, the only game that has shown some progress has been Splinter Cell Chaos Theory. That does, however, cause the Bridge to hang indefinitely until it crashes.

Please do share a list here of games that you've been successful in playing with RTX-Remis, as well as any steps required in order to overcome issues with those games. I'll update this main post to keep track of the games that run without issue.

Additionally, it might be worth sharing primary specs as your mileage may vary. I'll start.
CPU: 13900KF
GPU; 4090FE
RAM: 64GB DDR5-5600MHz

_Update_: Many thanks to @mralexs5 for sharing the following thread. I'll not reinvent the wheel by generating a compatability list, instead I'll just reference this.

https://www.reddit.com/r/RTXRemix/comments/10b9hg7/want_to_know_if_a_game_works_heres_the_remix_game/

**Comment by Drommedhar** [comment]
I second such a list. For me none I tried worked (for now).
These were:
Splinter Cell 1
Splinter Cell Chaos Theory
Metal Gear Solid Integral

Also on a side note, we should consider a community discord or something for Remix Mods etc. Is there one already or should we start one?

**Comment by Epana07** [comment]
I would also like a list.
CPU: 5600
GPU: 4070 Ti
RAM: 32GB DDR4

I've managed to get Half-Life Source and Half-Life 2 running relatively stable, with some major graphical issues in outside areas
Call of Juarez: Gunslinger consistently crashes on startup

**Comment by mralexs5** [comment]
https://www.reddit.com/r/RTXRemix/ has a excel sheet that they're updating
https://docs.google.com/spreadsheets/u/1/d/1uNrI-K-LPsIP3cDDTYfgjZl2W6rtKBdzneRwyR878Wg/edit?usp=sharing

**Comment by ColinM9991** [comment]
> https://www.reddit.com/r/RTXRemix/ has a excel sheet that they're updating https://docs.google.com/spreadsheets/u/1/d/1uNrI-K-LPsIP3cDDTYfgjZl2W6rtKBdzneRwyR878Wg/edit?usp=sharing

Updated the main post to include a link to the Reddit thread. Thanks for sharing this.

**Comment by nyleusmani** [comment]
> I second such a list. For me none I tried worked (for now).
> 
> My System CPU: 13700KF GPU: 3080 RAM: 32GB DDR5
> 
> The tested games that didn't work: Splinter Cell 1 Splinter Cell Chaos Theory ([#37 (comment)](https://github.com/NVIDIAGameWorks/rtx-remix/issues/37#issuecomment-1509728136)) Metal Gear Solid Integral
> 
> Also on a side note, we should consider a community discord or something for Remix Mods etc. Is there one already or should we start one?

There is a fairly large one with official NVIDIA engineers in it here:

https://discord.gg/6WcY5GrUzx

**Comment by Drommedhar** [comment]
I actually can't accept the invite here :D

**Comment by ifeelagood** [comment]
Moved here: https://trello.com/b/c4NgbGoL/rtx-remix-compatibility

**Comment by mirh** [comment]
And now: https://www.moddb.com/rtx

**Comment by NV-LL** [comment]
Thank you for reaching out! As this question has been addressed in previous comments, we're going to close this ticket. Please open another one if you have other questions or issues.
