### ISSUE TITLE
Batman Arkham Asylum Shader Model 3 Error

### ISSUE THREAD

**Issue by Andrea332** [NVIDIAGameWorks/rtx-remix#98]
**Describe the bug**
- Starting the game with remix cause Shader Model 3 Error.
- Main Branch remix-0.1.1
- RTX 3080
- 531.61.0
- Game version 1.1 from Epic Games

**To Reproduce**
1. Start the game from epic launcher with remix installed

**Expected behavior**
Game should start with Remix

**Screenshots**
![image](https://user-images.githubusercontent.com/74671832/232613275-106ccff7-e69f-45bc-a499-cc90945f4500.png)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11255953/NvRemixBridge.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11255955/d3d9.log)
[ShippingPC-BmGame_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11255956/ShippingPC-BmGame_d3d9.log)

**Comment by EliteCombineSoldier** [comment]
its 9.0c
wont work probably

**Comment by Andrea332** [comment]
> Try to move `bridge.conf` to `.trex` folder and in `bridge.conf` set `client.shaderVersion` to `3.0` and remove `#`

Splash screen appears (the small window with Batman), intro's audio starts for about 1 second and then the game crash stopped working with a white rectangle at the top left corner of the screen

![image](https://user-images.githubusercontent.com/74671832/232760687-41b57b11-81d2-42d2-967d-fe3ba755edb8.png)

**Comment by Lobastiy** [comment]
> > Try to move `bridge.conf` to `.trex` folder and in `bridge.conf` set `client.shaderVersion` to `3.0` and remove `#`
> 
> Splash screen appears (the small window with Batman), intro's audio starts for about 1 second and then the game crash stopped working with a white rectangle at the top left corner of the screen
> 
> ![image](https://user-images.githubusercontent.com/74671832/232760687-41b57b11-81d2-42d2-967d-fe3ba755edb8.png)

Can you share with (exe name)_d3d9.log

**Comment by Andrea332** [comment]
> 

[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11261393/NvRemixBridge.log)
[ShippingPC-BmGame_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11261394/ShippingPC-BmGame_d3d9.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11261395/d3d9.log)

**Comment by Rmurray2006** [comment]
use dkvx fork, games from 2009.

**Comment by CDSFounder** [comment]
> use dkvx fork, games from 2009.

Can you elaborate a bit more / how to do this?

**Comment by AHBZero** [comment]
> > use dkvx fork, games from 2009.
> 
> Can you elaborate a bit more / how to do this?

I think is this one:
https://github.com/doitsujin/dxvk

**Comment by EliteCombineSoldier** [comment]
> > > > use dkvx fork, games from 2009.
> > > 
> > > 
> > > Can you elaborate a bit more / how to do this?
> > 
> > I think is this one: https://github.com/doitsujin/dxvk
> 
> this, https://github.com/NVIDIAGameWorks/dxvk-remix

Its literally the same thing

**Comment by Rmurray2006** [comment]
> 

then you'll see the log file in the trex file if you use the other because it says its not dxvk supported

**Comment by EliteCombineSoldier** [comment]
> > 
> 
> then you'll see the log file in the trex file if you use the other because it says its not dxvk supported
You are loading the bridge


The bridge isnt DXVK

Which is true

**Comment by NV-DM** [comment]
Shader-based games are not in scope for Remix, as it's a difficult technical problem to solve. We therefore have no plans to support them for now. (There is extremely limited support for vertex shaders in some games, but it's focused on specific use cases that we can currently support.)
